param(
 [string]$ProjectRoot = (Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path,
 [string]$IntegrationBundle = '',
 [string]$RunId = ''
)
$ErrorActionPreference='Stop'; Set-StrictMode -Version 2.0
$Module=Join-Path $ProjectRoot 'scripts\windows\modules\LiNRR_M03A4_Calibration.psm1';Import-Module $Module -Force
$Fixtures=Join-Path $ProjectRoot 'tests\fixtures\M03A_4';$Results=New-Object Collections.Generic.List[object]
function Assert-True([bool]$Condition,[string]$Message){if(-not$Condition){throw $Message}}
function Add-Case([string]$Id,[string]$Name,[string]$Expected,[scriptblock]$Body){try{&$Body;$Results.Add([pscustomobject][ordered]@{case_id=$Id;case_name=$Name;expected=$Expected;actual=$Expected;status='PASS';failure_reason=''})}catch{$Results.Add([pscustomobject][ordered]@{case_id=$Id;case_name=$Name;expected=$Expected;actual='UNEXPECTED';status='FAIL';failure_reason=$_.Exception.Message})}}
function New-Ledger([double]$Total=3.04462809917){@(
 [pscustomobject]@{sample_id='T';component_name='EIS_HFR_total';value_ohm=$Total;uncertainty_ohm=.003;status='SYNTHETIC_CONSENSUS_ACCEPTED';source_type='SYNTHETIC';source_reference='synthetic'},
 [pscustomobject]@{sample_id='T';component_name='fixture';value_ohm=.1;uncertainty_ohm=.001;status='SYNTHETIC_DEFINED';source_type='SYNTHETIC';source_reference='synthetic'},
 [pscustomobject]@{sample_id='T';component_name='contact';value_ohm=.05;uncertainty_ohm=.001;status='SYNTHETIC_DEFINED';source_type='SYNTHETIC';source_reference='synthetic'},
 [pscustomobject]@{sample_id='T';component_name='membrane';value_ohm=.2;uncertainty_ohm=.002;status='SYNTHETIC_DEFINED';source_type='SYNTHETIC';source_reference='synthetic'},
 [pscustomobject]@{sample_id='T';component_name='other_series';value_ohm=.05;uncertainty_ohm=.001;status='SYNTHETIC_DEFINED';source_type='SYNTHETIC';source_reference='synthetic'})}
function Copy-Rows([object[]]$Rows){@($Rows|ForEach-Object{$_|Select-Object *})}
function Get-Hash([string]$Path){(Get-FileHash -Algorithm SHA256 -LiteralPath $Path).Hash.ToLowerInvariant()}
function New-ParentResolvedFixture {
 $Values=[ordered]@{EIS_HFR_total=@(3.044,.003,'ohm','SYNTHETIC_CONSENSUS_ACCEPTED');fixture=@(.1,.001,'ohm','SYNTHETIC_DEFINED');contact=@(.05,.001,'ohm','SYNTHETIC_DEFINED');membrane=@(.2,.002,'ohm','SYNTHETIC_DEFINED');other_series=@(.05,.001,'ohm','SYNTHETIC_DEFINED');electrode_spacing=@(.004,.00002,'m','SYNTHETIC_DEFINED');EIS_area=@(.003025,.000006,'m^2','SYNTHETIC_DEFINED')}
 @($Values.Keys|ForEach-Object{[pscustomobject][ordered]@{sample_id='T';quantity_name=$_;target_parameter='';value_SI=$Values[$_][0];uncertainty_SI=$Values[$_][1];unit=$Values[$_][2];data_origin='SYNTHETIC';evidence_status=$Values[$_][3];resolution_method='TEST';source_table='test.csv';source_rows='2';source_reference='synthetic regression';source_sha256=('a'*64);status='PASS';failure_reason=''}})
}

$Good=Import-M03A4Eis (Join-Path $Fixtures 'S001_complete_rep1.csv') C001 Hz ohm S R1
Add-Case C001 'complete synthetic EIS' PASS {Assert-True ($Good.Status-eq'PASS') 'complete import failed';$H=Get-M03A4HfrEstimate $Good;Assert-True ((Test-M03A4Finite $H.EstimateOhm)-and$H.SelectedPointCount-gt0) 'HFR failed';$P=@(Import-Csv (Join-Path $Fixtures 'fixture_manifest.csv'));$Files=@(Get-ChildItem $Fixtures -Filter 'S*.csv' -File);Assert-True ($P.Count-eq$Files.Count) 'fixture provenance coverage incomplete';Assert-True (@($P|Where-Object data_origin -ne 'SYNTHETIC').Count-eq0) 'synthetic fixture origin mislabeled'}
Add-Case C002 'incomplete experimental manifest' EXPERIMENTAL_INPUT_INCOMPLETE {$M=Import-M03A4Manifest (Join-Path $ProjectRoot 'config\M03A_4_experimental_manifest.csv') $ProjectRoot;Assert-True (@($M|Where-Object status -eq 'EXPERIMENTAL_INPUT_INCOMPLETE').Count-eq1) 'experimental row not incomplete'}
Add-Case C003 'missing EIS file' BLOCKED_MISSING_FILE {$Caught=$false;try{Import-M03A4Eis (Join-Path $Fixtures 'does_not_exist.csv') C003|Out-Null}catch{$Caught=$true};Assert-True $Caught 'missing file accepted'}
Add-Case C004 'duplicate frequencies retained' WARNING_DUPLICATE_FREQUENCY {$X=Import-M03A4Eis (Join-Path $Fixtures 'S002_duplicate.csv') C004;Assert-True ($X.DuplicateCount-ge2-and$X.Rows.Count-eq10) 'duplicates not retained'}
Add-Case C005 'shuffled frequencies normalized' PASS {$X=Import-M03A4Eis (Join-Path $Fixtures 'S003_shuffled.csv') C005;for($i=1;$i-lt$X.Rows.Count;$i++){Assert-True ($X.Rows[$i-1].FrequencyHz-ge$X.Rows[$i].FrequencyHz) 'not descending'};Assert-True (@($X.Rows|Where-Object OriginalRowNumber -eq 2).Count-eq1) 'original row lost'}
Add-Case C006 'NaN blocked' BLOCKED_INVALID_NUMERIC_DATA {$X=Import-M03A4Eis (Join-Path $Fixtures 'S004_nan.csv') C006;Assert-True ($X.Status-eq'BLOCKED_INVALID_NUMERIC_DATA') 'NaN accepted'}
Add-Case C007 'Inf blocked' BLOCKED_INVALID_NUMERIC_DATA {$X=Import-M03A4Eis (Join-Path $Fixtures 'S005_inf.csv') C007;Assert-True ($X.Status-eq'BLOCKED_INVALID_NUMERIC_DATA') 'Inf accepted'}
Add-Case C008 'blank blocked' BLOCKED_INVALID_NUMERIC_DATA {$X=Import-M03A4Eis (Join-Path $Fixtures 'S006_blank.csv') C008;Assert-True ($X.Status-eq'BLOCKED_INVALID_NUMERIC_DATA') 'blank accepted'}
Add-Case C009 'string blocked' BLOCKED_INVALID_NUMERIC_DATA {$X=Import-M03A4Eis (Join-Path $Fixtures 'S007_string.csv') C009;Assert-True ($X.Status-eq'BLOCKED_INVALID_NUMERIC_DATA') 'string accepted'}
Add-Case C010 'insufficient high-frequency coverage' BLOCKED_INSUFFICIENT_HIGH_FREQUENCY_COVERAGE {$X=Import-M03A4Eis (Join-Path $Fixtures 'S008_insufficient_hf.csv') C010;$H=Get-M03A4HfrEstimate $X;Assert-True ($H.Status-eq'BLOCKED_INSUFFICIENT_HIGH_FREQUENCY_COVERAGE') 'coverage accepted'}
Add-Case C011 'inductive artifact retained' WARNING_HIGH_FREQUENCY_INDUCTIVE_ARTIFACT {$X=Import-M03A4Eis (Join-Path $Fixtures 'S009_inductive.csv') C011;Assert-True ($X.InductiveHighFrequencyCount-gt0-and$X.Rows.Count-eq10) 'inductive rows lost'}
Add-Case C012 'replicate agreement' PASS {$H1=Get-M03A4HfrEstimate $Good;$G2=Import-M03A4Eis (Join-Path $Fixtures 'S001_complete_rep2.csv') C012 Hz ohm S R2;$H2=Get-M03A4HfrEstimate $G2;$C=Get-M03A4ReplicateConsensus @($H1,$H2);Assert-True ($C[0].consensus_status-eq'PASS') 'agreement rejected'}
Add-Case C013 'replicate disagreement retained' REPLICATE_DISAGREEMENT {$H1=Get-M03A4HfrEstimate $Good;$G2=Import-M03A4Eis (Join-Path $Fixtures 'S010_replicate_disagree.csv') C013 Hz ohm S R2;$H2=Get-M03A4HfrEstimate $G2;$C=Get-M03A4ReplicateConsensus @($H1,$H2);Assert-True ($C[0].consensus_status-eq'REPLICATE_DISAGREEMENT'-and$C[0].replicate_count-eq2) 'outlier removed or disagreement missed'}
Add-Case C014 'negative de-embedded resistance' BLOCKED_NEGATIVE_DEEMBEDDED_RESISTANCE {$L=New-Ledger .3;$R=Get-M03A4ResistanceLedger T $L;Assert-True ($R.status-eq'BLOCKED_NEGATIVE_DEEMBEDDED_RESISTANCE') 'negative repaired'}
Add-Case C015 'zero de-embedded resistance' BLOCKED_NONPOSITIVE_DEEMBEDDED_RESISTANCE {$L=New-Ledger .4;$R=Get-M03A4ResistanceLedger T $L;Assert-True ($R.status-eq'BLOCKED_NONPOSITIVE_DEEMBEDDED_RESISTANCE') 'zero repaired'}
Add-Case C016 'missing fixture resistance' BLOCKED_SERIES_RESISTANCE_LEDGER_INCOMPLETE {$L=@(New-Ledger|Where-Object component_name -ne 'fixture');$R=Get-M03A4ResistanceLedger T $L;Assert-True ($R.status-eq'BLOCKED_SERIES_RESISTANCE_LEDGER_INCOMPLETE') 'fixture defaulted'}
Add-Case C017 'missing contact resistance' BLOCKED_SERIES_RESISTANCE_LEDGER_INCOMPLETE {$L=@(New-Ledger|Where-Object component_name -ne 'contact');$R=Get-M03A4ResistanceLedger T $L;Assert-True ($R.status-eq'BLOCKED_SERIES_RESISTANCE_LEDGER_INCOMPLETE') 'contact defaulted'}
Add-Case C018 'missing membrane resistance' BLOCKED_SERIES_RESISTANCE_LEDGER_INCOMPLETE {$L=@(New-Ledger|Where-Object component_name -ne 'membrane');$R=Get-M03A4ResistanceLedger T $L;Assert-True ($R.status-eq'BLOCKED_SERIES_RESISTANCE_LEDGER_INCOMPLETE') 'membrane defaulted'}
Add-Case C019 'NOT_APPLICABLE without evidence' BLOCKED_SERIES_RESISTANCE_LEDGER_INCOMPLETE {$L=New-Ledger;$R=@($L|Where-Object component_name -eq 'fixture')[0];$R.status='NOT_APPLICABLE_WITH_EVIDENCE';$R.source_reference='';$R=Get-M03A4ResistanceLedger T $L;Assert-True ($R.status-eq'BLOCKED_SERIES_RESISTANCE_LEDGER_INCOMPLETE') 'evidence-free zero accepted'}
$AreaConfig=@(Import-Csv (Join-Path $ProjectRoot 'config\M03A_4_area_measurements.csv')|Where-Object sample_id -eq 'SYN_DRY_001')
Add-Case C020 'area mapping mismatch' AREA_BASIS_MISMATCH {$A=Copy-Rows $AreaConfig;(@($A|Where-Object quantity_name -eq 'EIS_area')[0]).mapping_reference='';$R=Invoke-M03A4AreaAudit SYN_DRY_001 $A;Assert-True ($R[0].overall_status-eq'AREA_BASIS_MISMATCH') 'mismatch accepted'}
Add-Case C021 'zero area' AREA_BASIS_MISMATCH {$A=Copy-Rows $AreaConfig;(@($A|Where-Object quantity_name -eq 'EIS_area')[0]).value_SI='0';$R=Invoke-M03A4AreaAudit SYN_DRY_001 $A;Assert-True ($R[0].overall_status-eq'AREA_BASIS_MISMATCH') 'zero area repaired'}
Add-Case C022 'negative area' AREA_BASIS_MISMATCH {$A=Copy-Rows $AreaConfig;(@($A|Where-Object quantity_name -eq 'EIS_area')[0]).value_SI='-1';$R=Invoke-M03A4AreaAudit SYN_DRY_001 $A;Assert-True ($R[0].overall_status-eq'AREA_BASIS_MISMATCH') 'negative area repaired'}
Add-Case C023 'missing electrode spacing' AREA_MAPPING_INCOMPLETE {$A=@($AreaConfig|Where-Object quantity_name -ne 'electrode_spacing');$R=Invoke-M03A4AreaAudit SYN_DRY_001 $A;Assert-True ($R[0].overall_status-eq'AREA_MAPPING_INCOMPLETE') 'missing spacing accepted'}
Add-Case C024 'direct versus HFR conflict' CALIBRATION_CONFLICT {$R=Compare-M03A4Conductivity 1 .01 .5 .01;Assert-True ($R.status-eq'CALIBRATION_CONFLICT'-and$R.selection-eq'NONE_AUTOMATIC') 'truth auto-selected'}
Add-Case C025 'acceptable conductivity agreement' PASS {$R=Compare-M03A4Conductivity .505 .01 .5 .01;Assert-True ($R.status-eq'PASS'-and$R.selection-eq'NONE_AUTOMATIC') 'agreement failed'}
Add-Case C026 'Monte Carlo rejected fraction above one percent' FAILED_INPUT_DISTRIBUTION {$Vals=[ordered]@{EIS_HFR_total=@(.401,.02,'ohm');fixture=@(.1,.01,'ohm');contact=@(.1,.01,'ohm');membrane=@(.1,.01,'ohm');other_series=@(.1,.01,'ohm');electrode_spacing=@(.004,.00001,'m');EIS_area=@(.003,.00001,'m^2')};$Rows=@($Vals.Keys|ForEach-Object{[pscustomobject]@{sample_id='T';quantity_name=$_;value_SI=$Vals[$_][0];uncertainty_SI=$Vals[$_][1];unit=$Vals[$_][2];data_origin='SYNTHETIC';status='PASS';source_sha256=('a'*64)}});$R=Invoke-M03A4MonteCarloFromResolved $Rows T 20000 40304;Assert-True ($R.status-eq'FAILED_INPUT_DISTRIBUTION'-and[double]$R.rejected_fraction-gt.01-and[int]$R.total_generated-eq20000) 'nonphysical samples clipped or wrong denominator'}
Add-Case C027 'parameter unit mismatch' PARAMETER_UNIT_MISMATCH {$M=@(Import-Csv (Join-Path $ProjectRoot 'config\M03A_4_parameter_mapping.csv')|Select-Object *);(@($M|Where-Object source_quantity -eq 'conductivity')[0]).source_unit='mS/cm';$R=Invoke-M03A4ParameterMappingAudit $M;Assert-True (@($R|Where-Object status -eq 'PARAMETER_UNIT_MISMATCH').Count-eq1) 'unit mismatch accepted'}
Add-Case C028 'parameter target missing' PARAMETER_TARGET_MISSING {$M=@(Import-Csv (Join-Path $ProjectRoot 'config\M03A_4_parameter_mapping.csv')|Where-Object source_quantity -ne 'conductivity');$R=Invoke-M03A4ParameterMappingAudit $M;Assert-True (@($R|Where-Object status -eq 'PARAMETER_TARGET_MISSING').Count-eq1) 'missing target accepted'}
Add-Case C029 'synthetic transfer preflight' SYNTHETIC_TRANSFER_PREFLIGHT_PASS {$M=Invoke-M03A4ParameterMappingAudit @(Import-Csv (Join-Path $ProjectRoot 'config\M03A_4_parameter_mapping.csv'));Assert-True (@($M|Where-Object status -ne 'PASS').Count-eq0) 'mapping audit failed';$R=Get-M03A4ResistanceLedger SYN_DRY_001 @(Import-Csv (Join-Path $ProjectRoot 'config\M03A_4_resistance_ledger.csv'));Assert-True ($R.status-eq'PASS') 'synthetic de-embedding failed'}
Add-Case C030 'experimental completeness remains false' EXPERIMENTAL_INPUT_COMPLETE_FALSE {$G=New-M03A4CompletenessGate $true;Assert-True (@($G|Where-Object item -eq 'EXPERIMENTAL_PARAMETER_TRANSFER_PASS'|Where-Object value -eq 'FALSE').Count-eq1) 'synthetic result promoted to experimental'}
Add-Case C031 'duplicate ledger row blocks' BLOCKED_SERIES_RESISTANCE_LEDGER_INCOMPLETE {$L=@(New-Ledger);$L+=($L|Where-Object component_name -eq 'fixture'|Select-Object *);$R=Get-M03A4ResistanceLedger T $L;Assert-True ($R.status-eq'BLOCKED_SERIES_RESISTANCE_LEDGER_INCOMPLETE') 'duplicate row silently overwritten'}
Add-Case C032 'quoted comma parsed by Import-Csv' PASS {$P=Join-Path ([IO.Path]::GetTempPath()) ('m03a4_quoted_'+[guid]::NewGuid().ToString('N')+'.csv');try{[IO.File]::WriteAllText($P,"a,b`r`n1,`"quoted, value`"`r`n",[Text.UTF8Encoding]::new($false));$R=@(Import-Csv -LiteralPath $P);Assert-True ($R.Count-eq1-and$R[0].b-eq'quoted, value') 'RFC 4180 quoted comma changed columns'}finally{if(Test-Path $P){Remove-Item -LiteralPath $P}}}
Add-Case C033 'synthetic source origin enforced' AREA_MAPPING_INCOMPLETE {$A=Copy-Rows $AreaConfig;(@($A|Where-Object quantity_name -eq 'electrode_spacing')[0]).data_origin='EXPERIMENTAL';$R=Invoke-M03A4AreaAudit SYN_DRY_001 $A;Assert-True ($R[0].overall_status-eq'AREA_MAPPING_INCOMPLETE') 'origin mismatch accepted'}
Add-Case C034 'mapping formula whitelist enforced' PARAMETER_FORMULA_NOT_WHITELISTED {$M=@(Import-Csv (Join-Path $ProjectRoot 'config\M03A_4_parameter_mapping.csv')|Select-Object *);(@($M|Where-Object source_quantity -eq 'conductivity')[0]).conversion_formula='arbitrary(kappa)';$R=Invoke-M03A4ParameterMappingAudit $M;Assert-True (@($R|Where-Object status -eq 'PARAMETER_FORMULA_NOT_WHITELISTED').Count-eq1) 'untrusted formula accepted'}
Add-Case C035 'direct conductivity provenance complete' PASS {$R=Test-M03A4DirectConductivity SYN_DRY_001 @(Import-Csv (Join-Path $ProjectRoot 'config\M03A_4_direct_conductivity.csv'));Assert-True ($R.status-eq'PASS'-and$R.data_origin-eq'SYNTHETIC') 'direct provenance failed'}
Add-Case C036 'synthetic gate consumes false integration result' FAIL {$G=New-M03A4CompletenessGate $false;Assert-True (@($G|Where-Object item -eq 'SYNTHETIC_PARAMETER_TRANSFER_PASS'|Where-Object value -eq 'FALSE'|Where-Object status -eq 'FAIL').Count-eq1) 'synthetic gate ignored parameter'}
Add-Case C038 'fixture value changes parent digest' PASS {$A=New-ParentResolvedFixture;$D1=(New-M03A4ParentProvenance $A T).Digest;$B=Copy-Rows $A;(@($B|Where-Object quantity_name -eq 'fixture')[0]).value_SI='.101';$D2=(New-M03A4ParentProvenance $B T).Digest;Assert-True ($D1-ne$D2) 'fixture value did not change digest'}
Add-Case C039 'EIS area uncertainty changes parent digest' PASS {$A=New-ParentResolvedFixture;$D1=(New-M03A4ParentProvenance $A T).Digest;$B=Copy-Rows $A;(@($B|Where-Object quantity_name -eq 'EIS_area')[0]).uncertainty_SI='.000007';$D2=(New-M03A4ParentProvenance $B T).Digest;Assert-True ($D1-ne$D2) 'EIS area uncertainty did not change digest'}
Add-Case C040 'spacing source hash changes parent digest' PASS {$A=New-ParentResolvedFixture;$D1=(New-M03A4ParentProvenance $A T).Digest;$B=Copy-Rows $A;(@($B|Where-Object quantity_name -eq 'electrode_spacing')[0]).source_sha256=('b'*64);$D2=(New-M03A4ParentProvenance $B T).Digest;Assert-True ($D1-ne$D2) 'spacing source hash did not change digest'}
Add-Case C041 'missing parent blocks conductivity provenance' BLOCKED_MISSING_PARENT {$A=@(New-ParentResolvedFixture|Where-Object quantity_name -ne 'fixture');$Caught=$false;try{New-M03A4ParentProvenance $A T|Out-Null}catch{$Caught=$true};Assert-True $Caught 'missing parent accepted'}

if(-not[string]::IsNullOrWhiteSpace($IntegrationBundle)){
 Add-Case C037 'synthetic COMSOL integration artifact' SYNTHETIC_COMSOL_INTEGRATION_ARTIFACT_PASS {
  Assert-True (-not[string]::IsNullOrWhiteSpace($RunId)) 'integration run_id missing'
  $Required=@('M03A_4_case_results.csv','M03A_4_coupled_closure.csv','M03A_4_parameter_response.csv','M03A_4_parameter_transfer.csv','M03A_4_reload_audit.csv','M03A_4_runtime_audit.csv','M03A_4_attempt_history.csv','M03A_4_readiness.csv')
  $Tables=Join-Path $IntegrationBundle 'tables';$ManifestPath=Join-Path $IntegrationBundle 'manifest\M03A_4_RELEASE_MANIFEST.csv'
  foreach($Name in $Required){Assert-True (Test-Path -LiteralPath (Join-Path $Tables $Name) -PathType Leaf) "missing integration artifact: $Name"}
  Assert-True (Test-Path -LiteralPath $ManifestPath -PathType Leaf) 'release manifest missing'
  $Manifest=@(Import-Csv -LiteralPath $ManifestPath -Encoding UTF8);Assert-True ($Manifest.Count-gt0) 'release manifest empty'
  foreach($Entry in $Manifest){$Artifact=Join-Path $IntegrationBundle ($Entry.relative_path.Replace('/','\'));Assert-True ($Entry.run_id-eq$RunId) "manifest run_id mismatch: $($Entry.relative_path)";Assert-True (Test-Path -LiteralPath $Artifact -PathType Leaf) "manifest artifact missing: $($Entry.relative_path)";Assert-True ([long]$Entry.size_bytes-eq(Get-Item -LiteralPath $Artifact).Length) "manifest size mismatch: $($Entry.relative_path)";Assert-True ($Entry.sha256-eq(Get-Hash $Artifact)) "manifest hash mismatch: $($Entry.relative_path)";Assert-True ($Entry.validation_status-eq'PASS') "manifest validation not PASS: $($Entry.relative_path)"}
  $Case=@(Import-Csv -LiteralPath (Join-Path $Tables 'M03A_4_case_results.csv') -Encoding UTF8);$Combined=@($Case|Where-Object case_id -eq 'COMBINED_NONIDENTITY');Assert-True ($Combined.Count-eq1-and$Combined[0].status-eq'PASS') 'COMBINED_NONIDENTITY missing or failed';foreach($N in @('geometry_rebuilt','mesh_rebuilt','old_solution_cleared','spf_active','tds_active','cd_active','fresh_full_solve')){Assert-True ([double]$Combined[0].$N-ne0) "$N not true"}
  $Transfer=@(Import-Csv -LiteralPath (Join-Path $Tables 'M03A_4_parameter_transfer.csv') -Encoding UTF8);Assert-True (@($Transfer|Where-Object{$_.case_id-eq'COMBINED_NONIDENTITY'-and$_.status-eq'PASS'}).Count-eq5) 'five parameter consumers did not pass'
  $Closure=@(Import-Csv -LiteralPath (Join-Path $Tables 'M03A_4_coupled_closure.csv') -Encoding UTF8);Assert-True ($Closure.Count-eq1-and$Closure[0].status-eq'SYNTHETIC_PARAMETER_TRANSFER_PASS') 'actual TDS closure failed';Assert-True ([double]$Closure[0].current_to_TDS_N2_relative_error-le1e-6-and[double]$Closure[0].current_to_TDS_NH3_relative_error-le1e-6-and[double]$Closure[0].N2_balance-le1e-4-and[double]$Closure[0].NH3_balance-le1e-4-and[double]$Closure[0].nitrogen_balance-le1e-4-and[double]$Closure[0].current_conservation-le1e-6) 'conservation thresholds failed'
  $Reload=@(Import-Csv -LiteralPath (Join-Path $Tables 'M03A_4_reload_audit.csv') -Encoding UTF8);Assert-True ($Reload.Count-eq5-and@($Reload|Where-Object status -ne 'PASS').Count-eq0) 'independent reload did not pass';Assert-True (@($Reload|Where-Object{$_.expected_origin-ne$_.stored_origin-or$_.expected_source_sha256-ne$_.stored_source_sha256-or$_.expected_resolved_sha256-ne$_.stored_resolved_sha256-or$_.expected_target_parameter-ne$_.stored_target_parameter}).Count-eq0) 'full provenance round-trip failed'
  $Runtime=@(Import-Csv -LiteralPath (Join-Path $Tables 'M03A_4_runtime_audit.csv') -Encoding UTF8);Assert-True ($Runtime.Count-eq1-and[int]$Runtime[0].process_exit_status-eq0-and$Runtime[0].completion_marker-eq'True'-and[int]$Runtime[0].reload_exit_status-eq0-and$Runtime[0].reload_marker-eq'True'-and$Runtime[0].status-eq'PASS') 'runtime or completion marker failed'
  $Attempts=@(Import-Csv -LiteralPath (Join-Path $Tables 'M03A_4_attempt_history.csv') -Encoding UTF8);$Accepted=@($Attempts|Where-Object accepted_for_formal_results -eq 'TRUE');Assert-True ($Accepted.Count-eq1-and$Accepted[0].run_id-eq$RunId) 'exactly one current run was not accepted'
  $Readiness=@(Import-Csv -LiteralPath (Join-Path $Tables 'M03A_4_readiness.csv') -Encoding UTF8);Assert-True (@($Readiness|Where-Object{$_.run_id-eq$RunId}).Count-eq$Readiness.Count) 'readiness run_id mismatch';Assert-True (@($Readiness|Where-Object{$_.item-eq'EXPERIMENTAL_INPUT_COMPLETE'-and$_.value-eq'FALSE'}).Count-eq1) 'experimental input promoted';Assert-True (@($Readiness|Where-Object{$_.item-eq'M03B_READY'-and$_.value-eq'FALSE'}).Count-eq1) 'M03B incorrectly ready'
  foreach($Name in @('M03A_4_case_results.csv','M03A_4_coupled_closure.csv','M03A_4_parameter_response.csv','M03A_4_parameter_transfer.csv','M03A_4_reload_audit.csv','M03A_4_runtime_audit.csv')){$Rows=@(Import-Csv -LiteralPath (Join-Path $Tables $Name) -Encoding UTF8);Assert-True (@($Rows|Where-Object run_id -ne $RunId).Count-eq0) "artifact run_id mismatch: $Name"}
 }
}

foreach($R in $Results){"M03A4_REGRESSION|$($R.case_id)|$($R.case_name)|$($R.expected)|$($R.actual)|$($R.status)|$($R.failure_reason.Replace('|','/'))"}
if(@($Results|Where-Object status -ne 'PASS').Count){throw 'One or more M03A.4 regressions failed'}
"M03A4_TESTS|PASS|$($Results.Count) structured cases retained"
