param([string]$OutputPath,[string]$OnlyTestId)

Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$ProjectRoot=(Resolve-Path(Join-Path $PSScriptRoot '..\..')).Path
Import-Module(Join-Path $ProjectRoot 'scripts\windows\modules\LiNRR_M03A6_Acquisition.psm1') -Force -DisableNameChecking
$ExpectedTestIds=@(1..91|ForEach-Object{'A{0:D3}'-f$_})
if(-not[string]::IsNullOrWhiteSpace($OnlyTestId)){
    if($OnlyTestId-cnotin$ExpectedTestIds){Write-Error "INVALID_TEST_ID: $OnlyTestId";exit 2}
    if(-not$PSBoundParameters.ContainsKey('OutputPath')-or[string]::IsNullOrWhiteSpace($OutputPath)){Write-Error 'ONLY_TEST_ID_REQUIRES_EXTERNAL_OUTPUT';exit 2}
    try{[void](Assert-M03A6OutsideRepository $OutputPath $ProjectRoot)}catch{Write-Error "ONLY_TEST_OUTPUT_INSIDE_REPOSITORY: $($_.Exception.Message)";exit 2}
}elseif([string]::IsNullOrWhiteSpace($OutputPath)){$OutputPath=Join-Path $ProjectRoot 'results\tables\M03A_6_tool_regression.csv'}
$Results=New-Object Collections.Generic.List[object]
$TempBase=[IO.Path]::GetFullPath([IO.Path]::GetTempPath()).TrimEnd('\','/')
$TempRoot=Join-Path $TempBase('LiNRR_M03A6_TEST_'+[guid]::NewGuid().ToString('N'))
[void][IO.Directory]::CreateDirectory($TempRoot)
$ExtraCleanup=New-Object Collections.Generic.List[string]

function Add-Result([string]$Id,[string]$Name,[string]$Expected,[string]$Actual,[string]$Status,[string]$Detail=''){[void]$Results.Add([pscustomobject][ordered]@{test_id=$Id;test_name=$Name;expected=$Expected;actual=$Actual;status=$Status;detail=$Detail})}
function Invoke-Case([string]$Id,[string]$Name,[scriptblock]$Body){if(-not[string]::IsNullOrWhiteSpace($OnlyTestId)-and$Id-cne$OnlyTestId){return};try{&$Body;Add-Result $Id $Name PASS PASS PASS}catch{Add-Result $Id $Name PASS UNEXPECTED FAIL $_.Exception.Message}}
function New-Row([string[]]$Columns,[hashtable]$Values){$O=[ordered]@{};foreach($C in $Columns){$O[$C]=if($Values.ContainsKey($C)){[string]$Values[$C]}else{''}};return [pscustomobject]$O}
function New-Package([string]$Name){$Root=Join-Path $TempRoot $Name;[void](Initialize-M03A6AcquisitionPackage $Root $ProjectRoot);return $Root}
function Write-Data([string]$Path,[string]$Text){Write-M03A6Utf8NoBomText $Path $Text;return [pscustomobject]@{path=$Path;size=([long](Get-Item -LiteralPath $Path).Length).ToString([Globalization.CultureInfo]::InvariantCulture);hash=Get-M03A6Sha256 $Path}}
function ConvertTo-ProcessArgument([string]$Value){if($Value-notmatch'[\s"]'){return $Value};return '"'+$Value.Replace('"','\"')+'"'}
function Invoke-ProcessCapture([string]$FileName,[string[]]$Arguments){
    $Info=New-Object Diagnostics.ProcessStartInfo;$Info.FileName=$FileName;$Info.Arguments=(@($Arguments|ForEach-Object{ConvertTo-ProcessArgument $_})-join' ');$Info.UseShellExecute=$false;$Info.RedirectStandardOutput=$true;$Info.RedirectStandardError=$true;$Info.CreateNoWindow=$true
    $Process=New-Object Diagnostics.Process;$Process.StartInfo=$Info;$OutReader=$null;$ErrReader=$null
    try{[void]$Process.Start();$OutReader=$Process.StandardOutput;$ErrReader=$Process.StandardError;$StdOut=$OutReader.ReadToEnd();$StdErr=$ErrReader.ReadToEnd();$Process.WaitForExit();$ExitCode=$Process.ExitCode}
    finally{if($null-ne$OutReader){$OutReader.Dispose()};if($null-ne$ErrReader){$ErrReader.Dispose()};$Process.Dispose()}
    return [pscustomobject]@{ExitCode=$ExitCode;StdOut=$StdOut;StdErr=$StdErr}
}

function Publish-M03A6RegressionResultAtomically {
    param(
        [Parameter(Mandatory=$true)][object[]]$Rows,
        [Parameter(Mandatory=$true)][string[]]$ExpectedIds,
        [Parameter(Mandatory=$true)][string]$TargetPath,
        [ValidateSet('NONE','BEFORE_REPLACE','AFTER_REPLACE')][string]$InjectFailureAt='NONE'
    )
    $Columns=@('test_id','test_name','expected','actual','status','detail')
    $Target=[IO.Path]::GetFullPath($TargetPath);$Parent=[IO.Path]::GetDirectoryName($Target)
    if(-not[IO.Directory]::Exists($Parent)){throw "REGRESSION_OUTPUT_PARENT_MISSING: $Parent"}
    $Guid=[guid]::NewGuid().ToString('N');$Temp=Join-Path $Parent ('.M03A6_REGRESSION_'+$Guid+'.tmp');$Backup=Join-Path $Parent ('.M03A6_REGRESSION_'+$Guid+'.bak');$RollbackDiscard=Join-Path $Parent ('.M03A6_REGRESSION_'+$Guid+'.rollback')
    if([IO.Path]::GetPathRoot($Temp)-cne[IO.Path]::GetPathRoot($Target)){throw 'REGRESSION_OUTPUT_VOLUME_MISMATCH'}
    $TargetExisted=[IO.File]::Exists($Target);$OriginalBytes=if($TargetExisted){[IO.File]::ReadAllBytes($Target)}else{$null}
    $TempCreated=$false;$ReplaceStarted=$false;$TargetReplaced=$false;$BackupCreated=$false;$BackupDeleted=$false
    try{
        Write-M03A6Utf8NoBomCsv $Columns $Rows $Temp;$TempCreated=$true
        [void](Assert-M03A6Rfc4180Utf8NoBom $Temp -RequireDataRow)
        $Verify=@(Import-M03A6Csv $Temp $Columns -ExactHeader);$Ids=@($Verify|ForEach-Object{$_.test_id})
        if($Verify.Count-ne$ExpectedIds.Count-or($Ids-join',')-cne($ExpectedIds-join',')){throw 'REGRESSION_ID_SEQUENCE_INVALID'}
        if(@($Ids|Select-Object -Unique).Count-ne$ExpectedIds.Count){throw 'REGRESSION_ID_SEQUENCE_INVALID'}
        if(@($Verify|Where-Object{$_.status-cne'PASS'}).Count){throw 'REGRESSION_OUTPUT_CONTAINS_FAILURE'}
        if($InjectFailureAt-eq'BEFORE_REPLACE'){throw 'INJECTED_REGRESSION_PUBLISH_BEFORE_REPLACE'}
        $ReplaceStarted=$true
        if($TargetExisted){[IO.File]::Replace($Temp,$Target,$Backup);$TempCreated=$false;$TargetReplaced=$true;$BackupCreated=[IO.File]::Exists($Backup)}
        else{[IO.File]::Move($Temp,$Target);$TempCreated=$false;$TargetReplaced=$true}
        if($InjectFailureAt-eq'AFTER_REPLACE'){throw 'INJECTED_REGRESSION_PUBLISH_AFTER_REPLACE'}
        if($BackupCreated){[IO.File]::Delete($Backup);$BackupCreated=$false;$BackupDeleted=$true}else{$BackupDeleted=$true}
        if([IO.File]::Exists($Temp)-or[IO.File]::Exists($Backup)-or[IO.File]::Exists($RollbackDiscard)){throw 'REGRESSION_PUBLISH_RESIDUAL_FILE'}
        return [pscustomobject]@{TargetPath=$Target;TempCreated=$TempCreated;ReplaceStarted=$ReplaceStarted;TargetReplaced=$TargetReplaced;BackupCreated=$BackupCreated;BackupDeleted=$BackupDeleted}
    }catch{
        $OriginalFailure=$_.Exception;$RollbackFailure=$null
        try{
            if($TargetReplaced){
                if($TargetExisted){
                    if(-not[IO.File]::Exists($Backup)){throw "REGRESSION_PUBLISH_BACKUP_MISSING: $Backup"}
                    [IO.File]::Replace($Backup,$Target,$RollbackDiscard);$BackupCreated=$false
                    $Restored=[IO.File]::ReadAllBytes($Target)
                    if($Restored.Length-ne$OriginalBytes.Length){throw 'REGRESSION_PUBLISH_ROLLBACK_BYTE_MISMATCH'}
                    for($I=0;$I-lt$Restored.Length;$I++){if($Restored[$I]-ne$OriginalBytes[$I]){throw 'REGRESSION_PUBLISH_ROLLBACK_BYTE_MISMATCH'}}
                    if([IO.File]::Exists($RollbackDiscard)){[IO.File]::Delete($RollbackDiscard)}
                }elseif([IO.File]::Exists($Target)){[IO.File]::Delete($Target)}
            }
            if([IO.File]::Exists($Temp)){[IO.File]::Delete($Temp);$TempCreated=$false}
            if([IO.File]::Exists($Backup)){[IO.File]::Delete($Backup);$BackupCreated=$false}
            if([IO.File]::Exists($RollbackDiscard)){[IO.File]::Delete($RollbackDiscard)}
        }catch{$RollbackFailure=$_.Exception}
        if($null-ne$RollbackFailure){throw "REGRESSION_PUBLISH_ROLLBACK_FATAL: backup=$Backup; rollback_discard=$RollbackDiscard; original=$($OriginalFailure.Message); rollback=$($RollbackFailure.Message)"}
        throw $OriginalFailure
    }
}

function Get-M03A6CaseAlias([string]$RelativePath){
    $Chars=$RelativePath.ToCharArray();$Changed=$false
    for($I=0;$I-lt$Chars.Length;$I++){if([char]::IsLetter($Chars[$I])){$Replacement=if([char]::IsUpper($Chars[$I])){[char]::ToLowerInvariant($Chars[$I])}else{[char]::ToUpperInvariant($Chars[$I])};if($Replacement-cne$Chars[$I]){$Chars[$I]=$Replacement;$Changed=$true;break}}}
    $Alias=-join$Chars;if(-not$Changed-or$Alias-ceq$RelativePath-or-not$Alias.Equals($RelativePath,[StringComparison]::OrdinalIgnoreCase)){throw 'CASE_ALIAS_CONSTRUCTION_FAILED'};return $Alias
}
function Set-M03A6CaseEnumerationTestHook([AllowNull()][object]$Hook){$Module=Get-Module LiNRR_M03A6_Acquisition;if($null-eq$Module){throw 'ACQUISITION_MODULE_NOT_LOADED'};&$Module{param($Value)$script:M03A6CaseEnumerationTestHook=$Value}$Hook}
function Test-M03A6CaseEnumerationTestHookCleared {$Module=Get-Module LiNRR_M03A6_Acquisition;if($null-eq$Module){return $false};return [bool](&$Module{$null-eq$script:M03A6CaseEnumerationTestHook})}
function Add-M03A6TestLedgerRow([string]$LedgerPath,[string]$RelativePath,[string]$SizeBytes,[string]$Sha256){$Rows=New-Object Collections.Generic.List[object];foreach($Row in @(Import-M03A6Csv $LedgerPath (Get-M03A6Schema Ledger) -ExactHeader)){[void]$Rows.Add($Row)};if($Rows.Count-eq0){throw 'TEST_LEDGER_SEED_REQUIRED'};$Seed=$Rows[0];[void]$Rows.Add((New-Row (Get-M03A6Schema Ledger) @{ledger_version=$Seed.ledger_version;relative_path=$RelativePath;size_bytes=$SizeBytes;sha256=$Sha256;frozen_at=$Seed.frozen_at;timezone_offset=$Seed.timezone_offset;tool_version=$Seed.tool_version}));Write-M03A6Utf8NoBomCsv (Get-M03A6Schema Ledger) $Rows (Get-M03A6NormalizedFullPath $LedgerPath)}

function New-CompletePackage([string]$Name,[string]$Origin='EXPERIMENTAL',[string]$Mutation='NONE'){
    $Root=New-Package $Name;$Inv=New-Object Collections.Generic.List[object];$Eis=New-Object Collections.Generic.List[object]
    $RepCount=if($Mutation-eq'MISSING_REPLICATE'){2}else{3}
    for($I=1;$I-le$RepCount;$I++){
        $Sample='SAMPLE_A';$Cell='CELL_A';$Rep="REP_$I";if($Mutation-eq'DUPLICATE_REPLICATE'-and$I-eq 3){$Rep='REP_2'};if($Mutation-eq'CROSS_SAMPLE_REPLICATE'-and$I-eq 3){$Sample='SAMPLE_B';$Rep='REP_2'}
        $RawRel="raw/eis/raw_$I.dat";$NormRel="normalized/eis/norm_$I.csv";if($Mutation-eq'RAW_NORMALIZED_COLLISION'-and$I-eq 1){$NormRel=$RawRel}
        $Raw=Write-Data(Join-Path $Root $RawRel)"SYNTHETIC TEST RAW $I`r`n"
        $NormText="frequency,z_real,z_imag`r`n100000,4.1,0.2`r`n100000,4.2,-0.1`r`n1000,6.3,-1.2`r`n";if($Mutation-eq'INVALID_NORMALIZED_SCHEMA'-and$I-eq 1){$NormText="frequency,z_real,extra`r`n1000,1,2`r`n"};if($Mutation-eq'INVALID_NORMALIZED_NUMERIC'-and$I-eq 1){$NormText="frequency,z_real,z_imag`r`nNaN,1,2`r`n"};if($Mutation-eq'EMPTY_NORMALIZED'-and$I-eq 1){$NormText="frequency,z_real,z_imag`r`n"}
        if($NormRel-ne$RawRel){$Norm=Write-Data(Join-Path $Root $NormRel)$NormText}else{$Norm=$Raw}
        $InvSample=$Sample;$InvCell=$Cell;if($Mutation-eq'SAMPLE_MISMATCH'-and$I-eq 1){$InvSample='OTHER_SAMPLE'};if($Mutation-eq'CELL_MISMATCH'-and$I-eq 1){$InvCell='OTHER_CELL'}
        [void]$Inv.Add((New-Row(Get-M03A6Schema Inventory)@{relative_path=$RawRel;evidence_role='EIS_RAW';sample_id=$InvSample;cell_id=$InvCell;replicate_id=$Rep;data_origin=$Origin;status='MEASURED';notes='SYNTHETIC SOFTWARE TEST'}));[void]$Inv.Add((New-Row(Get-M03A6Schema Inventory)@{relative_path=$NormRel;evidence_role='EIS_NORMALIZED';sample_id=$Sample;cell_id=$Cell;replicate_id=$Rep;data_origin=$Origin;status='MEASURED';notes='SYNTHETIC SOFTWARE TEST'}))
        $When=if($Mutation-eq'MISSING_TIMEZONE'-and$I-eq 1){'2026-01-01T10:00:00'}else{"2026-01-0${I}T10:00:00+08:00"}
        [void]$Eis.Add((New-Row(Get-M03A6Schema Eis)@{sample_id=$Sample;cell_id=$Cell;replicate_id=$Rep;operator='SYNTHETIC_OPERATOR';measurement_datetime=$When;instrument='SYNTHETIC_INSTRUMENT';instrument_software='SYNTHETIC_SOFTWARE';raw_file_path=$RawRel;raw_file_size_bytes=$Raw.size;raw_file_sha256=$Raw.hash;normalized_table_path=$NormRel;normalized_table_size_bytes=$Norm.size;normalized_table_sha256=$Norm.hash;frequency_unit='Hz';impedance_unit='ohm';frequency_min_Hz='1000';frequency_max_Hz='100000';points_per_decade='2';perturbation_amplitude_V='0.01';dc_condition='OCP';temperature_K='300';electrolyte_composition='SYNTHETIC_COMPOSITION';electrolyte_batch='SYNTHETIC_BATCH';salt_concentration_mol_L='1';water_content='1';water_content_unit='ppm';water_content_method='SYNTHETIC_METHOD';gas_atmosphere='N2';pressure_Pa='100000';flow_rate_m3_s='0.000001';stabilization_time_s='60';eis_area_basis='EIS_area';eis_area_m2='0.0001';source_notebook_reference='SYNTHETIC_REFERENCE';data_origin=$Origin;status='MEASURED';notes='SYNTHETIC SOFTWARE TEST ONLY'}))
    }
    $Series=New-Object Collections.Generic.List[object];foreach($Component in @('fixture','contact','membrane','other_series')){if($Mutation-eq'MISSING_SERIES'-and$Component-eq'contact'){continue};$Rel="raw/series_resistance/$Component.dat";$D=Write-Data(Join-Path $Root $Rel)"SYNTHETIC $Component`r`n";[void]$Series.Add((New-Row(Get-M03A6Schema Series)@{sample_id='SAMPLE_A';component_name=$Component;value_ohm='1';uncertainty_ohm='0.1';unit='ohm';method='SYNTHETIC_METHOD';replicate_count='3';temperature_K='300';source_reference='SYNTHETIC_REFERENCE';raw_evidence_path=$Rel;raw_evidence_size_bytes=$D.size;raw_evidence_sha256=$D.hash;data_origin=$Origin;status='MEASURED';notes='SYNTHETIC SOFTWARE TEST'}));[void]$Inv.Add((New-Row(Get-M03A6Schema Inventory)@{relative_path=$Rel;evidence_role='SERIES_RESISTANCE';sample_id='SAMPLE_A';data_origin=$Origin;status='MEASURED';notes='SYNTHETIC SOFTWARE TEST'}))}
    $Areas=New-Object Collections.Generic.List[object];foreach($Quantity in @('electrode_spacing','out_of_plane_depth','geometric_electrode_area','EIS_area','current_density_reporting_area')){if($Mutation-eq'MISSING_AREA'-and$Quantity-eq'EIS_area'){continue};$Rel="raw/geometry_area/$Quantity.dat";$D=Write-Data(Join-Path $Root $Rel)"SYNTHETIC $Quantity`r`n";$Unit=if($Quantity-in@('electrode_spacing','out_of_plane_depth')){'m'}else{'m^2'};[void]$Areas.Add((New-Row(Get-M03A6Schema Area)@{sample_id='SAMPLE_A';quantity_name=$Quantity;value_SI='0.001';uncertainty_SI='0.0001';unit=$Unit;measurement_method='SYNTHETIC_METHOD';source_reference='SYNTHETIC_REFERENCE';raw_evidence_path=$Rel;raw_evidence_size_bytes=$D.size;raw_evidence_sha256=$D.hash;data_origin=$Origin;status='MEASURED';definition='SYNTHETIC DEFINITION';notes='SYNTHETIC SOFTWARE TEST'}));[void]$Inv.Add((New-Row(Get-M03A6Schema Inventory)@{relative_path=$Rel;evidence_role='GEOMETRY_AREA';sample_id='SAMPLE_A';data_origin=$Origin;status='MEASURED';notes='SYNTHETIC SOFTWARE TEST'}))}
    $Direct=New-Object Collections.Generic.List[object];if($Mutation-ne'MISSING_DIRECT'){$Rel='raw/direct_conductivity/direct.dat';if($Mutation-eq'HASHES_EVIDENCE'){$Rel='hashes/direct.dat'};if($Mutation-eq'REPORTS_EVIDENCE'){$Rel='reports/direct.dat'};if($Mutation-eq'ROLE_DIRECTORY_MISMATCH'){$Rel='raw/eis/direct.dat'};$D=Write-Data(Join-Path $Root $Rel)"SYNTHETIC DIRECT`r`n";[void]$Direct.Add((New-Row(Get-M03A6Schema Direct)@{sample_id='SAMPLE_A';conductivity_S_m='1';uncertainty_S_m='0.1';unit='S/m';temperature_K='300';method='SYNTHETIC_METHOD';cell_constant='1';cell_constant_unit='1/m';calibration_standard='SYNTHETIC_STANDARD';instrument='SYNTHETIC_INSTRUMENT';raw_evidence_path=$Rel;raw_evidence_size_bytes=$D.size;raw_evidence_sha256=$D.hash;source_reference='SYNTHETIC_REFERENCE';data_origin=$Origin;status='MEASURED';notes='SYNTHETIC SOFTWARE TEST'}));[void]$Inv.Add((New-Row(Get-M03A6Schema Inventory)@{relative_path=$Rel;evidence_role='DIRECT_CONDUCTIVITY';sample_id='SAMPLE_A';data_origin=$Origin;status='MEASURED';notes='SYNTHETIC SOFTWARE TEST'}))}
    if($Mutation-eq'UNKNOWN_ROLE'){$Rel='raw/eis/unknown.dat';[void](Write-Data(Join-Path $Root $Rel)"SYNTHETIC UNKNOWN`r`n");[void]$Inv.Add((New-Row(Get-M03A6Schema Inventory)@{relative_path=$Rel;evidence_role='ALIEN_ROLE';sample_id='SAMPLE_A';data_origin=$Origin;status='MEASURED'}))}
    if($Mutation-in@('ORPHAN_SERIES','UNKNOWN_SERIES')){$Component=if($Mutation-eq'UNKNOWN_SERIES'){'alien_component'}else{'fixture'};$Rel="raw/series_resistance/${Mutation}.dat";$D=Write-Data(Join-Path $Root $Rel)"SYNTHETIC EXTRA SERIES`r`n";$Sample=if($Mutation-eq'ORPHAN_SERIES'){'ORPHAN'}else{'SAMPLE_A'};[void]$Series.Add((New-Row(Get-M03A6Schema Series)@{sample_id=$Sample;component_name=$Component;value_ohm='1';uncertainty_ohm='0.1';unit='ohm';method='SYN';replicate_count='1';temperature_K='300';source_reference='SYN';raw_evidence_path=$Rel;raw_evidence_size_bytes=$D.size;raw_evidence_sha256=$D.hash;data_origin=$Origin;status='MEASURED'}));[void]$Inv.Add((New-Row(Get-M03A6Schema Inventory)@{relative_path=$Rel;evidence_role='SERIES_RESISTANCE';sample_id=$Sample;data_origin=$Origin;status='MEASURED'}))}
    if($Mutation-in@('ORPHAN_AREA','UNKNOWN_AREA')){$Quantity=if($Mutation-eq'UNKNOWN_AREA'){'alien_quantity'}else{'EIS_area'};$Rel="raw/geometry_area/${Mutation}.dat";$D=Write-Data(Join-Path $Root $Rel)"SYNTHETIC EXTRA AREA`r`n";$Sample=if($Mutation-eq'ORPHAN_AREA'){'ORPHAN'}else{'SAMPLE_A'};[void]$Areas.Add((New-Row(Get-M03A6Schema Area)@{sample_id=$Sample;quantity_name=$Quantity;value_SI='1';uncertainty_SI='0.1';unit='m^2';measurement_method='SYN';source_reference='SYN';raw_evidence_path=$Rel;raw_evidence_size_bytes=$D.size;raw_evidence_sha256=$D.hash;data_origin=$Origin;status='MEASURED';definition='SYN'}));[void]$Inv.Add((New-Row(Get-M03A6Schema Inventory)@{relative_path=$Rel;evidence_role='GEOMETRY_AREA';sample_id=$Sample;data_origin=$Origin;status='MEASURED'}))}
    if($Mutation-eq'ORPHAN_DIRECT'){$Rel='raw/direct_conductivity/orphan.dat';$D=Write-Data(Join-Path $Root $Rel)"SYNTHETIC ORPHAN DIRECT`r`n";[void]$Direct.Add((New-Row(Get-M03A6Schema Direct)@{sample_id='ORPHAN';conductivity_S_m='1';uncertainty_S_m='0.1';unit='S/m';temperature_K='300';method='SYN';cell_constant='1';cell_constant_unit='1/m';calibration_standard='SYN';instrument='SYN';raw_evidence_path=$Rel;raw_evidence_size_bytes=$D.size;raw_evidence_sha256=$D.hash;source_reference='SYN';data_origin=$Origin;status='MEASURED'}));[void]$Inv.Add((New-Row(Get-M03A6Schema Inventory)@{relative_path=$Rel;evidence_role='DIRECT_CONDUCTIVITY';sample_id='ORPHAN';data_origin=$Origin;status='MEASURED'}))}
    if($Mutation-eq'PATH_ESCAPE'){$Inv[0].relative_path='../outside.dat';$Eis[0].raw_file_path='../outside.dat'}
    Write-M03A6Utf8NoBomCsv(Get-M03A6Schema Inventory)$Inv(Join-Path $Root 'FILE_INVENTORY.csv');Write-M03A6Utf8NoBomCsv(Get-M03A6Schema Eis)$Eis(Join-Path $Root 'metadata/EIS_METADATA.csv');Write-M03A6Utf8NoBomCsv(Get-M03A6Schema Series)$Series(Join-Path $Root 'metadata/SERIES_RESISTANCE_EVIDENCE.csv');Write-M03A6Utf8NoBomCsv(Get-M03A6Schema Area)$Areas(Join-Path $Root 'metadata/GEOMETRY_AREA_EVIDENCE.csv');Write-M03A6Utf8NoBomCsv(Get-M03A6Schema Direct)$Direct(Join-Path $Root 'metadata/DIRECT_CONDUCTIVITY_EVIDENCE.csv')
    $Freeze=Freeze-M03A6ExperimentalEvidence $Root v001;return [pscustomobject]@{Root=$Root;Ledger=$Freeze.LedgerPath;Freeze=$Freeze}
}

function Invoke-Blocked([string]$Id,[string]$Name,[string]$Mutation,[string]$Code,[string]$Origin='EXPERIMENTAL'){
    $Body={ $P=New-CompletePackage("pkg_"+$Id)$Origin $Mutation;$R=Invoke-M03A6Preflight $P.Root $P.Ledger $ProjectRoot;if($R.Status-ne'PRE_INTAKE_BLOCKED'-or-not@($R.Findings|Where-Object code -eq $Code).Count){throw "expected $Code; got $((@($R.Findings.code|Select-Object -Unique))-join',')"} }.GetNewClosure();Invoke-Case $Id $Name $Body
}

try{
    Invoke-Case A001 'external initialization and true empty READY' {$R=New-Package init;if((Invoke-M03A6Preflight $R '' $ProjectRoot).Status-ne'ACQUISITION_PACKAGE_READY'){throw 'not ready'}}
    Invoke-Case A002 'repository destination rejected' {$Caught=$false;try{[void](Initialize-M03A6AcquisitionPackage(Join-Path $ProjectRoot 'changes/blocked')$ProjectRoot)}catch{$Caught=$_.Exception.Message-like'*BLOCKED_DESTINATION_INSIDE_REPOSITORY*'};if(-not$Caught){throw 'accepted'}}
    Invoke-Case A003 'existing nonempty target blocked and preserved' {$R=Join-Path $TempRoot nonempty;[void][IO.Directory]::CreateDirectory($R);[void](Write-Data (Join-Path $R user.txt) 'USER');$Caught=$false;try{[void](Initialize-M03A6AcquisitionPackage $R $ProjectRoot)}catch{$Caught=$true};if(-not$Caught-or-not[IO.File]::Exists((Join-Path $R user.txt))){throw 'not preserved'}}
    Invoke-Case A004 'exact Int64 adjacent above 2^53' {$A=ConvertTo-M03A6Int64Exact '9007199254740992';$B=ConvertTo-M03A6Int64Exact '9007199254740993';if($B-$A-ne 1){throw 'precision'}}
    Invoke-Case A005 'freeze raw size hash timestamp unchanged' {$P=New-CompletePackage rawstate;if(-not$P.Freeze.RawBytesUnchanged-or-not$P.Freeze.RawTimestampUnchanged){throw 'raw changed'}}
    Invoke-Case A006 'same ledger version blocked' {$R=New-Package ledger;[void](Freeze-M03A6ExperimentalEvidence $R v001);$Caught=$false;try{[void](Freeze-M03A6ExperimentalEvidence $R v001)}catch{$Caught=$true};if(-not$Caught){throw 'overwrite'}}
    Invoke-Case A007 'evidence child junction blocked' {$R=New-Package childjunction;[IO.Directory]::Delete((Join-Path $R 'raw/eis'));$T=Join-Path $TempRoot childtarget;[void][IO.Directory]::CreateDirectory($T);[void](New-Item -ItemType Junction -Path(Join-Path $R 'raw/eis')-Target $T -ErrorAction Stop);$P=Invoke-M03A6Preflight $R '' $ProjectRoot;if(-not@($P.Findings|Where-Object code -eq 'BLOCKED_PATH_REPARSE_POINT').Count){throw 'junction not blocked'}}
    Invoke-Blocked A008 'path escape blocked' PATH_ESCAPE BLOCKED_PATH_BOUNDARY_ESCAPE
    Invoke-Blocked A009 'raw normalized collision blocked' RAW_NORMALIZED_COLLISION BLOCKED_CONFLICTING_EVIDENCE_ROLE
    Invoke-Blocked A010 'missing replicate blocked' MISSING_REPLICATE BLOCKED_MISSING_REPLICATE
    Invoke-Blocked A011 'duplicate replicate blocked' DUPLICATE_REPLICATE BLOCKED_DUPLICATE_REPLICATE_ID
    Invoke-Blocked A012 'missing timezone blocked' MISSING_TIMEZONE BLOCKED_MISSING_TIMEZONE
    Invoke-Blocked A013 'missing series blocked' MISSING_SERIES BLOCKED_SERIES_CARDINALITY
    Invoke-Blocked A014 'missing area blocked' MISSING_AREA BLOCKED_AREA_CARDINALITY
    Invoke-Blocked A015 'missing direct blocked' MISSING_DIRECT BLOCKED_DIRECT_CARDINALITY
    Invoke-Case A016 'unsupported profile blocked' {$Caught=$false;try{[void](Prepare-M03A6NormalizedEis(Join-Path $ProjectRoot 'tests/fixtures/M03A_6/synthetic_eis_source.csv')(Join-Path $TempRoot u.csv)'UNKNOWN')}catch{$Caught=$_.Exception.Message-like'*UNSUPPORTED_PROFILE*'};if(-not$Caught){throw 'accepted'}}
    Invoke-Case A017 'duplicate inductive order retained' {$O=Join-Path $TempRoot norm.csv;$X=Prepare-M03A6NormalizedEis(Join-Path $ProjectRoot 'tests/fixtures/M03A_6/synthetic_eis_source.csv')$O EXPLICIT_RFC4180_COLUMN_MAP freq_source zr_source zi_source;$Rows=@(Import-Csv $O);if($Rows.Count-ne 4-or@($Rows|Where-Object frequency -eq '100000').Count-ne 2-or[double]$Rows[0].z_imag-le 0){throw 'rows changed'}}
    Invoke-Blocked A018 'synthetic origin isolation' NONE BLOCKED_NONEXPERIMENTAL_ORIGIN SYNTHETIC
    Invoke-Case A019 'M03B always false' {$P=New-CompletePackage gates;$R=Invoke-M03A6Preflight $P.Root $P.Ledger $ProjectRoot;if($R.M03BReady-or$R.M03BCandidate-or$R.ExperimentalInputComplete){throw 'gate opened'}}
    Invoke-Case A020 'BOM and LF rejected' {$B=Join-Path $TempRoot bom.csv;[IO.File]::WriteAllText($B,"a,b`r`n1,2`r`n",[Text.UTF8Encoding]::new($true));$L=Join-Path $TempRoot lf.csv;[IO.File]::WriteAllText($L,"a,b`n1,2`n",[Text.UTF8Encoding]::new($false));foreach($P in @($B,$L)){$C=$false;try{Assert-M03A6Rfc4180Utf8NoBom $P|Out-Null}catch{$C=$true};if(-not$C){throw 'accepted'}}}
    Invoke-Case A021 'M03A6 framework paths frozen against M03A6 commit' {$B='6f4d4520a465f03339f132683cdb88cc70bdb28a';foreach($P in @(git -C $ProjectRoot ls-tree -r --name-only $B)){if($P-in@('tests/fixtures/M03A_6/synthetic_eis_source.csv','tests/powershell/Test_M03A_6_Acquisition.ps1','results/tables/M03A_6_tool_regression.csv')){continue};if($P-notmatch'(^|/)(M03A_6|M03A6)' -and$P-notmatch'^tests/powershell/Test_M03A_6'){continue};git -C $ProjectRoot diff --quiet $B -- $P;if($LASTEXITCODE){throw $P}}}
    Invoke-Case A022 'D0017 append-only with resources disposed' {$B='6c5fb2dc81be4f79891645510bffce36d7fa00c0';$I=New-Object Diagnostics.ProcessStartInfo;$I.FileName='git.exe';$I.Arguments="-C `"$ProjectRoot`" cat-file blob $B`:docs/DECISIONS.md";$I.UseShellExecute=$false;$I.RedirectStandardOutput=$true;$I.CreateNoWindow=$true;$P=New-Object Diagnostics.Process;$P.StartInfo=$I;$M=New-Object IO.MemoryStream;try{[void]$P.Start();$P.StandardOutput.BaseStream.CopyTo($M);$P.WaitForExit();$BB=$M.ToArray()}finally{$M.Dispose();$P.Dispose()};$C=[IO.File]::ReadAllBytes((Join-Path $ProjectRoot 'docs/DECISIONS.md'));for($N=0;$N-lt$BB.Length;$N++){if($C[$N]-ne$BB[$N]){throw 'prefix'}}}
    Invoke-Case A023 'all CLI entry points' {$R=Join-Path $TempRoot cli;$Base=@('-NoProfile','-ExecutionPolicy','Bypass','-File');$C19=Invoke-ProcessCapture 'powershell.exe' ($Base+@((Join-Path $ProjectRoot 'scripts/windows/19_initialize_M03A_6_acquisition_package.ps1'),'-DestinationRoot',$R));if($C19.ExitCode-ne 0-or$C19.StdOut-notlike'*ACQUISITION_PACKAGE_READY=*'){throw "CLI19 exit=$($C19.ExitCode) stderr=$($C19.StdErr)"};$C22=Invoke-ProcessCapture 'powershell.exe' ($Base+@((Join-Path $ProjectRoot 'scripts/windows/22_preflight_M03A_6_experimental_evidence.ps1'),'-PackageRoot',$R));if($C22.ExitCode-ne 0-or$C22.StdOut.Trim()-cne'ACQUISITION_PACKAGE_READY'){throw "CLI22 exit=$($C22.ExitCode) stdout=$($C22.StdOut) stderr=$($C22.StdErr)"};$O=Join-Path $R 'normalized/eis/cli.csv';$C21=Invoke-ProcessCapture 'powershell.exe' ($Base+@((Join-Path $ProjectRoot 'scripts/windows/21_prepare_M03A_6_normalized_eis.ps1'),'-InputPath',(Join-Path $ProjectRoot 'tests/fixtures/M03A_6/synthetic_eis_source.csv'),'-OutputPath',$O,'-ParserProfile','EXPLICIT_RFC4180_COLUMN_MAP','-FrequencyColumn','freq_source','-ZRealColumn','zr_source','-ZImagColumn','zi_source'));foreach($Marker in @('ROWS_RETAINED=4','M03A6_RAW_BYTES_UNCHANGED=PASS','M03A6_RAW_TIMESTAMP_UNCHANGED=PASS')){if($C21.StdOut-notlike"*$Marker*"){throw "CLI21 missing $Marker"}};if($C21.ExitCode-ne 0-or-not[IO.File]::Exists($O)-or-not[IO.File]::Exists($O+'.row_mapping.csv')-or-not[IO.File]::Exists($O+'.conversion_provenance.csv')){throw "CLI21 exit=$($C21.ExitCode) stderr=$($C21.StdErr)"};$C20=Invoke-ProcessCapture 'powershell.exe' ($Base+@((Join-Path $ProjectRoot 'scripts/windows/20_freeze_M03A_6_experimental_evidence.ps1'),'-PackageRoot',$R,'-LedgerVersion','cli'));foreach($Marker in @('M03A6_EXACT_HASH_LEDGER=PASS','M03A6_RAW_BYTES_UNCHANGED=PASS','M03A6_RAW_TIMESTAMP_UNCHANGED=PASS')){if($C20.StdOut-notlike"*$Marker*"){throw "CLI20 missing $Marker"}};if($C20.ExitCode-ne 0){throw "CLI20 exit=$($C20.ExitCode) stderr=$($C20.StdErr)"}}
    Invoke-Case A024 'repository destination junction ancestor blocked' {$Link=Join-Path $TempRoot repo_link;[void](New-Item -ItemType Junction -Path $Link -Target(Join-Path $ProjectRoot 'changes')-ErrorAction Stop);$Caught=$false;try{[void](Initialize-M03A6AcquisitionPackage(Join-Path $Link blocked)$ProjectRoot)}catch{$Caught=$_.Exception.Message-like'*BLOCKED_PATH_REPARSE_POINT*'};if(-not$Caught){throw 'bypass'}}
    Invoke-Case A025 'package root parent junction blocked' {$Target=Join-Path $TempRoot realparent;[void][IO.Directory]::CreateDirectory((Join-Path $Target package));$Link=Join-Path $TempRoot parentlink;[void](New-Item -ItemType Junction -Path $Link -Target $Target -ErrorAction Stop);$Caught=$false;try{[void](Freeze-M03A6ExperimentalEvidence(Join-Path $Link package)v1)}catch{$Caught=$_.Exception.Message-like'*BLOCKED_PATH_REPARSE_POINT*'};if(-not$Caught){throw 'bypass'}}
    Invoke-Case A026 'similar prefix outside repository allowed' {$Parent=Split-Path -Parent $ProjectRoot;$R=Join-Path $Parent((Split-Path -Leaf $ProjectRoot)+'_similar_'+[guid]::NewGuid().ToString('N'));[void]$ExtraCleanup.Add($R);[void](Initialize-M03A6AcquisitionPackage $R $ProjectRoot);if(-not[IO.Directory]::Exists($R)){throw 'false positive'}}
    Invoke-Case A027 'case slash dotdot repository bypass blocked' {$Candidate=(([IO.Path]::GetFullPath((Join-Path $ProjectRoot ('..\'+(Split-Path -Leaf $ProjectRoot)+'\changes\x')))).ToUpperInvariant()).Replace('\','/');$C=$false;try{[void](Initialize-M03A6AcquisitionPackage $Candidate $ProjectRoot)}catch{$C=$_.Exception.Message-like'*BLOCKED_DESTINATION_INSIDE_REPOSITORY*'};if(-not$C){throw 'bypass'}}
    Invoke-Case A028 'injected initializer failure leaves no destination' {$R=Join-Path $TempRoot injected;$Before=@(Get-ChildItem -LiteralPath $TempRoot -Directory -Filter '.M03A6_STAGING_*').Count;$C=$false;try{[void](Initialize-M03A6AcquisitionPackage $R $ProjectRoot AFTER_FILES)}catch{$C=$true};$After=@(Get-ChildItem -LiteralPath $TempRoot -Directory -Filter '.M03A6_STAGING_*').Count;if(-not$C-or[IO.Directory]::Exists($R)-or$Before-ne$After){throw 'partial'}}
    Invoke-Case A029 'existing empty target blocked and preserved' {$R=Join-Path $TempRoot emptyuser;[void][IO.Directory]::CreateDirectory($R);$C=$false;try{[void](Initialize-M03A6AcquisitionPackage $R $ProjectRoot)}catch{$C=$true};if(-not$C-or-not[IO.Directory]::Exists($R)){throw 'deleted'}}
    $Src=Join-Path $ProjectRoot 'tests/fixtures/M03A_6/synthetic_eis_source.csv'
    Invoke-Case A030 'output rowmap collision blocked' {$O=Join-Path $TempRoot c30.csv;$C=$false;try{[void](Prepare-M03A6NormalizedEis $Src $O EXPLICIT_RFC4180_COLUMN_MAP freq_source zr_source zi_source $O '')}catch{$C=$_.Exception.Message-like'*BLOCKED_NORMALIZED_PATH_COLLISION*'};if(-not$C){throw 'collision'}}
    Invoke-Case A031 'output provenance collision blocked' {$O=Join-Path $TempRoot c31.csv;$C=$false;try{[void](Prepare-M03A6NormalizedEis $Src $O EXPLICIT_RFC4180_COLUMN_MAP freq_source zr_source zi_source '' $O)}catch{$C=$_.Exception.Message-like'*BLOCKED_NORMALIZED_PATH_COLLISION*'};if(-not$C){throw 'collision'}}
    Invoke-Case A032 'rowmap provenance collision blocked' {$O=Join-Path $TempRoot c32.csv;$X=Join-Path $TempRoot same32.csv;$C=$false;try{[void](Prepare-M03A6NormalizedEis $Src $O EXPLICIT_RFC4180_COLUMN_MAP freq_source zr_source zi_source $X $X)}catch{$C=$_.Exception.Message-like'*BLOCKED_NORMALIZED_PATH_COLLISION*'};if(-not$C){throw 'collision'}}
    Invoke-Case A033 'input output collision blocked' {$C=$false;try{[void](Prepare-M03A6NormalizedEis $Src $Src EXPLICIT_RFC4180_COLUMN_MAP freq_source zr_source zi_source)}catch{$C=$_.Exception.Message-like'*BLOCKED_NORMALIZED_PATH_COLLISION*'};if(-not$C){throw 'collision'}}
    Invoke-Case A034 'dotdot normalized collision blocked' {$O=Join-Path $TempRoot c34.csv;$Alias=Join-Path $TempRoot 'x\..\c34.csv';$C=$false;try{[void](Prepare-M03A6NormalizedEis $Src $O EXPLICIT_RFC4180_COLUMN_MAP freq_source zr_source zi_source $Alias '')}catch{$C=$_.Exception.Message-like'*BLOCKED_NORMALIZED_PATH_COLLISION*'};if(-not$C){throw 'collision'}}
    Invoke-Case A035 'conversion provenance values, hashes, paths, and row mapping independently verified' {
        $O=Join-Path $TempRoot c35.csv;$X=Prepare-M03A6NormalizedEis $Src $O EXPLICIT_RFC4180_COLUMN_MAP freq_source zr_source zi_source;$P=@(Import-Csv -LiteralPath $X.ProvenancePath)[0]
        $ExpectedStrings=[ordered]@{tool_name='LiNRR M03A.6 acquisition tools';tool_version='M03A6_ACQUISITION_2.0.0';parser_profile='EXPLICIT_RFC4180_COLUMN_MAP';frequency_column='freq_source';z_real_column='zr_source';z_imag_column='zi_source'}
        foreach($Name in $ExpectedStrings.Keys){if([string]$P.$Name-cne$ExpectedStrings[$Name]){throw "provenance exact field $Name"}}
        $PathCases=@(@('input_path',$Src,$ProjectRoot,$Src.Substring($ProjectRoot.Length).TrimStart('\','/')),@('output_path',$O,$TempRoot,$O.Substring($TempRoot.Length).TrimStart('\','/')),@('row_mapping_path',$X.RowMappingPath,$TempRoot,$X.RowMappingPath.Substring($TempRoot.Length).TrimStart('\','/')))
        foreach($Case in $PathCases){$Declared=[string]$P.($Case[0]);if(-not[IO.Path]::IsPathRooted($Declared)){throw "relative provenance path $($Case[0])"};$Normalized=Get-M03A6NormalizedFullPath $Declared;if($Declared-cne$Normalized){throw "noncanonical provenance path $($Case[0])"};$ExpectedCanonical=(Resolve-M03A6CanonicalPackagePath $Case[2] $Case[3] -RequireFile).CanonicalFullPath;if(-not$Declared.Equals($ExpectedCanonical,[StringComparison]::OrdinalIgnoreCase)-or$Declared-cne$ExpectedCanonical){throw "wrong provenance path $($Case[0])"}}
        foreach($Case in @(@($P.input_path,$P.input_size_bytes,$P.input_sha256),@($P.output_path,$P.output_size_bytes,$P.output_sha256),@($P.row_mapping_path,$P.row_mapping_size_bytes,$P.row_mapping_sha256))){$Item=Get-Item -LiteralPath $Case[0];$ActualSize=[long]$Item.Length;$ActualHash=(Get-FileHash -LiteralPath $Case[0] -Algorithm SHA256).Hash.ToLowerInvariant();if((ConvertTo-M03A6Int64Exact $Case[1])-ne$ActualSize-or[string]$Case[2]-cne$ActualHash){throw "provenance exact bytes $($Case[0])"}}
        $SourceRows=@(Import-Csv -LiteralPath $Src);$OutputRows=@(Import-Csv -LiteralPath $O);$Map=@(Import-Csv -LiteralPath $X.RowMappingPath)
        $SourceCount=ConvertTo-M03A6Int64Exact $P.source_row_count;$OutputCount=ConvertTo-M03A6Int64Exact $P.output_row_count;if($SourceCount-ne$SourceRows.Count-or$OutputCount-ne$OutputRows.Count-or$Map.Count-ne$SourceRows.Count-or$SourceCount-ne$OutputCount){throw 'provenance row count'}
        $SeenSource=New-Object 'Collections.Generic.HashSet[string]' ([StringComparer]::Ordinal);$SeenOutput=New-Object 'Collections.Generic.HashSet[string]' ([StringComparer]::Ordinal)
        for($I=0;$I-lt$SourceRows.Count;$I++){
            if($OutputRows[$I].frequency-cne$SourceRows[$I].freq_source-or$OutputRows[$I].z_real-cne$SourceRows[$I].zr_source-or$OutputRows[$I].z_imag-cne$SourceRows[$I].zi_source){throw "normalized row mismatch $I"}
            foreach($Field in @('frequency','z_real','z_imag')){$Number=0.0;if(-not[double]::TryParse([string]$OutputRows[$I].$Field,[Globalization.NumberStyles]::Float,[Globalization.CultureInfo]::InvariantCulture,[ref]$Number)-or[double]::IsNaN($Number)-or[double]::IsInfinity($Number)-or($Field-eq'frequency'-and$Number-le0)){throw "normalized numeric $I/$Field"}}
            $ExpectedRow=($I+2).ToString([Globalization.CultureInfo]::InvariantCulture);if($Map[$I].source_row-cne$ExpectedRow-or$Map[$I].output_row-cne$ExpectedRow-or$Map[$I].row_action-cne'RETAINED'){throw "row mapping $I"};if(-not$SeenSource.Add($Map[$I].source_row)-or-not$SeenOutput.Add($Map[$I].output_row)){throw "duplicate row mapping $I"}
        }
        if(@($SourceRows|Where-Object freq_source -ceq '100000').Count-ne 2-or@($OutputRows|Where-Object frequency -ceq '100000').Count-ne 2){throw 'duplicate frequency not retained'}
        if(@($SourceRows|Where-Object{[double]::Parse($_.zi_source,[Globalization.CultureInfo]::InvariantCulture)-gt0}).Count-ne@($OutputRows|Where-Object{[double]::Parse($_.z_imag,[Globalization.CultureInfo]::InvariantCulture)-gt0}).Count){throw 'inductive row not retained'}
        $Dto=[DateTimeOffset]::MinValue;if(-not[DateTimeOffset]::TryParse($P.conversion_datetime,[Globalization.CultureInfo]::InvariantCulture,[Globalization.DateTimeStyles]::None,[ref]$Dto)-or$P.conversion_datetime-notmatch'[+-][0-9]{2}:[0-9]{2}$'-or[string]::IsNullOrWhiteSpace($P.conversion_timezone)-or$Dto.ToString('zzz',[Globalization.CultureInfo]::InvariantCulture)-cne$P.conversion_timezone){throw 'conversion datetime timezone'}
        foreach($Name in @('smoothing_applied','interpolation_applied','outlier_removal_applied','sorting_applied','hfr_calculated')){if([string]$P.$Name-cne'FALSE'){throw "$Name not exact FALSE"}}
    }
    Invoke-Blocked A036 'unknown evidence role blocked' UNKNOWN_ROLE BLOCKED_UNKNOWN_EVIDENCE_ROLE
    Invoke-Blocked A037 'role directory mismatch blocked' ROLE_DIRECTORY_MISMATCH BLOCKED_EVIDENCE_ROLE_DIRECTORY_MISMATCH
    Invoke-Blocked A038 'invalid normalized schema blocked' INVALID_NORMALIZED_SCHEMA BLOCKED_NORMALIZED_EIS_SCHEMA
    Invoke-Blocked A039 'invalid normalized numeric blocked' INVALID_NORMALIZED_NUMERIC BLOCKED_NORMALIZED_EIS_NUMERIC
    Invoke-Blocked A040 'sample mismatch blocked' SAMPLE_MISMATCH BLOCKED_CROSS_SAMPLE_EVIDENCE
    Invoke-Blocked A041 'cell mismatch blocked' CELL_MISMATCH BLOCKED_CROSS_CELL_EVIDENCE
    Invoke-Blocked A042 'cross sample replicate collision blocked' CROSS_SAMPLE_REPLICATE BLOCKED_DUPLICATE_REPLICATE_ID
    Invoke-Blocked A043 'orphan series blocked' ORPHAN_SERIES BLOCKED_ORPHAN_SERIES_SAMPLE
    Invoke-Blocked A044 'orphan area blocked' ORPHAN_AREA BLOCKED_ORPHAN_AREA_SAMPLE
    Invoke-Blocked A045 'orphan direct blocked' ORPHAN_DIRECT BLOCKED_ORPHAN_DIRECT_SAMPLE
    Invoke-Blocked A046 'unknown series component blocked' UNKNOWN_SERIES BLOCKED_UNKNOWN_SERIES_COMPONENT
    Invoke-Blocked A047 'unknown area quantity blocked' UNKNOWN_AREA BLOCKED_UNKNOWN_AREA_QUANTITY
    Invoke-Blocked A048 'hashes evidence blocked' HASHES_EVIDENCE BLOCKED_EVIDENCE_ROLE_DIRECTORY_MISMATCH
    Invoke-Blocked A049 'reports evidence blocked' REPORTS_EVIDENCE BLOCKED_EVIDENCE_ROLE_DIRECTORY_MISMATCH
    Invoke-Case A050 'unregistered file blocks header-only package' {$R=New-Package unregistered;[void](Write-Data (Join-Path $R 'raw/eis/file.dat') 'SYNTHETIC');$P=Invoke-M03A6Preflight $R '' $ProjectRoot;if(-not@($P.Findings|Where-Object code -eq 'BLOCKED_UNREGISTERED_EVIDENCE_FILE').Count){throw 'not blocked'}}
    Invoke-Case A051 'header-only template package ready' {$R=New-Package emptyready;if((Invoke-M03A6Preflight $R '' $ProjectRoot).Status-ne'ACQUISITION_PACKAGE_READY'){throw 'not ready'}}
    Invoke-Case A052 'complete experimental evidence received' {$P=New-CompletePackage received;$R=Invoke-M03A6Preflight $P.Root $P.Ledger $ProjectRoot;if($R.Status-ne'EXPERIMENTAL_EVIDENCE_RECEIVED'){throw((@($R.Findings|ForEach-Object{"$($_.code):$($_.detail)"}))-join'|')}}
    Invoke-Case A053 'evidence received does not open later gates' {$P=New-CompletePackage receivedgates;$R=Invoke-M03A6Preflight $P.Root $P.Ledger $ProjectRoot;if($R.ExperimentalInputComplete-or$R.M03BCandidate-or$R.M03BReady-or$R.ParameterTransferMode-ne'NOT_RUN'){throw 'gate'}}
    Invoke-Case A054 'actual hash mismatch rechecked' {$P=New-CompletePackage hashmismatch;$F=Join-Path $P.Root 'raw/eis/raw_1.dat';$Bytes=[IO.File]::ReadAllBytes($F);$Bytes[0]=$Bytes[0]-bxor 1;[IO.File]::WriteAllBytes($F,$Bytes);$R=Invoke-M03A6Preflight $P.Root $P.Ledger $ProjectRoot;if(-not@($R.Findings|Where-Object code -eq 'BLOCKED_LEDGER_HASH_MISMATCH').Count){throw 'hash not checked'}}
    Invoke-Case A055 'actual size mismatch rechecked' {$P=New-CompletePackage sizemismatch;$F=Join-Path $P.Root 'raw/eis/raw_1.dat';[IO.File]::AppendAllText($F,'X',[Text.UTF8Encoding]::new($false));$R=Invoke-M03A6Preflight $P.Root $P.Ledger $ProjectRoot;if(-not@($R.Findings|Where-Object code -eq 'BLOCKED_LEDGER_SIZE_MISMATCH').Count){throw 'size not checked'}}
    Invoke-Case A056 'worksheet schemas map exactly to M03A5' {$R=New-Package schemas;$Pairs=@(@('metadata/EIS_METADATA.csv','config/M03A_5_experimental_manifest.csv'),@('metadata/SERIES_RESISTANCE_EVIDENCE.csv','config/M03A_5_resistance_ledger.csv'),@('metadata/GEOMETRY_AREA_EVIDENCE.csv','config/M03A_5_area_measurements.csv'),@('metadata/DIRECT_CONDUCTIVITY_EVIDENCE.csv','config/M03A_5_direct_conductivity.csv'));foreach($Pair in $Pairs){$Canonical=@((Get-Content -LiteralPath (Join-Path $ProjectRoot $Pair[1]) -First 1)-split',');[void](Import-M03A6Csv (Join-Path $R $Pair[0]) $Canonical -AllowHeaderOnly -ExactHeader)}}
    Invoke-Case A057 'ledger ordinal deterministic order' {$R=New-Package ordinal;[void](Write-Data (Join-Path $R 'raw/eis/z.dat') 'Z');[void](Write-Data (Join-Path $R 'raw/eis/A.dat') 'A');$F=Freeze-M03A6ExperimentalEvidence $R ord;$Paths=@(Import-Csv $F.LedgerPath|ForEach-Object{$_.relative_path});for($I=1;$I-lt$Paths.Count;$I++){if([StringComparer]::Ordinal.Compare($Paths[$I-1],$Paths[$I])-gt 0){throw 'not ordinal'}}}
    Invoke-Case A058 'case equivalent ledger version blocked' {$R=New-Package caseledger;[void](Freeze-M03A6ExperimentalEvidence $R vCase);$C=$false;try{[void](Freeze-M03A6ExperimentalEvidence $R VCASE)}catch{$C=$true};if(-not$C){throw 'case bypass'}}
    Invoke-Case A059 'existing normalized output blocked' {$O=Join-Path $TempRoot existingnorm.csv;[void](Write-Data $O 'USER');$C=$false;try{[void](Prepare-M03A6NormalizedEis $Src $O EXPLICIT_RFC4180_COLUMN_MAP freq_source zr_source zi_source)}catch{$C=$true};if(-not$C-or([IO.File]::ReadAllText($O)-ne'USER')){throw 'overwrite'}}
    Invoke-Blocked A060 'empty normalized table blocked' EMPTY_NORMALIZED BLOCKED_NORMALIZED_EIS_EMPTY
    Invoke-Case A061 'normalized input timestamp unchanged' {$O=Join-Path $TempRoot timestampnorm.csv;$Before=(Get-Item $Src).LastWriteTimeUtc;$R=Prepare-M03A6NormalizedEis $Src $O EXPLICIT_RFC4180_COLUMN_MAP freq_source zr_source zi_source;if(-not$R.RawTimestampUnchanged-or(Get-Item $Src).LastWriteTimeUtc-ne$Before){throw 'timestamp'}}
    Invoke-Case A062 'duplicate ledger entry blocked' {$P=New-CompletePackage dupledger;$Rows=@(Import-Csv $P.Ledger);$Rows+=($Rows[0]|Select-Object *);Write-M03A6Utf8NoBomCsv(Get-M03A6Schema Ledger)$Rows $P.Ledger;$R=Invoke-M03A6Preflight $P.Root $P.Ledger $ProjectRoot;if(-not@($R.Findings|Where-Object code -eq 'BLOCKED_DUPLICATE_LEDGER_PATH').Count){throw 'not blocked'}}
    Invoke-Case A063 'duplicate role path blocked' {$P=New-CompletePackage duprole;$Rows=@(Import-Csv(Join-Path $P.Root 'FILE_INVENTORY.csv'));$Rows+=($Rows[0]|Select-Object *);Write-M03A6Utf8NoBomCsv(Get-M03A6Schema Inventory)$Rows(Join-Path $P.Root 'FILE_INVENTORY.csv');$F=Freeze-M03A6ExperimentalEvidence $P.Root v002;$R=Invoke-M03A6Preflight $P.Root $F.LedgerPath $ProjectRoot;if(-not@($R.Findings|Where-Object code -eq 'BLOCKED_DUPLICATE_ROLE_PATH').Count){throw 'not blocked'}}
    Invoke-Case A064 'header-only metadata with missing ledger record blocked' {$R=New-Package ledgeronly;$Schema=Get-M03A6Schema Ledger;$Row=New-Row $Schema @{ledger_version='planned';relative_path='raw/eis/ghost.dat';size_bytes='1';sha256=('0'*64);frozen_at='2026-01-01T00:00:00+00:00';timezone_offset='+00:00';tool_version='SYNTHETIC_TEST'};Write-M03A6Utf8NoBomCsv -Columns $Schema -Rows @($Row) -Path (Join-Path $R 'HASH_LEDGER.csv');$P=Invoke-M03A6Preflight $R '' $ProjectRoot;if(-not@($P.Findings|Where-Object code -eq 'BLOCKED_LEDGER_FILE_MISSING').Count){$Details=@($P.Findings|ForEach-Object{$_.code+':'+$_.detail});throw ("missing ledger evidence treated as empty; status=$($P.Status); findings="+($Details-join'|'))}}
    Invoke-Case A065 'initializer creates exact directory manifest' {$R=New-Package exactdirs;$Expected=@('hashes','metadata','normalized','normalized/eis','raw','raw/direct_conductivity','raw/eis','raw/geometry_area','raw/series_resistance','reports');$Actual=@(Get-ChildItem -LiteralPath $R -Directory -Recurse -Force|ForEach-Object{$_.FullName.Substring($R.Length).TrimStart('\','/').Replace('\','/')}|Sort-Object);if(($Actual-join'|')-cne(($Expected|Sort-Object)-join'|')){throw 'directory manifest'}}
    Invoke-Case A066 'normalized output parent junction blocked' {$Target=Join-Path $TempRoot normalized_target;[void][IO.Directory]::CreateDirectory($Target);$Link=Join-Path $TempRoot normalized_link;[void](New-Item -ItemType Junction -Path $Link -Target $Target -ErrorAction Stop);$Caught=$false;try{[void](Prepare-M03A6NormalizedEis $Src (Join-Path $Link 'blocked.csv') EXPLICIT_RFC4180_COLUMN_MAP freq_source zr_source zi_source)}catch{$Caught=$_.Exception.Message-like'*BLOCKED_PATH_REPARSE_POINT*'};if(-not$Caught){throw 'normalized junction accepted'}}
    Invoke-Case A067 'noncanonical inventory role directory alias blocked' {$P=New-CompletePackage alias67;$Inv=@(Import-Csv -LiteralPath (Join-Path $P.Root 'FILE_INVENTORY.csv'));$Inv+=New-Row (Get-M03A6Schema Inventory) @{relative_path='raw/eis/../series_resistance/fixture.dat';evidence_role='EIS_RAW';sample_id='SAMPLE_A';cell_id='CELL_A';replicate_id='ALIAS_67';data_origin='EXPERIMENTAL';status='MEASURED';notes='SYNTHETIC ALIAS TEST'};Write-M03A6Utf8NoBomCsv (Get-M03A6Schema Inventory) $Inv (Join-Path $P.Root 'FILE_INVENTORY.csv');$R=Invoke-M03A6Preflight $P.Root $P.Ledger $ProjectRoot;if(-not@($R.Findings|Where-Object code -eq 'BLOCKED_NONCANONICAL_EVIDENCE_PATH').Count-or-not@($R.Findings|Where-Object code -eq 'BLOCKED_EVIDENCE_ROLE_DIRECTORY_MISMATCH').Count){throw 'alias role directory accepted'}}
    Invoke-Case A068 'canonical alias conflicting physical role blocked' {$P=New-CompletePackage alias68;$Inv=@(Import-Csv -LiteralPath (Join-Path $P.Root 'FILE_INVENTORY.csv'));$Inv+=New-Row (Get-M03A6Schema Inventory) @{relative_path='raw/eis/../series_resistance/fixture.dat';evidence_role='EIS_RAW';sample_id='SAMPLE_A';cell_id='CELL_A';replicate_id='ALIAS_68';data_origin='EXPERIMENTAL';status='MEASURED';notes='SYNTHETIC PHYSICAL ROLE TEST'};Write-M03A6Utf8NoBomCsv (Get-M03A6Schema Inventory) $Inv (Join-Path $P.Root 'FILE_INVENTORY.csv');$R=Invoke-M03A6Preflight $P.Root $P.Ledger $ProjectRoot;if(-not@($R.Findings|Where-Object code -eq 'BLOCKED_CONFLICTING_PHYSICAL_EVIDENCE_ROLE').Count){throw 'physical role conflict accepted'}}
    Invoke-Case A069 'canonical alias duplicate physical ledger blocked' {$P=New-CompletePackage alias69;$Rows=@(Import-Csv -LiteralPath $P.Ledger);$Alias=$Rows|Where-Object relative_path -eq 'raw/eis/raw_1.dat'|Select-Object -First 1;$Copy=$Alias|Select-Object *;$Copy.relative_path='raw/eis/sub/../raw_1.dat';$Rows+=$Copy;Write-M03A6Utf8NoBomCsv (Get-M03A6Schema Ledger) $Rows $P.Ledger;$R=Invoke-M03A6Preflight $P.Root $P.Ledger $ProjectRoot;if(-not@($R.Findings|Where-Object code -eq 'BLOCKED_DUPLICATE_LEDGER_PHYSICAL_PATH').Count){throw 'physical ledger duplicate accepted'}}
    Invoke-Case A070 'metadata alias canonical identity closure blocked' {$P=New-CompletePackage alias70;$Path=Join-Path $P.Root 'metadata/EIS_METADATA.csv';$Rows=@(Import-Csv -LiteralPath $Path);$Rows[0].raw_file_path='raw/eis/sub/../raw_1.dat';Write-M03A6Utf8NoBomCsv (Get-M03A6Schema Eis) $Rows $Path;$R=Invoke-M03A6Preflight $P.Root $P.Ledger $ProjectRoot;if(-not@($R.Findings|Where-Object code -eq 'BLOCKED_NONCANONICAL_EVIDENCE_PATH').Count-or@($R.Findings|Where-Object code -eq 'BLOCKED_EIS_IDENTIFIER_MISMATCH').Count){throw 'metadata alias did not close by canonical identity'}}
    Invoke-Case A071 'raw normalized physical alias collision blocked' {$P=New-CompletePackage alias71;$EisPath=Join-Path $P.Root 'metadata/EIS_METADATA.csv';$Eis=@(Import-Csv -LiteralPath $EisPath);$Eis[0].normalized_table_path='normalized/eis/../../raw/eis/raw_1.dat';$Eis[0].normalized_table_size_bytes=$Eis[0].raw_file_size_bytes;$Eis[0].normalized_table_sha256=$Eis[0].raw_file_sha256;Write-M03A6Utf8NoBomCsv (Get-M03A6Schema Eis) $Eis $EisPath;$InvPath=Join-Path $P.Root 'FILE_INVENTORY.csv';$Inv=@(Import-Csv -LiteralPath $InvPath);$Inv+=New-Row (Get-M03A6Schema Inventory) @{relative_path='normalized/eis/../../raw/eis/raw_1.dat';evidence_role='EIS_NORMALIZED';sample_id='SAMPLE_A';cell_id='CELL_A';replicate_id='REP_1';data_origin='EXPERIMENTAL';status='MEASURED';notes='SYNTHETIC COLLISION TEST'};Write-M03A6Utf8NoBomCsv (Get-M03A6Schema Inventory) $Inv $InvPath;$R=Invoke-M03A6Preflight $P.Root $P.Ledger $ProjectRoot;if(-not@($R.Findings|Where-Object code -eq 'BLOCKED_RAW_NORMALIZED_PATH_COLLISION').Count){throw 'raw normalized physical alias collision accepted'}}
    Invoke-Case A072 'OnlyTestId requires external output and preserves durable result' {$Durable=Join-Path $ProjectRoot 'results/tables/M03A_6_tool_regression.csv';$BeforeSize=[long](Get-Item -LiteralPath $Durable).Length;$BeforeHash=Get-M03A6Sha256 $Durable;$C=Invoke-ProcessCapture 'powershell.exe' @('-NoProfile','-ExecutionPolicy','Bypass','-File',$PSCommandPath,'-OnlyTestId','A064');if($C.ExitCode-eq 0-or($C.StdOut+$C.StdErr)-notlike'*ONLY_TEST_ID_REQUIRES_EXTERNAL_OUTPUT*'-or[long](Get-Item -LiteralPath $Durable).Length-ne$BeforeSize-or(Get-M03A6Sha256 $Durable)-cne$BeforeHash){throw 'focused default output was not blocked'}}
    Invoke-Case A073 'invalid OnlyTestId creates no output' {$Out=Join-Path $TempRoot 'invalid_only.csv';$C=Invoke-ProcessCapture 'powershell.exe' @('-NoProfile','-ExecutionPolicy','Bypass','-File',$PSCommandPath,'-OnlyTestId','INVALID_ID','-OutputPath',$Out);if($C.ExitCode-eq 0-or($C.StdOut+$C.StdErr)-notlike'*INVALID_TEST_ID*'-or[IO.File]::Exists($Out)){throw 'invalid focused test accepted'}}
    Invoke-Case A074 'OnlyTestId repository output blocked and durable preserved' {$Durable=Join-Path $ProjectRoot 'results/tables/M03A_6_tool_regression.csv';$BeforeSize=[long](Get-Item -LiteralPath $Durable).Length;$BeforeHash=Get-M03A6Sha256 $Durable;$C=Invoke-ProcessCapture 'powershell.exe' @('-NoProfile','-ExecutionPolicy','Bypass','-File',$PSCommandPath,'-OnlyTestId','A064','-OutputPath',$Durable);if($C.ExitCode-eq 0-or($C.StdOut+$C.StdErr)-notlike'*ONLY_TEST_OUTPUT_INSIDE_REPOSITORY*'-or[long](Get-Item -LiteralPath $Durable).Length-ne$BeforeSize-or(Get-M03A6Sha256 $Durable)-cne$BeforeHash){throw 'repository focused output accepted'}}
    Invoke-Case A075 'valid OnlyTestId writes one external row only' {$Durable=Join-Path $ProjectRoot 'results/tables/M03A_6_tool_regression.csv';$BeforeSize=[long](Get-Item -LiteralPath $Durable).Length;$BeforeHash=Get-M03A6Sha256 $Durable;$Out=Join-Path $TempRoot 'valid_only.csv';$C=Invoke-ProcessCapture 'powershell.exe' @('-NoProfile','-ExecutionPolicy','Bypass','-File',$PSCommandPath,'-OnlyTestId','A064','-OutputPath',$Out);$Rows=@(Import-Csv -LiteralPath $Out);if($C.ExitCode-ne 0-or$Rows.Count-ne 1-or$Rows[0].test_id-cne'A064'-or[long](Get-Item -LiteralPath $Durable).Length-ne$BeforeSize-or(Get-M03A6Sha256 $Durable)-cne$BeforeHash){throw "valid focused test failed exit=$($C.ExitCode) stderr=$($C.StdErr)"}}
    Invoke-Case A076 'inventory evidence path case alias blocked' {$P=New-CompletePackage caseinventory;$Path=Join-Path $P.Root 'FILE_INVENTORY.csv';$Rows=@(Import-Csv -LiteralPath $Path);$Row=$Rows|Where-Object evidence_role -ceq 'EIS_RAW'|Select-Object -First 1;$Canonical=[string]$Row.relative_path;$Alias=Get-M03A6CaseAlias $Canonical;if($Alias-ceq$Canonical){throw 'case alias unchanged'};$Row.relative_path=$Alias;Write-M03A6Utf8NoBomCsv (Get-M03A6Schema Inventory) $Rows $Path;$R=Invoke-M03A6Preflight $P.Root $P.Ledger $ProjectRoot;if(-not@($R.Findings|Where-Object code -eq 'BLOCKED_NONCANONICAL_EVIDENCE_PATH').Count){throw 'inventory case alias accepted'}}
    Invoke-Case A077 'ledger evidence path case alias blocked' {$P=New-CompletePackage caseledgerpath;$Rows=@(Import-Csv -LiteralPath $P.Ledger);$Row=$Rows|Where-Object relative_path -ceq 'raw/eis/raw_1.dat'|Select-Object -First 1;$Canonical=[string]$Row.relative_path;$Alias=Get-M03A6CaseAlias $Canonical;if($Alias-ceq$Canonical){throw 'case alias unchanged'};$Row.relative_path=$Alias;Write-M03A6Utf8NoBomCsv (Get-M03A6Schema Ledger) $Rows $P.Ledger;$R=Invoke-M03A6Preflight $P.Root $P.Ledger $ProjectRoot;if(-not@($R.Findings|Where-Object code -eq 'BLOCKED_NONCANONICAL_EVIDENCE_PATH').Count){throw 'ledger case alias accepted'}}
    Invoke-Case A078 'metadata evidence path case alias blocked' {$P=New-CompletePackage casemetadata;$Path=Join-Path $P.Root 'metadata/EIS_METADATA.csv';$Rows=@(Import-Csv -LiteralPath $Path);$Canonical=[string]$Rows[0].raw_file_path;$Alias=Get-M03A6CaseAlias $Canonical;if($Alias-ceq$Canonical){throw 'case alias unchanged'};$Rows[0].raw_file_path=$Alias;Write-M03A6Utf8NoBomCsv (Get-M03A6Schema Eis) $Rows $Path;$R=Invoke-M03A6Preflight $P.Root $P.Ledger $ProjectRoot;if(-not@($R.Findings|Where-Object code -eq 'BLOCKED_NONCANONICAL_EVIDENCE_PATH').Count){throw 'metadata case alias accepted'}}
    Invoke-Case A079 'failure before replace preserves target' {$Target=Join-Path $TempRoot publish_before.csv;[void](Write-Data $Target 'ORIGINAL BEFORE');$Before=[IO.File]::ReadAllBytes($Target);$BeforeHash=Get-M03A6Sha256 $Target;$Ids=@('A001','A002');$PublishRows=@([pscustomobject][ordered]@{test_id='A001';test_name='one';expected='PASS';actual='PASS';status='PASS';detail=''},[pscustomobject][ordered]@{test_id='A002';test_name='two';expected='PASS';actual='PASS';status='PASS';detail='' });$Caught=$false;try{[void](Publish-M03A6RegressionResultAtomically $PublishRows $Ids $Target BEFORE_REPLACE)}catch{$Caught=$_.Exception.Message-like'*INJECTED_REGRESSION_PUBLISH_BEFORE_REPLACE*'};$After=[IO.File]::ReadAllBytes($Target);if(-not$Caught-or[Convert]::ToBase64String($After)-cne[Convert]::ToBase64String($Before)-or(Get-M03A6Sha256 $Target)-cne$BeforeHash-or@(Get-ChildItem -LiteralPath $TempRoot -File -Filter '.M03A6_REGRESSION_*').Count){throw 'before replace did not preserve target or clean residuals'}}
    Invoke-Case A080 'failure after replace restores target and removes backup' {$Target=Join-Path $TempRoot publish_after.csv;[void](Write-Data $Target 'ORIGINAL AFTER');$Before=[IO.File]::ReadAllBytes($Target);$BeforeHash=Get-M03A6Sha256 $Target;$Ids=@('A001','A002');$PublishRows=@([pscustomobject][ordered]@{test_id='A001';test_name='one';expected='PASS';actual='PASS';status='PASS';detail=''},[pscustomobject][ordered]@{test_id='A002';test_name='two';expected='PASS';actual='PASS';status='PASS';detail='' });$Caught=$false;try{[void](Publish-M03A6RegressionResultAtomically $PublishRows $Ids $Target AFTER_REPLACE)}catch{$Caught=$_.Exception.Message-like'*INJECTED_REGRESSION_PUBLISH_AFTER_REPLACE*'};$After=[IO.File]::ReadAllBytes($Target);if(-not$Caught-or[Convert]::ToBase64String($After)-cne[Convert]::ToBase64String($Before)-or(Get-M03A6Sha256 $Target)-cne$BeforeHash-or@(Get-ChildItem -LiteralPath $TempRoot -File -Filter '.M03A6_REGRESSION_*').Count){throw 'after replace did not restore target or clean residuals'}}
    Invoke-Case A081 'successful replace leaves no temp or backup' {$Target=Join-Path $TempRoot publish_success.csv;[void](Write-Data $Target 'ORIGINAL SUCCESS');$BeforeHash=Get-M03A6Sha256 $Target;$Ids=@('A001','A002');$PublishRows=@([pscustomobject][ordered]@{test_id='A001';test_name='one';expected='PASS';actual='PASS';status='PASS';detail=''},[pscustomobject][ordered]@{test_id='A002';test_name='two';expected='PASS';actual='PASS';status='PASS';detail='' });$Published=Publish-M03A6RegressionResultAtomically $PublishRows $Ids $Target;$Verified=@(Import-M03A6Csv $Target @('test_id','test_name','expected','actual','status','detail') -ExactHeader);if($Verified.Count-ne2-or($Verified.test_id-join',')-cne($Ids-join',')-or(Get-M03A6Sha256 $Target)-ceq$BeforeHash-or-not$Published.TargetReplaced-or-not$Published.BackupDeleted-or@(Get-ChildItem -LiteralPath $TempRoot -File -Filter '.M03A6_REGRESSION_*').Count){throw 'successful publish result or cleanup invalid'}}
    Invoke-Case A082 'canonical root case-only rename is re-resolved' {$Root=New-Package CaseRootA082;$Relative='ACQUISITION_PACKAGE_README.md';$First=Resolve-M03A6CanonicalPackagePath $Root $Relative -RequireFile;$Parent=[IO.Path]::GetDirectoryName($Root);$Intermediate=Join-Path $Parent 'CaseRootA082_intermediate';$Renamed=Join-Path $Parent 'caseroota082';[IO.Directory]::Move($Root,$Intermediate);[IO.Directory]::Move($Intermediate,$Renamed);$Disk=@(Get-ChildItem -LiteralPath $Parent -Directory -Force|Where-Object{$_.Name.Equals('caseroota082',[StringComparison]::OrdinalIgnoreCase)});if($Disk.Count-ne1-or$Disk[0].Name-cne'caseroota082'){throw 'case-only rename not established'};$Second=Resolve-M03A6CanonicalPackagePath $Renamed $Relative -RequireFile;if($Second.CanonicalFullPath-ceq$First.CanonicalFullPath-or-not$Second.CanonicalFullPath.Equals($First.CanonicalFullPath,[StringComparison]::OrdinalIgnoreCase)-or$Second.CanonicalFullPath-notlike'*\caseroota082\ACQUISITION_PACKAGE_README.md'){throw 'canonical root was not re-resolved'}}
    Invoke-Case A083 'existing PackageRoot segment zero-match blocked' {$Root=New-Package rootzero083;$Leaf=[IO.Path]::GetFileName($Root);$Hook={param($Info)if($Info.Phase-ceq'ROOT'-and$Info.Segment-ceq$Leaf){'ZERO'}}.GetNewClosure();$Caught=$false;try{Set-M03A6CaseEnumerationTestHook $Hook;try{[void](Resolve-M03A6CanonicalPackagePath $Root 'ACQUISITION_PACKAGE_README.md' -RequireFile)}catch{$Caught=$_.Exception.Message-like'BLOCKED_PATH_CASE_NOT_FOUND:*'}}finally{Set-M03A6CaseEnumerationTestHook $null};if(-not$Caught-or-not(Test-M03A6CaseEnumerationTestHookCleared)){throw 'existing root zero match not blocked or hook retained'}}
    Invoke-Case A084 'existing evidence segment zero-match blocked' {$P=New-CompletePackage evidencezero084;$Hook={param($Info)if($Info.Phase-ceq'RELATIVE'-and$Info.Segment-ceq'raw_1.dat'){'ZERO'}};$Result=$null;try{Set-M03A6CaseEnumerationTestHook $Hook;$Result=Invoke-M03A6Preflight $P.Root $P.Ledger $ProjectRoot}finally{Set-M03A6CaseEnumerationTestHook $null};if($null-eq$Result-or$Result.Status-ne'PRE_INTAKE_BLOCKED'-or-not@($Result.Findings|Where-Object code -eq 'BLOCKED_PATH_CASE_NOT_FOUND').Count-or-not(Test-M03A6CaseEnumerationTestHookCleared)){throw 'existing evidence zero match not blocked or hook retained'}}
    Invoke-Case A085 'optional missing tail requires true absence' {$Root=New-Package missingtail085;$Relative='raw/eis/NewLeafA085.csv';$Candidate=Join-Path $Root $Relative;if([IO.File]::Exists($Candidate)-or[IO.Directory]::Exists($Candidate)){throw 'missing candidate already exists'};$First=Resolve-M03A6CanonicalPackagePath $Root $Relative -PathMode AllowMissingTail;if(-not$First.MissingTailStarted-or$First.CanonicalRelativePath-cne$Relative-or[IO.File]::Exists($Candidate)-or[IO.Directory]::Exists($Candidate)){throw 'true missing tail not preserved'};$ActualRelative='raw/eis/newleafa085.csv';[void](Write-Data (Join-Path $Root $ActualRelative) 'SYNTHETIC MISSING TAIL BOUNDARY');$Second=Resolve-M03A6CanonicalPackagePath $Root $Relative -PathMode AllowMissingTail;if($Second.MissingTailStarted-or$Second.WasCanonical-or$Second.CanonicalRelativePath-cne$ActualRelative){throw 'existing case alias treated as missing tail'}}
    Invoke-Case A086 'selected ledger missing file is blocked' {$P=New-CompletePackage ledger_missing086;$Selected=Join-Path $P.Root 'hashes/SELECTED_LEDGER_A086.csv';if(([IO.Path]::GetFileName($Selected))-like'HASH_LEDGER_*.csv'){throw 'selected ledger unexpectedly matches candidate glob'};$SeedRows=@(Import-M03A6Csv $P.Ledger (Get-M03A6Schema Ledger) -ExactHeader);if(@($SeedRows|Where-Object relative_path -ceq 'auxiliary_missing_A086.dat').Count){throw 'candidate ledger contains target missing row'};Write-M03A6Utf8NoBomCsv (Get-M03A6Schema Ledger) $SeedRows $Selected;Add-M03A6TestLedgerRow $Selected 'auxiliary_missing_A086.dat' '1' ('0'*64);$SelectedRows=@(Import-M03A6Csv $Selected (Get-M03A6Schema Ledger) -ExactHeader);if(@($SelectedRows|Where-Object relative_path -ceq 'auxiliary_missing_A086.dat').Count-ne1){throw 'explicit selected ledger missing row not established'};$R=Invoke-M03A6Preflight $P.Root $Selected $ProjectRoot;$Missing=@($R.Findings|Where-Object code -eq 'BLOCKED_LEDGER_FILE_MISSING');if($R.Status-ne'PRE_INTAKE_BLOCKED'-or$Missing.Count-ne1-or$R.ExperimentalEvidenceReceived){throw "isolated selected-ledger row not blocked: status=$($R.Status); findings=$((@($R.Findings.code|Select-Object -Unique))-join',')"}}
    Invoke-Case A087 'unreferenced ledger size and hash are independently rechecked' {$PS=New-CompletePackage ledger_size087;$DS=Write-Data (Join-Path $PS.Root 'auxiliary_size_A087.dat') "SYNTHETIC UNREFERENCED SIZE`r`n";$WrongSize=([long]$DS.size+1).ToString([Globalization.CultureInfo]::InvariantCulture);Add-M03A6TestLedgerRow $PS.Ledger 'auxiliary_size_A087.dat' $WrongSize $DS.hash;$RS=Invoke-M03A6Preflight $PS.Root $PS.Ledger $ProjectRoot;if($RS.Status-ne'PRE_INTAKE_BLOCKED'-or-not@($RS.Findings|Where-Object code -eq 'BLOCKED_LEDGER_SIZE_MISMATCH').Count){throw "unreferenced ledger size mismatch not blocked: $((@($RS.Findings.code|Select-Object -Unique))-join',')"};$PH=New-CompletePackage ledger_hash087;$DH=Write-Data (Join-Path $PH.Root 'auxiliary_hash_A087.dat') "SYNTHETIC UNREFERENCED HASH`r`n";Add-M03A6TestLedgerRow $PH.Ledger 'auxiliary_hash_A087.dat' $DH.size ('0'*64);$RH=Invoke-M03A6Preflight $PH.Root $PH.Ledger $ProjectRoot;if($RH.Status-ne'PRE_INTAKE_BLOCKED'-or-not@($RH.Findings|Where-Object code -eq 'BLOCKED_LEDGER_HASH_MISMATCH').Count){throw "unreferenced ledger hash mismatch not blocked: $((@($RH.Findings.code|Select-Object -Unique))-join',')"}}
    Invoke-Case A088 'RequireFile disappearance after initial existence check is blocked' {$P=New-CompletePackage required_disappear088;$Relative='raw/eis/raw_1.dat';$Target=Join-Path $P.Root $Relative;if(-not[IO.File]::Exists($Target)){throw 'required target not initially present'};$State=[pscustomobject]@{Triggered=$false};$Hook={param($Info)if($Info.Phase-ceq'RELATIVE'-and$Info.Segment-ceq'raw_1.dat'){$State.Triggered=$true;if($Info.ActualMatches.Count-ne1-or-not[IO.File]::Exists($Target)){throw 'TOCTOU_PRECONDITION_FAILED'};[IO.File]::Delete($Target);'ZERO'}}.GetNewClosure();$Caught=$false;$Returned=$false;try{Set-M03A6CaseEnumerationTestHook $Hook;try{[void](Resolve-M03A6CanonicalPackagePath $P.Root $Relative -RequireFile);$Returned=$true}catch{$Caught=$_.Exception.Message-like'BLOCKED_PATH_CASE_NOT_FOUND:*'}}finally{Set-M03A6CaseEnumerationTestHook $null};if(-not$State.Triggered-or-not$Caught-or$Returned-or[IO.File]::Exists($Target)-or-not(Test-M03A6CaseEnumerationTestHookCleared)){throw 'RequireFile disappearance was not fail-closed or hook retained'}}
    Invoke-Case A089 'selected ledger actual integrity is checked before semantic rejection' {$P=New-CompletePackage ledger_order089;$Selected=Join-Path $P.Root 'hashes/SELECTED_LEDGER_A089.csv';if(([IO.Path]::GetFileName($Selected))-like'HASH_LEDGER_*.csv'){throw 'selected ledger unexpectedly matches candidate glob'};$Rows=New-Object Collections.Generic.List[object];foreach($Row in @(Import-M03A6Csv $P.Ledger (Get-M03A6Schema Ledger) -ExactHeader)){[void]$Rows.Add($Row)};$Original=$Rows|Where-Object relative_path -ceq 'raw/eis/raw_1.dat'|Select-Object -First 1;if($null-eq$Original){throw 'duplicate seed row missing'};$Duplicate=New-Row (Get-M03A6Schema Ledger) @{ledger_version=$Original.ledger_version;relative_path=$Original.relative_path;size_bytes=([long]$Original.size_bytes+1).ToString([Globalization.CultureInfo]::InvariantCulture);sha256=$Original.sha256;frozen_at=$Original.frozen_at;timezone_offset=$Original.timezone_offset;tool_version=$Original.tool_version};[void]$Rows.Add($Duplicate);Write-M03A6Utf8NoBomCsv (Get-M03A6Schema Ledger) $Rows.ToArray() $Selected;$R=Invoke-M03A6Preflight $P.Root $Selected $ProjectRoot;$Codes=@($R.Findings|ForEach-Object{$_.code});$SizeIndex=[array]::IndexOf([string[]]$Codes,'BLOCKED_LEDGER_SIZE_MISMATCH');$DuplicateIndex=[array]::IndexOf([string[]]$Codes,'BLOCKED_DUPLICATE_LEDGER_PHYSICAL_PATH');if($R.Status-ne'PRE_INTAKE_BLOCKED'-or$R.ExperimentalEvidenceReceived-or$SizeIndex-lt0-or$DuplicateIndex-lt0-or$SizeIndex-ge$DuplicateIndex-or@($R.Findings|Where-Object code -eq 'BLOCKED_SIZE_MISMATCH').Count){throw "actual integrity did not precede semantic rejection or invalid row entered map: $($Codes-join',')"}}
    Invoke-Case A090 'explicit selected ledger root case alias is blocked' {$P=New-CompletePackage ledger_root_case090;$Parent=[IO.Path]::GetDirectoryName($P.Root);$Leaf=[IO.Path]::GetFileName($P.Root);$AliasLeaf=Get-M03A6CaseAlias $Leaf;$AliasRoot=Join-Path $Parent $AliasLeaf;$Relative=$P.Ledger.Substring($P.Root.Length).TrimStart('\','/');$AliasLedger=Join-Path $AliasRoot $Relative;if($AliasLedger-ceq$P.Ledger-or-not$AliasLedger.Equals($P.Ledger,[StringComparison]::OrdinalIgnoreCase)-or-not[IO.File]::Exists($AliasLedger)){throw 'root case alias precondition failed'};$R=Invoke-M03A6Preflight $P.Root $AliasLedger $ProjectRoot;if($R.Status-ne'PRE_INTAKE_BLOCKED'-or$R.ExperimentalEvidenceReceived-or$R.Findings.Count-eq0-or$R.Findings[0].code-cne'BLOCKED_NONCANONICAL_EVIDENCE_PATH'){throw "explicit selected-ledger root case alias accepted: $((@($R.Findings.code|Select-Object -Unique))-join',')"}}
    Invoke-Case A091 'explicit selected ledger lexical alias is blocked' {foreach($Kind in @('DOTDOT','DOT','FORWARD_SEPARATOR')){$P=New-CompletePackage ('ledger_lexical091_'+$Kind.ToLowerInvariant());$Selected=Join-Path $P.Root 'hashes/SELECTED_LEDGER_A091.csv';$Rows=@(Import-M03A6Csv $P.Ledger (Get-M03A6Schema Ledger) -ExactHeader);Write-M03A6Utf8NoBomCsv (Get-M03A6Schema Ledger) $Rows $Selected;$Alias=if($Kind-ceq'DOTDOT'){Join-Path $P.Root 'hashes\..\hashes\SELECTED_LEDGER_A091.csv'}elseif($Kind-ceq'DOT'){Join-Path $P.Root 'hashes\.\SELECTED_LEDGER_A091.csv'}else{$Selected.Replace('\','/')};if($Kind-ceq'FORWARD_SEPARATOR'-and($Alias.Equals($Selected,[StringComparison]::Ordinal)-or-not[IO.Path]::GetFullPath($Alias).Equals($Selected,[StringComparison]::Ordinal)-or-not[IO.File]::Exists($Alias))){throw "$Kind lexical alias precondition failed"};if(-not[IO.File]::Exists($Alias)-or[IO.Path]::GetFullPath($Alias)-cne$Selected){throw "$Kind lexical alias precondition failed"};$R=Invoke-M03A6Preflight $P.Root $Alias $ProjectRoot;if($R.Status-ne'PRE_INTAKE_BLOCKED'-or$R.ExperimentalEvidenceReceived-or$R.Findings.Count-eq0-or$R.Findings[0].code-cne'BLOCKED_NONCANONICAL_EVIDENCE_PATH'){throw "$Kind selected-ledger lexical alias accepted: $((@($R.Findings.code|Select-Object -Unique))-join',')"}}}
}finally{
    foreach($R in @($ExtraCleanup)+@($TempRoot)){if([string]::IsNullOrWhiteSpace($R)){continue};$Full=[IO.Path]::GetFullPath($R);$Allowed=$Full.StartsWith($TempBase+[IO.Path]::DirectorySeparatorChar,[StringComparison]::OrdinalIgnoreCase)-or$Full.StartsWith([IO.Path]::GetFullPath((Split-Path -Parent $ProjectRoot))+[IO.Path]::DirectorySeparatorChar,[StringComparison]::OrdinalIgnoreCase);if(-not$Allowed){throw "cleanup boundary: $Full"};if(Test-Path -LiteralPath $Full){Get-ChildItem -LiteralPath $Full -Recurse -Force -File -ErrorAction SilentlyContinue|ForEach-Object{$_.IsReadOnly=$false};Remove-Item -LiteralPath $Full -Recurse -Force}}
}

$Failed=@($Results|Where-Object status -ne 'PASS')
"M03A6_REGRESSION_COUNT=$($Results.Count)";"M03A6_REGRESSION_PASS_COUNT=$(@($Results|Where-Object status -eq 'PASS').Count)";"M03A6_REGRESSION_FAIL_COUNT=$($Failed.Count)"
if($Failed.Count){$Failed|ForEach-Object{"FAIL|$($_.test_id)|$($_.detail)"};exit 1}
$ActualIds=@($Results|ForEach-Object{$_.test_id})
if(-not[string]::IsNullOrWhiteSpace($OnlyTestId)){
    if($Results.Count-ne 1-or$ActualIds[0]-cne$OnlyTestId){Write-Error "REGRESSION_CASE_COUNT_MISMATCH: expected one $OnlyTestId";exit 3}
}else{
    if($Results.Count-ne$ExpectedTestIds.Count){Write-Error "REGRESSION_CASE_COUNT_MISMATCH: expected $($ExpectedTestIds.Count) got $($Results.Count)";exit 3}
    if(@($ActualIds|Select-Object -Unique).Count-ne$ExpectedTestIds.Count-or($ActualIds-join',')-cne($ExpectedTestIds-join',')){Write-Error 'REGRESSION_ID_SEQUENCE_INVALID';exit 3}
}
[void](Publish-M03A6RegressionResultAtomically -Rows $Results.ToArray() -ExpectedIds $ActualIds -TargetPath $OutputPath)
'M03A6_TESTS=PASS'
