import com.comsol.model.Model;
import com.comsol.model.physics.Physics;
import com.comsol.model.util.ModelUtil;

import java.io.BufferedWriter;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

/** Final M10A3 GUI result organization, evidence export, and independent MPH reload audit. */
public final class LiNRR_M10A3_FinalAudit {
    private static final String RT="LiNRR_M10A3_FinalRuntimeInputs";private static int imageSerial=0;
    private LiNRR_M10A3_FinalAudit(){}
    public static void main(String[]args)throws Exception{Path out=Paths.get(rt("EVIDENCE_DIR"));Files.createDirectories(out);Model m=ModelUtil.load("M10A3Final",rt("INPUT_MPH"));try{assertNoElectrochemistry(m);createEngineeringPlots(m,Paths.get(rt("RTD_TABLE")));organizeResults(m);compactStoredSolutions(m);exportInventories(m,out);m.save(rt("OUTPUT_MPH"));exportImages(m,out);System.out.println("M10A3_FINAL_EVIDENCE_EXPORT=PASS");}finally{ModelUtil.remove("M10A3Final");}independentReload(rt("OUTPUT_MPH"));}

    private static void assertNoElectrochemistry(Model m){String forbidden="secondary current|tertiary current|nernst|butler|sei|li3n|li plating|li-nrr|her kinetics|hor kinetics|faradaic";for(String c:m.component().tags())for(String p:m.component(c).physics().tags()){String x=(p+" "+m.component(c).physics(p).getType()+" "+m.component(c).physics(p).label()).toLowerCase(Locale.ROOT);for(String q:forbidden.split("\\|"))if(x.contains(q))throw new IllegalStateException("FORBIDDEN_ELECTROCHEMISTRY "+c+"/"+p);}System.out.println("ELECTROCHEMISTRY_CREATED=FALSE");System.out.println("LI_PLATING_CREATED=FALSE");System.out.println("LINRR_KINETICS_CREATED=FALSE");System.out.println("HER_CREATED=FALSE");System.out.println("HOR_CREATED=FALSE");}

    private static void createEngineeringPlots(Model m,Path rtdTable)throws Exception{
        globalPlot(m,"pg_n2_transport_resistance","N2 Transport Resistance | HOMOGENIZED SSC | PROVISIONAL_SENSITIVITY","dset_species_n2_gas","1/(k_N2_ssc*A_n2_interface)","s/m^3");globalPlot(m,"pg_h2_transport_resistance","H2 Gas Transport Resistance | POROUS-INTERFACE SCAFFOLD","dset_species_h2_gas","t_ssc/(D_H2_gas*eps_ssc/tau_ssc*A_h2_interface)","s/m^3");
        String lc="comp_species_liq_real";if(m.component(lc).cpl().hasTag("intop_rtd_out"))m.component(lc).cpl().remove("intop_rtd_out");installRtdTables(m,lc,rtdTable);surfacePlot(m,"pg_tracer_real","REAL SPECIES TRANSPORT | Tracer - Real Geometry | PROVISIONAL Q","dset_rtd","cTracer");
        String pc="comp_nh3_downstream";for(String op:new String[]{"intop_pipe_out","intop_pipe_inv"})if(m.component(pc).cpl().hasTag(op))m.component(pc).cpl().remove(op);linePlot(m,"pg_nh3_downstream","TRANSIENT / ENGINEERING | NH3 Downstream Response | REDUCED equivalent PFA","dset_nh3_downstream","sel_dom_nh3_pipe","cNH3pipe","mol/m^3");pointPlot(m,"pg_nh3_breakthrough","NH3 Outlet Breakthrough | REDUCED equivalent downstream","dset_nh3_downstream","sel_bnd_nh3_pipe_outlet","cNH3pipe/c_NH3_cell_outlet_transfer","1");linePlot(m,"pg_nh3_inventory","NH3 Inventory Density Profile | REDUCED equivalent downstream","dset_nh3_downstream","sel_dom_nh3_pipe","cNH3pipe*A_pipe_equiv","mol/m");
    }
    private static void installRtdTables(Model m,String comp,Path table)throws Exception{List<String>lines=Files.readAllLines(table,StandardCharsets.UTF_8);if(lines.size()<4)throw new IllegalStateException("RTD_TABLE_EMPTY "+table);double[][]e=new double[lines.size()-1][2],f=new double[lines.size()-1][2];for(int i=1;i<lines.size();i++){String[]v=lines.get(i).split(",",-1);if(v.length<4)throw new IllegalStateException("RTD_TABLE_SHAPE "+table+" line="+(i+1));e[i-1][0]=Double.parseDouble(v[0]);e[i-1][1]=Double.parseDouble(v[2]);f[i-1][0]=Double.parseDouble(v[0]);f[i-1][1]=Double.parseDouble(v[3]);}for(String tag:new String[]{"func_rtd_e","func_rtd_f"}){if(m.func().hasTag(tag))m.func().remove(tag);if(m.component(comp).func().hasTag(tag))m.component(comp).func().remove(tag);}for(String tag:new String[]{"pg_rtd_e","pg_rtd_f"})if(m.result().hasTag(tag))m.result().remove(tag);for(String tag:new String[]{"tbl_rtd_e","tbl_rtd_f"})if(m.result().table().hasTag(tag))m.result().table().remove(tag);m.result().table().create("tbl_rtd_e","Table");m.result().table("tbl_rtd_e").label("RTD E(t) | ACCEPTED MEDIUM | Q PROVISIONAL_SENSITIVITY");m.result().table("tbl_rtd_e").setColumnHeaders(new String[]{"time_s","E_1_s"});m.result().table("tbl_rtd_e").setTableData(e);m.result().table().create("tbl_rtd_f","Table");m.result().table("tbl_rtd_f").label("RTD F(t) | ACCEPTED MEDIUM | Q PROVISIONAL_SENSITIVITY");m.result().table("tbl_rtd_f").setColumnHeaders(new String[]{"time_s","F"});m.result().table("tbl_rtd_f").setTableData(f);}
    private static void globalPlot(Model m,String tag,String label,String data,String expr,String unit){if(m.result().hasTag(tag))m.result().remove(tag);m.result().create(tag,"PlotGroup1D");m.result(tag).label(label);m.result(tag).set("data",data);m.result(tag).create("glob","Global");m.result(tag).feature("glob").set("expr",new String[]{expr});m.result(tag).feature("glob").set("unit",new String[]{unit});}
    private static void pointPlot(Model m,String tag,String label,String data,String selection,String expr,String unit){if(m.result().hasTag(tag))m.result().remove(tag);m.result().create(tag,"PlotGroup1D");m.result(tag).label(label);m.result(tag).set("data",data);m.result(tag).create("point","PointGraph");m.result(tag).feature("point").selection().named(selection);m.result(tag).feature("point").set("expr",new String[]{expr});m.result(tag).feature("point").set("unit",new String[]{unit});}
    private static void linePlot(Model m,String tag,String label,String data,String selection,String expr,String unit){if(m.result().hasTag(tag))m.result().remove(tag);m.result().create(tag,"PlotGroup1D");m.result(tag).label(label);m.result(tag).set("data",data);m.result(tag).create("line","LineGraph");m.result(tag).feature("line").selection().named(selection);m.result(tag).feature("line").set("expr",new String[]{expr});m.result(tag).feature("line").set("unit",new String[]{unit});}
    private static void surfacePlot(Model m,String tag,String label,String data,String expr){if(m.result().hasTag(tag))m.result().remove(tag);m.result().create(tag,"PlotGroup3D");m.result(tag).label(label);m.result(tag).set("data",data);m.result(tag).create("surf","Surface");m.result(tag).feature("surf").set("expr",expr);}

    private static void organizeResults(Model m){label(m,"pg00_physical_cell","00 Physical Cell - Full 3D | REAL / PHYSICAL");label(m,"pg_n2_velocity","REAL GAS FLOW | N2 Velocity");label(m,"pg_n2_pressure","REAL GAS FLOW | N2 Pressure");label(m,"pg_h2_velocity","REAL GAS FLOW | H2 Velocity");label(m,"pg_h2_pressure","REAL GAS FLOW | H2 Pressure");label(m,"pg_n2_gas_conc","REAL SPECIES TRANSPORT | N2 Gas Concentration - Real Geometry");label(m,"pg_n2_dissolved_real","REAL SPECIES TRANSPORT | Dissolved N2 - Real Geometry");label(m,"pg_n2_availability","REAL SPECIES TRANSPORT | N2 Availability at Cathode");label(m,"pg_h2_gas_conc","REAL SPECIES TRANSPORT | H2 Gas Concentration - Real Geometry");label(m,"pg_h2_availability","REAL SPECIES TRANSPORT | H2 Availability at PtAuSSC");label(m,"pg_donor_real","REAL SPECIES TRANSPORT | Proton Donor - Real Geometry | CALIBRATION_REQUIRED identity");label(m,"pg_nh3_real","REAL SPECIES TRANSPORT | NH3 - Real Geometry | NUMERICAL_VERIFICATION_ONLY source");label(m,"pg_tracer_real","REAL SPECIES TRANSPORT | Tracer - Real Geometry | PROVISIONAL Q");label(m,"pg_nh3_downstream","TRANSIENT / ENGINEERING | NH3 Downstream Response | REDUCED equivalent PFA");String[]order={"pg00_physical_cell","pg_n2_velocity","pg_n2_pressure","pg_h2_velocity","pg_h2_pressure","pg_n2_gas_conc","pg_n2_dissolved_real","pg_n2_availability","pg_n2_flux_real","pg_n2_transport_resistance","pg_n2_reaction_uniformity","pg_h2_gas_conc","pg_h2_availability","pg_h2_transport_resistance","pg_donor_real","pg_nh3_real","pg_tracer_real","pg_nh3_downstream","pg_nh3_breakthrough","pg_nh3_inventory","pg_rtd_e","pg_rtd_f"};for(int i=order.length-1;i>=0;i--)if(m.result().hasTag(order[i]))m.result().move(order[i],0);}
    private static void label(Model m,String t,String l){if(m.result().hasTag(t))m.result(t).label(l);}

    private static void compactStoredSolutions(Model m){double[]times=m.sol("sol18").getPVals();List<Integer>keep=new ArrayList<Integer>();int pulseEnd=0;for(int i=0;i<times.length;i++)if(times[i]<=60.0+1e-9){keep.add(i);pulseEnd=i;}for(int i=pulseEnd+1;i<times.length;i+=24)keep.add(i);if(keep.get(keep.size()-1)!=times.length-1)keep.add(times.length-1);double[][]states=new double[keep.size()][];double[]keptTimes=new double[keep.size()];for(int i=0;i<keep.size();i++){int source=keep.get(i);keptTimes[i]=times[source];states[i]=m.sol("sol18").getU(source+1);}m.sol("sol18").clearSolution();m.sol("sol18").setPVals(keptTimes);for(int i=0;i<states.length;i++)m.sol("sol18").setU(i+1,states[i]);m.sol("sol18").createSolution();if(m.sol("sol18").getPVals().length!=keptTimes.length)throw new IllegalStateException("RTD_ARCHIVE_SNAPSHOT_COUNT_MISMATCH");for(String tag:new String[]{"sol1","sol2","sol3","sol6","sol7","sol8","sol9","sol10","sol11","sol14"})if(m.sol().hasTag(tag))m.sol(tag).clearSolution();m.param().set("rtd_audit_output_points",Integer.toString(times.length),"DERIVED accepted medium RTD ledger rows retained in native tables");m.param().set("rtd_archived_solution_points",Integer.toString(keptTimes.length),"DERIVED accepted medium field snapshots stored in final MPH; full ledger retained in tables");System.out.println("M10A3_FINAL_STORAGE_COMPACTION|audit_points="+times.length+"|stored_snapshots="+keptTimes.length+"|pulse_snapshots="+(pulseEnd+1)+"|PASS");}

    private static void exportInventories(Model m,Path o)throws Exception{write(o.resolve("component_inventory.csv"),"tag,label,dimension,classification",components(m));write(o.resolve("geometry_inventory.csv"),"component,geometry,dimension,feature_count,classification",geometries(m));write(o.resolve("selection_inventory.csv"),"component,selection,dimension,count,label",selections(m));write(o.resolve("physics_inventory.csv"),"component,physics_tag,physics_type,label,features",physics(m));write(o.resolve("study_inventory.csv"),"study_tag,label,features,solver_sequences",studies(m));write(o.resolve("dataset_inventory.csv"),"dataset_tag,dataset_type,label",datasets(m));write(o.resolve("result_inventory.csv"),"result_tag,result_type,label,features",results(m));write(o.resolve("parameter_inventory.csv"),"parameter,expression,source_class,description",parameters(m));tree(m,o.resolve("model_tree.json"));calibration(o.resolve("M10A3_calibration_required.csv"));}
    private static List<String[]> components(Model m){List<String[]>r=new ArrayList<String[]>();for(String c:m.component().tags()){int d=m.component(c).geom().tags().length==0?0:m.component(c).geom(m.component(c).geom().tags()[0]).getSDim();r.add(new String[]{c,m.component(c).label(),Integer.toString(d),classify(m.component(c).label())});}return r;}
    private static List<String[]> geometries(Model m){List<String[]>r=new ArrayList<String[]>();for(String c:m.component().tags())for(String g:m.component(c).geom().tags())r.add(new String[]{c,g,Integer.toString(m.component(c).geom(g).getSDim()),Integer.toString(m.component(c).geom(g).feature().tags().length),classify(m.component(c).label())});return r;}
    private static List<String[]> selections(Model m){List<String[]>r=new ArrayList<String[]>();for(String c:m.component().tags())for(String s:m.component(c).selection().tags()){int d=-1,n=-1;for(int x=3;x>=0;x--)try{int q=m.component(c).selection(s).entities(x).length;if(q>0){d=x;n=q;break;}}catch(Throwable ignored){}r.add(new String[]{c,s,Integer.toString(d),Integer.toString(n),m.component(c).selection(s).label()});}return r;}
    private static List<String[]> physics(Model m){List<String[]>r=new ArrayList<String[]>();for(String c:m.component().tags())for(String p:m.component(c).physics().tags()){Physics x=m.component(c).physics(p);r.add(new String[]{c,p,x.getType(),x.label(),String.join(";",x.feature().tags())});}return r;}
    private static List<String[]> studies(Model m){List<String[]>r=new ArrayList<String[]>();for(String s:m.study().tags())r.add(new String[]{s,m.study(s).label(),String.join(";",m.study(s).feature().tags()),String.join(";",m.study(s).getSolverSequences("SolverSequence"))});return r;}
    private static List<String[]> datasets(Model m){List<String[]>r=new ArrayList<String[]>();for(String d:m.result().dataset().tags())r.add(new String[]{d,m.result().dataset(d).getType(),m.result().dataset(d).label()});return r;}
    private static List<String[]> results(Model m){List<String[]>r=new ArrayList<String[]>();for(String p:m.result().tags())r.add(new String[]{p,m.result(p).getType(),m.result(p).label(),String.join(";",m.result(p).feature().tags())});for(String t:m.result().table().tags())r.add(new String[]{t,m.result().table(t).getType(),m.result().table(t).label(),"rows="+m.result().table(t).getTableData(false).length});return r;}
    private static List<String[]> parameters(Model m){List<String[]>r=new ArrayList<String[]>();for(String p:m.param().varnames()){String d=m.param().descr(p);r.add(new String[]{p,m.param().get(p),source(d),d});}return r;}
    private static String source(String d){String x=String.valueOf(d).toUpperCase(Locale.ROOT);for(String s:new String[]{"LAB_MANUAL","REAL_CAD","EXPERIMENTAL_GATE","LITERATURE_REPORTED","LITERATURE_SAME_PLATFORM","LITERATURE_ESTIMATE","PROVISIONAL_SENSITIVITY","CALIBRATION_REQUIRED","DERIVED","NUMERICAL_VERIFICATION_ONLY"})if(x.contains(s))return s;if(x.contains("COMPUT")||x.contains("FORMULA")||x.contains("MAPPED")||x.contains("INHERITED AUDIT"))return "DERIVED";if(x.contains("MANUAL"))return "LAB_MANUAL";if(x.contains("CALIBRATION")||x.contains("UNKNOWN"))return "CALIBRATION_REQUIRED";return "PROVISIONAL_SENSITIVITY";}
    private static String classify(String s){String x=String.valueOf(s).toUpperCase(Locale.ROOT);if(x.contains("REDUCED"))return "REDUCED";if(x.contains("PROVISIONAL"))return "PROVISIONAL";if(x.contains("NUMERICAL"))return "NUMERICAL_VERIFICATION_ONLY";if(x.contains("REAL")||x.contains("PHYSICAL"))return "REAL_PHYSICAL";return "SUPPORT";}
    private static void calibration(Path p)throws Exception{List<String[]>r=new ArrayList<String[]>();r.add(new String[]{"H_N2","CALIBRATION_REQUIRED","Electrolyte-specific N2 partition data absent"});r.add(new String[]{"H2_bulk_liquid_dissolution","CALIBRATION_REQUIRED","No reliable electrolyte-specific H2 solubility; prediction intentionally absent"});r.add(new String[]{"proton_donor_identity","CALIBRATION_REQUIRED","Manual/project schema does not uniquely identify donor"});r.add(new String[]{"Q_liq_sweep","PROVISIONAL_SENSITIVITY","RTD is numerical sensitivity, not experimental RTD"});r.add(new String[]{"latex_downstream_length","CALIBRATION_REQUIRED","Unknown latex length excluded from explicit PFA equivalent network"});write(p,"item,status,reason",r);}

    private static void tree(Model m,Path p)throws Exception{StringBuilder j=new StringBuilder("{\n  \"model\":\"LiNRR_M10A3_real_species_transport\",\n  \"components\":[\n");String[]cs=m.component().tags();for(int i=0;i<cs.length;i++){String c=cs[i];if(i>0)j.append(",\n");j.append("    {\"tag\":\"").append(js(c)).append("\",\"label\":\"").append(js(m.component(c).label())).append("\",\"geometry\":[");String[]gs=m.component(c).geom().tags();for(int a=0;a<gs.length;a++){if(a>0)j.append(',');j.append("{\"tag\":\"").append(js(gs[a])).append("\",\"features\":[");String[]fs=m.component(c).geom(gs[a]).feature().tags();for(int b=0;b<fs.length;b++){if(b>0)j.append(',');j.append("{\"tag\":\"").append(js(fs[b])).append("\",\"type\":\"").append(js(m.component(c).geom(gs[a]).feature(fs[b]).getType())).append("\"}");}j.append("]}");}j.append("],\"physics\":[");String[]ps=m.component(c).physics().tags();for(int a=0;a<ps.length;a++){if(a>0)j.append(',');j.append("{\"tag\":\"").append(js(ps[a])).append("\",\"type\":\"").append(js(m.component(c).physics(ps[a]).getType())).append("\"}");}j.append("]}");}j.append("\n  ],\n  \"studies\":[");String[]ss=m.study().tags();for(int i=0;i<ss.length;i++){if(i>0)j.append(',');j.append("\"").append(js(ss[i])).append("\"");}j.append("],\n  \"results\":[");String[]rr=m.result().tags();for(int i=0;i<rr.length;i++){if(i>0)j.append(',');j.append("\"").append(js(rr[i])).append("\"");}j.append("],\n  \"tables\":[");String[]tt=m.result().table().tags();for(int i=0;i<tt.length;i++){if(i>0)j.append(',');j.append("\"").append(js(tt[i])).append("\"");}j.append("]\n}\n");Files.write(p,j.toString().getBytes(StandardCharsets.UTF_8));}
    private static void exportImages(Model m,Path out){for(String[]x:new String[][]{{"pg00_physical_cell","physical_cell_full_3d.png"},{"pg_n2_gas_conc","n2_gas_concentration_real.png"},{"pg_h2_gas_conc","h2_gas_concentration_real.png"},{"pg_n2_dissolved_real","n2_dissolved_real.png"},{"pg_donor_real","proton_donor_real.png"},{"pg_nh3_real","nh3_real.png"},{"pg_tracer_real","tracer_real.png"}})image(m,x[0],out.resolve(x[1]));}
    private static void image(Model m,String plot,Path file){String t="img_m10a3_"+(++imageSerial);m.result(plot).run();m.result().export().create(t,plot,"Image3D");try{m.result().export(t).set("target","file");m.result().export(t).set("filename",file.toString());m.result().export(t).set("width",1400);m.result().export(t).set("height",1000);m.result().export(t).run();if(!Files.isRegularFile(file)||file.toFile().length()==0)throw new IllegalStateException("IMAGE_EMPTY "+plot);}finally{m.result().export().remove(t);}}
    private static void independentReload(String file)throws Exception{Model m=ModelUtil.load("M10A3Reload",file);try{String[]required={"pg00_physical_cell","pg_n2_velocity","pg_n2_pressure","pg_h2_velocity","pg_h2_pressure","pg_n2_gas_conc","pg_n2_dissolved_real","pg_n2_availability","pg_h2_gas_conc","pg_h2_availability","pg_donor_real","pg_nh3_real","pg_tracer_real","pg_nh3_downstream","pg_nh3_breakthrough","pg_nh3_inventory"};for(String p:required){if(!m.result().hasTag(p))throw new IllegalStateException("REQUIRED_PLOT_MISSING "+p);m.result(p).run();if(m.result(p).hasWarning())throw new IllegalStateException("REQUIRED_PLOT_WARNING "+p);System.out.println("M10A3_RELOAD_PLOT|"+p+"|PASS");}for(String t:new String[]{"tbl_rtd_e","tbl_rtd_f"}){if(!m.result().table().hasTag(t))throw new IllegalStateException("REQUIRED_RTD_TABLE_MISSING "+t);String[][]v=m.result().table(t).getTableData(false);if(v.length<3)throw new IllegalStateException("REQUIRED_RTD_TABLE_EMPTY "+t);for(String[]row:v)for(String x:row)if(x==null||x.toLowerCase(Locale.ROOT).contains("undefined")||x.toLowerCase(Locale.ROOT).contains("nan"))throw new IllegalStateException("REQUIRED_RTD_TABLE_NONFINITE "+t);System.out.println("M10A3_RELOAD_TABLE|"+t+"|rows="+v.length+"|PASS");}System.out.println("M10A3_INDEPENDENT_RELOAD=PASS");}finally{ModelUtil.remove("M10A3Reload");}}
    private static String resolveSelection(Model m,String c,String wanted){if(m.component(c).selection().hasTag(wanted))return wanted;for(String s:m.component(c).selection().tags())if(wanted.equals(m.component(c).selection(s).label()))return s;throw new IllegalStateException("SELECTION_NOT_FOUND "+c+"/"+wanted);}
    private static void write(Path p,String h,List<String[]>r)throws Exception{Files.createDirectories(p.getParent());try(BufferedWriter w=Files.newBufferedWriter(p,StandardCharsets.UTF_8)){w.write(h);w.newLine();for(String[]x:r){for(int i=0;i<x.length;i++){if(i>0)w.write(',');w.write(csv(x[i]));}w.newLine();}}}
    private static String csv(String s){String x=String.valueOf(s);return x.contains(",")||x.contains("\"")||x.contains("\n")?"\""+x.replace("\"","\"\"")+"\"":x;}
    private static String js(String s){return String.valueOf(s).replace("\\","\\\\").replace("\"","\\\"").replace("\n","\\n").replace("\r","");}
    private static String rt(String n){try{return((String)Class.forName(RT).getField(n).get(null)).trim();}catch(Exception e){throw new IllegalStateException("RUNTIME_INPUT_MISSING "+n,e);}}
}
