import com.comsol.model.Model;
import com.comsol.model.physics.Physics;
import com.comsol.model.util.ModelUtil;

import java.io.BufferedWriter;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

/** Adds the M10A3 explicit downstream NH3 line and real-cell numerical tracer RTD. */
public final class LiNRR_M10A3_TransientClosure {
    private static final String RT="LiNRR_M10A3_TransientRuntimeInputs";
    private static int serial=0;
    private LiNRR_M10A3_TransientClosure(){}

    public static void main(String[] args)throws Exception{
        Path run=Paths.get(rt("RUN_DIR")),tables=Paths.get(rt("TABLE_DIR"));Files.createDirectories(run);Files.createDirectories(tables);
        Model m=ModelUtil.load("M10A3T",rt("INPUT_MPH"));
        try{
            defineTransientParameters(m);
            if(m.component().hasTag("comp_nh3_downstream")&&m.result().dataset().hasTag("dset_nh3_downstream"))System.out.println("M10A3_RESUME_NH3_DOWNSTREAM=PASS");else{buildAndRunDownstream(m);m.save(run.resolve("checkpoint_06_nh3_downstream.mph").toString());System.out.println("M10A3_CHECKPOINT_06_DOWNSTREAM=PASS");}
            buildAndRunTracerRtd(m,tables);
            writeUpdatedLedgers(m,tables);
            createTransientResults(m);
            m.save(run.resolve("checkpoint_07_rtd.mph").toString());
            m.save(rt("OUTPUT_MPH"));
            System.out.println("M10A3_CHECKPOINT_07=PASS");
            System.out.println("M10A3D_RTD_TRANSPORT=PASS");
            System.out.println("M10A3C_NH3_DOWNSTREAM_CLOSURE=PASS");
        }finally{ModelUtil.remove("M10A3T");}
    }

    private static void defineTransientParameters(Model m){
        p(m,"t_tracer_pulse","60[s]","NUMERICAL_VERIFICATION_ONLY finite normalized tracer pulse");
        p(m,"L_pipe_equiv","0.60[m]","DERIVED documented PFA segment total; latex length excluded");
        p(m,"V_pipe_equiv","pi*(liq_pfa_id/2)^2*(L_liq_20+2*L_liq_15)+pi*(liq_pfa_id_large/2)^2*L_liq_10","DERIVED documented PFA volume; equivalent 1D network");
        p(m,"t_downstream_ramp","(V_pipe_equiv/Q_liq_sweep)/10","NUMERICAL_VERIFICATION_ONLY smooth startup over 0.1 reduced-network residence time; final prescribed molar-flow amplitude unchanged");
        p(m,"A_pipe_equiv","V_pipe_equiv/L_pipe_equiv","DERIVED volume-preserving equivalent 1D area");
        p(m,"u_pipe_equiv","Q_liq_sweep/A_pipe_equiv","DERIVED equivalent 1D advection speed");
        p(m,"c_NH3_cell_outlet_transfer","nh3_outlet_rate/Q_liq_sweep","DERIVED strict 3D cell outlet molar-flow transfer to explicit 1D network");
    }

    private static void buildAndRunDownstream(Model m){
        String c="comp_nh3_downstream",g="geom_nh3_downstream",ph="tds_nh3_pipe";
        if(m.component().hasTag(c))m.component().remove(c);m.component().create(c,true);m.component(c).label("REDUCED | explicit equivalent 1D downstream liquid network");m.component(c).geom().create(g,1);m.component(c).geom(g).label("Equivalent documented PFA length; not continuous 3D CAD");m.component(c).geom(g).create("int_pipe","Interval");m.component(c).geom(g).feature("int_pipe").set("p",new String[]{"0","L_pipe_equiv"});m.component(c).geom(g).run();
        box1(m,c,"sel_dom_nh3_pipe",1,"-1e-9[m]","L_pipe_equiv+1e-9[m]");box1(m,c,"sel_bnd_nh3_pipe_inlet",0,"-1e-9[m]","1e-9[m]");box1(m,c,"sel_bnd_nh3_pipe_outlet",0,"L_pipe_equiv-1e-9[m]","L_pipe_equiv+1e-9[m]");
        Physics t=m.component(c).physics().create(ph,"DilutedSpecies",g,new String[]{"cNH3pipe"});t.label("NH3 downstream response | strict molar-flow inlet | REDUCED 1D");t.selection().named("sel_dom_nh3_pipe");t.feature("cdm1").set("D_cNH3pipe_mat","userdef");t.feature("cdm1").set("D_cNH3pipe","D_NH3_liq");t.feature("cdm1").set("u",new String[][]{{"u_pipe_equiv"},{"0[m/s]"},{"0[m/s]"}});conservative(t);t.feature("init1").set("initc",new String[]{"0[mol/m^3]"});t.create("inflow","Inflow",0);t.feature("inflow").selection().named("sel_bnd_nh3_pipe_inlet");t.feature("inflow").set("BoundaryConditionType","FluxDanckwerts");t.feature("inflow").set("c0",new String[]{"c_NH3_cell_outlet_transfer*(1-exp(-t/t_downstream_ramp))"});t.create("outflow","Outflow",0);t.feature("outflow").selection().named("sel_bnd_nh3_pipe_outlet");
        m.component(c).mesh().create("mesh_nh3_pipe");m.component(c).mesh("mesh_nh3_pipe").autoMeshSize(3);m.component(c).mesh("mesh_nh3_pipe").run();
        double tend=6*m.param().evaluate("V_pipe_equiv/Q_liq_sweep","s");runTimeStudy(m,"std_nh3_downstream","time",ph,"range(0,1,"+f(tend)+")","dset_nh3_downstream",c);
        double min=eval(m,"MinLine","dset_nh3_downstream",c,"sel_dom_nh3_pipe",1,"cNH3pipe","mol/m^3");
        String inletRate="Q_liq_sweep*c_NH3_cell_outlet_transfer*(1-exp(-t/t_downstream_ramp))",outletRate="Q_liq_sweep*cNH3pipe";double in=eval(m,"EvalPoint","dset_nh3_downstream",c,"sel_bnd_nh3_pipe_inlet",0,inletRate,"mol/s"),out=eval(m,"EvalPoint","dset_nh3_downstream",c,"sel_bnd_nh3_pipe_outlet",0,outletRate,"mol/s"),acc=eval(m,"IntLine","dset_nh3_downstream",c,"sel_dom_nh3_pipe",1,"d(cNH3pipe,t)*A_pipe_equiv","mol/s"),res=in-out-acc,rr=Math.abs(res)/Math.max(Math.abs(in),1e-300);
        double inventory=eval(m,"IntLine","dset_nh3_downstream",c,"sel_dom_nh3_pipe",1,"cNH3pipe*A_pipe_equiv","mol"),rawTolerance=1e-8;
        double[] time=series(m,"EvalPoint","dset_nh3_downstream",c,"sel_bnd_nh3_pipe_inlet",0,"t","s"),inSeries=series(m,"EvalPoint","dset_nh3_downstream",c,"sel_bnd_nh3_pipe_inlet",0,inletRate,"mol/s"),outSeries=series(m,"EvalPoint","dset_nh3_downstream",c,"sel_bnd_nh3_pipe_outlet",0,outletRate,"mol/s");
        double generated=trap(time,inSeries),discharged=trap(time,outSeries),cumulativeResidual=generated-discharged-inventory,cumulativeRelative=Math.abs(cumulativeResidual)/Math.max(Math.abs(generated),1e-300);
        if(min<-rawTolerance||rr>1e-6||cumulativeRelative>1e-6)throw new IllegalStateException("NH3_DOWNSTREAM_AUDIT min="+min+" rr="+rr+" cumulative_rr="+cumulativeRelative);
        p(m,"nh3_downstream_outlet_rate",f(out)+"[mol/s]","DERIVED explicit equivalent 1D network response");p(m,"nh3_downstream_relative_residual",f(Math.max(rr,cumulativeRelative)),"DERIVED maximum instantaneous/cumulative conservative balance");p(m,"nh3_retained_inventory",f(inventory)+"[mol]","DERIVED explicit reduced-network retained inventory");p(m,"nh3_generated_inventory",f(generated)+"[mol]","DERIVED time-integrated prescribed numerical source entering downstream network");p(m,"nh3_discharged_inventory",f(discharged)+"[mol]","DERIVED time-integrated downstream outlet");System.out.println("M10A3_NH3_DOWNSTREAM|in="+f(in)+"|out="+f(out)+"|accumulation="+f(acc)+"|retained_inventory="+f(inventory)+"|generated="+f(generated)+"|discharged="+f(discharged)+"|relative_residual="+f(Math.max(rr,cumulativeRelative))+"|min="+f(min));
    }

    private static void buildAndRunTracerRtd(Model m,Path tables)throws Exception{
        String c="comp_species_liq_real",ph="tds_tracer";String geom=m.component(c).geom().tags()[0],dom=resolveSelection(m,c,"sel_dom_electrolyte_fluid"),inlet=resolveSelection(m,c,"sel_bnd_electrolyte_inlet"),outlet=resolveSelection(m,c,"sel_bnd_electrolyte_outlet");
        double volume=geomMeasure(m,c,geom,3,m.component(c).selection(dom).entities(3))*1e-9,Q=m.param().evaluate("Q_liq_sweep","m^3/s"),tauNom=volume/Q,tEnd=6*tauNom,dt=Math.max(1.0,tauNom/600.0);p(m,"V_liq_real",f(volume)+"[m^3]","REAL_CAD selected real electrolyte fluid volume");p(m,"tau_rtd_nom",f(tauNom)+"[s]","DERIVED V_REAL_CAD/Q_PROVISIONAL");p(m,"t_rtd_end",f(tEnd)+"[s]","NUMERICAL_VERIFICATION_ONLY six nominal residence times");p(m,"dt_rtd_output",f(dt)+"[s]","NUMERICAL_VERIFICATION_ONLY post-pulse output spacing; adaptive internal solver unchanged");
        boolean resumeCoarse=m.component(c).physics().hasTag(ph)&&m.result().dataset().hasTag("dset_rtd")&&hasParameter(m,"rtd_coarse_tau_mean")&&hasParameter(m,"rtd_coarse_elements");
        if(!resumeCoarse){if(m.component(c).physics().hasTag(ph))m.component(c).physics().remove(ph);Physics t=m.component(c).physics().create(ph,"DilutedSpecies",geom,new String[]{"cTracer"});t.label("Nonreactive tracer | REAL electrolyte CAD | PROVISIONAL Q");t.selection().named(dom);t.feature("cdm1").set("D_cTracer_mat","userdef");t.feature("cdm1").set("D_cTracer","D_tracer+beta_species_numdiff*max(sqrt(u_liq_species^2+v_liq_species^2+w_liq_species^2),u_liq_species_ref)*h");t.feature("cdm1").set("u",new String[][]{{"u_liq_species"},{"v_liq_species"},{"w_liq_species"}});conservative(t);t.feature("init1").set("initc",new String[]{"0[mol/m^3]"});t.create("pulse","Inflow",2);t.feature("pulse").selection().named(inlet);t.feature("pulse").set("BoundaryConditionType","FluxDanckwerts");t.feature("pulse").set("c0",new String[]{"if(t<=t_tracer_pulse,c_tracer_pulse*sin(pi*t/t_tracer_pulse)^2,0[mol/m^3])"});t.create("outflow","Outflow",2);t.feature("outflow").selection().named(outlet);}
        String mesh=m.component(c).mesh().tags()[0];double[] means=new double[2];int[] elements=new int[2];String list="range(0,0.5,60) range(60+"+f(dt)+","+f(dt)+","+f(tEnd)+")";double[][] reference=readRtd(tables.resolve("M10A3_RTD_medium.csv"));
        if(resumeCoarse){means[0]=m.param().evaluate("rtd_coarse_tau_mean","s");elements[0]=(int)Math.round(m.param().evaluate("rtd_coarse_elements"));writeRtd(tables.resolve("M10A3_RTD_coarse.csv"),calculateRtd(m,"dset_rtd",c,outlet,dom,ph));System.out.println("M10A3_RESUME_RTD_COARSE=PASS|elements="+elements[0]+"|tau_mean="+f(means[0]));}
        else{m.component(c).mesh(mesh).run();elements[0]=m.component(c).mesh(mesh).getNumElem();runTimeStudy(m,"std_rtd","time",ph,list,"dset_rtd",c);double[][] coarse=calculateRtd(m,"dset_rtd",c,outlet,dom,ph);means[0]=coarse[4][0];writeRtd(tables.resolve("M10A3_RTD_coarse.csv"),coarse);System.out.println("M10A3_RTD_MESH|mesh=coarse|elements="+elements[0]+"|tau_mean="+f(coarse[4][0])+"|relative_residual="+f(Math.max(coarse[4][5],coarse[4][6])));p(m,"rtd_coarse_tau_mean",f(coarse[4][0])+"[s]","DERIVED coarse real-CAD RTD mean");p(m,"rtd_coarse_elements",Integer.toString(elements[0]),"DERIVED coarse RTD mesh elements");m.save(Paths.get(rt("RUN_DIR")).resolve("checkpoint_06_rtd_coarse.mph").toString());System.out.println("M10A3_CHECKPOINT_06_RTD_COARSE=PASS");}
        addRtdRefinement(m,c,mesh);m.component(c).mesh(mesh).run();elements[1]=m.component(c).mesh(mesh).getNumElem();m.study("std_rtd").feature("time").set("tlist",list);m.study("std_rtd").feature("time").set("rtol","1e-8");m.study("std_rtd").run();rebind(m,"std_rtd","dset_rtd",c);Path preAudit=Paths.get(rt("RUN_DIR")).resolve("checkpoint_07_rtd_medium_pre_audit.mph");m.save(preAudit.toString());if(!Files.isRegularFile(preAudit))throw new IllegalStateException("RTD_MEDIUM_PRE_AUDIT_CHECKPOINT_MISSING");System.out.println("M10A3_CHECKPOINT_07_RTD_MEDIUM_PRE_AUDIT=PASS");double[][] medium=calculateRtd(m,"dset_rtd",c,outlet,dom,ph);means[1]=medium[4][0];writeRtd(tables.resolve("M10A3_RTD_medium.csv"),medium);writeTemporalConvergence(tables.resolve("M10A3_RTD_temporal_quadrature_convergence.csv"),reference,medium,tauNom);System.out.println("M10A3_RTD_MESH|mesh=medium|elements="+elements[1]+"|tau_mean="+f(medium[4][0])+"|relative_residual="+f(Math.max(medium[4][5],medium[4][6])));
        if(elements[1]<=elements[0])throw new IllegalStateException("RTD_MEDIUM_MESH_NOT_REFINED coarse="+elements[0]+" medium="+elements[1]);double md=rel(means[0],means[1]);p(m,"mesh_diff_rtd",f(md),"DERIVED coarse-medium RTD mean difference");if(md>0.10)throw new IllegalStateException("RTD_MESH_SENSITIVITY_GT_10_PERCENT "+md);double[][] r=medium;p(m,"rtd_tau_mean",f(r[4][0])+"[s]","DERIVED real-CAD numerical RTD");p(m,"rtd_variance",f(r[4][1])+"[s^2]","DERIVED");p(m,"rtd_std",f(Math.sqrt(r[4][1]))+"[s]","DERIVED");p(m,"rtd_t10",f(r[4][2])+"[s]","DERIVED");p(m,"rtd_t50",f(r[4][3])+"[s]","DERIVED");p(m,"rtd_t90",f(r[4][4])+"[s]","DERIVED");p(m,"rtd_tau_mean_over_nom",f(r[4][0]/tauNom),"DERIVED");p(m,"rtd_outlet_mass",f(r[4][8])+"[mol]","DERIVED recovered tracer mass used to normalize E(t)");p(m,"rtd_recovered_fraction",f(r[4][9]),"DERIVED outlet mass divided by formally integrated Danckwerts inlet flux");p(m,"rtd_injected_mass_numerical",f(r[4][11])+"[mol]","DERIVED temporal integration of formally imposed Danckwerts inlet flux");p(m,"rtd_injected_mass_analytical",f(r[4][12])+"[mol]","DERIVED prescribed sin-squared pulse using actual solved inlet volumetric flow");p(m,"rtd_injected_mass_relative_difference",f(r[4][13]),"DERIVED numerical versus analytical prescribed input");p(m,"rtd_final_inventory",f(r[4][10])+"[mol]","DERIVED final tracer inventory");p(m,"tracer_conservation_relative",f(Math.max(r[4][5],r[4][6])),"DERIVED maximum instantaneous/cumulative PDE balance");System.out.println("TRACER_INPUT_AUDIT|numerical="+f(r[4][11])+"|analytical_actual_flow="+f(r[4][12])+"|relative_difference="+f(r[4][13])+"|actual_inlet_Q="+f(r[4][14]));System.out.println("TRACER_AUDIT|min="+f(r[4][7])+"|instantaneous_rr="+f(r[4][5])+"|cumulative_rr="+f(r[4][6])+"|outlet_mass="+f(r[4][8])+"|final_inventory="+f(r[4][10])+"|output_points="+(int)Math.round(r[4][16])+"|output_dt="+f(r[4][15]));if(r[4][7]<-1e-8||r[4][5]>1e-6||r[4][6]>1e-6)throw new IllegalStateException("TRACER_AUDIT min="+r[4][7]+" instantaneous_rr="+r[4][5]+" cumulative_rr="+r[4][6]);writeRtd(tables.resolve("M10A3_RTD.csv"),r);Path accepted=Paths.get(rt("RUN_DIR")).resolve("checkpoint_07_rtd_medium_accepted.mph");m.save(accepted.toString());if(!Files.isRegularFile(accepted))throw new IllegalStateException("RTD_MEDIUM_ACCEPTED_CHECKPOINT_MISSING");System.out.println("M10A3_CHECKPOINT_07_RTD_MEDIUM_ACCEPTED=PASS");
    }

    private static void addRtdRefinement(Model m,String c,String mesh){String tag="m10a3_rtd_refine";if(m.component(c).mesh(mesh).feature().hasTag(tag))m.component(c).mesh(mesh).feature().remove(tag);m.component(c).mesh(mesh).create(tag,"Refine");List<Integer> ids=new ArrayList<Integer>();for(String s:new String[]{"sel_bnd_electrolyte_inlet","sel_bnd_electrolyte_outlet","sel_bnd_electrolyte_gde_top","sel_bnd_electrolyte_gde_bottom"})for(int id:m.component(c).selection(resolveSelection(m,c,s)).entities(2))if(!ids.contains(id))ids.add(id);int[] a=new int[ids.size()];for(int i=0;i<a.length;i++)a[i]=ids.get(i);m.component(c).mesh(mesh).feature(tag).selection().geom(2);m.component(c).mesh(mesh).feature(tag).selection().set(a);}

    private static double[][] calculateRtd(Model m,String data,String c,String outlet,String dom,String ph){String un="(u_liq_species*nx+v_liq_species*ny+w_liq_species*nz)",pulse="if(t<=t_tracer_pulse,c_tracer_pulse*sin(pi*t/t_tracer_pulse)^2,0[mol/m^3])",inlet=resolveSelection(m,c,"sel_bnd_electrolyte_inlet");double[] time=series(m,"AvSurface",data,c,outlet,2,"t","s"),flow=series(m,"IntSurface",data,c,outlet,2,"cTracer*"+un,"mol/s"),inSeries=series(m,"IntSurface",data,c,inlet,2,"-"+pulse+"*"+un,"mol/s");if(time.length!=flow.length||time.length!=inSeries.length||time.length<3)throw new IllegalStateException("RTD_SERIES_SHAPE");double mass=trap(time,flow),massHighOrder=piecewiseSimpson(time,flow),injected=trap(time,inSeries),qActual=eval(m,"IntSurface",data,c,inlet,2,"-"+un,"m^3/s"),injectedAnalytical=qActual*m.param().evaluate("c_tracer_pulse","mol/m^3")*m.param().evaluate("t_tracer_pulse","s")/2,m1=0;if(!(mass>0&&injected>0&&injectedAnalytical>0))throw new IllegalStateException("RTD_MASS_INVALID outlet="+mass+" injected="+injected+" analytical="+injectedAnalytical);for(int i=1;i<time.length;i++)m1+=0.5*(time[i-1]*flow[i-1]+time[i]*flow[i])*(time[i]-time[i-1]);double mean=m1/mass,var=0;for(int i=1;i<time.length;i++){double a=(time[i-1]-mean)*(time[i-1]-mean)*flow[i-1],b=(time[i]-mean)*(time[i]-mean)*flow[i];var+=0.5*(a+b)*(time[i]-time[i-1]);}var/=mass;double[] E=new double[flow.length],F=new double[flow.length];for(int i=0;i<flow.length;i++)E[i]=flow[i]/mass;for(int i=1;i<F.length;i++)F[i]=F[i-1]+0.5*(E[i-1]+E[i])*(time[i]-time[i-1]);double t10=quantile(time,F,.1),t50=quantile(time,F,.5),t90=quantile(time,F,.9),peakIn=0;for(double x:inSeries)peakIn=Math.max(peakIn,Math.abs(x));double in=inSeries[inSeries.length-1],out=flow[flow.length-1],acc=eval(m,"IntVolume",data,c,dom,3,"d(cTracer,t)","mol/s"),instantaneous=Math.abs(in-out-acc)/Math.max(peakIn,1e-300),inventory=eval(m,"IntVolume",data,c,dom,3,"cTracer","mol"),cumulative=Math.abs(injected-mass-inventory)/Math.max(Math.abs(injected),1e-300),min=eval(m,"MinVolume",data,c,dom,3,"cTracer","mol/m^3"),dtPost=maxStep(time);return new double[][]{time,flow,E,F,new double[]{mean,var,t10,t50,t90,instantaneous,cumulative,min,mass,mass/injected,inventory,injected,injectedAnalytical,rel(injected,injectedAnalytical),qActual,dtPost,time.length,massHighOrder,rel(mass,massHighOrder)}};}

    private static void writeUpdatedLedgers(Model m,Path tables)throws Exception{Path p=tables.resolve("M10A3_species_conservation.csv");List<String> lines=Files.readAllLines(p,StandardCharsets.UTF_8),out=new ArrayList<String>();for(String s:lines)if(!s.startsWith("tracer,"))out.add(s);double rr=m.param().evaluate("tracer_conservation_relative");out.add("tracer,real_liquid_RTD,0,0,0,0,DERIVED_FROM_d_c_dt,0,"+f(rr)+",PASS");out.add("NH3,explicit_equivalent_1D_downstream,"+f(m.param().evaluate("nh3_outlet_rate","mol/s"))+","+f(m.param().evaluate("nh3_downstream_outlet_rate","mol/s")) +",0,0,DERIVED_FROM_d_c_dt,0,"+f(m.param().evaluate("nh3_downstream_relative_residual")) +",PASS");Files.write(p,out,StandardCharsets.UTF_8);Path mesh=tables.resolve("M10A3_mesh_convergence.csv");List<String> ml=Files.readAllLines(mesh,StandardCharsets.UTF_8);double d=m.param().evaluate("mesh_diff_rtd");ml.add("rtd_tau_mean,coarse_to_medium,"+f(d)+","+(d<=.05?"PASS":"LIMITATION"));Files.write(mesh,ml,StandardCharsets.UTF_8);double prev=m.param().evaluate("mesh_max_key_difference");p(m,"mesh_max_key_difference",f(Math.max(prev,d)),"DERIVED all M10A3 coarse-medium key metrics");}

    private static void createTransientResults(Model m){if(m.result().hasTag("pg_nh3_downstream"))m.result().remove("pg_nh3_downstream");m.result().create("pg_nh3_downstream","PlotGroup1D");m.result("pg_nh3_downstream").label("NH3 Downstream Response | REDUCED equivalent 1D PFA");m.result("pg_nh3_downstream").set("data","dset_nh3_downstream");m.result("pg_nh3_downstream").create("line","LineGraph");m.result("pg_nh3_downstream").feature("line").set("expr","cNH3pipe");if(m.result().hasTag("pg_tracer_real"))m.result().remove("pg_tracer_real");m.result().create("pg_tracer_real","PlotGroup3D");m.result("pg_tracer_real").label("Tracer - Real Geometry | PROVISIONAL_SENSITIVITY Q");m.result("pg_tracer_real").set("data","dset_rtd");m.result("pg_tracer_real").create("surf","Surface");m.result("pg_tracer_real").feature("surf").set("expr","cTracer");}

    private static void runTimeStudy(Model m,String tag,String step,String active,String list,String data,String comp){if(m.study().hasTag(tag))m.study().remove(tag);m.study().create(tag);m.study(tag).label(tag+" | M10A3");m.study(tag).create(step,"Transient");m.study(tag).feature(step).set("tlist",list);m.study(tag).feature(step).set("rtol",tag.equals("std_nh3_downstream")?"1e-7":"1e-5");for(String c:m.component().tags())for(String p:m.component(c).physics().tags())m.study(tag).feature(step).activate(p,p.equals(active));m.study(tag).run();rebind(m,tag,data,comp);}
    private static void rebind(Model m,String study,String data,String comp){String[]s=m.study(study).getSolverSequences("SolverSequence");if(s.length<1)throw new IllegalStateException("NO_SOLVER "+study);if(!m.result().dataset().hasTag(data))m.result().dataset().create(data,"Solution");m.result().dataset(data).set("solution",s[s.length-1]);m.result().dataset(data).set("comp",comp);}
    private static void conservative(Physics t){t.prop("AdvancedSettings").set("ConvectiveTerm","cons");t.prop("MassConsistentStabilization").set("massStreamlineDiffusion",true);t.prop("MassConsistentStabilization").set("massCrosswindDiffusion",false);t.prop("ShapeProperty").set("order_concentration",1);}
    private static void box1(Model m,String c,String tag,int dim,String xmin,String xmax){m.component(c).selection().create(tag,"Box");m.component(c).selection(tag).set("entitydim",dim);m.component(c).selection(tag).set("condition","inside");m.component(c).selection(tag).set("xmin",xmin);m.component(c).selection(tag).set("xmax",xmax);}
    private static String resolveSelection(Model m,String c,String wanted){if(m.component(c).selection().hasTag(wanted))return wanted;for(String s:m.component(c).selection().tags())if(wanted.equals(m.component(c).selection(s).label()))return s;throw new IllegalStateException("SELECTION_NOT_FOUND "+c+"/"+wanted);}
    private static double eval(Model m,String type,String data,String comp,String sel,int dim,String expr,String unit){double[]x=series(m,type,data,comp,sel,dim,expr,unit);return x[x.length-1];}
    private static double[] series(Model m,String type,String data,String comp,String sel,int dim,String expr,String unit){String tag="m10a3t_ev_"+(++serial);m.result().numerical().create(tag,type);try{m.result().numerical(tag).set("data",data);m.result().numerical(tag).selection().geom(m.component(comp).geom().tags()[0],dim);m.result().numerical(tag).selection().set(m.component(comp).selection(resolveSelection(m,comp,sel)).entities(dim));m.result().numerical(tag).set("expr",new String[]{expr});m.result().numerical(tag).set("unit",new String[]{unit});if(type.startsWith("Int")){m.result().numerical(tag).set("intorderactive",true);m.result().numerical(tag).set("intorder",8);}double[][]v=m.result().numerical(tag).getReal();if(v==null||v.length==0||v[0].length==0)throw new IllegalStateException("EMPTY_EVAL "+expr);return v[0];}finally{m.result().numerical().remove(tag);}}
    private static double geomMeasure(Model m,String c,String g,int dim,int[]ids){m.component(c).geom(g).measureFinal().selection().geom(dim);m.component(c).geom(g).measureFinal().selection().set(ids);return m.component(c).geom(g).measureFinal().getVolume();}
    private static void writeRtd(Path path,double[][] r)throws Exception{try(BufferedWriter w=Files.newBufferedWriter(path,StandardCharsets.UTF_8)){w.write("time_s,outlet_mol_s,E_1_s,F");w.newLine();for(int i=0;i<r[0].length;i++){w.write(f(r[0][i])+","+f(r[1][i])+","+f(r[2][i])+","+f(r[3][i]));w.newLine();}}}
    private static double[][] readRtd(Path path)throws Exception{if(!Files.isRegularFile(path))return null;List<String> lines=Files.readAllLines(path,StandardCharsets.UTF_8);if(lines.size()<4)return null;double[]t=new double[lines.size()-1],q=new double[t.length],e=new double[t.length],cdf=new double[t.length];for(int i=1;i<lines.size();i++){String[]v=lines.get(i).split(",",-1);if(v.length<4)throw new IllegalStateException("RTD_REFERENCE_CSV_SHAPE "+path);t[i-1]=Double.parseDouble(v[0]);q[i-1]=Double.parseDouble(v[1]);e[i-1]=Double.parseDouble(v[2]);cdf[i-1]=Double.parseDouble(v[3]);}double mass=trap(t,q),moment=0;for(int i=1;i<t.length;i++)moment+=.5*(t[i-1]*q[i-1]+t[i]*q[i])*(t[i]-t[i-1]);return new double[][]{t,q,e,cdf,new double[]{moment/mass,0,quantile(t,cdf,.1),quantile(t,cdf,.5),quantile(t,cdf,.9),runtimeDouble("RTD_REFERENCE_INSTANTANEOUS_RR"),runtimeDouble("RTD_REFERENCE_CUMULATIVE_RR"),runtimeDouble("RTD_REFERENCE_TRACER_MIN"),mass,Double.NaN,Double.NaN,Double.NaN,Double.NaN,Double.NaN,Double.NaN,maxStep(t),t.length,piecewiseSimpson(t,q),rel(mass,piecewiseSimpson(t,q))}};}
    private static void writeTemporalConvergence(Path path,double[][] reference,double[][] current,double tauNom)throws Exception{double change=reference==null?Double.NaN:rel(reference[4][8],current[4][8]),tol=1e-6;try(BufferedWriter w=Files.newBufferedWriter(path,StandardCharsets.UTF_8)){w.write("case,post_output_dt_s,output_points,outlet_integrated_mass_mol,outlet_piecewise_simpson_mass_mol,final_inventory_mol,injected_mass_numerical_mol,injected_mass_analytical_actual_flow_mol,injected_relative_difference,instantaneous_relative_residual,cumulative_relative_residual,tracer_min_mol_m3,tau_nom_s,tau_mean_s,t10_s,t50_s,t90_s,outlet_mass_relative_change,status,notes");w.newLine();if(reference!=null){w.write("existing_tau_nom_over_300,"+f(reference[4][15])+","+(int)Math.round(reference[4][16])+","+f(reference[4][8])+","+f(reference[4][17])+",NA_NOT_EMITTED_BEFORE_CHECKPOINT,"+f(current[4][12])+","+f(current[4][12])+",0,"+f(reference[4][5])+","+f(reference[4][6])+","+f(reference[4][7])+","+f(tauNom)+","+f(reference[4][0])+","+f(reference[4][2])+","+f(reference[4][3])+","+f(reference[4][4])+",0,REFERENCE_CUMULATIVE_FAIL,Failed run did not preserve final inventory; exact prescribed input reconstructed from solved flow and pulse law");w.newLine();}w.write("two_x_denser_tau_nom_over_600,"+f(current[4][15])+","+(int)Math.round(current[4][16])+","+f(current[4][8])+","+f(current[4][17])+","+f(current[4][10])+","+f(current[4][11])+","+f(current[4][12])+","+f(current[4][13])+","+f(current[4][5])+","+f(current[4][6])+","+f(current[4][7])+","+f(tauNom)+","+f(current[4][0])+","+f(current[4][2])+","+f(current[4][3])+","+f(current[4][4])+","+f(change)+","+((!Double.isNaN(change)&&change<=tol)?"OUTPUT_QUADRATURE_CONVERGED":"REQUIRES_FOUR_X_OUTPUT_TEST")+",Spatial mesh physics pulse and adaptive internal solver definition frozen");w.newLine();}System.out.println("RTD_TEMPORAL_QUADRATURE|outlet_mass_relative_change="+f(change)+"|threshold="+f(tol)+"|status="+((!Double.isNaN(change)&&change<=tol)?"PASS":"FAIL"));if(Double.isNaN(change)||change>tol)throw new IllegalStateException("RTD_OUTPUT_QUADRATURE_NOT_CONVERGED relative_change="+change);System.out.println("RTD_TEMPORAL_QUADRATURE_CONVERGED=PASS");}
    private static double trap(double[]x,double[]y){if(x.length!=y.length||x.length<2)throw new IllegalArgumentException("INTEGRATION_SERIES_SHAPE");double z=0;for(int i=1;i<x.length;i++)z+=.5*(y[i-1]+y[i])*(x[i]-x[i-1]);return z;}
    private static double piecewiseSimpson(double[]x,double[]y){if(x.length!=y.length||x.length<2)throw new IllegalArgumentException("INTEGRATION_SERIES_SHAPE");double z=0;int start=0;for(int i=2;i<x.length;i++){double a=x[i-1]-x[i-2],b=x[i]-x[i-1],tol=Math.max(Math.max(Math.abs(a),Math.abs(b))*1e-9,1e-12);if(Math.abs(a-b)>tol){z+=uniformSimpson(x,y,start,i-1);start=i-1;}}return z+uniformSimpson(x,y,start,x.length-1);}
    private static double uniformSimpson(double[]x,double[]y,int first,int last){int intervals=last-first,simpsonIntervals=intervals-(intervals%2);double z=0;for(int offset=0;offset<simpsonIntervals;offset+=2){int i=first+offset;z+=(x[i+2]-x[i])*(y[i]+4*y[i+1]+y[i+2])/6;}if(simpsonIntervals<intervals)z+=.5*(y[last-1]+y[last])*(x[last]-x[last-1]);return z;}
    private static double maxStep(double[]x){double z=0;for(int i=1;i<x.length;i++)z=Math.max(z,x[i]-x[i-1]);return z;}
    private static double quantile(double[]t,double[]f,double q){for(int i=1;i<f.length;i++)if(f[i]>=q){double a=(q-f[i-1])/Math.max(f[i]-f[i-1],1e-300);return t[i-1]+a*(t[i]-t[i-1]);}return t[t.length-1];}
    private static double rel(double a,double b){return Math.abs(a-b)/Math.max(Math.max(Math.abs(a),Math.abs(b)),1e-300);}
    private static boolean hasParameter(Model m,String name){for(String x:m.param().varnames())if(x.equals(name))return true;return false;}
    private static void p(Model m,String n,String v,String d){m.param().set(n,v,d);}
    private static String f(double x){return String.format(Locale.ROOT,"%.15g",x);}
    private static double runtimeDouble(String n){try{return Double.parseDouble(((String)Class.forName(RT).getField(n).get(null)).trim());}catch(Exception e){return Double.NaN;}}
    private static String rt(String n){try{return((String)Class.forName(RT).getField(n).get(null)).trim();}catch(Exception e){throw new IllegalStateException("RUNTIME_INPUT_MISSING "+n,e);}}
}
