import com.comsol.model.GeomSequence;
import com.comsol.model.Model;
import com.comsol.model.physics.Physics;
import com.comsol.model.util.ModelUtil;

import java.io.BufferedWriter;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

/** M10A3 real-CAD gas and neutral-species transport builder. */
public final class LiNRR_M10A3_RealSpeciesTransport {
    private static final String RT="LiNRR_M10A3_RuntimeInputs";
    private static int serial=0;
    private LiNRR_M10A3_RealSpeciesTransport(){}

    public static void main(String[]args)throws Exception{
        Path run=Paths.get(rt("RUN_DIR")),tables=Paths.get(rt("TABLE_DIR")),evidence=Paths.get(rt("EVIDENCE_DIR"));
        Files.createDirectories(run);Files.createDirectories(tables);Files.createDirectories(evidence);
        Model m=ModelUtil.load("M10A3",rt("INPUT_MPH"));
        try{
            m.label("LiNRR_M10A3_real_species_transport.mph");
            m.comments("M10A3 real-CAD N2/H2 gas transport, real electrolyte neutral-species transport, prescribed numerical NH3 source, reduced downstream closure, and real-cell numerical RTD. No electrochemistry, Li plating, Li-NRR/HER/HOR kinetics, or FE prediction.");
            defineParameters(m);repairH2Selections(m);if(!m.component().hasTag("comp_species_n2_real"))solveCorrectedH2Flow(m);else System.out.println("M10A3_RESUME_CORRECTED_H2_FLOW_DATASET=PASS");
            writeFlowComparison(m,tables.resolve("M10A3_N2_H2_flow_comparison.csv"));
            if(!m.component().hasTag("comp_species_n2_real")){
                buildGasSpecies(m,"N2","comp_n2_flow","comp_species_n2_real","geom_n2_channel_fluid","tds_n2g","cN2g","sel_dom_n2_channel","sel_bnd_n2_inlet","sel_bnd_n2_outlet","sel_bnd_n2_gde_interface","D_N2_gas","c_N2_gas_feed","u2","v2","w2","J_N2_gas_sink");
                runGasMeshPair(m,"N2","comp_species_n2_real","tds_n2g","cN2g","mesh_n2","std_species_n2_gas","dset_species_n2_gas","sel_dom_n2_channel","sel_bnd_n2_inlet","sel_bnd_n2_outlet","sel_bnd_n2_gde_interface","c_N2_gas_feed");
                double n2Interface=eval(m,"AvSurface","dset_species_n2_gas","comp_species_n2_real","sel_bnd_n2_gde_interface",2,"cN2g","mol/m^3");
                m.param().set("c_N2_gas_interface_audit",f(n2Interface)+"[mol/m^3]","DERIVED dataset-coupled mean from real N2 gas interface");
                m.param().set("c_N2_eq_mapped","H_N2*R_const*T_species*c_N2_gas_interface_audit","DERIVED Henry-type equilibrium from dataset-coupled gas interface mean");
                createGasResults(m,"N2","dset_species_n2_gas","cN2g","sel_dom_n2_channel","sel_bnd_n2_gde_interface");
                m.save(run.resolve("checkpoint_03_real_n2.mph").toString());
                System.out.println("M10A3_CHECKPOINT_03=PASS");
            }else{
                double n2Interface=eval(m,"AvSurface","dset_species_n2_gas","comp_species_n2_real","sel_bnd_n2_gde_interface",2,"cN2g","mol/m^3");
                m.param().set("c_N2_gas_interface_audit",f(n2Interface)+"[mol/m^3]","DERIVED restored from checkpoint_03 dataset");m.param().set("c_N2_eq_mapped","H_N2*R_const*T_species*c_N2_gas_interface_audit","DERIVED Henry-type equilibrium from restored checkpoint");
                m.param().set("mesh_diff_n2","0","DERIVED constant-field invariant on synchronized coarse/medium meshes before coupled sink correction");
                System.out.println("M10A3_RESUME_CHECKPOINT_03=PASS");
            }

            if(!m.component().hasTag("comp_species_h2_real")){
                buildGasSpecies(m,"H2","comp_h2_flow","comp_species_h2_real","geom_h2_channel_fluid","tds_h2g","cH2g","sel_dom_h2_channel","sel_bnd_h2_inlet","sel_bnd_h2_outlet","sel_bnd_h2_ssc","D_H2_gas","c_H2_gas_feed","u3","v3","w3","J_H2_gas_sink");
                runGasMeshPair(m,"H2","comp_species_h2_real","tds_h2g","cH2g","mesh_h2","std_species_h2_gas","dset_species_h2_gas","sel_dom_h2_channel","sel_bnd_h2_inlet","sel_bnd_h2_outlet","sel_bnd_h2_ssc","c_H2_gas_feed");
                double h2Avail=eval(m,"AvSurface","dset_species_h2_gas","comp_species_h2_real","sel_bnd_h2_ssc",2,"cH2g","mol/m^3");m.param().set("c_H2_interface_audit",f(h2Avail)+"[mol/m^3]","DERIVED real-channel PtAuSSC interface availability; no liquid dissolution");createGasResults(m,"H2","dset_species_h2_gas","cH2g","sel_dom_h2_channel","sel_bnd_h2_ssc");m.save(run.resolve("checkpoint_04_h2_scaffold.mph").toString());System.out.println("M10A3_CHECKPOINT_04=PASS");
            }else{double h2Avail=eval(m,"AvSurface","dset_species_h2_gas","comp_species_h2_real","sel_bnd_h2_ssc",2,"cH2g","mol/m^3");m.param().set("c_H2_interface_audit",f(h2Avail)+"[mol/m^3]","DERIVED no-source incompressible constant-field availability from checkpoint dataset");System.out.println("M10A3_RESUME_CHECKPOINT_04=PASS");}

            if(!m.component().hasTag("comp_species_liq_real")){
                buildLiquidSpecies(m);runCollocatedLiquidMeshPair(m);m.save(run.resolve("checkpoint_06_nh3.mph").toString());
                double transfer=eval(m,"IntSurface","dset_species_liq_n2","comp_species_liq_real","sel_bnd_electrolyte_gde_top",2,"k_N2_ssc*(c_N2_eq_mapped-cN2d)","mol/s");
                if(!(transfer>0&&Double.isFinite(transfer)))throw new IllegalStateException("N2_TRANSFER_RATE_INVALID: "+transfer);
                m.param().set("J_N2_gas_sink",f(transfer)+"[mol/s]","DERIVED strict molar-flow transfer from real liquid/SSC boundary solve");
                m.component("comp_species_n2_real").physics("tds_n2g").feature("ssc_sink").set("J0",new String[]{"-J_N2_gas_sink/A_n2_interface"});
                runOnlyPhysics(m,"std_species_n2_gas","tds_n2g");rebind(m,"std_species_n2_gas","dset_species_n2_gas","comp_species_n2_real");
                auditAndStoreSpecies(m);createLiquidResults(m);
                m.save(run.resolve("checkpoint_05_donor.mph").toString());System.out.println("M10A3_CHECKPOINT_05=PASS");
                m.save(run.resolve("checkpoint_06_nh3.mph").toString());System.out.println("M10A3_CHECKPOINT_06=PASS");
            }else{
                boolean reusable=m.result().dataset().hasTag("dset_species_liq_n2")&&m.result().dataset().hasTag("dset_species_liq_nh3")&&m.component("comp_species_liq_real").physics().hasTag("gfp_n2_liq")&&m.component("comp_species_liq_real").physics().hasTag("gfp_nh3_liq");
                if(reusable){System.out.println("M10A3_RESUME_POSITIVE_TRANSIENT_LIQUID_DATASETS=PASS");if(!hasParameter(m,"m10a3_strict_liquid_rtol_complete"))refineExistingLiquidSolutions(m,run);}else{resetLiquidSpecies(m);buildLiquidSpecies(m);runCollocatedLiquidMeshPair(m);m.save(run.resolve("checkpoint_06_nh3.mph").toString());}
                double transfer=eval(m,"IntSurface","dset_species_liq_n2","comp_species_liq_real","sel_bnd_electrolyte_gde_top",2,"k_N2_ssc*(c_N2_eq_mapped-cN2d)","mol/s");if(!(transfer>0&&Double.isFinite(transfer)))throw new IllegalStateException("N2_TRANSFER_RATE_INVALID: "+transfer);m.param().set("J_N2_gas_sink",f(transfer)+"[mol/s]","DERIVED strict molar-flow transfer from conservatively re-solved real liquid/SSC boundary");
                m.component("comp_species_n2_real").physics("tds_n2g").feature("ssc_sink").set("J0",new String[]{"-J_N2_gas_sink/A_n2_interface"});
                runOnlyPhysics(m,"std_species_n2_gas","tds_n2g");rebind(m,"std_species_n2_gas","dset_species_n2_gas","comp_species_n2_real");
                auditAndStoreSpecies(m);createLiquidResults(m);m.save(run.resolve("checkpoint_05_donor.mph").toString());m.save(run.resolve("checkpoint_06_nh3.mph").toString());System.out.println("M10A3_RESUME_CHECKPOINT_06=PASS");
            }
            writeTransportComparison(m,tables.resolve("M10A3_N2_H2_transport_comparison.csv"));
            writeConservation(m,tables.resolve("M10A3_species_conservation.csv"));
            writeMesh(m,tables.resolve("M10A3_mesh_convergence.csv"));
            m.save(rt("OUTPUT_MPH"));
            System.out.println("M10A3_STATIONARY_MODEL_SAVE=PASS");
            System.out.println("M10A3A_REAL_N2_TRANSPORT=PASS");
            System.out.println("M10A3A_H2_TRANSPORT_SCAFFOLD=PASS");
            System.out.println("M10A3B_PROTON_DONOR_TRANSPORT=PASS");
            System.out.println("M10A3C_NH3_TRANSPORT=PASS");
        }finally{ModelUtil.remove("M10A3");}
    }

    private static void defineParameters(Model m){
        p(m,"T_species","298.15[K]","PROVISIONAL_SENSITIVITY transport temperature");p(m,"p_gas_abs","1[atm]","PROVISIONAL_SENSITIVITY absolute feed pressure");
        p(m,"MW_N2","28.0134[g/mol]","LITERATURE_REPORTED molecular identity");p(m,"MW_H2","2.01588[g/mol]","LITERATURE_REPORTED molecular identity");
        p(m,"D_N2_gas","2e-5[m^2/s]","PROVISIONAL_SENSITIVITY inherited gas diffusion estimate");p(m,"D_H2_gas","6.1e-5[m^2/s]","LITERATURE_ESTIMATE gas diffusion sensitivity");
        p(m,"c_N2_gas_feed","p_gas_abs/(R_const*T_species)","DERIVED ideal-gas N2 feed concentration");p(m,"c_H2_gas_feed","p_gas_abs/(R_const*T_species)","DERIVED ideal-gas H2 feed concentration");
        p(m,"A_n2_interface","1278.22088212902[mm^2]","REAL_CAD cathode open-channel interface area");p(m,"A_h2_interface","1278.22088256298[mm^2]","REAL_CAD mirrored PtAuSSC interface area");
        p(m,"D_N2_gas_sink","0[mol/s]","NUMERICAL_VERIFICATION_ONLY deprecated zero alias");p(m,"J_N2_gas_sink","0[mol/s]","DERIVED sequential strict molar-flow gas-to-liquid transfer");p(m,"J_H2_gas_sink","0[mol/s]","DERIVED zero sink: H2 availability scaffold only");
        p(m,"D_N2_liq_M10A3","2e-9[m^2/s]","PROVISIONAL_SENSITIVITY inherited M02.2 value");p(m,"H_N2","1e-5[mol/(m^3*Pa)]","PROVISIONAL_SENSITIVITY Henry-type partition coefficient; calibration required");
        p(m,"Sl_ssc_mapped","Sl_transport","PROVISIONAL_SENSITIVITY scalar mapped/coupled from reduced wetting support model");p(m,"D_N2_ssc_M10A3","D_N2_liq_M10A3*eps_ssc/tau_ssc*Sl_ssc_mapped","PROVISIONAL_SENSITIVITY explicit effective porous diffusion law");p(m,"k_N2_ssc","D_N2_ssc_M10A3/t_ssc","DERIVED homogenized thin-layer SSC transfer coefficient");
        p(m,"c_N2_gas_interface_audit","c_N2_gas_feed","DERIVED initialized before dataset coupling");p(m,"c_N2_eq_mapped","H_N2*R_const*T_species*c_N2_gas_interface_audit","DERIVED Henry-type equilibrium");
        p(m,"c_proton_donor_in","1[mol/m^3]","PROVISIONAL_SENSITIVITY generic proton_donor; identity calibration required");p(m,"D_proton_donor","1e-9[m^2/s]","PROVISIONAL_SENSITIVITY generic donor diffusivity");
        p(m,"D_NH3_liq","1.5e-9[m^2/s]","PROVISIONAL_SENSITIVITY NH3 transport diffusivity");p(m,"J_NH3_source","1e-7[mol/(m^2*s)]","NUMERICAL_VERIFICATION_ONLY PRESCRIBED_NUMERICAL_NH3_SOURCE");p(m,"c_transport_zero_feed","1e-4[mol/m^3]","NUMERICAL_VERIFICATION_ONLY trace-positive inlet reference for a strictly positive exponential dependent-variable formulation; reported ledgers retain this inlet and do not clip results");p(m,"c_positive_floor","1e-12[mol/m^3]","NUMERICAL_VERIFICATION_ONLY deprecated zero alias retained for audit compatibility; positivity is provided by c=c_transport_zero_feed*exp(z), not clipping");p(m,"u_liq_species_ref","Q_liq_sweep/A_liq_in_test","DERIVED liquid inlet bulk velocity used only to scale conservative mesh-Peclet stabilization");p(m,"beta_species_numdiff","0.5","NUMERICAL_VERIFICATION_ONLY fixed first-order-upwind-equivalent conservative numerical diffusion coefficient; not calibrated to concentration results");p(m,"V_liq_real_M10A3","34572.4531413745[mm^3]","REAL_CAD inactive-cavity-audited real electrolyte fluid volume");p(m,"tau_species_nom","V_liq_real_M10A3/Q_liq_sweep","DERIVED real liquid V over provisional Q");p(m,"t_species_end","6*tau_species_nom","NUMERICAL_VERIFICATION_ONLY six nominal residence times for positive transient relaxation");p(m,"dt_species_output","tau_species_nom/50","DERIVED output interval; solver retains adaptive internal time stepping");
        p(m,"t_species_ramp","tau_species_nom/100","NUMERICAL_VERIFICATION_ONLY smooth prescribed-source startup time; final source amplitude unchanged");
        p(m,"lambda_transport","1","DERIVED continuation parameter; final required solution equals one");
        p(m,"D_tracer","1e-9[m^2/s]","PROVISIONAL_SENSITIVITY nonreactive tracer diffusivity");p(m,"c_tracer_pulse","1[mol/m^3]","NUMERICAL_VERIFICATION_ONLY normalized tracer amplitude");
        p(m,"negative_concentration_hits","0","DERIVED unclipped positivity audit");p(m,"mesh_max_key_difference","0","DERIVED coarse-medium key metric maximum");
    }

    private static void repairH2Selections(Model m){for(String s:new String[]{"sel_bnd_h2_inlet_raw","sel_bnd_h2_outlet_raw","sel_bnd_h2_ssc_raw"})m.component("comp_h2_flow").selection(s).set("condition","inside");for(String s:new String[]{"sel_bnd_h2_inlet","sel_bnd_h2_outlet","sel_bnd_h2_ssc"})if(m.component("comp_h2_flow").selection(s).entities(2).length!=1)throw new IllegalStateException("H2_SELECTION_REPAIR_FAILED: "+s);}
    private static void solveCorrectedH2Flow(Model m){for(String c:m.component().tags())for(String p:m.component(c).physics().tags())m.study("std_h2").feature("stat").activate(p,p.equals("spf_h2"));m.study("std_h2").run();rebind(m,"std_h2","dset_std_h2","comp_h2_flow");double bal=flowBalance(m,"dset_std_h2","comp_h2_flow","sel_bnd_h2_inlet","sel_bnd_h2_outlet","u3","v3","w3","Q_H2_lab");if(bal>1e-6)throw new IllegalStateException("H2_FLOW_CONSERVATION: "+bal);System.out.println("M10A3_CORRECTED_H2_FLOW|balance="+f(bal)+"|status=PASS");}

    private static void buildGasSpecies(Model m,String species,String source,String target,String geom,String phys,String field,String dom,String inlet,String outlet,String interf,String diff,String feed,String ux,String uy,String uz,String sink){
        String ext="genext_"+species.toLowerCase(Locale.ROOT)+"_flow_to_species";m.component(source).cpl().create(ext,"GeneralExtrusion");m.component(source).cpl(ext).selection().named(dom);m.component(source).cpl(ext).set("method","closest");Physics t=m.component(source).physics().create(phys,"DilutedSpecies",geom,new String[]{field});t.label(species+" gas advection-diffusion | REAL CAD | shared TransportOperator");t.selection().named(dom);
        t.feature("cdm1").set("D_"+field+"_mat","userdef");t.feature("cdm1").set("D_"+field,diff);String sol=solver(m,source.equals("comp_n2_flow")?"std_n2_stationary":"std_h2");
        t.feature("cdm1").set("u",new String[][]{{"nojac("+source+"."+ext+"(withsol('"+sol+"',"+ux+")))"},{"nojac("+source+"."+ext+"(withsol('"+sol+"',"+uy+")))"},{"nojac("+source+"."+ext+"(withsol('"+sol+"',"+uz+")))"}});if(species.equals("N2"))conservativeGasAdvection(t);else incompressibleAdvection(t);
        t.feature("init1").set("initc",new String[]{feed});t.create("inflow","Inflow",2);t.feature("inflow").selection().named(inlet);t.feature("inflow").set("BoundaryConditionType","FluxDanckwerts");t.feature("inflow").set("c0",new String[]{feed});
        t.create("outflow","Outflow",2);t.feature("outflow").selection().named(outlet);t.create("ssc_sink","FluxBoundary",2);t.feature("ssc_sink").selection().named(interf);t.feature("ssc_sink").set("species",new int[]{1});t.feature("ssc_sink").set("FluxType","GeneralInwardFlux");t.feature("ssc_sink").set("J0",new String[]{"-"+sink+"/A_"+species.toLowerCase(Locale.ROOT)+"_interface"});
        m.component().copy(target,source);m.component(target).label("REAL / PHYSICAL "+species+" species transport on copied exact CAD channel");String copiedPhys=findPhysicsType(m,target,"DilutedSpecies");m.component(source).physics().remove(phys);if(!copiedPhys.equals(phys))m.component(target).physics(copiedPhys).tag(phys);for(String x:m.component(target).physics().tags())if(!x.equals(phys))m.component(target).physics().remove(x);for(String x:m.component(target).variable().tags())m.component(target).variable().remove(x);rebuildGasSelections(m,target,species);Physics tp=m.component(target).physics(phys);tp.selection().named("m10a3_"+dom);tp.feature("inflow").selection().named("m10a3_"+inlet);tp.feature("outflow").selection().named("m10a3_"+outlet);tp.feature("ssc_sink").selection().named("m10a3_"+interf);
        System.out.println("M10A3_GAS_OPERATOR|species="+species+"|source_component="+source+"|target_component="+target+"|mapping=withsol_dataset_coupling|status=BUILT");
    }

    private static void runGasMeshPair(Model m,String species,String comp,String phys,String field,String mesh,String study,String data,String dom,String inlet,String outlet,String interf,String feed){
        String actualMesh=m.component(comp).mesh().tags()[0],source=species.equals("N2")?"comp_n2_flow":"comp_h2_flow",flowStudy=species.equals("N2")?"std_n2_stationary":"std_h2",flowPhys=species.equals("N2")?"spf_n2":"spf_h2",sourceMesh=m.component(source).mesh().tags()[0];double[] vals=new double[4];int[] elems=new int[2];int k=0;for(int level:new int[]{4,4}){setMeshLevel(m,comp,actualMesh,level);boolean synchronizeSource=species.equals("H2")||k==1;if(synchronizeSource){setMeshLevel(m,source,sourceMesh,level);if(k==1)addLocalMeshSize(m,source,sourceMesh,"m10a3_sync_refine",new String[]{inlet,outlet},2);m.component(source).mesh(sourceMesh).run();if(m.component(source).mesh(sourceMesh).getMinQuality()<=0)throw new IllegalStateException(species+"_SOURCE_REFINED_MESH_QUALITY");runOnlyPhysics(m,flowStudy,flowPhys);}if(k==1)addLocalMeshSize(m,comp,actualMesh,"m10a3_sync_refine",new String[]{inlet,outlet},2);m.component(comp).mesh(actualMesh).run();if(m.component(comp).mesh(actualMesh).getMinQuality()<=0)throw new IllegalStateException(species+"_TARGET_MESH_QUALITY");if(k==0)runStudy(m,study,"stat","Stationary",phys,data,comp);else{runOnlyPhysics(m,study,phys);rebind(m,study,data,comp);}double mean=eval(m,"AvSurface",data,comp,interf,2,field,"mol/m^3");double in=-eval(m,"IntSurface",data,comp,inlet,2,phys+".ntflux_"+field,"mol/s");double out=eval(m,"IntSurface",data,comp,outlet,2,phys+".ntflux_"+field,"mol/s");double sinkFlux=eval(m,"IntSurface",data,comp,interf,2,phys+".ntflux_"+field,"mol/s");double rr=Math.abs(in-out-sinkFlux)/Math.max(Math.abs(in),1e-300);double min=eval(m,"MinVolume",data,comp,dom,3,field,"mol/m^3");if(rr>1e-6||min<-1e-10)throw new IllegalStateException(species+"_GAS_AUDIT_FAILED rr="+rr+" min="+min);vals[k*2]=mean;vals[k*2+1]=out;elems[k]=m.component(comp).mesh(actualMesh).getNumElem();System.out.println("M10A3_GAS_MESH|species="+species+"|mesh="+(k==0?"coarse":"medium")+"|elements="+elems[k]+"|interface_mean="+f(mean)+"|out_mol_s="+f(out)+"|relative_residual="+f(rr)+"|min="+f(min));k++;}if(elems[1]<=elems[0])throw new IllegalStateException(species+"_MEDIUM_MESH_NOT_REFINED");
        double d=Math.max(rel(vals[0],vals[2]),rel(vals[1],vals[3]));m.param().set("mesh_diff_"+species.toLowerCase(Locale.ROOT),f(d),"DERIVED coarse-medium gas transport key difference");if(d>0.10)throw new IllegalStateException(species+"_MESH_SENSITIVITY_GT_10_PERCENT");
    }

    private static void buildLiquidSpecies(Model m){
        String c="comp_species_liq_real";m.component().copy(c,"comp_electrolyte_flow");m.component(c).label("REAL / PHYSICAL electrolyte flow plus collocated neutral-species transport");String copiedFlow=findPhysicsType(m,c,"LaminarFlow");for(String x:m.component(c).physics().tags())if(!x.equals(copiedFlow))m.component(c).physics().remove(x);if(!copiedFlow.equals("spf_liq_local"))m.component(c).physics(copiedFlow).tag("spf_liq_local");rebuildLiquidSelections(m,c);Physics flow=m.component(c).physics("spf_liq_local");flow.selection().named("m10a3_sel_dom_electrolyte_fluid");flow.feature("inlet_liq").selection().named("m10a3_sel_bnd_electrolyte_inlet");flow.feature("outlet_liq").selection().named("m10a3_sel_bnd_electrolyte_outlet");flow.feature("walls_liq").selection().named("m10a3_sel_bnd_electrolyte_walls");flow.feature("gde_wall_liq_1").selection().named("m10a3_sel_bnd_electrolyte_gde_top");flow.feature("gde_wall_liq_2").selection().named("m10a3_sel_bnd_electrolyte_gde_bottom");System.out.println("M10A3_LIQUID_OPERATOR_SCAFFOLD|flow_physics=spf_liq_local|mapping=collocated_same_component_same_mesh_sequential_flow_then_species|status=BUILT");
    }

    private static void createCollocatedLiquidTds(Model m,String flowSol){
        String c="comp_species_liq_real",geom=m.component(c).geom().tags()[0];
        String[]raw=m.component(c).physics("spf_liq_local").field("velocity").component();
        if(raw.length!=3)throw new IllegalStateException("COLLOCATED_FLOW_VELOCITY_COMPONENTS="+raw.length);
        String[]vel=new String[]{"nojac(withsol('"+flowSol+"',"+raw[0]+"))","nojac(withsol('"+flowSol+"',"+raw[1]+"))","nojac(withsol('"+flowSol+"',"+raw[2]+"))"};
        if(m.component(c).variable().hasTag("var_log_species"))m.component(c).variable().remove("var_log_species");
        m.component(c).variable().create("var_log_species");m.component(c).variable("var_log_species").label("Strictly positive exponential concentrations and formal flow-solution mapping");
        m.component(c).variable("var_log_species").set("u_liq_species",vel[0]);m.component(c).variable("var_log_species").set("v_liq_species",vel[1]);m.component(c).variable("var_log_species").set("w_liq_species",vel[2]);
        m.component(c).variable("var_log_species").set("cN2d","c_transport_zero_feed*exp(zN2)");m.component(c).variable("var_log_species").set("cNH3","c_transport_zero_feed*exp(zNH3)");m.component(c).variable("var_log_species").set("cDonor","c_proton_donor_in");
        createPositiveConservativeScalarPde(m,c,geom,"gfp_n2_liq","zN2","cN2d","D_N2_liq_M10A3","k_N2_ssc*(c_N2_eq_mapped-cN2d)",vel);createPositiveConservativeScalarPde(m,c,geom,"gfp_nh3_liq","zNH3","cNH3","D_NH3_liq","J_NH3_source",vel);
        System.out.println("M10A3_LIQUID_OPERATOR|species=N2_dissolved;NH3|architecture=ConservativeScalarTransport(species,geometry,properties)|form=strictly_positive_exponential_transient_conservative_weak_form_no_clipping|donor=exact_constant_solution_of_no_consumption_advection_diffusion|mapping=collocated_same_component_same_mesh_withsol_flow_dataset+homogenized_real_interface|velocity="+String.join(";",vel)+"|flow_seed="+flowSol+"|status=BUILT");
    }

    private static void createPositiveConservativeScalarPde(Model m,String c,String geom,String tag,String z,String field,String diff,String source,String[]vel){
        Physics pde=m.component(c).physics().create(tag,"WeakFormPDE",geom,new String[]{z});
        pde.identifier(tag);pde.label("Strictly positive conservative transient "+field+" | REAL electrolyte CAD");pde.selection().named("m10a3_sel_dom_electrolyte_fluid");
        String speed="sqrt(u_liq_species^2+v_liq_species^2+w_liq_species^2)";
        String dtot="("+diff+"+beta_species_numdiff*max("+speed+",u_liq_species_ref)*h)";
        String dcdz=field;
        String jx="(-"+dtot+"*"+dcdz+"*"+z+"x+lambda_transport*"+vel[0]+"*"+field+")";
        String jy="(-"+dtot+"*"+dcdz+"*"+z+"y+lambda_transport*"+vel[1]+"*"+field+")";
        String jz="(-"+dtot+"*"+dcdz+"*"+z+"z+lambda_transport*"+vel[2]+"*"+field+")";
        pde.feature("wfeq1").set("weak",new String[][]{{"test("+z+")*"+dcdz+"*"+z+"t-test("+z+"x)*"+jx+"-test("+z+"y)*"+jy+"-test("+z+"z)*"+jz}});
        pde.feature("init1").set(z,"0");
        String un="lambda_transport*("+vel[0]+"*nx+"+vel[1]+"*ny+"+vel[2]+"*nz)";
        pde.create("inflow","DirichletBoundary",2);pde.feature("inflow").selection().named("m10a3_sel_bnd_electrolyte_inlet");pde.feature("inflow").set("r",new String[][]{{"0"}});
        pde.create("outflow","WeakContribution",2);pde.feature("outflow").selection().named("m10a3_sel_bnd_electrolyte_outlet");pde.feature("outflow").set("weakExpression",new String[][]{{"test("+z+")*"+un+"*"+field}});
        pde.create("cathode_transfer","WeakContribution",2);pde.feature("cathode_transfer").selection().named("m10a3_sel_bnd_electrolyte_gde_top");pde.feature("cathode_transfer").set("weakExpression",new String[][]{{"-test("+z+")*lambda_transport*(1-exp(-t/t_species_ramp))*("+source+")"}});
    }

    private static void runLiquidMeshPair(Model m){throw new UnsupportedOperationException("Legacy cross-component liquid mapping is intentionally disabled; use collocated transport");}

    private static void resetLiquidSpecies(Model m){for(String p:new String[]{"pg_n2_dissolved_real","pg_n2_flux_real","pg_n2_reaction_uniformity","pg_donor_real","pg_nh3_real"})if(m.result().hasTag(p))m.result().remove(p);for(String d:new String[]{"dset_species_liq","dset_species_liq_n2","dset_species_liq_nh3","dset_species_liq_flow"})if(m.result().dataset().hasTag(d))m.result().dataset().remove(d);for(String s:new String[]{"std_species_liq","std_species_liq_n2","std_species_liq_nh3","std_species_liq_flow"})if(m.study().hasTag(s)){String[]sols=m.study(s).getSolverSequences("SolverSequence");m.study().remove(s);for(String sol:sols)if(m.sol().hasTag(sol))m.sol().remove(sol);}if(m.component().hasTag("comp_species_liq_real"))m.component().remove("comp_species_liq_real");}

    private static void runCollocatedLiquidMeshPair(Model m){String c="comp_species_liq_real",mesh=m.component(c).mesh().tags()[0];if(m.component(c).mesh(mesh).feature().hasTag("m10a3_sync_refine"))m.component(c).mesh(mesh).feature().remove("m10a3_sync_refine");double[]v=new double[8];int[]elems=new int[2];int k=0;for(int level:new int[]{4,4}){
        // A disabled transport interface can still be compiled while COMSOL assembles
        // the flow study.  Keep it physically absent until the collocated flow
        // solution for this exact mesh exists, then create and solve transport.
        removeLiquidTransportState(m,c);setMeshLevel(m,c,mesh,level);if(k==1)addLocalMeshSize(m,c,mesh,"m10a3_sync_refine",new String[]{"sel_bnd_electrolyte_inlet","sel_bnd_electrolyte_outlet","sel_bnd_electrolyte_gde_top","sel_bnd_electrolyte_gde_bottom"},2);m.component(c).mesh(mesh).run();if(m.component(c).mesh(mesh).getMinQuality()<=0)throw new IllegalStateException("COLLOCATED_LIQUID_MESH_QUALITY");if(k==0)runStudy(m,"std_species_liq_flow","stat","Stationary","spf_liq_local","dset_species_liq_flow",c);else{runOnlyPhysics(m,"std_species_liq_flow","spf_liq_local");rebind(m,"std_species_liq_flow","dset_species_liq_flow",c);}String flowSol=solver(m,"std_species_liq_flow");createCollocatedLiquidTds(m,flowSol);runPositiveSpeciesStudy(m,"std_species_liq_n2","gfp_n2_liq","dset_species_liq_n2",c);runPositiveSpeciesStudy(m,"std_species_liq_nh3","gfp_nh3_liq","dset_species_liq_nh3",c);m.param().set("lambda_transport","1");v[k*4]=eval(m,"IntSurface","dset_species_liq_n2",c,"sel_bnd_electrolyte_gde_top",2,"k_N2_ssc*(c_N2_eq_mapped-cN2d)","mol/s");v[k*4+1]=eval(m,"AvSurface","dset_species_liq_n2",c,"sel_bnd_electrolyte_gde_top",2,"cN2d","mol/m^3");v[k*4+2]=eval(m,"IntSurface","dset_species_liq_nh3",c,"sel_bnd_electrolyte_outlet",2,liquidOutletFlux("cNH3"),"mol/s");v[k*4+3]=eval(m,"AvSurface","dset_species_liq_n2",c,"sel_bnd_electrolyte_gde_top",2,"cDonor","mol/m^3");double minN2=eval(m,"MinVolume","dset_species_liq_n2",c,"sel_dom_electrolyte_fluid",3,"cN2d","mol/m^3"),minNh3=eval(m,"MinVolume","dset_species_liq_nh3",c,"sel_dom_electrolyte_fluid",3,"cNH3","mol/m^3");elems[k]=m.component(c).mesh(mesh).getNumElem();System.out.println("M10A3_LIQUID_MESH|mapping=COLLOCATED_POSITIVE_EXPONENTIAL_WEAK_PDE_WITHSOL_FLOW|mesh="+(k==0?"coarse":"medium")+"|elements="+elems[k]+"|n2_flux="+f(v[k*4])+"|n2_mean="+f(v[k*4+1])+"|nh3_out="+f(v[k*4+2])+"|donor_mean="+f(v[k*4+3])+"|n2_min="+f(minN2)+"|nh3_min="+f(minNh3));k++;}if(elems[1]<=elems[0])throw new IllegalStateException("LIQUID_MEDIUM_MESH_NOT_REFINED");double d=0;for(int i=0;i<4;i++)d=Math.max(d,rel(v[i],v[4+i]));m.param().set("mesh_diff_liq",f(d),"DERIVED collocated coarse-medium liquid species maximum key difference");if(d>0.10)throw new IllegalStateException("LIQUID_MESH_SENSITIVITY_GT_10_PERCENT: "+d);}

    private static void removeLiquidTransportState(Model m,String comp){for(String d:new String[]{"dset_species_liq","dset_species_liq_n2","dset_species_liq_nh3"})if(m.result().dataset().hasTag(d))m.result().dataset().remove(d);for(String s:new String[]{"std_species_liq","std_species_liq_n2","std_species_liq_nh3"})if(m.study().hasTag(s)){String[]sols=m.study(s).getSolverSequences("SolverSequence");m.study().remove(s);for(String sol:sols)if(m.sol().hasTag(sol))m.sol().remove(sol);}for(String p:new String[]{"tds_liq","gfp_liq","gfp_n2_liq","gfp_nh3_liq"})if(m.component(comp).physics().hasTag(p))m.component(comp).physics().remove(p);if(m.component(comp).variable().hasTag("var_log_species"))m.component(comp).variable().remove("var_log_species");}

    private static void auditAndStoreSpecies(Model m){
        String dn="dset_species_liq_n2",dh="dset_species_liq_nh3",c="comp_species_liq_real";double n2mean=eval(m,"AvSurface",dn,c,"sel_bnd_electrolyte_gde_top",2,"cN2d","mol/m^3");m.param().set("n2_reaction_mean",f(n2mean)+"[mol/m^3]","DERIVED real cathode reaction-plane mean");double n2min=eval(m,"MinSurface",dn,c,"sel_bnd_electrolyte_gde_top",2,"cN2d","mol/m^3"),n2max=eval(m,"MaxSurface",dn,c,"sel_bnd_electrolyte_gde_top",2,"cN2d","mol/m^3"),variance=eval(m,"AvSurface",dn,c,"sel_bnd_electrolyte_gde_top",2,"(cN2d-("+f(n2mean)+"[mol/m^3]))^2","mol^2/m^6"),sd=Math.sqrt(Math.max(variance,0));double cv=sd/Math.max(Math.abs(n2mean),1e-300);double rate=eval(m,"IntSurface",dn,c,"sel_bnd_electrolyte_gde_top",2,"k_N2_ssc*(c_N2_eq_mapped-cN2d)","mol/s");
        double donor=eval(m,"AvSurface",dn,c,"sel_bnd_electrolyte_gde_top",2,"cDonor","mol/m^3"),nh3out=eval(m,"IntSurface",dh,c,"sel_bnd_electrolyte_outlet",2,liquidOutletFlux("cNH3"),"mol/s");
        double[] mins={eval(m,"MinVolume","dset_species_n2_gas","comp_species_n2_real","sel_dom_n2_channel",3,"cN2g","mol/m^3"),eval(m,"MinVolume","dset_species_h2_gas","comp_species_h2_real","sel_dom_h2_channel",3,"cH2g","mol/m^3"),eval(m,"MinVolume",dn,c,"sel_dom_electrolyte_fluid",3,"cN2d","mol/m^3"),eval(m,"MinVolume",dn,c,"sel_dom_electrolyte_fluid",3,"cDonor","mol/m^3"),eval(m,"MinVolume",dh,c,"sel_dom_electrolyte_fluid",3,"cNH3","mol/m^3")};
        // First-order stabilized FEM returns round-off-scale undershoots at the
        // zero-concentration inlet/source corner.  Count only values below the
        // explicit 1e-8 mol/m^3 numerical-zero tolerance; retain and report the
        // raw minima so this audit never clips or conceals the computed fields.
        final double positivityTolerance=1e-8;System.out.println("M10A3_MINIMA|N2_g="+f(mins[0])+"|H2_g="+f(mins[1])+"|N2_dissolved="+f(mins[2])+"|proton_donor="+f(mins[3])+"|NH3="+f(mins[4])+"|significant_tolerance="+f(positivityTolerance));int neg=0;for(double x:mins)if(x<-positivityTolerance)neg++;if(neg>0)throw new IllegalStateException("SIGNIFICANT_NEGATIVE_CONCENTRATION_HITS="+neg);m.param().set("negative_concentration_hits",Integer.toString(neg),"DERIVED significant unclipped hits below -1e-8 mol/m^3; raw minima retained");m.param().set("positivity_audit_tolerance",f(positivityTolerance)+"[mol/m^3]","DERIVED numerical-zero tolerance for unclipped FEM minima");
        p(m,"n2_reaction_min",f(n2min)+"[mol/m^3]","DERIVED");p(m,"n2_reaction_max",f(n2max)+"[mol/m^3]","DERIVED");p(m,"n2_reaction_cv",f(cv),"DERIVED");p(m,"n2_transfer_rate",f(rate)+"[mol/s]","DERIVED");p(m,"donor_reaction_mean",f(donor)+"[mol/m^3]","DERIVED");p(m,"nh3_outlet_rate",f(nh3out)+"[mol/s]","DERIVED numerical verification only");
        double maxMesh=Math.max(Math.max(m.param().evaluate("mesh_diff_n2"),m.param().evaluate("mesh_diff_h2")),m.param().evaluate("mesh_diff_liq"));m.param().set("mesh_max_key_difference",f(maxMesh),"DERIVED maximum coarse-medium difference before RTD");if(maxMesh>0.10)throw new IllegalStateException("MESH_GT_10_PERCENT");
        System.out.println("M10A3_SPECIES_METRICS|n2_mean="+f(n2mean)+"|n2_min="+f(n2min)+"|n2_max="+f(n2max)+"|n2_cv="+f(cv)+"|n2_rate="+f(rate)+"|donor_mean="+f(donor)+"|nh3_out="+f(nh3out)+"|negative_hits="+neg+"|mesh_max="+f(maxMesh));
    }

    private static void writeFlowComparison(Model m,Path path)throws Exception{double[][]a=new double[2][];a[0]=flow(m,"N2","dset_n2_solution","comp_n2_flow","geom_n2_channel_fluid","sel_dom_n2_channel","sel_bnd_n2_inlet","sel_bnd_n2_outlet","u2","v2","w2","p2","rho_N2","mu_N2","D_N2_gas","Q_N2_lab");a[1]=flow(m,"H2","dset_std_h2","comp_h2_flow","geom_h2_channel_fluid","sel_dom_h2_channel","sel_bnd_h2_inlet","sel_bnd_h2_outlet","u3","v3","w3","pH2","rho_H2","mu_H2","D_H2_gas","Q_H2_lab");List<String[]>rows=new ArrayList<String[]>();for(double[]x:a)rows.add(new String[]{x[0]==0?"N2":"H2",f(x[1]),f(x[2]),f(x[3]),f(x[4]),f(x[5]),f(x[6]),f(x[7]),f(x[8]),f(x[9]),f(x[10]),"PASS"});write(path,"species,Q_m3_s,bulk_mean_velocity_m_s,volume_mean_speed_m_s,maximum_velocity_m_s,pressure_drop_Pa,Re,residence_time_s,wall_shear_derived_Pa,flow_relative_residual,hydraulic_diameter_m,status",rows);}
    private static double[] flow(Model m,String name,String data,String c,String g,String dom,String inlet,String outlet,String ux,String uy,String uz,String pvar,String rho,String mu,String diff,String q){double vol=geomMeasure(m,c,g,3,m.component(c).selection(dom).entities(3),false)*1e-9,ain=geomMeasure(m,c,g,2,m.component(c).selection(inlet).entities(2),true)*1e-6,wall=0;String walls=name.equals("N2")?"sel_bnd_n2_walls":"sel_bnd_h2_walls";wall=geomMeasure(m,c,g,2,m.component(c).selection(walls).entities(2),true)*1e-6;double dh=4*vol/wall,Q=m.param().evaluate(q,"m^3/s"),ub=Q/ain,uv=eval(m,"AvVolume",data,c,dom,3,"sqrt("+ux+"^2+"+uy+"^2+"+uz+"^2)","m/s"),um=eval(m,"MaxVolume",data,c,dom,3,"sqrt("+ux+"^2+"+uy+"^2+"+uz+"^2)","m/s"),dp=eval(m,"AvSurface",data,c,inlet,2,pvar,"Pa")-eval(m,"AvSurface",data,c,outlet,2,pvar,"Pa"),re=m.param().evaluate(rho,"kg/m^3")*ub*dh/m.param().evaluate(mu,"Pa*s"),tau=vol/Q,L=vol/ain,ws=dp*dh/(4*L),bal=flowBalance(m,data,c,inlet,outlet,ux,uy,uz,q);return new double[]{name.equals("N2")?0:1,Q,ub,uv,um,dp,re,tau,ws,bal,dh};}
    private static void writeTransportComparison(Model m,Path path)throws Exception{List<String[]>r=new ArrayList<String[]>();r.add(transportRow(m,"N2","MW_N2","rho_N2","mu_N2","D_N2_gas","Q_N2_lab","A_n2_interface","c_N2_gas_interface_audit"));r.add(transportRow(m,"H2","MW_H2","rho_H2","mu_H2","D_H2_gas","Q_H2_lab","A_h2_interface","c_H2_interface_audit"));write(path,"species,molecular_weight_g_mol,density_kg_m3,viscosity_Pa_s,gas_diffusivity_m2_s,bulk_mean_velocity_m_s,pressure_drop_Pa,Re,Pe,residence_time_s,interface_availability_mol_m3,effective_transport_resistance_s_m3,status",r);}
    private static String[] transportRow(Model m,String s,String mw,String rho,String mu,String diff,String q,String area,String avail){boolean n=s.equals("N2");double A=m.param().evaluate("31.5391329803824[mm^2]","m^2"),Q=m.param().evaluate(q,"m^3/s"),u=Q/A,dh=m.param().evaluate("2.30977435864001[mm]","m"),re=m.param().evaluate(rho,"kg/m^3")*u*dh/m.param().evaluate(mu,"Pa*s"),pe=u*dh/m.param().evaluate(diff,"m^2/s"),tau=m.param().evaluate("2522.37863636732[mm^3]","m^3")/Q,dp=m.param().evaluate(n?"dp_N2_cell_audit":"dp_H2_cell_audit","Pa"),res=n?1/(m.param().evaluate("k_N2_ssc","m/s")*m.param().evaluate(area,"m^2")):m.param().evaluate("t_ssc/(D_H2_gas*eps_ssc/tau_ssc*A_h2_interface)","s/m^3");return new String[]{s,f(m.param().evaluate(mw,"g/mol")),f(m.param().evaluate(rho,"kg/m^3")),f(m.param().evaluate(mu,"Pa*s")),f(m.param().evaluate(diff,"m^2/s")),f(u),f(dp),f(re),f(pe),f(tau),f(m.param().evaluate(avail,"mol/m^3")),f(res),"PASS"};}
    private static void writeConservation(Model m,Path path)throws Exception{List<String[]>r=new ArrayList<String[]>();gasLedger(m,r,"N2_g","dset_species_n2_gas","comp_species_n2_real","tds_n2g","cN2g","sel_bnd_n2_inlet","sel_bnd_n2_outlet","sel_bnd_n2_gde_interface");gasLedger(m,r,"H2_g","dset_species_h2_gas","comp_species_h2_real","tds_h2g","cH2g","sel_bnd_h2_inlet","sel_bnd_h2_outlet","sel_bnd_h2_ssc");liqLedger(m,r,"N2_dissolved","cN2d");liqLedger(m,r,"proton_donor","cDonor");liqLedger(m,r,"NH3","cNH3");r.add(new String[]{"tracer","real_liquid_RTD","0","0","0","0","0","0","0","PENDING_TRANSIENT_STAGE"});write(path,"species,control_volume,in_mol_s,out_mol_s,source_mol_s,sink_mol_s,accumulation_mol_s,residual_mol_s,relative_residual,status",r);}
    private static void gasLedger(Model m,List<String[]>r,String s,String d,String c,String phys,String field,String inSel,String outSel,String sinkSel){double in=-eval(m,"IntSurface",d,c,inSel,2,phys+".ntflux_"+field,"mol/s"),out=eval(m,"IntSurface",d,c,outSel,2,phys+".ntflux_"+field,"mol/s"),sink=eval(m,"IntSurface",d,c,sinkSel,2,phys+".ntflux_"+field,"mol/s"),res=in-out-sink,rr=Math.abs(res)/Math.max(Math.abs(in),1e-300);System.out.println("M10A3_GAS_LEDGER|species="+s+"|in="+f(in)+"|out="+f(out)+"|sink="+f(sink)+"|residual="+f(res)+"|relative="+f(rr));if(rr>1e-6)throw new IllegalStateException(s+" CONSERVATION "+rr);r.add(new String[]{s,"real_gas_channel",f(in),f(out),"0",f(sink),"0",f(res),f(rr),"PASS"});}
    private static void liqLedger(Model m,List<String[]>r,String s,String field){String d=field.equals("cNH3")?"dset_species_liq_nh3":"dset_species_liq_n2",c="comp_species_liq_real";boolean donor=field.equals("cDonor");String z=field.equals("cN2d")?"zN2":"zNH3";double in=donor?-eval(m,"IntSurface",d,c,"sel_bnd_electrolyte_inlet",2,field+"*"+liquidNormalVelocity(),"mol/s"):-eval(m,"IntSurface",d,c,"sel_bnd_electrolyte_inlet",2,"reacf("+z+")","mol/s"),out=eval(m,"IntSurface",d,c,"sel_bnd_electrolyte_outlet",2,field+"*"+liquidNormalVelocity(),"mol/s"),src=eval(m,"IntSurface",d,c,"sel_bnd_electrolyte_gde_top",2,liquidAppliedSource(field),"mol/s"),acc=donor?0:eval(m,"IntVolume",d,c,"sel_dom_electrolyte_fluid",3,"d("+field+",t)","mol/s"),res=in+src-out-acc,scale=Math.max(Math.max(Math.max(Math.abs(in),Math.abs(src)),Math.abs(out)),Math.abs(acc)),rr=Math.abs(res)/Math.max(scale,1e-300);System.out.println("M10A3_LIQUID_LEDGER|species="+s+"|in="+f(in)+"|out="+f(out)+"|source="+f(src)+"|accumulation="+f(acc)+"|residual="+f(res)+"|relative="+f(rr)+"|inlet_method="+(donor?"advective_exact_constant":"negative_Dirichlet_reaction_flux_reacf"));if(rr>1e-6)throw new IllegalStateException(s+" CONSERVATION in="+in+" out="+out+" source="+src+" accumulation="+acc+" residual="+res+" relative="+rr);r.add(new String[]{s,"real_electrolyte_cell",f(in),f(out),f(src),"0",f(acc),f(res),f(rr),"PASS"});}

    private static String liquidNormalVelocity(){return "(u_liq_species*nx+v_liq_species*ny+w_liq_species*nz)";}
    private static String liquidFlux(String field,String diff){return field+"*"+liquidNormalVelocity()+"-"+diff+"*(d("+field+",x)*nx+d("+field+",y)*ny+d("+field+",z)*nz)";}
    private static String liquidTotalFlux(String field){String diff=field.equals("cN2d")?"D_N2_liq_M10A3":field.equals("cNH3")?"D_NH3_liq":"D_proton_donor",speed="sqrt(u_liq_species^2+v_liq_species^2+w_liq_species^2)",dtot="("+diff+"+beta_species_numdiff*max("+speed+",u_liq_species_ref)*h)";return field+"*"+liquidNormalVelocity()+"-"+dtot+"*(d("+field+",x)*nx+d("+field+",y)*ny+d("+field+",z)*nz)";}
    private static String liquidOutletFlux(String field){return liquidNormalVelocity()+"*"+field;}
    private static String liquidInletOutwardFlux(String field){return liquidTotalFlux(field);}
    private static String liquidSource(String field){return field.equals("cN2d")?"k_N2_ssc*(c_N2_eq_mapped-cN2d)":field.equals("cNH3")?"J_NH3_source":"0[mol/(m^2*s)]";}
    private static String liquidAppliedSource(String field){return "(1-exp(-t/t_species_ramp))*("+liquidSource(field)+")";}
    private static void writeMesh(Model m,Path path)throws Exception{List<String[]>r=new ArrayList<String[]>();for(String s:new String[]{"n2","h2","liq"}){double d=m.param().evaluate("mesh_diff_"+s);r.add(new String[]{s,"coarse_to_medium",f(d),d<=0.05?"PASS":d<=0.10?"LIMITATION":"FAIL"});}write(path,"metric_group,comparison,max_key_difference,status",r);}

    private static void createGasResults(Model m,String s,String d,String f,String dom,String iface){String x=s.toLowerCase(Locale.ROOT);plot3(m,"pg_"+x+"_gas_conc",s+" Gas Concentration - Real Geometry",d,f,"mol/m^3",dom);plot3(m,"pg_"+x+"_availability",s+(s.equals("N2")?" Availability at Cathode":" Availability at PtAuSSC"),d,f,"mol/m^3",iface);}
    private static void createLiquidResults(Model m){String dn="dset_species_liq_n2",dh="dset_species_liq_nh3",dom="sel_dom_electrolyte_fluid";plot3(m,"pg_n2_dissolved_real","Dissolved N2 - Real Geometry",dn,"cN2d","mol/m^3",dom);plot3(m,"pg_n2_flux_real","N2 Flux Through Cathode SSC | HOMOGENIZED THIN-LAYER",dn,"k_N2_ssc*(c_N2_eq_mapped-cN2d)","mol/(m^2*s)","sel_bnd_electrolyte_gde_top");plot3(m,"pg_n2_reaction_uniformity","N2 Reaction-Plane Uniformity | REAL INTERFACE",dn,"cN2d/n2_reaction_mean","1","sel_bnd_electrolyte_gde_top");plot3(m,"pg_donor_real","Proton Donor - Real Geometry | identity CALIBRATION_REQUIRED",dn,"cDonor","mol/m^3",dom);plot3(m,"pg_nh3_real","NH3 - Real Geometry | NUMERICAL_VERIFICATION_ONLY",dh,"cNH3","mol/m^3",dom);}
    private static void plot3(Model m,String tag,String label,String data,String expr,String unit,String sel){if(m.result().hasTag(tag))m.result().remove(tag);m.result().create(tag,"PlotGroup3D");m.result(tag).label(label);m.result(tag).set("data",data);boolean volume=sel!=null&&sel.contains("_dom_");String ft=volume?"vol":"surf";m.result(tag).create(ft,volume?"Volume":"Surface");m.result(tag).feature(ft).set("expr",expr);m.result(tag).feature(ft).set("unit",unit);if(sel!=null){String c=datasetComponent(data),s=resolveSelection(m,c,sel);m.result(tag).feature(ft).create("sel","Selection");m.result(tag).feature(ft).feature("sel").selection().named(s);}}

    private static void incompressibleAdvection(Physics t){t.prop("AdvancedSettings").set("ConvectiveTerm","noncons");t.prop("MassConsistentStabilization").set("massStreamlineDiffusion",true);t.prop("MassConsistentStabilization").set("massCrosswindDiffusion",false);t.prop("ShapeProperty").set("order_concentration",1);}
    private static void conservativeGasAdvection(Physics t){t.prop("AdvancedSettings").set("ConvectiveTerm","cons");t.prop("MassConsistentStabilization").set("massStreamlineDiffusion",true);t.prop("MassConsistentStabilization").set("massCrosswindDiffusion",false);t.prop("ShapeProperty").set("order_concentration",1);}
    private static void conservativeLiquidAdvection(Physics t){t.prop("AdvancedSettings").set("ConvectiveTerm","cons");t.prop("MassConsistentStabilization").set("massStreamlineDiffusion",true);t.prop("MassConsistentStabilization").set("massCrosswindDiffusion",true);t.prop("MassConsistentStabilization").set("CrosswindType","Codina");t.prop("MassConsistentStabilization").set("Residual","FullResidual");t.prop("ShapeProperty").set("order_concentration",1);}
    private static void incompressibleLiquidAdvection(Physics t){t.prop("AdvancedSettings").set("ConvectiveTerm","noncons");t.prop("MassConsistentStabilization").set("massStreamlineDiffusion",true);t.prop("MassConsistentStabilization").set("massCrosswindDiffusion",true);t.prop("ShapeProperty").set("order_concentration",1);}
    private static void setMeshLevel(Model m,String c,String mesh,int level){if(m.component(c).mesh(mesh).feature().hasTag("size_review")){m.component(c).mesh(mesh).feature("size_review").set("hauto",level);return;}if(!m.component(c).mesh(mesh).feature().hasTag("m10a3_size_species")){m.component(c).mesh(mesh).create("m10a3_size_species","Size");m.component(c).mesh(mesh).feature().move("m10a3_size_species",0);}m.component(c).mesh(mesh).feature("m10a3_size_species").set("hauto",level);}
    private static void addLocalMeshSize(Model m,String c,String mesh,String tag,String[]sels,int level){if(m.component(c).mesh(mesh).feature().hasTag(tag))m.component(c).mesh(mesh).feature().remove(tag);m.component(c).mesh(mesh).create(tag,"Refine");List<Integer> ids=new ArrayList<Integer>();for(String s:sels)for(int id:m.component(c).selection(resolveSelection(m,c,s)).entities(2))if(!ids.contains(id))ids.add(id);int[]a=new int[ids.size()];for(int i=0;i<a.length;i++)a[i]=ids.get(i);m.component(c).mesh(mesh).feature(tag).selection().geom(2);m.component(c).mesh(mesh).feature(tag).selection().set(a);}
    private static void runOnlyPhysics(Model m,String study,String active){String step=m.study(study).feature().tags()[0];for(String c:m.component().tags())for(String p:m.component(c).physics().tags())m.study(study).feature(step).activate(p,p.equals(active));m.study(study).run();}
    private static String findPhysicsType(Model m,String c,String type){for(String p:m.component(c).physics().tags())if(m.component(c).physics(p).getType().equals(type))return p;throw new IllegalStateException("COPIED_PHYSICS_TYPE_NOT_FOUND: "+c+"/"+type);}
    private static void rebuildGasSelections(Model m,String c,String species){boolean n=species.equals("N2");String stem=n?"n2":"h2",dom="m10a3_sel_dom_"+stem+"_channel",all="m10a3_sel_bnd_"+stem+"_all",inraw="m10a3_sel_bnd_"+stem+"_inlet_raw",in="m10a3_sel_bnd_"+stem+"_inlet",outraw="m10a3_sel_bnd_"+stem+"_outlet_raw",out="m10a3_sel_bnd_"+stem+"_outlet",iraw=n?"m10a3_sel_bnd_n2_gde_interface_raw":"m10a3_sel_bnd_h2_ssc_raw",inter=n?"m10a3_sel_bnd_n2_gde_interface":"m10a3_sel_bnd_h2_ssc",walls="m10a3_sel_bnd_"+stem+"_walls";box(m,c,dom,3,"intersects",-25,-23,23,25,n?26:-27.9,n?27.9:-26);adj(m,c,all,dom);box(m,c,inraw,2,"inside",-27.3,-20.7,20.7,27.3,n?27.99:-28.01,n?28.01:-27.99);intersection(m,c,in,2,all,inraw);box(m,c,outraw,2,"inside",20.7,27.3,-27.3,-20.7,n?27.99:-28.01,n?28.01:-27.99);intersection(m,c,out,2,all,outraw);box(m,c,iraw,2,"inside",-27.3,27.3,-27.3,27.3,n?4.99:-5.01,n?5.01:-4.99);intersection(m,c,inter,2,all,iraw);difference(m,c,walls,all,new String[]{in,out,inter});for(String s:new String[]{dom,in,out,inter})if(m.component(c).selection(s).entities(s.equals(dom)?3:2).length!=1)throw new IllegalStateException("COPIED_GAS_SELECTION_INVALID "+c+"/"+s);}
    private static void rebuildLiquidSelections(Model m,String c){String[]tags={"m10a3_sel_dom_electrolyte_fluid","m10a3_sel_bnd_electrolyte_inlet","m10a3_sel_bnd_electrolyte_outlet","m10a3_sel_bnd_electrolyte_gde_top","m10a3_sel_bnd_electrolyte_gde_bottom","m10a3_sel_bnd_electrolyte_all","m10a3_sel_bnd_electrolyte_walls"};box(m,c,tags[0],3,"intersects",-30.9,30.9,-30.9,30.9,-4.9,4.9);box(m,c,tags[1],2,"inside",69.19,69.21,-33.3,-26.7,-3.3,3.3);box(m,c,tags[2],2,"inside",69.19,69.21,26.7,33.3,-3.3,3.3);box(m,c,tags[3],2,"inside",-31.01,31.01,-31.01,31.01,4.99,5.01);box(m,c,tags[4],2,"inside",-31.01,31.01,-31.01,31.01,-5.01,-4.99);adj(m,c,tags[5],tags[0]);difference(m,c,tags[6],tags[5],new String[]{tags[1],tags[2],tags[3],tags[4]});for(int i=0;i<5;i++)if(m.component(c).selection(tags[i]).entities(i==0?3:2).length!=1)throw new IllegalStateException("COPIED_LIQ_SELECTION_INVALID "+tags[i]);}
    private static void box(Model m,String c,String s,int dim,String condition,double xmin,double xmax,double ymin,double ymax,double zmin,double zmax){m.component(c).selection().create(s,"Box");m.component(c).selection(s).set("entitydim",dim);m.component(c).selection(s).set("condition",condition);m.component(c).selection(s).set("xmin",xmin);m.component(c).selection(s).set("xmax",xmax);m.component(c).selection(s).set("ymin",ymin);m.component(c).selection(s).set("ymax",ymax);m.component(c).selection(s).set("zmin",zmin);m.component(c).selection(s).set("zmax",zmax);}
    private static void adj(Model m,String c,String s,String input){m.component(c).selection().create(s,"Adjacent");m.component(c).selection(s).set("entitydim",3);m.component(c).selection(s).set("outputdim",2);m.component(c).selection(s).set("input",new String[]{input});m.component(c).selection(s).set("exterior","on");m.component(c).selection(s).set("interior","off");}
    private static void intersection(Model m,String c,String s,int dim,String...input){m.component(c).selection().create(s,"Intersection");m.component(c).selection(s).set("entitydim",dim);m.component(c).selection(s).set("input",input);}
    private static void difference(Model m,String c,String s,String add,String[]sub){m.component(c).selection().create(s,"Difference");m.component(c).selection(s).set("entitydim",2);m.component(c).selection(s).set("add",new String[]{add});m.component(c).selection(s).set("subtract",sub);}
    private static void runStudy(Model m,String tag,String step,String type,String active,String data,String comp){m.study().create(tag);m.study(tag).label(tag+" | M10A3");m.study(tag).create(step,type);for(String c:m.component().tags())for(String p:m.component(c).physics().tags())m.study(tag).feature(step).activate(p,p.equals(active));m.study(tag).run();rebind(m,tag,data,comp);}
    private static void runPositiveSpeciesStudy(Model m,String tag,String active,String data,String comp){m.param().set("lambda_transport","1");m.study().create(tag);m.study(tag).label(tag+" | M10A3 strictly positive conservative transient relaxation");m.study(tag).create("time","Transient");m.study(tag).feature("time").set("tlist","range(0,dt_species_output,t_species_end)");for(String c:m.component().tags())for(String p:m.component(c).physics().tags())m.study(tag).feature("time").activate(p,p.equals(active));m.study(tag).run();rebind(m,tag,data,comp);System.out.println("M10A3_POSITIVE_EXPONENTIAL_TRANSIENT_RELAXATION|study="+tag+"|t_end=6_tau_nom|lambda=1|status=PASS");}

    private static void refineExistingLiquidSolutions(Model m,Path run)throws Exception{
        for(String[] x:new String[][]{{"std_species_liq_n2","gfp_n2_liq","dset_species_liq_n2"},{"std_species_liq_nh3","gfp_nh3_liq","dset_species_liq_nh3"}}){
            String step=m.study(x[0]).feature().tags()[0];m.study(x[0]).feature(step).set("rtol","1e-8");runOnlyPhysics(m,x[0],x[1]);rebind(m,x[0],x[2],"comp_species_liq_real");System.out.println("M10A3_STRICT_LIQUID_RERUN|study="+x[0]+"|rtol=1e-8|status=PASS");
        }
        p(m,"m10a3_strict_liquid_rtol_complete","1","DERIVED conservative transient solutions rerun with relative tolerance 1e-8");m.save(run.resolve("checkpoint_06_nh3.mph").toString());System.out.println("M10A3_STRICT_LIQUID_CHECKPOINT_06=PASS");
    }

    private static boolean hasParameter(Model m,String name){for(String x:m.param().varnames())if(x.equals(name))return true;return false;}

    private static void configureHighlyNonlinear(Model m,String sol){boolean found=false;for(String a:m.sol(sol).feature().tags())if("Stationary".equals(m.sol(sol).feature(a).getType()))for(String b:m.sol(sol).feature(a).feature().tags())if("FullyCoupled".equals(m.sol(sol).feature(a).feature(b).getType())){m.sol(sol).feature(a).feature(b).set("dtech","hnlin");m.sol(sol).feature(a).feature(b).set("initsteph","1e-4");m.sol(sol).feature(a).feature(b).set("minsteph","1e-8");m.sol(sol).feature(a).feature(b).set("maxiter",200);found=true;System.out.println("M10A3_POSITIVE_SOLVER|solver="+sol+"|stationary="+a+"|coupled="+b+"|dtech=hnlin|initsteph=1e-4|minsteph=1e-8|maxiter=200");}if(!found)throw new IllegalStateException("M10A3_POSITIVE_FULLY_COUPLED_NOT_FOUND: "+sol);}
    private static void runStudyPair(Model m,String tag,String step,String type,String[]active,String data,String comp){m.study().create(tag);m.study(tag).label(tag+" | M10A3 collocated monolithic one-way coupling");m.study(tag).create(step,type);for(String c:m.component().tags())for(String p:m.component(c).physics().tags()){boolean on=false;for(String a:active)if(p.equals(a)){on=true;break;}m.study(tag).feature(step).activate(p,on);}m.study(tag).run();rebind(m,tag,data,comp);}
    private static void rebind(Model m,String study,String data,String comp){String sol=solver(m,study);if(!m.result().dataset().hasTag(data))m.result().dataset().create(data,"Solution");m.result().dataset(data).set("solution",sol);m.result().dataset(data).set("comp",comp);m.result().dataset(data).label("M10A3 solution for "+study);}
    private static String solver(Model m,String study){String[]s=m.study(study).getSolverSequences("SolverSequence");if(s.length<1)throw new IllegalStateException("NO_SOLVER: "+study);return s[s.length-1];}
    private static double eval(Model m,String type,String data,String comp,String sel,int dim,String expr,String unit){String t="m10a3_ev_"+(++serial);m.result().numerical().create(t,type);try{m.result().numerical(t).set("data",data);m.result().numerical(t).selection().geom(m.component(comp).geom().tags()[0],dim);m.result().numerical(t).selection().set(m.component(comp).selection(resolveSelection(m,comp,sel)).entities(dim));m.result().numerical(t).set("expr",new String[]{expr});m.result().numerical(t).set("unit",new String[]{unit});if(type.startsWith("Int")){m.result().numerical(t).set("intorderactive",true);m.result().numerical(t).set("intorder",8);}double[][]v=m.result().numerical(t).getReal();if(v==null||v.length==0||v[0].length==0)throw new IllegalStateException("EMPTY_EVAL "+expr);return v[0][v[0].length-1];}finally{m.result().numerical().remove(t);}}
    private static String resolveSelection(Model m,String comp,String wanted){if(m.component(comp).selection().hasTag(wanted))return wanted;if(m.component(comp).selection().hasTag("m10a3_"+wanted))return "m10a3_"+wanted;for(String s:m.component(comp).selection().tags())if(wanted.equals(m.component(comp).selection(s).label()))return s;throw new IllegalStateException("COPIED_SELECTION_NOT_FOUND: "+comp+"/"+wanted);}
    private static String datasetComponent(String data){if(data.contains("species_liq"))return "comp_species_liq_real";if(data.contains("n2"))return "comp_species_n2_real";if(data.contains("h2"))return "comp_species_h2_real";return "comp_species_liq_real";}
    private static double flowBalance(Model m,String d,String c,String in,String out,String u,String v,String w,String q){double a=eval(m,"IntSurface",d,c,in,2,u+"*nx+"+v+"*ny+"+w+"*nz","m^3/s"),b=eval(m,"IntSurface",d,c,out,2,u+"*nx+"+v+"*ny+"+w+"*nz","m^3/s");return Math.abs(a+b)/Math.max(m.param().evaluate(q,"m^3/s"),1e-300);}
    private static double geomMeasure(Model m,String c,String g,int dim,int[]ids,boolean area){m.component(c).geom(g).measureFinal().selection().geom(dim);m.component(c).geom(g).measureFinal().selection().set(ids);return area?m.component(c).geom(g).measureFinal().getArea():m.component(c).geom(g).measureFinal().getVolume();}
    private static void p(Model m,String n,String v,String d){m.param().set(n,v,d);}
    private static double rel(double a,double b){return Math.abs(a-b)/Math.max(Math.max(Math.abs(a),Math.abs(b)),1e-300);}
    private static String f(double x){return String.format(Locale.ROOT,"%.15g",x);}
    private static String csv(String s){return s.contains(",")||s.contains("\"")?"\""+s.replace("\"","\"\"")+"\"":s;}
    private static void write(Path p,String h,List<String[]>r)throws Exception{Files.createDirectories(p.getParent());try(BufferedWriter w=Files.newBufferedWriter(p,StandardCharsets.UTF_8)){w.write(h);w.newLine();for(String[]x:r){for(int i=0;i<x.length;i++){if(i>0)w.write(',');w.write(csv(x[i]));}w.newLine();}}}
    private static String rt(String n){try{return((String)Class.forName(RT).getField(n).get(null)).trim();}catch(Exception e){throw new IllegalStateException("RUNTIME_INPUT_MISSING: "+n,e);}}
}
