import com.comsol.model.Model;
import com.comsol.model.util.ModelUtil;
import java.io.BufferedWriter;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;

/** Coarse-versus-accepted-medium M10A4 mesh convergence; preserves immutable medium MPH. */
public final class LiNRR_M10A4_MeshConvergence {
 private static final String ROOT="F:\\LiNRR_COMSOL\\worktrees\\LiNRR_M10A4_INTEGRATED",RUN=ROOT+"\\runs\\M10A4\\20260820_121258";
 private static final String INPUT=RUN+"\\checkpoint_A4_electrical_loss.mph",PRELIM=RUN+"\\checkpoint_A4_mesh_hmin1045_resume_none.mph",ACCEPTED=RUN+"\\checkpoint_A4_mesh_coarse_hmin1045.mph",TABLE=ROOT+"\\results\\tables\\M10A4_mesh_convergence.csv";
 private static final String COMP="comp_species_liq_real",GEOM="geom_electrolyte_fluid1",DOM="m10a3_sel_dom_electrolyte_fluid",CATH="m10a3_sel_bnd_electrolyte_gde_top",AN="m10a3_sel_bnd_electrolyte_gde_bottom",IN="m10a3_sel_bnd_electrolyte_inlet",OUT="m10a3_sel_bnd_electrolyte_outlet";
 private static final String DA="dset_a4a_ohmic",DB="dset_a4b_ionic_en";private static int serial=0;
 private LiNRR_M10A4_MeshConvergence(){}
 public static void main(String[]args)throws Exception{
  if(Files.exists(Paths.get(ACCEPTED)))throw new IllegalStateException("REFUSE_OVERWRITE_ACCEPTED_COARSE_MESH_CHECKPOINT");
  long mediumElems;Map<String,double[]> med;Model medium=ModelUtil.load("M10A4Medium",INPUT);try{String mesh=medium.component(COMP).mesh().tags()[0];mediumElems=medium.component(COMP).mesh(mesh).getNumElem();med=mediumMetrics(medium);}finally{ModelUtil.remove("M10A4Medium");}
  Model m=ModelUtil.load("M10A4Mesh",Files.exists(Paths.get(PRELIM))?PRELIM:INPUT);try{
   String mesh=m.component(COMP).mesh().tags()[0];long coarseElems;
   if(Files.exists(Paths.get(PRELIM))){coarseElems=m.component(COMP).mesh(mesh).getNumElem();System.out.println("M10A4_MESH_RESUME|source="+PRELIM+"|coarse_elements="+coarseElems+"|solves_rerun=FALSE");}
   else{String refine="m10a4b_ion_boundary_refine";
   require(m.component(COMP).mesh(mesh).feature().hasTag(refine),"ACCEPTED_MEDIUM_REFINEMENT_MISSING");
   m.component(COMP).mesh(mesh).feature().remove(refine);
   String target="m10a4_mesh_hmin1045_all_boundary_refine",wall="m10a3_sel_bnd_electrolyte_walls";String size=m.component(COMP).mesh(mesh).feature().hasTag("size_review")?"size_review":"m10a3_size_species";require(m.component(COMP).mesh(mesh).feature().hasTag(size),"GLOBAL_SIZE_FEATURE_MISSING");m.component(COMP).mesh(mesh).feature(size).set("hauto",4);m.component(COMP).mesh(mesh).feature(size).set("custom","on");m.component(COMP).mesh(mesh).feature(size).set("hmax","8.02");m.component(COMP).mesh(mesh).feature(size).set("hmin","1.045");m.component(COMP).mesh(mesh).feature(size).set("hgrad","1.45");m.component(COMP).mesh(mesh).feature(size).set("hcurve","0.5");m.component(COMP).mesh(mesh).feature(size).set("hnarrow","0.6");List<Integer>ids=new ArrayList<>();for(String sel:new String[]{CATH,AN,IN,OUT,wall})for(int id:m.component(COMP).selection(sel).entities(2))if(!ids.contains(id))ids.add(id);int[]arr=new int[ids.size()];for(int i=0;i<arr.length;i++)arr[i]=ids.get(i);m.component(COMP).mesh(mesh).create(target,"Refine");m.component(COMP).mesh(mesh).feature(target).selection().geom(2);m.component(COMP).mesh(mesh).feature(target).selection().set(arr);
   m.component(COMP).mesh(mesh).run();coarseElems=m.component(COMP).mesh(mesh).getNumElem();
   require(coarseElems<mediumElems,"COARSE_NOT_COARSER medium="+mediumElems+" coarse="+coarseElems);
   System.out.println("M10A4_MESH_REBUILD|medium_elements="+mediumElems+"|coarse_elements="+coarseElems+"|removed_feature="+refine+"|global_size_feature="+size+"|hauto=4|hmax=8.02|custom_hmin=1.045_vs_medium_1.00|all_boundary_refine="+target+"|refined_boundaries="+arr.length);
   activateOnly(m,"std_a4a_ohmic","stat","cd_a4a");m.study("std_a4a_ohmic").run();
   activateOnly(m,"std_a4b_flow_repair","stat","spf_liq_local");m.study("std_a4b_flow_repair").run();
   activateOnly(m,"std_a4b_ionic_en","time","gfp_salt_a4b");m.study("std_a4b_ionic_en").run();
   }
   require(coarseElems<mediumElems,"COARSE_NOT_COARSER medium="+mediumElems+" coarse="+coarseElems);
   m.label("LiNRR_M10A4_mesh_coarse_hmin1045_verification.mph");m.comments("Separate modestly coarsened mesh: accepted level-4 settings retained except hmin 1.045 versus 1.00, with identical full named boundary refinement. Accepted medium immutable; no M10A3 physics changed.");m.save(ACCEPTED);
   auditConservation(m);Map<String,double[]> coarse=coarseMetrics(m);List<String[]>rows=new ArrayList<>();double max=0;String limiting="";
   for(String key:med.keySet()){double[] a=med.get(key),b=coarse.get(key);require(b!=null,"COARSE_METRIC_MISSING "+key);boolean fraction=a[1]>0.5;double d=relative(a[0],b[0],fraction);if(d>max){max=d;limiting=key;}rows.add(new String[]{"medium",key,f(a[0]),unit(key),"medium",f(a[0]),"0","BASELINE","accepted medium artifact","ACCEPTED_MEDIUM_IMMUTABLE"});rows.add(new String[]{"coarse",key,f(b[0]),unit(key),"medium",f(a[0]),f(d),fraction&&Math.abs(a[0])<=1e-12?"ABSOLUTE_DIFFERENCE_FOR_ZERO_REFERENCE_FRACTION":"ABS_COARSE_MINUS_MEDIUM_OVER_ABS_MEDIUM",d<=.05?"PASS_PREFERRED":d<=.10?"PASS_WITH_LIMITATION":"BLOCK"});}
   rows.add(new String[]{"comparison","MESH_MAX_KEY_DIFFERENCE",f(max),"1","medium","0",f(max),"MAX_NOT_AVERAGE",limiting,max<=.05?"PASS_PREFERRED":max<=.10?"PASS_WITH_LIMITATION":"BLOCK"});
   write(Paths.get(TABLE),rows);System.out.println("M10A4_MESH_CONVERGENCE|medium_elements="+mediumElems+"|coarse_elements="+coarseElems+"|max_relative="+f(max)+"|limiting_metric="+limiting+"|status="+(max<=.05?"PASS_PREFERRED":max<=.10?"PASS_WITH_LIMITATION":"BLOCK"));if(max>.10)throw new IllegalStateException("MESH_MAX_KEY_DIFFERENCE_GT_0.10 "+max+" metric="+limiting);System.out.println("M10A4_MESH_CONVERGENCE=PASS");
  }finally{ModelUtil.remove("M10A4Mesh");}
 }
 private static Map<String,double[]>mediumMetrics(Model m)throws Exception{Map<String,double[]>x=new LinkedHashMap<>();Map<String,String>c=csv(Paths.get(ROOT,"results","tables","M10A4_current_distribution_statistics.csv"),"quantity","value");Map<String,String>l=csvKey(Paths.get(ROOT,"results","tables","M10A4_li_faraday_ledger.csv"));Map<String,String>s=spatial();x.put("R_ohmic",metric(11.0169921792010,false));x.put("mean_cathode_j",metric(d(c.get("j_surface_magnitude_mean")),false));x.put("max_cathode_j",metric(d(c.get("j_surface_magnitude_max")),false));x.put("cathode_j_CV",metric(d(c.get("j_surface_magnitude_CV")),false));double[]li=meanCv(m,DB,CATH,"cLi_a4b","mol/m^3");x.put("mean_Li",metric(li[0],false));x.put("Li_CV",metric(li[1],false));x.put("Li_equiv_297C_mean_thickness",metric(d(l.get("mean_thickness_m")),false));x.put("Li_equiv_297C_thickness_CV",metric(d(l.get("CV_thickness")),false));x.put("N2_current_high_high_fraction",metric(d(s.get("N2_CURRENT_OVERLAP|HIGH_HIGH")),true));for(String cat:cats())x.put("colim_"+cat,metric(d(s.get("N2_LI_DONOR_CURRENT_COLIMITATION|"+cat)),true));return x;}
 private static Map<String,double[]>coarseMetrics(Model m){Map<String,double[]>x=new LinkedHashMap<>();String as=solver(m,"std_a4a_ohmic"),ns=solver(m,"std_species_liq_n2");double ia=ev(m,"IntSurface",DA,CATH,2,"cd.nIl","A"),drop=ev(m,"AvSurface",DA,AN,2,"cd.phil","V")-ev(m,"AvSurface",DA,CATH,2,"cd.phil","V");String j="sqrt((withsol('"+as+"',cd.nIl))^2)";double area=ev(m,"IntSurface",DB,CATH,2,"1","m^2"),jm=ev(m,"IntSurface",DB,CATH,2,j,"A")/area,jmax=ev(m,"MaxSurface",DB,CATH,2,j,"A/m^2"),jv=ev(m,"IntSurface",DB,CATH,2,"("+j+"-("+f(jm)+"[A/m^2]))^2","A^2/m^2")/area,jcv=Math.sqrt(Math.max(jv,0))/jm;double[]li=meanCv(m,DB,CATH,"cLi_a4b","mol/m^3");x.put("R_ohmic",metric(drop/Math.abs(ia),false));x.put("mean_cathode_j",metric(jm,false));x.put("max_cathode_j",metric(jmax,false));x.put("cathode_j_CV",metric(jcv,false));x.put("mean_Li",metric(li[0],false));x.put("Li_CV",metric(li[1],false));double thick=jm*(297/Math.abs(ia))*m.param().evaluate("M_Li_a4d","kg/mol")/(m.param().evaluate("F_const","C/mol")*m.param().evaluate("rho_Li_a4d","kg/m^3"));x.put("Li_equiv_297C_mean_thickness",metric(thick,false));x.put("Li_equiv_297C_thickness_CV",metric(jcv,false));String n2="withsol('"+ns+"',cN2d)",liE="cLi_a4b",don="withsol('"+ns+"',cDonor)";String[]e={n2,liE,don,j},u={"mol/m^3","mol/m^3","mol/m^3","A/m^2"};double[]t=new double[4];for(int k=0;k<4;k++)t[k]=quantile(m,e[k],u[k],area,.5);String nh=ge(e[0],t[0],u[0]),lh=ge(e[1],t[1],u[1]),dh=ge(e[2],t[2],u[2]),jh=ge(e[3],t[3],u[3]),nl=not(nh),ll=not(lh),dl=not(dh),jl=not(jh),multi="(("+nl+"&&"+ll+")||("+nl+"&&"+dl+")||("+ll+"&&"+dl+"))";Map<String,String>ce=new LinkedHashMap<>();ce.put("MULTI_LIMITED",multi);ce.put("BALANCED","("+nh+"&&"+lh+"&&"+dh+"&&"+jh+")");ce.put("LI_LIMITED","("+nh+"&&"+ll+"&&"+dh+"&&"+jh+")");ce.put("DONOR_LIMITED","("+nh+"&&"+lh+"&&"+dl+"&&"+jh+")");ce.put("CURRENT_RICH_N2_POOR","("+jh+"&&"+nl+"&&"+lh+"&&"+dh+")");ce.put("N2_RICH_CURRENT_POOR","("+nh+"&&"+jl+"&&!"+multi+")");String used="("+String.join("||",ce.values())+")";ce.put("MIXED_UNCLASSIFIED","(!"+used+")");x.put("N2_current_high_high_fraction",metric(ev(m,"IntSurface",DB,CATH,2,"if("+nh+"&&"+jh+",1,0)","m^2")/area,true));for(String cat:cats())x.put("colim_"+cat,metric(ev(m,"IntSurface",DB,CATH,2,"if("+ce.get(cat)+",1,0)","m^2")/area,true));return x;}
 private static void auditConservation(Model m){String as=solver(m,"std_a4a_ohmic"),un="u_liq_a4b_x*nx+u_liq_a4b_y*ny+u_liq_a4b_z*nz",ramp="(1-exp(-t/t_a4b_ramp))*lambda_a4b",jn="withsol('"+as+"',cd.nIl)";double in=ev(m,"IntSurface",DB,IN,2,"c_salt_bulk_a4b*("+un+")","mol/s"),out=ev(m,"IntSurface",DB,OUT,2,"cSalt_a4b*("+un+")","mol/s"),ci=ev(m,"IntSurface",DB,CATH,2,ramp+"*("+jn+")","A"),ai=ev(m,"IntSurface",DB,AN,2,ramp+"*("+jn+")","A"),acc=ev(m,"IntVolume",DB,DOM,3,"d(cSalt_a4b,t)","mol/s"),tp=m.param().evaluate("t_plus_a4b"),F=m.param().evaluate("F_const","C/mol"),net=in+out+(1-tp)*(ci+ai)/F,scale=Math.max(Math.max(Math.abs(in),Math.abs(out)),Math.max(Math.abs(acc),Math.max(Math.abs(ci/F),Math.abs(ai/F)))),salt= Math.abs(net+acc)/Math.max(scale,1e-300),charge=Math.abs(ci+ai)/Math.max(Math.max(Math.abs(ci),Math.abs(ai)),1e-300),cmin=ev(m,"MinVolume",DB,DOM,3,"cLi_a4b","mol/m^3");System.out.println("M10A4_COARSE_CONSERVATION|Li_relative="+f(salt)+"|BF4_relative="+f(salt)+"|charge_relative="+f(charge)+"|c_min="+f(cmin));require(salt<=1e-6&&charge<=1e-8&&cmin>0,"COARSE_CONSERVATION_GATE_FAIL");}
 private static double[]meanCv(Model m,String data,String sel,String e,String u){double area=ev(m,"IntSurface",data,sel,2,"1","m^2"),mean=ev(m,"IntSurface",data,sel,2,e,"mol/m")/area,var=ev(m,"IntSurface",data,sel,2,"("+e+"-("+f(mean)+"["+u+"]))^2","mol^2/m^4")/area;return new double[]{mean,Math.sqrt(Math.max(var,0))/Math.abs(mean)};}
 private static double quantile(Model m,String e,String u,double area,double q){double lo=ev(m,"MinSurface",DB,CATH,2,e,u),hi=ev(m,"MaxSurface",DB,CATH,2,e,u);if(Math.abs(hi-lo)<=1e-12*Math.max(Math.abs(hi),1))return .5*(lo+hi);for(int i=0;i<18;i++){double z=.5*(lo+hi),fr=ev(m,"IntSurface",DB,CATH,2,"if(("+e+")<=("+f(z)+"["+u+"]),1,0)","m^2")/area;if(fr<q)lo=z;else hi=z;}return .5*(lo+hi);}
 private static Map<String,String>spatial()throws Exception{Map<String,String>x=new LinkedHashMap<>();List<String[]>r=read(Paths.get(ROOT,"results","tables","M10A4_spatial_colimitation.csv"));for(String[]a:r)if(a.length>4&&"0.500000000000000".equals(a[1]))x.put(a[0]+"|"+a[2],a[3]);return x;}
 private static Map<String,String>csv(Path p,String k,String v)throws Exception{List<String[]>r=read(p);String[]h=r.remove(0);int ki=index(h,k),vi=index(h,v);Map<String,String>x=new LinkedHashMap<>();for(String[]a:r)if(a.length>Math.max(ki,vi))x.put(a[ki],a[vi]);return x;}
 private static Map<String,String>csvKey(Path p)throws Exception{List<String[]>r=read(p);String[]h=r.remove(0);int qi=index(h,"Q_C"),fi=index(h,"f_Li_current");Map<String,String>x=new LinkedHashMap<>();for(String[]a:r)if("297.000000000000".equals(a[qi])&&"1.00000000000000".equals(a[fi]))for(int i=0;i<h.length&&i<a.length;i++)x.put(h[i],a[i]);return x;}
 private static List<String[]>read(Path p)throws Exception{List<String[]>r=new ArrayList<>();for(String line:Files.readAllLines(p,StandardCharsets.UTF_8)){List<String>a=new ArrayList<>();StringBuilder b=new StringBuilder();boolean q=false;for(int i=0;i<line.length();i++){char c=line.charAt(i);if(c=='\"'){if(q&&i+1<line.length()&&line.charAt(i+1)=='\"'){b.append(c);i++;}else q=!q;}else if(c==','&&!q){a.add(b.toString());b.setLength(0);}else b.append(c);}a.add(b.toString());r.add(a.toArray(new String[0]));}return r;}
 private static int index(String[]h,String n){for(int i=0;i<h.length;i++)if(h[i].equals(n))return i;throw new IllegalStateException("CSV_COLUMN_MISSING "+n);}private static double d(String s){require(s!=null,"MISSING_MEDIUM_VALUE");return Double.parseDouble(s);}
 private static String[]cats(){return new String[]{"CURRENT_RICH_N2_POOR","N2_RICH_CURRENT_POOR","LI_LIMITED","DONOR_LIMITED","BALANCED","MULTI_LIMITED","MIXED_UNCLASSIFIED"};}private static String ge(String e,double v,String u){return "(("+e+")>=("+f(v)+"["+u+"]))";}private static String not(String x){return "(!"+x+")";}
 private static double relative(double a,double b,boolean fraction){if(fraction&&Math.abs(a)<=1e-12)return Math.abs(b-a);return Math.abs(b-a)/Math.max(Math.abs(a),1e-300);}
 private static void activateOnly(Model m,String study,String step,String physics){for(String c:m.component().tags())for(String p:m.component(c).physics().tags())m.study(study).feature(step).activate(p,c.equals(COMP)&&p.equals(physics));System.out.println("M10A4_MESH_STUDY_ACTIVATION|study="+study+"|only="+physics);}
 private static String solver(Model m,String s){String[]x=m.study(s).getSolverSequences("SolverSequence");require(x.length>0,"NO_SOLVER "+s);return x[x.length-1];}
 private static double entityArea(Model m,int id){String t="m10a4mesh_area_"+(++serial);m.result().numerical().create(t,"IntSurface");try{m.result().numerical(t).set("data",DB);m.result().numerical(t).selection().geom(GEOM,2);m.result().numerical(t).selection().set(new int[]{id});m.result().numerical(t).set("expr",new String[]{"1"});m.result().numerical(t).set("unit",new String[]{"m^2"});double[][]v=m.result().numerical(t).getReal();require(v!=null&&v.length>0&&v[0].length>0,"EMPTY_WALL_AREA "+id);return v[0][v[0].length-1];}finally{m.result().numerical().remove(t);}}
 private static double ev(Model m,String type,String data,String sel,int dim,String e,String u){String t="m10a4mesh_ev_"+(++serial);m.result().numerical().create(t,type);try{m.result().numerical(t).set("data",data);m.result().numerical(t).selection().geom(GEOM,dim);m.result().numerical(t).selection().set(m.component(COMP).selection(sel).entities(dim));m.result().numerical(t).set("expr",new String[]{e});m.result().numerical(t).set("unit",new String[]{u});if(type.startsWith("Int")){m.result().numerical(t).set("intorderactive",true);m.result().numerical(t).set("intorder",8);}double[][]v=m.result().numerical(t).getReal();require(v!=null&&v.length>0&&v[0].length>0,"EMPTY "+e);return v[0][v[0].length-1];}finally{m.result().numerical().remove(t);}}
 private static void write(Path p,List<String[]>r)throws Exception{try(BufferedWriter w=Files.newBufferedWriter(p,StandardCharsets.UTF_8)){w.write("mesh,metric,value,unit,reference_mesh,reference_value,relative_difference,comparison_method,status,notes");w.newLine();for(String[]a:r){for(int i=0;i<a.length;i++){if(i>0)w.write(',');w.write(csvq(a[i]));}w.newLine();}}}private static String csvq(String s){return s.contains(",")||s.contains("\"")?"\""+s.replace("\"","\"\"")+"\"":s;}
 private static double[]metric(double v,boolean fraction){return new double[]{v,fraction?1:0};}private static String unit(String key){if(key.equals("R_ohmic"))return "ohm";if(key.equals("mean_cathode_j")||key.equals("max_cathode_j"))return "A/m^2";if(key.equals("mean_Li"))return "mol/m^3";if(key.equals("Li_equiv_297C_mean_thickness"))return "m";return "1";}
 private static String f(double x){return String.format(Locale.ROOT,"%.15g",x);}private static void require(boolean b,String s){if(!b)throw new IllegalStateException(s);}
}
