param([string]$RunStamp='')
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop';$env:GIT_PAGER='cat'
$ProjectRoot=(Resolve-Path(Join-Path $PSScriptRoot '..\..')).Path
$ModulePath=Join-Path $ProjectRoot 'scripts\windows\modules\LiNRR_M03A2_EIS.psm1';$TestPath=Join-Path $ProjectRoot 'tests\powershell\Test_M03A_2_EIS.ps1';$ManifestPath=Join-Path $ProjectRoot 'config\M03A_2_eis_manifest.csv';$AreaConfigPath=Join-Path $ProjectRoot 'config\M03A_2_area_audit.csv';$DictionaryPath=Join-Path $ProjectRoot 'docs\M03A_2_eis_data_dictionary.md'
if([string]::IsNullOrWhiteSpace($RunStamp)){$RunStamp=Get-Date -Format yyyyMMdd_HHmmss}
$RunDir=Join-Path $ProjectRoot "runs\${RunStamp}_M03A_2";$LatestDir=Join-Path $ProjectRoot 'runs\latest';$TableDir=Join-Path $ProjectRoot 'results\tables';$FigureDir=Join-Path $ProjectRoot 'results\figures'
$RunLog=Join-Path $RunDir 'M03A_2_build.log';$LatestLog=Join-Path $LatestDir 'M03A_2_build.log';$RunReport=Join-Path $RunDir 'M03A_2_report.md';$LatestReport=Join-Path $LatestDir 'M03A_2_report.md';$TestOut=Join-Path $RunDir 'M03A_2_test_stdout.log';$TestErr=Join-Path $RunDir 'M03A_2_test_stderr.log';$FrozenBeforePath=Join-Path $RunDir 'M03A_2_frozen_hashes_before.csv';$FrozenAfterPath=Join-Path $RunDir 'M03A_2_frozen_hashes_after.csv'
$ImportCsv=Join-Path $TableDir 'M03A_2_eis_import_audit.csv';$HfrCsv=Join-Path $TableDir 'M03A_2_hfr_estimates.csv';$ConsensusCsv=Join-Path $TableDir 'M03A_2_replicate_consensus.csv';$LedgerCsv=Join-Path $TableDir 'M03A_2_resistance_ledger.csv';$ConductivityCsv=Join-Path $TableDir 'M03A_2_conductivity_crosscheck.csv';$AreaCsv=Join-Path $TableDir 'M03A_2_area_audit.csv';$ReadinessCsv=Join-Path $TableDir 'M03A_2_readiness.csv';$RegressionCsv=Join-Path $TableDir 'M03A_2_synthetic_regression.csv'
$NyquistPng=Join-Path $FigureDir 'M03A_2_synthetic_nyquist.png';$HfrPng=Join-Path $FigureDir 'M03A_2_hfr_recovery.png';$ReplicatePng=Join-Path $FigureDir 'M03A_2_replicate_comparison.png';$LedgerPng=Join-Path $FigureDir 'M03A_2_resistance_ledger.png'
$RunState='SYNTHETIC_SMOKE_TEST';$CalibrationMode='PROVISIONAL';$M03BReady='FALSE';$Log=New-Object Text.StringBuilder
function Add-Log{param([string]$Text)[void]$Log.AppendLine("$(Get-Date -Format o)|$Text")}
function Assert-True{param([bool]$Condition,[string]$Message)if(-not$Condition){throw $Message}}
function Test-Utf8NoBom{param([string]$Path)$B=[IO.File]::ReadAllBytes($Path);if($B.Length-ge3-and$B[0]-eq239-and$B[1]-eq187-and$B[2]-eq191){throw "UTF-8 BOM forbidden: $Path"};[void](New-Object Text.UTF8Encoding($false,$true)).GetString($B)}
function Test-Png{param([string]$Path)$B=[IO.File]::ReadAllBytes($Path);$S=[byte[]](137,80,78,71,13,10,26,10);if($B.Length-le8){throw "PNG empty: $Path"};for($I=0;$I-lt8;$I++){if($B[$I]-ne$S[$I]){throw "PNG signature invalid: $Path"}}}
function Get-Frozen{param([string[]]$Paths)$O=@();foreach($R in $Paths){$P=Join-Path $ProjectRoot $R;$O+=[PSCustomObject][ordered]@{path=$R;sha256=(Get-FileHash -Algorithm SHA256 -LiteralPath $P).Hash}};return $O}
function Case{param([object[]]$Rows,[string]$Id)return @($Rows|Where-Object case_id -eq $Id)[0]}
function NumberOrBlank{param([double]$Value)if(Test-M03A2Finite $Value){return Format-M03A2Number $Value};return ''}
function New-HfrRow{param([object]$Case,[object]$E)
    return [PSCustomObject][ordered]@{sample_id=$Case.sample_id;replicate_id=$Case.replicate_id;case_id=$Case.case_id;method=$E.Method;method_class=$E.MethodClass;HFR_ohm=NumberOrBlank([double]$E.EstimateOhm);HFR_uncertainty_ohm=NumberOrBlank([double]$E.StandardUncertaintyOhm);selected_point_count=$E.SelectedPointCount;selected_original_rows=$E.SelectedOriginalRows;frequency_min_Hz=NumberOrBlank([double]$E.FrequencyMinHz);frequency_max_Hz=NumberOrBlank([double]$E.FrequencyMaxHz);intercept_model=$E.InterceptModel;residual_metric=NumberOrBlank([double]$E.ResidualMetric);high_frequency_coverage_status=$E.HighFrequencyCoverageStatus;inductive_artifact_status=$E.InductiveArtifactStatus;duplicate_frequency_status=$E.DuplicateFrequencyStatus;fit_quality_status=$E.FitQualityStatus;status=$E.Status;failure_reason=$E.FailureReason;source_file=$Case.file_path;equivalent_circuit=$E.EquivalentCircuit;fitting_software=$E.FittingSoftware;fit_file=$E.FitFile;Rs_ohm=$E.RsOhm;Rs_standard_error_ohm=$E.RsStandardErrorOhm;fit_quality_metric=$E.FitQualityMetric;fit_quality_value=$E.FitQualityValue;source_reference=$E.SourceReference;contract_status=$E.ContractStatus;notes=$E.Notes;detail=$E.Detail}
}
function New-ConductivityRow{param($Sample,$Case,$R,$RU,$Analytic,$Mc,$Status,$Reason,$Direct,$Difference)
    return [PSCustomObject][ordered]@{sample_id=$Sample;case_id=$Case;Hcell_m='0.0040000000000000001';Hcell_definition='synthetic electrode spacing for verification only';Hcell_uncertainty_m='4.0000000000000003E-05';EIS_area_m2='0.0030250000000000003';EIS_area_definition='explicit synthetic EIS normalization area';EIS_area_uncertainty_m2='3.0250000000000001E-05';R_electrolyte_ohm=Format-M03A2Number $R;R_electrolyte_uncertainty_ohm=Format-M03A2Number $RU;kappa_HFR_S_m=if($null-ne$Analytic){Format-M03A2Number $Analytic.kappa_S_m}else{''};kappa_HFR_analytical_uncertainty_S_m=if($null-ne$Analytic){Format-M03A2Number $Analytic.kappa_uncertainty_S_m}else{''};kappa_HFR_MC_mean_S_m=Format-M03A2Number $Mc.mean;kappa_HFR_MC_std_S_m=Format-M03A2Number $Mc.std;MC_seed=$Mc.MC_seed;MC_sample_count=$Mc.MC_sample_count;MC_accepted_count=$Mc.MC_accepted_count;MC_rejected_count=$Mc.MC_rejected_count;MC_rejected_fraction=Format-M03A2Number $Mc.MC_rejected_fraction;independence_assumption='INDEPENDENCE_ASSUMPTION_PROVISIONAL';direct_conductivity_S_m=$Direct;direct_vs_HFR_relative_difference=$Difference;status=$Status;failure_reason=$Reason}
}

New-Item -ItemType Directory -Force -Path $RunDir,$LatestDir,$TableDir,$FigureDir|Out-Null
try{
    Add-Log 'START|M03A.2 formal synthetic EIS contract verification'
    foreach($P in @($ModulePath,$TestPath,$ManifestPath,$AreaConfigPath,$DictionaryPath)){Assert-True (Test-Path -LiteralPath $P -PathType Leaf) "required input missing: $P"}
    $Tracked=@(& git -C $ProjectRoot ls-files);Assert-True ($LASTEXITCODE-eq0) 'git ls-files failed';$FrozenPaths=@($Tracked|Where-Object{$_-ne'docs/DECISIONS.md'}|Sort-Object);$Before=@(Get-Frozen $FrozenPaths);Import-Module $ModulePath -Force;Write-M03A2Utf8NoBomCsv $Before $FrozenBeforePath;Add-Log "FROZEN_SHA256_BEFORE|PASS|files=$($Before.Count)"
    foreach($P in @($ModulePath,$TestPath,$MyInvocation.MyCommand.Path)){$T=$null;$E=$null;[Management.Automation.Language.Parser]::ParseFile($P,[ref]$T,[ref]$E)|Out-Null;if(@($E).Count){throw "Parser.ParseFile findings in $P"}};Add-Log 'PARSER_PARSEFILE|PASS|module,test,driver'
    Remove-Module LiNRR_M03A2_EIS -Force;Import-Module $ModulePath -Force;Add-Log 'MODULE_IMPORT|PASS|Windows PowerShell 5.1'

    $Manifest=@(Import-Csv -LiteralPath $ManifestPath -Encoding UTF8);$RequiredManifest=@('sample_id','replicate_id','case_id','case_type','file_path','data_origin','frequency_unit','impedance_unit','temperature_K','electrolyte_composition','water_content','instrument','perturbation_amplitude_V','dc_bias_V','measurement_date','area_basis','EIS_area_m2','intercept_method','equivalent_circuit','source_reference','status','notes','expected_outcome','expected_hfr_ohm');Assert-True ($Manifest.Count-ge30) 'manifest has fewer than 30 cases';foreach($F in $RequiredManifest){Assert-True ($Manifest[0].PSObject.Properties.Name-contains$F) "manifest field missing: $F"};Assert-True (@($Manifest|Group-Object case_id|Where-Object Count -ne 1).Count-eq0) 'duplicate case id';Assert-True (@($Manifest|Where-Object{$_.data_origin-notin@('SYNTHETIC','EXPERIMENTAL','LITERATURE','UNKNOWN')}).Count-eq0) 'invalid data_origin enum';Assert-True (@($Manifest|Where-Object data_origin -eq SYNTHETIC_FIXED_DEFINITION).Count-eq0) 'legacy data_origin forbidden'
    $C023=Case $Manifest C023;$C023Path=Join-Path $ProjectRoot (($C023.file_path).Replace('/','\'));Assert-True ($C023.data_origin-eq'EXPERIMENTAL'-and-not(Test-Path $C023Path)-and[string]::IsNullOrWhiteSpace($C023.source_reference)) 'C023 incomplete experimental contract not preserved';Add-Log "MANIFEST_AUDIT|PASS|cases=$($Manifest.Count)|origins=$((@($Manifest|Group-Object data_origin)|ForEach-Object{"$($_.Name):$($_.Count)"})-join',')"
    New-M03A2SyntheticFixtures $Manifest $ProjectRoot;$Synthetic=@($Manifest|Where-Object data_origin -eq SYNTHETIC);foreach($C in $Synthetic){Assert-True (Test-Path(Join-Path $ProjectRoot (($C.file_path).Replace('/','\')))) "synthetic fixture missing: $($C.case_id)"};Assert-True (-not(Test-Path $C023Path)) 'experimental fixture was fabricated';$FixtureFiles=@(Get-ChildItem (Join-Path $ProjectRoot 'tests\fixtures\M03A_2') -File -Filter '*.csv');$FixtureNames=@{};foreach($C in $Synthetic){$FixtureNames[[IO.Path]::GetFileName($C.file_path)]=$true};Assert-True (@($FixtureFiles|Where-Object{-not$FixtureNames.ContainsKey($_.Name)}).Count-eq0) 'unmanifested synthetic fixture remains';Add-Log "FIXTURE_MANIFEST_AUDIT|PASS|synthetic=$($Synthetic.Count)|experimental_incomplete=1|unmanifested=0"
    Assert-True ((Format-M03A2Number(Convert-M03A2FrequencyToHz 1 mHz))-eq'0.001') 'mHz conversion';Assert-True ((Format-M03A2Number(Convert-M03A2FrequencyToHz 1 MHz))-eq'1000000') 'MHz conversion';Add-Log 'UNIT_CONVERSION_AUDIT|PASS|Hz,kHz,mHz,MHz,ohm,mohm,kohm;Unicode blocked'

    $PS51=Join-Path $env:SystemRoot 'System32\WindowsPowerShell\v1.0\powershell.exe'
    $TestLines=@(& $PS51 -NoProfile -ExecutionPolicy Bypass -File $TestPath -ProjectRoot $ProjectRoot -SkipFixtureGeneration 2>&1)
    $TestExit=$LASTEXITCODE
    Write-M03A2Utf8NoBomText $TestOut (($TestLines|ForEach-Object{[string]$_})-join"`n")
    Write-M03A2Utf8NoBomText $TestErr ''
    Assert-True ($TestExit-eq0) "self-contained tests exit $TestExit"
    $Pass=@($TestLines|Where-Object{[string]$_-like'M03A2_TEST|PASS|*'});Assert-True ($Pass.Count-eq1) 'self-contained PASS record missing';Add-Log "SELF_CONTAINED_TEST|$($Pass[0])"

    $ImportRows=New-Object Collections.Generic.List[object];$HfrRows=New-Object Collections.Generic.List[object];$Imports=@{};$Estimator=@{}
    foreach($C in $Manifest){
        if($C.data_origin-eq'EXPERIMENTAL'){
            $ImportRows.Add([PSCustomObject][ordered]@{sample_id=$C.sample_id;replicate_id=$C.replicate_id;case_id=$C.case_id;case_type=$C.case_type;data_origin=$C.data_origin;source_reference=$C.source_reference;source_file=$C.file_path;original_row_number='';normalized_order='';raw_frequency='';raw_z_real='';raw_z_imag='';frequency_Hz='';z_real_ohm='';z_imag_ohm='';duplicate_frequency='FALSE';high_frequency_inductive='FALSE';status='EXPERIMENTAL_INPUT_INCOMPLETE';detail='file or critical provenance deliberately missing; no fixture generated'})
            foreach($M in @('FIRST_POINT_DIAGNOSTIC','HIGH_FREQUENCY_INTERCEPT')){$Class=if($M-eq'FIRST_POINT_DIAGNOSTIC'){'LAB_SCREENING_HEURISTIC'}else{'HFR_ESTIMATOR'};$HfrRows.Add([PSCustomObject][ordered]@{sample_id=$C.sample_id;replicate_id=$C.replicate_id;case_id=$C.case_id;method=$M;method_class=$Class;HFR_ohm='';HFR_uncertainty_ohm='';selected_point_count=0;selected_original_rows='';frequency_min_Hz='';frequency_max_Hz='';intercept_model='NONE';residual_metric='';high_frequency_coverage_status='NOT_ASSESSED';inductive_artifact_status='NOT_ASSESSED';duplicate_frequency_status='NOT_ASSESSED';fit_quality_status='NOT_ASSESSED';status='EXPERIMENTAL_INPUT_INCOMPLETE';failure_reason='missing experimental file or critical provenance';source_file=$C.file_path;equivalent_circuit=$C.equivalent_circuit;fitting_software=$C.fitting_software;fit_file=$C.fit_file;Rs_ohm=$C.Rs_ohm;Rs_standard_error_ohm=$C.Rs_standard_error_ohm;fit_quality_metric=$C.fit_quality_metric;fit_quality_value=$C.fit_quality_value;source_reference=$C.source_reference;contract_status=$C.status;notes=$C.notes;detail='case classification is independent of RUN_STATE'})};continue
        }
        $Path=Join-Path $ProjectRoot (($C.file_path).Replace('/','\'));$I=Import-M03A2Eis $Path $C.case_id $C.frequency_unit $C.impedance_unit $C.sample_id $C.replicate_id $C.case_type;$Imports[$C.case_id]=$I
        foreach($R in @($I.AuditRows)){$ImportRows.Add([PSCustomObject][ordered]@{sample_id=$C.sample_id;replicate_id=$C.replicate_id;case_id=$C.case_id;case_type=$C.case_type;data_origin=$C.data_origin;source_reference=$C.source_reference;source_file=$C.file_path;original_row_number=$R.OriginalRowNumber;normalized_order=$R.NormalizedOrder;raw_frequency=$R.RawFrequency;raw_z_real=$R.RawZReal;raw_z_imag=$R.RawZImag;frequency_Hz=NumberOrBlank([double]$R.FrequencyHz);z_real_ohm=NumberOrBlank([double]$R.ZRealOhm);z_imag_ohm=NumberOrBlank([double]$R.ZImagOhm);duplicate_frequency=$R.DuplicateFrequency.ToString().ToUpperInvariant();high_frequency_inductive=$R.HighFrequencyInductive.ToString().ToUpperInvariant();status=$R.ParseStatus;detail=$R.Detail})}
        $D=Get-M03A2HfrEstimate $I FIRST_POINT_DIAGNOSTIC;$Contract=if($C.intercept_method-eq'USER_DEFINED_EQUIVALENT_CIRCUIT'){$C}else{$null};$E=Get-M03A2HfrEstimate $I $C.intercept_method $Contract;$Estimator[$C.case_id]=$E;$HfrRows.Add((New-HfrRow $C $D));$HfrRows.Add((New-HfrRow $C $E))
    }
    Assert-True ($Estimator.C030.Status-eq'BLOCKED_INSUFFICIENT_HIGH_FREQUENCY_COVERAGE') 'far-axis coverage case not blocked';Assert-True (@($HfrRows|Where-Object{$_.method-eq'FIRST_POINT_DIAGNOSTIC'-and$_.method_class-ne'LAB_SCREENING_HEURISTIC'}).Count-eq0) 'first-point class drift';Assert-True (@($HfrRows|Where-Object{$_.method-ne'FIRST_POINT_DIAGNOSTIC'-and$_.selected_point_count-gt0-and[string]::IsNullOrWhiteSpace($_.selected_original_rows)}).Count-eq0) 'selected row trace missing';Add-Log "EIS_IMPORT_AND_HFR_AUDIT|PASS|audit_rows=$($ImportRows.Count)|HFR_rows=$($HfrRows.Count)|far_axis_blocked=1"
    foreach($Id in @('C001','C002','C003')){$C=Case $Manifest $Id;$Rel=[Math]::Abs([double]$Estimator[$Id].EstimateOhm-[double]$C.expected_hfr_ohm)/[double]$C.expected_hfr_ohm;Assert-True ($Rel-le[double]$C.accuracy_threshold_relative) "$Id accuracy"};Add-Log 'HFR_ACCURACY|PASS|declared thresholds'
    Assert-True ($Estimator.C025.Status-eq'SUPPORTED_SYNTHETIC_RANDLES_ONLY'-and$Estimator.C025.InterceptModel-eq'DECLARED_SYNTHETIC_RANDLES_RS') 'equivalent-circuit positive contract';Assert-True ($Estimator.C032.Status-eq'BLOCKED_EQUIVALENT_CIRCUIT_CONTRACT') 'equivalent-circuit incomplete gate';Add-Log 'EQUIVALENT_CIRCUIT_CONTRACT|PASS|supported synthetic Randles only; incomplete blocked'

    $Rep=@();foreach($C in $Manifest|Where-Object fixture_group -in @('AGREE','DISAGREE')){$Rep+=[PSCustomObject]@{sample_id=$C.sample_id;method=$C.intercept_method;replicate_id=$C.replicate_id;case_id=$C.case_id;hfr_ohm=$Estimator[$C.case_id].EstimateOhm}};$Consensus=@(Get-M03A2ReplicateConsensus $Rep);Assert-True ($Consensus.Count-eq2-and@($Consensus|Where-Object sample_id -eq S_DISAGREE)[0].replicate_count-eq3) 'replicate consensus contract';Add-Log 'REPLICATE_CONSENSUS|PASS|individual=5|consensus_rows=2|outlier_retained=1'
    $Components=@{fixture=@{value_ohm=.2;uncertainty_ohm=.002;source='SYNTHETIC_FIXTURE_MEASUREMENT';status='MEASURED'};contact=@{value_ohm=.1;uncertainty_ohm=.002;source='SYNTHETIC_CONTACT_MEASUREMENT';status='MEASURED'};membrane=@{value_ohm=.15;uncertainty_ohm=.002;source='SYNTHETIC_MEMBRANE_MEASUREMENT';status='MEASURED'};other_series=@{value_ohm=.05;uncertainty_ohm=.002;source='SYNTHETIC_OTHER_SERIES_MEASUREMENT';status='MEASURED'}};$Missing=$Components.Clone();$Missing.Remove('other_series')
    $LedgerOk=Get-M03A2ResistanceLedger LEDGER_OK C001 2 .01 $Components;$LedgerNeg=Get-M03A2ResistanceLedger LEDGER_NEG C018 .4 .01 $Components;$LedgerZero=Get-M03A2ResistanceLedger LEDGER_ZERO C026 .5 .01 $Components;$LedgerMissing=Get-M03A2ResistanceLedger LEDGER_MISSING C022 2 .01 $Missing;$Ledgers=@($LedgerOk,$LedgerNeg,$LedgerZero,$LedgerMissing);Assert-True ($LedgerOk.status-eq'PASS'-and$LedgerNeg.status-eq'BLOCKED_NEGATIVE_DEEMBEDDED_RESISTANCE'-and$LedgerZero.status-eq'BLOCKED_NONPOSITIVE_DEEMBEDDED_RESISTANCE'-and$LedgerMissing.status-eq'BLOCKED_MISSING_SERIES_COMPONENT') 'resistance ledger gates';Add-Log 'RESISTANCE_LEDGER_PROVENANCE|PASS|finite value uncertainty source required; missing not zero'
    $Analytic=Get-M03A2AnalyticalUncertainty 2 .01 @(.2,.1,.15,.05) @(.002,.002,.002,.002) .004 .00004 .003025 .00003025;$Means=@{hfr=2.;fixture=.2;contact=.1;membrane=.15;other=.05;thickness=.004;area=.003025};$U=@{hfr=.01;fixture=.002;contact=.002;membrane=.002;other=.002;thickness=.00004;area=.00003025};$Mc=Invoke-M03A2MonteCarlo $Means $U 314159 20000;$Mc2=Invoke-M03A2MonteCarlo $Means $U 314159 20000;Assert-True ((Format-M03A2Number $Mc.mean)-eq(Format-M03A2Number $Mc2.mean)) 'fixed-seed MC repeatability';$BadMeans=$Means.Clone();$BadMeans.hfr=.55;$BadU=$U.Clone();$BadU.hfr=.1;$BadMc=Invoke-M03A2MonteCarlo $BadMeans $BadU 314159 20000;Assert-True ($BadMc.status-eq'FAILED_INPUT_DISTRIBUTION'-and$BadMc.MC_rejected_fraction-gt.01) 'MC rejection gate'
    $R=[double]$LedgerOk.R_electrolyte_ohm;$RU=[double]$LedgerOk.R_electrolyte_uncertainty_ohm;$K=$Analytic.kappa_S_m;$CmpOk=Compare-M03A2Conductivity .90 $K;$CmpBad=Compare-M03A2Conductivity 1.20 $K;$Conductivity=@((New-ConductivityRow COND_OK C001 $R $RU $Analytic $Mc $CmpOk.status '' '0.90000000000000002' (Format-M03A2Number $CmpOk.relative_difference)),(New-ConductivityRow COND_CONFLICT C020 $R $RU $Analytic $Mc $CmpBad.status 'direct and HFR estimates differ by more than 0.10; no truth selected' '1.2' (Format-M03A2Number $CmpBad.relative_difference)),(New-ConductivityRow COND_BAD_MC C021 .05 .1 $null $BadMc $BadMc.status 'rejected fraction exceeds 0.01; rejected draws were not clipped or repaired' '' ''));Add-Log "CONDUCTIVITY_UNCERTAINTY|PASS|MC_accepted=$($Mc.MC_accepted_count)|MC_rejected=$($Mc.MC_rejected_count)|input_distribution_rejected=$($BadMc.MC_rejected_count)"
    $Area=@(Invoke-M03A2AreaAudit @(Import-Csv $AreaConfigPath -Encoding UTF8));Assert-True ($Area.Count-eq18-and@($Area|Where-Object case_id -eq C019|Select-Object -First 1).status-eq'AREA_BASIS_MISMATCH') 'area long-form contract';Add-Log 'AREA_LONG_FORM_AUDIT|PASS|rows=18|six definitions per case|mapping evidence required'
    $Readiness=@([PSCustomObject][ordered]@{item='RUN_STATE';kind='STATE';status=$RunState;evidence='formal synthetic verification only';m03b_ready='FALSE'},[PSCustomObject][ordered]@{item='CALIBRATION_MODE';kind='STATE';status=$CalibrationMode;evidence='no experimental calibration';m03b_ready='FALSE'},[PSCustomObject][ordered]@{item='experimental_EIS_file';kind='EXPERIMENTAL_INPUT';status='MISSING';evidence='C023 file deliberately absent';m03b_ready='FALSE'},[PSCustomObject][ordered]@{item='experimental_source_reference';kind='EXPERIMENTAL_INPUT';status='MISSING';evidence='C023 source_reference absent';m03b_ready='FALSE'},[PSCustomObject][ordered]@{item='instrument_temperature_electrolyte_metadata';kind='EXPERIMENTAL_INPUT';status='MISSING';evidence='C023 critical metadata absent';m03b_ready='FALSE'},[PSCustomObject][ordered]@{item='series_resistance_measurements';kind='EXPERIMENTAL_INPUT';status='MISSING';evidence='ledger sources are synthetic fixtures';m03b_ready='FALSE'},[PSCustomObject][ordered]@{item='area_mapping_measurements';kind='EXPERIMENTAL_INPUT';status='MISSING';evidence='only synthetic mapping audit';m03b_ready='FALSE'},[PSCustomObject][ordered]@{item='direct_conductivity_measurement';kind='EXPERIMENTAL_INPUT';status='MISSING';evidence='synthetic cross-check only';m03b_ready='FALSE'},[PSCustomObject][ordered]@{item='CPE_nonlinear_fit';kind='METHOD_LIMITATION';status='NOT_IMPLEMENTED';evidence='arbitrary CPE nonlinear fitting and identifiability not demonstrated';m03b_ready='FALSE'},[PSCustomObject][ordered]@{item='M03B_READY';kind='TERMINAL_GATE';status='FALSE';evidence='M03A.2 never authorizes M03B';m03b_ready='FALSE'});Assert-True (@($Readiness|Where-Object m03b_ready -ne FALSE).Count-eq0) 'readiness invariant';Add-Log 'EXPERIMENTAL_INCOMPLETE_AND_READINESS_GATE|PASS|C023=EXPERIMENTAL_INPUT_INCOMPLETE|M03B_READY=FALSE'

    $Observed=@{};foreach($C in $Manifest){$Observed[$C.case_id]=if($C.case_id-eq'C023'){'EXPERIMENTAL_INPUT_INCOMPLETE'}else{$Estimator[$C.case_id].Status};switch($C.case_type){'REPLICATE_CONSENSUS_AGREE'{$Observed[$C.case_id]=@($Consensus|Where-Object sample_id -eq S_AGREE)[0].consensus_status};'THREE_REPLICATES_WITH_DISAGREEMENT'{$Observed[$C.case_id]=@($Consensus|Where-Object sample_id -eq S_DISAGREE)[0].consensus_status};'NEGATIVE_DEEMBEDDED_RESISTANCE'{$Observed[$C.case_id]=$LedgerNeg.status};'ZERO_DEEMBEDDED_RESISTANCE'{$Observed[$C.case_id]=$LedgerZero.status};'MISSING_SERIES_COMPONENT'{$Observed[$C.case_id]=$LedgerMissing.status};'AREA_BASIS_CONFLICT'{$Observed[$C.case_id]='AREA_BASIS_MISMATCH'};'CONDUCTIVITY_CONFLICT'{$Observed[$C.case_id]=$CmpBad.status};'FAILED_INPUT_DISTRIBUTION'{$Observed[$C.case_id]=$BadMc.status}}}
    $Regression=@();foreach($C in $Manifest){$E=$Observed[$C.case_id];$Outcome=if($E-eq$C.expected_outcome){'PASS'}else{'FAIL'};$Accuracy='NOT_APPLICABLE';$Rel='';if((-not[string]::IsNullOrWhiteSpace($C.accuracy_threshold_relative))-and(Test-M03A2Finite([double]$Estimator[$C.case_id].EstimateOhm))){$Rel=[Math]::Abs([double]$Estimator[$C.case_id].EstimateOhm-[double]$C.expected_hfr_ohm)/[Math]::Max([Math]::Abs([double]$C.expected_hfr_ohm),1e-30);$Accuracy=if($Rel-le[double]$C.accuracy_threshold_relative){'PASS'}else{'FAIL'}};$Retention=if($C.data_origin-eq'EXPERIMENTAL'){'NOT_APPLICABLE_NO_FILE'}elseif($Imports[$C.case_id].AuditRows.Count-eq$Imports[$C.case_id].OriginalRowCount){'PASS'}else{'FAIL'};$ExpectedMissingProvenance=$C.case_id-eq'C032'-and$C.expected_outcome-eq'BLOCKED_EQUIVALENT_CIRCUIT_CONTRACT';$Provenance=if($C.data_origin-eq'EXPERIMENTAL'-or$ExpectedMissingProvenance){'EXPECTED_INCOMPLETE_PROVENANCE'}elseif(-not[string]::IsNullOrWhiteSpace($C.source_reference)){'PASS'}else{'FAIL'};$BlockCheck=if($C.expected_outcome-like'BLOCKED_*'-or$C.expected_outcome-eq'EXPERIMENTAL_INPUT_INCOMPLETE'-or$C.expected_outcome-eq'FAILED_INPUT_DISTRIBUTION'-or$C.expected_outcome-eq'AREA_BASIS_MISMATCH'){$Outcome}else{'NOT_APPLICABLE'};$Final=if($Outcome-eq'PASS'-and$Accuracy-ne'FAIL'-and$Retention-ne'FAIL'-and$Provenance-ne'FAIL'){'PASS'}else{'FAIL'};$Regression+=[PSCustomObject][ordered]@{sample_id=$C.sample_id;case_id=$C.case_id;case_type=$C.case_type;data_origin=$C.data_origin;predeclared_expected_outcome=$C.expected_outcome;observed_outcome=$E;accuracy_threshold_relative=$C.accuracy_threshold_relative;observed_relative_error=if($Rel-ne''){Format-M03A2Number $Rel}else{''};expected_outcome_check=$Outcome;accuracy_check=$Accuracy;blocking_check=$BlockCheck;data_retention_check=$Retention;source_provenance_check=$Provenance;status=$Final;run_state=$RunState;calibration_mode=$CalibrationMode;m03b_ready=$M03BReady}}
    $RegressionFailures=@($Regression|Where-Object status -ne PASS)
    Assert-True ($RegressionFailures.Count-eq0) ("scientific regression mismatch: "+(($RegressionFailures|ForEach-Object{"$($_.case_id) expected=$($_.predeclared_expected_outcome) observed=$($_.observed_outcome) accuracy=$($_.accuracy_check) retention=$($_.data_retention_check) provenance=$($_.source_provenance_check)"})-join'; '))
    Add-Log "SCIENTIFIC_REGRESSION|PASS|cases=$($Regression.Count)|predeclared expectations unchanged"

    Write-M03A2Utf8NoBomCsv @($ImportRows|ForEach-Object{$_}) $ImportCsv;Write-M03A2Utf8NoBomCsv @($HfrRows|ForEach-Object{$_}) $HfrCsv;Write-M03A2Utf8NoBomCsv $Consensus $ConsensusCsv;Write-M03A2Utf8NoBomCsv $Ledgers $LedgerCsv;Write-M03A2Utf8NoBomCsv $Conductivity $ConductivityCsv;Write-M03A2Utf8NoBomCsv $Area $AreaCsv;Write-M03A2Utf8NoBomCsv $Readiness $ReadinessCsv;Write-M03A2Utf8NoBomCsv $Regression $RegressionCsv
    New-M03A2Plot NYQUIST @($Imports.C006.Rows) $NyquistPng;New-M03A2Plot HFR_RECOVERY @('C001','C002','C003'|ForEach-Object{[PSCustomObject]@{label=$_;value=$Estimator[$_].EstimateOhm}}) $HfrPng;New-M03A2Plot REPLICATES @($Rep|ForEach-Object{[PSCustomObject]@{label=$_.case_id;value=$_.hfr_ohm}}) $ReplicatePng;New-M03A2Plot LEDGER @([PSCustomObject]@{label='total';value=2},[PSCustomObject]@{label='non-electrolyte';value=.5},[PSCustomObject]@{label='electrolyte';value=1.5}) $LedgerPng;foreach($P in @($NyquistPng,$HfrPng,$ReplicatePng,$LedgerPng)){Test-Png $P};Add-Log 'PNG_SIGNATURE_AUDIT|PASS|4'
    $Contracts=[ordered]@{$ImportCsv=@('sample_id','case_id','data_origin','original_row_number','status');$HfrCsv=@('sample_id','replicate_id','case_id','method','method_class','HFR_ohm','HFR_uncertainty_ohm','selected_point_count','selected_original_rows','frequency_min_Hz','frequency_max_Hz','intercept_model','residual_metric','high_frequency_coverage_status','inductive_artifact_status','duplicate_frequency_status','fit_quality_status','status','failure_reason','source_file');$ConsensusCsv=@('sample_id','method','replicate_count','valid_replicate_count','mean_HFR_ohm','median_HFR_ohm','standard_deviation_ohm','coefficient_of_variation','minimum_HFR_ohm','maximum_HFR_ohm','relative_range','consensus_status','failure_reason');$LedgerCsv=@('sample_id','case_id','EIS_HFR_total_ohm','EIS_HFR_uncertainty_ohm','fixture_resistance_ohm','fixture_uncertainty_ohm','fixture_source','fixture_status','contact_resistance_ohm','contact_uncertainty_ohm','contact_source','contact_status','membrane_resistance_ohm','membrane_uncertainty_ohm','membrane_source','membrane_status','other_series_resistance_ohm','other_series_uncertainty_ohm','other_series_source','other_series_status','R_non_electrolyte_ohm','R_electrolyte_ohm','R_electrolyte_uncertainty_ohm','status','failure_reason');$ConductivityCsv=@('sample_id','case_id','Hcell_m','Hcell_definition','Hcell_uncertainty_m','EIS_area_m2','EIS_area_definition','EIS_area_uncertainty_m2','R_electrolyte_ohm','R_electrolyte_uncertainty_ohm','kappa_HFR_S_m','kappa_HFR_analytical_uncertainty_S_m','kappa_HFR_MC_mean_S_m','kappa_HFR_MC_std_S_m','MC_seed','MC_sample_count','MC_accepted_count','MC_rejected_count','MC_rejected_fraction','independence_assumption','status','failure_reason');$AreaCsv=@('sample_id','case_id','area_name','value_m2','uncertainty_m2','status','source_type','source_reference','definition','measurement_method','mapping_reference','notes');$ReadinessCsv=@('item','kind','status','evidence','m03b_ready');$RegressionCsv=@('case_id','predeclared_expected_outcome','observed_outcome','data_retention_check','source_provenance_check','status')}
    foreach($Entry in $Contracts.GetEnumerator()){$Rows=@(Import-Csv $Entry.Key -Encoding UTF8);Assert-True ($Rows.Count-gt0) "empty CSV: $($Entry.Key)";foreach($F in $Entry.Value){Assert-True ($Rows[0].PSObject.Properties.Name-contains$F) "CSV field missing $F"};Test-Utf8NoBom $Entry.Key;Add-Log "CSV_SCHEMA_ROW_AUDIT|PASS|$([IO.Path]::GetFileName($Entry.Key))|rows=$($Rows.Count)|fields=$(@($Rows[0].PSObject.Properties).Count)"}
    foreach($P in @($ManifestPath,$AreaConfigPath,$DictionaryPath,$ModulePath,$TestPath,$MyInvocation.MyCommand.Path)){Test-Utf8NoBom $P};foreach($C in $Synthetic){Test-Utf8NoBom(Join-Path $ProjectRoot (($C.file_path).Replace('/','\')))};Add-Log 'UTF8_NO_BOM|PASS|inputs,fixtures,outputs'
    $After=@(Get-Frozen $FrozenPaths);Write-M03A2Utf8NoBomCsv $After $FrozenAfterPath;Assert-True ($Before.Count-eq$After.Count) 'frozen count changed';for($I=0;$I-lt$Before.Count;$I++){Assert-True ($Before[$I].path-eq$After[$I].path-and$Before[$I].sha256-eq$After[$I].sha256) "frozen SHA changed: $($Before[$I].path)"};Add-Log 'FROZEN_SHA256_AFTER|PASS|unchanged'
    $DecisionText=[IO.File]::ReadAllText((Join-Path $ProjectRoot 'docs\DECISIONS.md'),[Text.Encoding]::UTF8);$Title='## D0013 '+[char]0x2014+' M03A.2 synthetic EIS and calibration-input verification';Assert-True (@(($DecisionText-replace"`r`n","`n")-split"`n"|Where-Object{$_-ceq$Title}).Count-eq1) 'D0013 count/title';$DecisionDiff=@(& git -C $ProjectRoot --no-pager diff --unified=0 -- docs/DECISIONS.md);Assert-True (@($DecisionDiff|Where-Object{$_-like'-*'-and$_-notlike'---*'}).Count-eq0) 'D0001-D0012 changed or removed';Add-Log 'DECISIONS_AUDIT|PASS|D0001-D0012 unchanged|D0013 exactly one'
    $Tmp=@(Get-ChildItem $ProjectRoot -Recurse -File -Force|Where-Object{$_.Name-like'*.tmp'-or$_.Name-like'*.temp'-or$_.Name-like'~*'});Assert-True ($Tmp.Count-eq0) 'temporary files remain';Add-Log 'TEMPORARY_FILE_AUDIT|PASS|0'
    $ChineseError=([string][char]38169)+([char]35823);$ChineseFailure=([string][char]20986)+([char]38169);$ChineseWarning=([string][char]35686)+([char]21578)
    $Fatal='(^|[^A-Z_])(error|exception|undefined|singular|out of memory)([^A-Z_]|$)|'+$ChineseError+'|'+$ChineseFailure;$Warn='(^|[^A-Z_])(warning)([^A-Z_]|$)|'+$ChineseWarning;$FatalHits=@(Select-String -LiteralPath $TestOut,$TestErr -Pattern $Fatal -CaseSensitive:$false);$WarningHits=@(Select-String -LiteralPath $TestOut,$TestErr -Pattern $Warn -CaseSensitive:$false);Assert-True ($FatalHits.Count-eq0) 'fatal runtime signature';Add-Log "FATAL_WARNING_CLASSIFICATION|PASS|fatal=$($FatalHits.Count)|runtime_warning=$($WarningHits.Count)|scientific_warning_rows=$(@($Regression|Where-Object observed_outcome -like 'WARNING_*').Count)"
    & git -C $ProjectRoot diff --check;Assert-True ($LASTEXITCODE-eq0) 'git diff --check';$Status=@(& git -C $ProjectRoot status --short);$Stat=@(& git -C $ProjectRoot --no-pager diff --stat);Add-Log 'GIT_DIFF_CHECK|PASS';[void]$Log.AppendLine('===== git status --short =====');foreach($L in $Status){[void]$Log.AppendLine($L)};[void]$Log.AppendLine('===== git diff --stat =====');foreach($L in $Stat){[void]$Log.AppendLine($L)}
    $OriginText=(@($Manifest|Group-Object data_origin)|ForEach-Object{"$($_.Name)=$($_.Count)"})-join', ';$MethodText=(@($HfrRows|Group-Object method)|ForEach-Object{"$($_.Name)=$($_.Count)"})-join', ';$Selected=@($HfrRows|Where-Object{$_.method-ne'FIRST_POINT_DIAGNOSTIC'-and$_.selected_point_count-gt0});$EcPass=@($HfrRows|Where-Object status -eq SUPPORTED_SYNTHETIC_RANDLES_ONLY).Count;$EcBlocked=@($HfrRows|Where-Object status -eq BLOCKED_EQUIVALENT_CIRCUIT_CONTRACT).Count
    $Report=@"
# M03A.2 Formal Synthetic EIS Contract Verification

- Run: ``$RunStamp``
- Result: **PASS - synthetic verification only**
- Manifest cases: ``$($Manifest.Count)``; data origins: $OriginText.
- Synthetic fixture count: ``$($Synthetic.Count)``; ``EXPERIMENTAL_INPUT_INCOMPLETE`` count: ``1``.
- HFR method counts: $MethodText.
- Selected-row/range audit: ``$($Selected.Count)`` estimator rows have explicit original-row lists and frequency ranges; full-arc fit rows are not mislabeled as high-frequency candidates.
- Equivalent-circuit contract: supported synthetic Randles ``$EcPass``; incomplete contracts blocked ``$EcBlocked``; declared ``Rs`` is read from the fit contract, never substituted by the first point.
- Resistance source completeness: one complete provenance row; missing, negative, and zero de-embedded regressions remain blocked.
- Area long-form audit: ``$($Area.Count)`` rows, six independent definitions per sample/case; mapping requires reference, formula, source, and uncertainty.
- Monte Carlo: accepted ``$($Mc.MC_accepted_count)``, rejected ``$($Mc.MC_rejected_count)``; failed-distribution regression rejected ``$($BadMc.MC_rejected_count)`` of ``$($BadMc.MC_sample_count)`` without clipping or repair.
- CPE case: ``METHOD_DEPENDENT_PROVISIONAL``. Arbitrary CPE nonlinear fitting is not implemented; the estimate depends on method choice and does not demonstrate experimental CPE parameter identifiability.

## Current experimental input gaps

- C023 has no experimental EIS file, source reference, temperature, electrolyte composition, water content, instrument, measurement date, or EIS area evidence.
- No experimental fixture/contact/membrane/other-series resistance values with uncertainties and provenance are supplied.
- No experimental area mapping, spacing measurement, direct conductivity measurement, or arbitrary-CPE fit-quality evidence is supplied.

M03A.2 passing means synthetic EIS and calibration-input verification only.
It is not experimental calibration.
It does not authorize M03B.

RUN_STATE = SYNTHETIC_SMOKE_TEST
CALIBRATION_MODE = PROVISIONAL
M03B_READY = FALSE
"@
    Write-M03A2Utf8NoBomText $LatestReport $Report;Copy-Item $LatestReport $RunReport -Force;foreach($P in @($ImportCsv,$HfrCsv,$ConsensusCsv,$LedgerCsv,$ConductivityCsv,$AreaCsv,$ReadinessCsv,$RegressionCsv,$NyquistPng,$HfrPng,$ReplicatePng,$LedgerPng)){Assert-True ((Test-Path $P)-and(Get-Item $P).Length-gt0) "artifact missing: $P";Copy-Item $P $RunDir -Force}
    Add-Log 'SUCCESS|M03A.2 formal synthetic EIS contract complete|RUN_STATE=SYNTHETIC_SMOKE_TEST|CALIBRATION_MODE=PROVISIONAL|M03B_READY=FALSE';Write-M03A2Utf8NoBomText $RunLog $Log.ToString();Copy-Item $RunLog $LatestLog -Force;Test-Utf8NoBom $LatestReport;Test-Utf8NoBom $LatestLog
    Write-Output 'SUCCESS|M03A.2 formal synthetic EIS contract complete|RUN_STATE=SYNTHETIC_SMOKE_TEST|CALIBRATION_MODE=PROVISIONAL|M03B_READY=FALSE'
}catch{Add-Log "FATAL|$($_.Exception.Message)";Write-M03A2Utf8NoBomText $RunLog $Log.ToString();Copy-Item $RunLog $LatestLog -Force;throw}
