Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$Invariant=[Globalization.CultureInfo]::InvariantCulture
$ProjectRoot=(Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path
$BaselineCommit='9a20c3486d7c832ef23f87e7fd1b1d6e1f7674f8'
$env:GIT_PAGER='cat'
$env:LINRR_PROJECT_ROOT=$ProjectRoot
$ProcessPath=[Environment]::GetEnvironmentVariable('Path',[EnvironmentVariableTarget]::Process)
[Environment]::SetEnvironmentVariable('PATH',$null,[EnvironmentVariableTarget]::Process)
[Environment]::SetEnvironmentVariable('Path',$ProcessPath,[EnvironmentVariableTarget]::Process)
$HostTemp=[IO.Path]::GetTempPath()

function Write-Text([string]$Path,[string]$Text){[IO.File]::WriteAllText($Path,$Text,[Text.UTF8Encoding]::new($false))}
function Export-CsvNoBom([object[]]$Rows,[string]$Path){if(@($Rows).Count-eq0){throw "Empty CSV: $Path"};Write-Text $Path (((@($Rows)|ConvertTo-Csv -NoTypeInformation)-join"`r`n")+"`r`n")}
function Number($Value){return [double]::Parse([string]$Value,[Globalization.NumberStyles]::Float,$Invariant)}
function Fmt([double]$Value){return $Value.ToString('G17',$Invariant)}
function Hash-Text([string]$Text){$H=[Security.Cryptography.SHA256]::Create();try{$B=[Text.Encoding]::UTF8.GetBytes($Text);return (($H.ComputeHash($B)|ForEach-Object{$_.ToString('x2')})-join'')}finally{$H.Dispose()}}
function Normalize-RepositoryPath([string]$Path){return ([IO.Path]::GetFullPath($Path).TrimEnd([char[]]'\/')).Replace('/','\')}
function Invoke-Captured([string]$File,[string[]]$Arguments,[string]$Stdout,[string]$Stderr){$P=Start-Process -FilePath $File -ArgumentList $Arguments -NoNewWindow -Wait -PassThru -RedirectStandardOutput $Stdout -RedirectStandardError $Stderr;return $P.ExitCode}
function Convert-PipeRows([string[]]$Lines,[string]$Prefix){if($Lines.Count-lt2){throw "Missing $Prefix rows"};$HeaderLine=$Lines[0];$H=@(($HeaderLine-split'\|')|Select-Object -Skip 1);$Out=foreach($L in $Lines|Select-Object -Skip 1){if($L-eq$HeaderLine){continue};$V=@(($L-split'\|')|Select-Object -Skip 1);if($V.Count-ne$H.Count){throw "Malformed $Prefix row"};$D=[ordered]@{};for($i=0;$i-lt$H.Count;$i++){$D[$H[$i]]=$V[$i]};[pscustomobject]$D};return @($Out)}
function Assert-NoBom([string]$Path){$B=[IO.File]::ReadAllBytes($Path);if($B.Length-ge3-and$B[0]-eq0xef-and$B[1]-eq0xbb-and$B[2]-eq0xbf){throw "BOM found: $Path"};[void][Text.UTF8Encoding]::new($false,$true).GetString($B)}
function Assert-Ascii([string]$Path){foreach($B in [IO.File]::ReadAllBytes($Path)){if($B-gt127){throw "Non-ASCII byte in canonical artifact: $Path"}}}
function Test-Png([string]$Path){$B=[IO.File]::ReadAllBytes($Path);$S=[byte[]](137,80,78,71,13,10,26,10);if($B.Length-le100){throw "PNG empty: $Path"};for($i=0;$i-lt8;$i++){if($B[$i]-ne$S[$i]){throw "PNG signature failed: $Path"}}}
function New-AuditPng([string]$Title,[string[]]$Lines,[string]$Path){Add-Type -AssemblyName System.Drawing;$B=[Drawing.Bitmap]::new(1100,650);$G=[Drawing.Graphics]::FromImage($B);$T=[Drawing.Font]::new('Arial',[single]18,[Drawing.FontStyle]::Bold);$F=[Drawing.Font]::new('Arial',[single]11);try{$G.Clear([Drawing.Color]::White);$G.DrawString($Title,$T,[Drawing.Brushes]::DarkBlue,45,30);for($i=0;$i-lt$Lines.Count;$i++){$y=100+48*$i;$G.FillEllipse([Drawing.Brushes]::DarkCyan,65,$y,12,12);$G.DrawString($Lines[$i],$F,[Drawing.Brushes]::Black,95,$y-4)};$B.Save($Path,[Drawing.Imaging.ImageFormat]::Png)}finally{$T.Dispose();$F.Dispose();$G.Dispose();$B.Dispose()}}
function New-ResolvedRow([string]$Sample,[string]$Quantity,[string]$Target,[double]$Value,[double]$Uncertainty,[string]$Unit,[string]$Evidence,[string]$Method,[string]$Table,[string]$Rows,[string]$Reference,[string]$Hash){if($Value-le0-or$Uncertainty-lt0){throw "Invalid resolved value: $Sample/$Quantity"};return [pscustomobject][ordered]@{sample_id=$Sample;quantity_name=$Quantity;target_parameter=$Target;value_SI=Fmt $Value;uncertainty_SI=Fmt $Uncertainty;unit=$Unit;data_origin='SYNTHETIC';evidence_status=$Evidence;resolution_method=$Method;source_table=$Table;source_rows=$Rows;source_reference=$Reference;source_sha256=$Hash;status='PASS';failure_reason=''}}
function Copy-Superseded([string]$Source,[string]$Relative,[string]$Root){if(Test-Path -LiteralPath $Source -PathType Leaf){$Dest=Join-Path $Root $Relative;$Parent=Split-Path -Parent $Dest;if(-not(Test-Path $Parent)){New-Item -ItemType Directory -Path $Parent|Out-Null};Copy-Item -LiteralPath $Source -Destination $Dest}}
function Add-RunId([object[]]$Rows,[string]$RunId){return @($Rows|ForEach-Object{$D=[ordered]@{run_id=$RunId};foreach($P in $_.PSObject.Properties){$D[$P.Name]=$P.Value};[pscustomobject]$D})}
function Get-ArtifactRole([string]$Relative){if($Relative-like'tables/*'){return 'TABLE'}elseif($Relative-like'figures/*'){return 'FIGURE'}elseif($Relative-like'models/*'){return 'DERIVATIVE_MPH'}elseif($Relative-like'reports/*'){return 'REPORT'}else{return 'OTHER'}}
function Get-SourceStage([string]$Relative){if($Relative-like'models/*'){return 'COMSOL_DERIVATIVE_SAVE'}elseif($Relative-like'tables/M03A_4_reload_audit.csv'){return 'INDEPENDENT_COMSOL_RELOAD'}elseif($Relative-like'tables/M03A_4_case_results.csv'-or$Relative-like'tables/M03A_4_coupled_closure.csv'-or$Relative-like'tables/M03A_4_parameter_response.csv'-or$Relative-like'tables/M03A_4_parameter_transfer.csv'){return 'COMSOL_FULL_SOLVE'}elseif($Relative-like'figures/*'){return 'POSTPROCESS_VISUAL_AUDIT'}elseif($Relative-like'reports/*'){return 'REPORTING'}else{return 'POWERSHELL_VERIFICATION'}}
function New-ReleaseManifest([string]$Bundle,[string]$RunId,[string]$ManifestPath){$Files=@(Get-ChildItem -LiteralPath $Bundle -Recurse -File|Where-Object{$_.FullName-ne$ManifestPath}|Sort-Object FullName);if($Files.Count-eq0){throw 'Release bundle is empty'};$Rows=@($Files|ForEach-Object{$Relative=$_.FullName.Substring($Bundle.Length+1).Replace('\','/');[pscustomobject][ordered]@{run_id=$RunId;relative_path=$Relative;size_bytes=$_.Length;sha256=(Get-FileHash -Algorithm SHA256 -LiteralPath $_.FullName).Hash.ToLowerInvariant();artifact_role=Get-ArtifactRole $Relative;source_stage=Get-SourceStage $Relative;validation_status='PASS'}});Export-CsvNoBom $Rows $ManifestPath;return $Rows}
function Assert-ReleaseManifest([string]$Bundle,[string]$ManifestPath,[string]$RunId){$Rows=@(Import-Csv -LiteralPath $ManifestPath -Encoding UTF8);$Files=@(Get-ChildItem -LiteralPath $Bundle -Recurse -File|Where-Object{$_.FullName-ne$ManifestPath});if($Rows.Count-ne$Files.Count){throw 'Release manifest coverage mismatch'};foreach($R in $Rows){if($R.run_id-ne$RunId-or$R.validation_status-ne'PASS'){throw "Release manifest status/run mismatch: $($R.relative_path)"};$P=Join-Path $Bundle $R.relative_path.Replace('/','\');if(-not(Test-Path -LiteralPath $P -PathType Leaf)){throw "Release manifest file missing: $($R.relative_path)"};if([long]$R.size_bytes-ne(Get-Item -LiteralPath $P).Length-or$R.sha256-ne(Get-FileHash -Algorithm SHA256 -LiteralPath $P).Hash.ToLowerInvariant()){throw "Release manifest hash audit failed: $($R.relative_path)"}}}
function Write-AtomicPointer([object]$Pointer,[string]$Path,[string]$BackupPath){$Parent=Split-Path -Parent $Path;if(-not(Test-Path $Parent)){New-Item -ItemType Directory -Path $Parent|Out-Null};$Temp=Join-Path $Parent ('.M03A_4_ACTIVE_RELEASE.'+[guid]::NewGuid().ToString('N')+'.tmp');Write-Text $Temp (($Pointer|ConvertTo-Json -Depth 4)+"`r`n");if(Test-Path -LiteralPath $Path -PathType Leaf){[IO.File]::Replace($Temp,$Path,$BackupPath,$true)}else{Move-Item -LiteralPath $Temp -Destination $Path}}
function Invoke-CompatibilityTransaction([object[]]$Pairs,[string]$BackupRoot,[string]$RollbackRoot,[int]$FailureAfter=0){foreach($D in @($BackupRoot,$RollbackRoot)){if(-not(Test-Path $D)){New-Item -ItemType Directory -Path $D|Out-Null}};foreach($Pair in $Pairs){$Dest=[string]$Pair.Destination;$Relative=[string]$Pair.Relative;if(Test-Path -LiteralPath $Dest -PathType Leaf){$B=Join-Path $BackupRoot $Relative;$BP=Split-Path -Parent $B;if(-not(Test-Path $BP)){New-Item -ItemType Directory -Path $BP|Out-Null};Copy-Item -LiteralPath $Dest -Destination $B -Force}};$Index=0;try{foreach($Pair in $Pairs){$Index++;$Dest=[string]$Pair.Destination;$Parent=Split-Path -Parent $Dest;if(-not(Test-Path $Parent)){New-Item -ItemType Directory -Path $Parent|Out-Null};Copy-Item -LiteralPath $Pair.Source -Destination $Dest -Force;if($FailureAfter-gt0-and$Index-eq$FailureAfter){throw "INJECTED_COMPATIBILITY_COPY_FAILURE_AFTER_$Index"}};return 'PASS'}catch{foreach($Pair in $Pairs){$Dest=[string]$Pair.Destination;$Relative=[string]$Pair.Relative;$B=Join-Path $BackupRoot $Relative;if(Test-Path -LiteralPath $B -PathType Leaf){Copy-Item -LiteralPath $B -Destination $Dest -Force}elseif(Test-Path -LiteralPath $Dest -PathType Leaf){$Q=Join-Path $RollbackRoot $Relative;$QP=Split-Path -Parent $Q;if(-not(Test-Path $QP)){New-Item -ItemType Directory -Path $QP|Out-Null};Move-Item -LiteralPath $Dest -Destination $Q -Force}};throw}
}

$GitRootOutput=@(&git -C $ProjectRoot rev-parse --show-toplevel);if($LASTEXITCODE-ne0-or$GitRootOutput.Count-ne1){throw 'Unable to resolve repository root'}
$GitRoot=Normalize-RepositoryPath ([string]$GitRootOutput[0]);$NormalizedProjectRoot=Normalize-RepositoryPath $ProjectRoot;if(-not([string]::Equals($GitRoot,$NormalizedProjectRoot,[StringComparison]::OrdinalIgnoreCase))){throw "Git root mismatch: $GitRoot != $NormalizedProjectRoot"}
&git -C $ProjectRoot cat-file -e "${BaselineCommit}^{commit}";if($LASTEXITCODE-ne0){throw "Baseline commit missing: $BaselineCommit"}
&git -C $ProjectRoot merge-base --is-ancestor $BaselineCommit HEAD;if($LASTEXITCODE-ne0){throw "Baseline is not an ancestor of HEAD: $BaselineCommit"}
$CurrentBranch=&git -C $ProjectRoot branch --show-current;if($LASTEXITCODE-ne0){throw 'Unable to read current branch'};if([string]::IsNullOrWhiteSpace($CurrentBranch)){$CurrentBranch='DETACHED_HEAD'};Write-Output "REPOSITORY_CONTEXT|ROOT=$GitRoot|BRANCH=$CurrentBranch|BASELINE=$BaselineCommit|BASELINE_IS_ANCESTOR=TRUE"
$StatusBefore=@(git -C $ProjectRoot status --short --untracked-files=all)
$Unexpected=@($StatusBefore|Where-Object{$Path=$_.Substring(3).Replace('\','/');$Path-ne'docs/DECISIONS.md'-and$Path-ne'results/.gitattributes'-and$Path-ne'runs/.gitattributes'-and$Path-notmatch'^(config/M03A_4_|docs/M03A_4_|models/generated/LiNRR_M03A_4_|results/M03A_4_ACTIVE_RELEASE\.json|results/(tables|figures)/M03A_4_|runs/(latest/M03A_4_|[0-9]{8}_[0-9]{6}_M03A_4/release_bundle/)|scripts/windows/17_verify_M03A_4_|scripts/windows/modules/LiNRR_M03A4_|src/java/LiNRR_M03A_4_|tests/(fixtures/M03A_4|java/LiNRR_M03A_4_|powershell/Test_M03A_4_))'})
if($Unexpected.Count){throw "Unexpected pre-run changes: $Unexpected"}
$Tokens=$null;$Errors=$null;[void][Management.Automation.Language.Parser]::ParseFile($PSCommandPath,[ref]$Tokens,[ref]$Errors);if(@($Errors).Count){throw "Driver parser errors: $($Errors.Message -join '; ')"}

$Stamp=Get-Date -Format 'yyyyMMdd_HHmmss'
$RunDir=Join-Path $ProjectRoot ("runs\{0}_M03A_4"-f$Stamp)
$Stage=Join-Path $RunDir 'artifact_staging';$SourceStage=Join-Path $RunDir 'java_source_stage';$ClassOut=Join-Path $RunDir 'java_class_output';$PrefsEvidence=Join-Path $RunDir 'comsol_preferences';$TmpEvidence=Join-Path $RunDir 'comsol_temporary';$Superseded=Join-Path $RunDir 'superseded_previous_artifacts';$ReleaseBundle=Join-Path $RunDir 'release_bundle';$ReleaseTables=Join-Path $ReleaseBundle 'tables';$ReleaseFigures=Join-Path $ReleaseBundle 'figures';$ReleaseModels=Join-Path $ReleaseBundle 'models';$ReleaseReports=Join-Path $ReleaseBundle 'reports';$ReleaseManifestDir=Join-Path $ReleaseBundle 'manifest';$ExecutionRoot=Join-Path $HostTemp ("LiNRRM034"+$Stamp.Replace('_',''));$Prefs=Join-Path $ExecutionRoot 'prefs';$Tmp=Join-Path $ExecutionRoot 'tmp';$RecoveryDir=Join-Path $ExecutionRoot 'recovery'
foreach($D in @($RunDir,$Stage,$SourceStage,$ClassOut,$PrefsEvidence,$TmpEvidence,$Superseded,$ReleaseBundle,$ReleaseTables,$ReleaseFigures,$ReleaseModels,$ReleaseReports,$ReleaseManifestDir,$ExecutionRoot,$Prefs,$Tmp,$RecoveryDir)){New-Item -ItemType Directory -Path $D|Out-Null}
$env:TEMP=$Tmp;$env:TMP=$Tmp

$BaselineTree=Join-Path $RunDir 'baseline_tree';New-Item -ItemType Directory $BaselineTree|Out-Null;$Archive=Join-Path $RunDir 'baseline.tar';&git archive --format=tar --output=$Archive $BaselineCommit;if($LASTEXITCODE){throw 'git archive failed'};&tar -xf $Archive -C $BaselineTree;if($LASTEXITCODE){throw 'baseline extract failed'}
$Tracked=@(git ls-tree -r --name-only $BaselineCommit);$Before=@($Tracked|ForEach-Object{[pscustomobject][ordered]@{path=$_;sha256=(Get-FileHash -Algorithm SHA256 -LiteralPath (Join-Path $BaselineTree $_)).Hash.ToLowerInvariant()}});Export-CsvNoBom $Before (Join-Path $RunDir 'frozen_hashes_before.csv')

$FormalCsv=@('M03A_4_resolved_inputs.csv','M03A_4_parent_provenance.csv','M03A_4_eis_import_audit.csv','M03A_4_hfr_estimates.csv','M03A_4_replicate_consensus.csv','M03A_4_resistance_ledger.csv','M03A_4_area_audit.csv','M03A_4_direct_conductivity_audit.csv','M03A_4_conductivity_crosscheck.csv','M03A_4_uncertainty.csv','M03A_4_parameter_mapping_audit.csv','M03A_4_case_results.csv','M03A_4_parameter_transfer.csv','M03A_4_parameter_response.csv','M03A_4_coupled_closure.csv','M03A_4_reload_audit.csv','M03A_4_completeness_gate.csv','M03A_4_synthetic_regression.csv','M03A_4_readiness.csv','M03A_4_attempt_history.csv','M03A_4_runtime_audit.csv')
$FormalPng=@('M03A_4_nyquist_audit.png','M03A_4_resistance_deembedding.png','M03A_4_conductivity_crosscheck.png','M03A_4_parameter_transfer.png')
$OutputMph=Join-Path $ProjectRoot 'models\generated\LiNRR_M03A_4_parameter_transfer_dry_run.mph'
foreach($N in $FormalCsv){Copy-Superseded (Join-Path $ProjectRoot "results\tables\$N") "results\tables\$N" $Superseded}
foreach($N in $FormalPng){Copy-Superseded (Join-Path $ProjectRoot "results\figures\$N") "results\figures\$N" $Superseded}
Copy-Superseded $OutputMph 'models\generated\LiNRR_M03A_4_parameter_transfer_dry_run.mph' $Superseded
Copy-Superseded (Join-Path $ProjectRoot 'runs\latest\M03A_4_report.md') 'runs\latest\M03A_4_report.md' $Superseded
Copy-Superseded (Join-Path $ProjectRoot 'runs\latest\M03A_4_build.log') 'runs\latest\M03A_4_build.log' $Superseded
Copy-Superseded (Join-Path $ProjectRoot 'results\M03A_4_ACTIVE_RELEASE.json') 'results\M03A_4_ACTIVE_RELEASE.json' $Superseded
Copy-Superseded (Join-Path $ProjectRoot 'results\tables\M03A_4_RELEASE_MANIFEST.csv') 'results\tables\M03A_4_RELEASE_MANIFEST.csv' $Superseded

$Module=Join-Path $ProjectRoot 'scripts\windows\modules\LiNRR_M03A4_Calibration.psm1';Import-Module $Module -Force
$PsFiles=@($PSCommandPath,$Module,(Join-Path $ProjectRoot 'tests\powershell\Test_M03A_4_Calibration.ps1'));foreach($F in $PsFiles){$T=$null;$E=$null;[void][Management.Automation.Language.Parser]::ParseFile($F,[ref]$T,[ref]$E);if(@($E).Count){throw "Parser failed: $F"}}
$TestOut=Join-Path $RunDir 'powershell_tests_stdout.log';$TestErr=Join-Path $RunDir 'powershell_tests_stderr.log';$Pwsh=(Get-Command powershell.exe).Source;$Code=Invoke-Captured $Pwsh @('-NoProfile','-ExecutionPolicy','Bypass','-File',(Join-Path $ProjectRoot 'tests\powershell\Test_M03A_4_Calibration.ps1'),'-ProjectRoot',$ProjectRoot) $TestOut $TestErr;if($Code){throw 'PowerShell regression tests failed'};$TestLines=@(Get-Content -Encoding UTF8 $TestOut);if(-not($TestLines-match'^M03A4_TESTS\|PASS\|40 ')){throw 'Missing 40-case preflight test marker'}
$Regression=@($TestLines|Where-Object{$_-like'M03A4_REGRESSION|*'}|ForEach-Object{$V=$_-split'\|',7;[pscustomobject][ordered]@{case_id=$V[1];case_name=$V[2];expected=$V[3];actual=$V[4];status=$V[5];failure_reason=$V[6]}});Export-CsvNoBom $Regression (Join-Path $Stage 'M03A_4_synthetic_regression.csv')

$ManifestPath=Join-Path $ProjectRoot 'config\M03A_4_experimental_manifest.csv';$Manifest=Import-M03A4Manifest $ManifestPath $ProjectRoot;$Audit=New-Object Collections.Generic.List[object];$Hfr=New-Object Collections.Generic.List[object]
foreach($M in $Manifest){if($M.status-ne'PASS'){$Audit.Add([pscustomobject][ordered]@{sample_id=$M.sample_id;replicate_id=$M.replicate_id;case_id=$M.sample_id;source_file=$M.file_path;original_row_number='';raw_frequency='';raw_z_real='';raw_z_imag='';frequency_Hz='';z_real_ohm='';z_imag_ohm='';normalized_order='';duplicate_frequency='';high_frequency_inductive='';parse_status=$M.status;detail=$M.failure_reason});continue};$I=Import-M03A4Eis $M.resolved_file_path $M.sample_id $M.frequency_unit $M.impedance_unit $M.sample_id $M.replicate_id;foreach($R in $I.AuditRows){$Audit.Add([pscustomobject][ordered]@{sample_id=$R.SampleId;replicate_id=$R.ReplicateId;case_id=$R.CaseId;source_file=$R.SourceFile;original_row_number=$R.OriginalRowNumber;raw_frequency=$R.RawFrequency;raw_z_real=$R.RawZReal;raw_z_imag=$R.RawZImag;frequency_Hz=Format-M03A4Number $R.FrequencyHz;z_real_ohm=Format-M03A4Number $R.ZRealOhm;z_imag_ohm=Format-M03A4Number $R.ZImagOhm;normalized_order=$R.NormalizedOrder;duplicate_frequency=$R.DuplicateFrequency;high_frequency_inductive=$R.HighFrequencyInductive;parse_status=$R.ParseStatus;detail=$R.Detail})};$Est=Get-M03A4HfrEstimate $I $M.intercept_method $null;if($Est.Status-ne'PASS'){throw "HFR estimate blocked: $($M.replicate_id)"};$Hfr.Add($Est)}
Export-CsvNoBom @($Audit|ForEach-Object{$_}) (Join-Path $Stage 'M03A_4_eis_import_audit.csv');$HfrRows=@($Hfr|ForEach-Object{$_});Export-CsvNoBom $HfrRows (Join-Path $Stage 'M03A_4_hfr_estimates.csv');$Consensus=@(Get-M03A4ReplicateConsensus $HfrRows);Export-CsvNoBom $Consensus (Join-Path $Stage 'M03A_4_replicate_consensus.csv')
$Selected=@($Consensus|Where-Object{$_.sample_id-eq'SYN_DRY_001'-and$_.consensus_status-eq'PASS'});if($Selected.Count-ne1-or[int]$Selected[0].valid_replicate_count-ne2){throw 'Accepted replicate consensus missing or ambiguous'};$SelectedConsensus=$Selected[0]
$SelectedMethod=[string]$SelectedConsensus.method;if($SelectedMethod-ne'HIGH_FREQUENCY_INTERCEPT'){throw 'Unexpected selected HFR method'}
$SourceEis=@($Manifest|Where-Object{$_.sample_id-eq'SYN_DRY_001'-and$_.status-eq'PASS'}|Sort-Object replicate_id);if($SourceEis.Count-ne2){throw 'Selected replicate set incomplete'}
$EisHashMaterial=($SourceEis|ForEach-Object{"$($_.replicate_id):$((Get-FileHash -Algorithm SHA256 -LiteralPath $_.resolved_file_path).Hash.ToLowerInvariant())"})-join';';$EisCompositeHash=Hash-Text ("$SelectedMethod|$EisHashMaterial")

$LedgerPath=Join-Path $ProjectRoot 'config\M03A_4_resistance_ledger.csv';$LedgerConfig=@(Import-Csv -LiteralPath $LedgerPath -Encoding UTF8);$SyntheticLedger=Get-M03A4ResistanceLedger SYN_DRY_001 $LedgerConfig $SelectedConsensus;$ExperimentalLedger=Get-M03A4ResistanceLedger EXP_TEMPLATE_001 $LedgerConfig $null;$Ledgers=@($SyntheticLedger,$ExperimentalLedger);Export-CsvNoBom $Ledgers (Join-Path $Stage 'M03A_4_resistance_ledger.csv');if($SyntheticLedger.status-ne'PASS'){throw "Synthetic ledger failed: $($SyntheticLedger.failure_reason)"}
$AreaPath=Join-Path $ProjectRoot 'config\M03A_4_area_measurements.csv';$AreaConfig=@(Import-Csv -LiteralPath $AreaPath -Encoding UTF8);$SyntheticArea=@(Invoke-M03A4AreaAudit SYN_DRY_001 $AreaConfig);$ExperimentalArea=@(Invoke-M03A4AreaAudit EXP_TEMPLATE_001 $AreaConfig);$AreaAudit=@($SyntheticArea+$ExperimentalArea);Export-CsvNoBom $AreaAudit (Join-Path $Stage 'M03A_4_area_audit.csv');if(@($SyntheticArea|Where-Object overall_status -ne 'PASS').Count){throw 'Blocking synthetic area/unit/origin audit failed'}
$DirectPath=Join-Path $ProjectRoot 'config\M03A_4_direct_conductivity.csv';$DirectConfig=@(Import-Csv -LiteralPath $DirectPath -Encoding UTF8);$DirectAudit=Test-M03A4DirectConductivity SYN_DRY_001 $DirectConfig;Export-CsvNoBom @($DirectAudit) (Join-Path $Stage 'M03A_4_direct_conductivity_audit.csv')
$MappingPath=Join-Path $ProjectRoot 'config\M03A_4_parameter_mapping.csv';$MappingRows=@(Import-Csv -LiteralPath $MappingPath -Encoding UTF8);$Mapping=Invoke-M03A4ParameterMappingAudit $MappingRows;Export-CsvNoBom $Mapping (Join-Path $Stage 'M03A_4_parameter_mapping_audit.csv');if(@($Mapping|Where-Object status -ne 'PASS').Count){throw 'Parameter mapping whitelist failed'}

$AreaHash=(Get-FileHash -Algorithm SHA256 -LiteralPath $AreaPath).Hash.ToLowerInvariant();$LedgerHash=(Get-FileHash -Algorithm SHA256 -LiteralPath $LedgerPath).Hash.ToLowerInvariant();$DirectHash=(Get-FileHash -Algorithm SHA256 -LiteralPath $DirectPath).Hash.ToLowerInvariant();$TransferPath=Join-Path $ProjectRoot 'config\M03A_4_transfer_cases.csv';$TransferHash=(Get-FileHash -Algorithm SHA256 -LiteralPath $TransferPath).Hash.ToLowerInvariant();$TransferConfig=@(Import-Csv -LiteralPath $TransferPath -Encoding UTF8)
$ExpectedCases=@('IDENTITY_REFERENCE','KAPPA_PERTURBATION','HCELL_PERTURBATION','DEPTH_PERTURBATION','EIS_AREA_PERTURBATION','REPORT_AREA_PERTURBATION','COMBINED_NONIDENTITY');foreach($C in $ExpectedCases){if(@($TransferConfig|Where-Object case_id -ceq $C).Count-ne1){throw "Transfer case missing or duplicate: $C"}}
if($TransferConfig.Count-ne$ExpectedCases.Count){throw 'Unexpected transfer case rows'}
$AreaByName=@{};foreach($R in $AreaConfig|Where-Object sample_id -eq 'SYN_DRY_001'){$AreaByName[$R.quantity_name]=$R}
$RTotal=Number $SyntheticLedger.R_HFR_total_ohm;$RTotalU=Number $SyntheticLedger.R_HFR_total_uncertainty_ohm;$RE=Number $SyntheticLedger.R_electrolyte_ohm;$REU=Number $SyntheticLedger.R_electrolyte_uncertainty_ohm;$Spacing=Number $AreaByName.electrode_spacing.value_SI;$SpacingU=Number $AreaByName.electrode_spacing.uncertainty_SI;$EisArea=Number $AreaByName.EIS_area.value_SI;$EisAreaU=Number $AreaByName.EIS_area.uncertainty_SI;$Kappa=$Spacing/($EisArea*$RE)
$Resolved=New-Object Collections.Generic.List[object]
$ConsensusU=(Number $SelectedConsensus.standard_deviation_ohm)/[Math]::Sqrt((Number $SelectedConsensus.valid_replicate_count));$Resolved.Add((New-ResolvedRow SYN_DRY_001 EIS_HFR_total '' (Number $SelectedConsensus.mean_HFR_ohm) $ConsensusU ohm SYNTHETIC_CONSENSUS_ACCEPTED 'REPLICATE_ARITHMETIC_MEAN_SEM' 'M03A_4_replicate_consensus.csv' 'R1;R2' (($SourceEis.file_path)-join';') $EisCompositeHash))
$LedgerComponents=@('fixture','contact','membrane','other_series');for($i=0;$i-lt$LedgerComponents.Count;$i++){$N=$LedgerComponents[$i];$Row=@($LedgerConfig|Where-Object{$_.sample_id-eq'SYN_DRY_001'-and$_.component_name-eq$N})[0];$Resolved.Add((New-ResolvedRow SYN_DRY_001 $N '' (Number $Row.value_ohm) (Number $Row.uncertainty_ohm) ohm $Row.status 'UNIQUE_VALIDATED_LEDGER_ROW' 'config/M03A_4_resistance_ledger.csv' ([string](3+$i)) $Row.source_reference $LedgerHash))}
$Resolved.Add((New-ResolvedRow SYN_DRY_001 R_electrolyte R_electrolyte_dry_run $RE $REU ohm DERIVED_DEEMBEDDED 'EIS_HFR_TOTAL_MINUS_VALIDATED_SERIES_SUM' 'config/M03A_4_resistance_ledger.csv' '2;3;4;5;6' 'resolved HFR chain and unique series ledger' $LedgerHash))
$AreaTargets=@{electrode_spacing='Hcell_dry_run';out_of_plane_thickness='depth_dry_run';EIS_area='A_EIS_dry_run';current_density_reporting_area='A_j_report_dry_run'};$Line=1;foreach($R in $AreaConfig){$Line++;if($R.sample_id-ne'SYN_DRY_001'){continue};$Target=if($AreaTargets.ContainsKey($R.quantity_name)){$AreaTargets[$R.quantity_name]}else{''};$Resolved.Add((New-ResolvedRow SYN_DRY_001 $R.quantity_name $Target (Number $R.value_SI) (Number $R.uncertainty_SI) $R.unit $R.status 'UNIQUE_VALIDATED_SYNTHETIC_SOURCE_ROW' 'config/M03A_4_area_measurements.csv' ([string]$Line) $R.source_reference $AreaHash))}
$AnalyticBeforeConductivity=Get-M03A4AnalyticalUncertaintyFromResolved @($Resolved|ForEach-Object{$_}) SYN_DRY_001;if((Number $AnalyticBeforeConductivity.conductivity_uncertainty_S_m)-le0){throw 'Resolved conductivity uncertainty must be positive'};if([Math]::Abs((Number $AnalyticBeforeConductivity.conductivity_S_m)-$Kappa)-gt1e-15){throw 'Analytical conductivity does not match resolved inversion'}
$Parent=New-M03A4ParentProvenance @($Resolved|ForEach-Object{$_}) SYN_DRY_001 conductivity;$ParentPath=Join-Path $Stage 'M03A_4_parent_provenance.csv';Export-CsvNoBom @($Parent.Rows) $ParentPath;Assert-NoBom $ParentPath;Assert-Ascii $ParentPath;if(@($Parent.Rows).Count-ne7){throw 'Conductivity parent provenance incomplete'}
$Resolved.Add((New-ResolvedRow SYN_DRY_001 conductivity kappa_dry_run $Kappa (Number $AnalyticBeforeConductivity.conductivity_uncertainty_S_m) 'S/m' DERIVED_HFR_CONDUCTIVITY 'H_OVER_A_EIS_R_ELECTROLYTE' 'results/tables/M03A_4_parent_provenance.csv' '2;3;4;5;6;7;8' ('conductivity_parent_digest_sha256='+$Parent.Digest) $Parent.Digest))
$Resolved.Add((New-ResolvedRow SYN_DRY_001 direct_conductivity '' (Number $DirectAudit.conductivity_S_m) (Number $DirectAudit.uncertainty_S_m) 'S/m' SYNTHETIC_DEFINED 'VALIDATED_DIRECT_CONDUCTIVITY' 'config/M03A_4_direct_conductivity.csv' '2' $DirectAudit.source_reference $DirectHash))
$TransferLine=1;foreach($C in $TransferConfig){$TransferLine++;if($C.data_origin-ne'SYNTHETIC'-or$C.status-ne'SYNTHETIC_DEFINED'-or[string]::IsNullOrWhiteSpace($C.source_reference)){throw "Transfer provenance failed: $($C.case_id)"};$Vals=[ordered]@{conductivity=@($C.conductivity_S_m,'S/m','kappa_dry_run');electrode_spacing=@($C.electrode_spacing_m,'m','Hcell_dry_run');out_of_plane_thickness=@($C.out_of_plane_thickness_m,'m','depth_dry_run');EIS_area=@($C.EIS_area_m2,'m^2','A_EIS_dry_run');current_density_reporting_area=@($C.current_density_reporting_area_m2,'m^2','A_j_report_dry_run')};foreach($N in $Vals.Keys){$V=Number $Vals[$N][0];if($V-le0){throw "Nonpositive transfer value: $($C.case_id)/$N"};$Method=if($N-eq'conductivity'){$C.conductivity_resolution}else{'WHITELIST_IDENTITY_TRANSFER'};$Resolved.Add((New-ResolvedRow $C.case_id $N $Vals[$N][2] $V 0.0 $Vals[$N][1] $C.status $Method 'config/M03A_4_transfer_cases.csv' ([string]$TransferLine) $C.source_reference $TransferHash))}}
$ResolvedPath=Join-Path $Stage 'M03A_4_resolved_inputs.csv';Export-CsvNoBom @($Resolved|ForEach-Object{$_}) $ResolvedPath;Assert-NoBom $ResolvedPath;Assert-Ascii $ResolvedPath;$ResolvedRows=@(Import-Csv -LiteralPath $ResolvedPath -Encoding UTF8);$ResolvedKeys=@{};foreach($R in $ResolvedRows){$Key="$($R.sample_id)|$($R.quantity_name)";if($ResolvedKeys.ContainsKey($Key)){throw "Duplicate resolved key: $Key"};$ResolvedKeys[$Key]=$true};$ResolvedConductivity=@($ResolvedRows|Where-Object{$_.sample_id-eq'SYN_DRY_001'-and$_.quantity_name-eq'conductivity'});if($ResolvedConductivity.Count-ne1-or(Number $ResolvedConductivity[0].uncertainty_SI)-le0){throw 'Resolved conductivity uncertainty audit failed'};if($ResolvedConductivity[0].source_table-ne'results/tables/M03A_4_parent_provenance.csv'-or$ResolvedConductivity[0].source_sha256-ne$Parent.Digest){throw 'Resolved conductivity parent provenance audit failed'}
$Identity=@($TransferConfig|Where-Object case_id -eq 'IDENTITY_REFERENCE')[0];if([Math]::Abs((Number $Identity.conductivity_S_m)-$Kappa)-gt1e-14){throw 'Identity transfer conductivity does not match resolved HFR chain'};if([Math]::Abs((Number $Identity.electrode_spacing_m)-$Spacing)-gt1e-14-or[Math]::Abs((Number $Identity.EIS_area_m2)-$EisArea)-gt1e-14){throw 'Identity geometry/area does not match resolved source'}
$EisCase=@($TransferConfig|Where-Object case_id -eq 'EIS_AREA_PERTURBATION')[0];$EisExpected=$Spacing/((Number $EisCase.EIS_area_m2)*$RE);if([Math]::Abs((Number $EisCase.conductivity_S_m)-$EisExpected)-gt1e-14){throw 'EIS area perturbation did not execute conductivity inversion'}
$Combined=@($TransferConfig|Where-Object case_id -eq 'COMBINED_NONIDENTITY')[0];$CombinedExpected=(Number $Combined.electrode_spacing_m)/((Number $Combined.EIS_area_m2)*$RE);if([Math]::Abs((Number $Combined.conductivity_S_m)-$CombinedExpected)-gt1e-14){throw 'Combined case conductivity inversion mismatch'}
$Analytic=Get-M03A4AnalyticalUncertaintyFromResolved $ResolvedRows SYN_DRY_001;if((Fmt (Number $Analytic.conductivity_uncertainty_S_m))-ne(Fmt (Number $ResolvedConductivity[0].uncertainty_SI))){throw 'Resolved conductivity uncertainty differs from analytical artifact'};$Mc=Invoke-M03A4MonteCarloFromResolved $ResolvedRows SYN_DRY_001 20000 40304;if($Mc.status-ne'PASS'-or$Mc.source_artifact-ne'results/tables/M03A_4_resolved_inputs.csv'){throw 'Synthetic Monte Carlo did not consume resolved artifact'}
$Cross=Compare-M03A4Conductivity (Number $DirectAudit.conductivity_S_m) (Number $DirectAudit.uncertainty_S_m) (Number $Analytic.conductivity_S_m) (Number $Analytic.conductivity_uncertainty_S_m);Export-CsvNoBom @($Cross) (Join-Path $Stage 'M03A_4_conductivity_crosscheck.csv');if($Cross.status-eq'CALIBRATION_CONFLICT'){throw 'Direct and HFR conductivity conflict; no value selected'}
$ResolvedHash=(Get-FileHash -Algorithm SHA256 -LiteralPath $ResolvedPath).Hash.ToLowerInvariant()
$UncertaintyRows=@(@($Analytic,$Mc)|ForEach-Object{$D=[ordered]@{};foreach($P in $_.PSObject.Properties){$D[$P.Name]=$P.Value};$D['source_artifact_sha256']=$ResolvedHash;[pscustomobject]$D});Export-CsvNoBom $UncertaintyRows (Join-Path $Stage 'M03A_4_uncertainty.csv');if(@($UncertaintyRows|Where-Object{$_.source_artifact-ne'results/tables/M03A_4_resolved_inputs.csv'-or$_.source_artifact_sha256-ne$ResolvedHash}).Count){throw 'Uncertainty consumer source audit failed'}

$ComsolRoot=if($env:COMSOL_ROOT){$env:COMSOL_ROOT}else{'F:\COMSOL64\Multiphysics'};$Compiler=Join-Path $ComsolRoot 'bin\win64\comsolcompile.exe';$Batch=Join-Path $ComsolRoot 'bin\win64\comsolbatch.exe';$Java=Join-Path $ComsolRoot 'java\win64\jre\bin\java.exe';$Ecj=Join-Path $ComsolRoot 'plugins\org.eclipse.jdt.core.compiler.batch_3.42.0.v20250526-2018.jar';$Api=Join-Path $ComsolRoot 'plugins\com.comsol.api_1.0.0.jar';$ModelJar=Join-Path $ComsolRoot 'plugins\com.comsol.model_1.0.0.jar';foreach($P in @($Compiler,$Batch,$Java,$Ecj,$Api,$ModelJar)){if(-not(Test-Path $P)){throw "COMSOL path missing: $P"}}
$JavaFiles=@('src\java\LiNRR_M03A_4_Metrics.java','src\java\LiNRR_M03A_4_ParameterTransfer.java','tests\java\LiNRR_M03A_4_LoadCheck.java');foreach($R in $JavaFiles){Copy-Item (Join-Path $ProjectRoot $R) $SourceStage};$StagedMph=Join-Path $Stage 'LiNRR_M03A_4_parameter_transfer_dry_run.mph';$RootJ=$ProjectRoot.Replace('\','\\');$MphJ=$StagedMph.Replace('\','\\');$ResolvedJ=$ResolvedPath.Replace('\','\\');$Bridge="public final class LiNRR_M03A_4_RunInputs { public static String get(String n) { if (`"LINRR_PROJECT_ROOT`".equals(n)) return `"$RootJ`"; if (`"M03A4_OUTPUT_MPH`".equals(n) || `"M03A4_RELOAD_MPH`".equals(n)) return `"$MphJ`"; if (`"M03A4_RESOLVED_INPUTS`".equals(n)) return `"$ResolvedJ`"; if (`"M03A4_RESOLVED_SHA256`".equals(n)) return `"$ResolvedHash`"; return null; } }";$BridgePath=Join-Path $SourceStage 'LiNRR_M03A_4_RunInputs.java';Write-Text $BridgePath $Bridge
$UserPrefs=Join-Path $env:USERPROFILE '.comsol\v64\comsol.prefs';$PrefText=[IO.File]::ReadAllText($UserPrefs)-replace'(?m)^security\.external\.filepermission=limited$','security.external.filepermission=full';$PrefText=$PrefText-replace'(?m)^tempfiles\.recovery\.recoverydir=.*$','tempfiles.recovery.recoverydir=';$PrefText=$PrefText-replace'(?m)^tempfiles\.recovery\.autosave=on$','tempfiles.recovery.autosave=off';$PrefText=$PrefText-replace'(?m)^tempfiles\.recovery\.checkforrecoveries=on$','tempfiles.recovery.checkforrecoveries=off';Write-Text (Join-Path $Prefs 'comsol.prefs') $PrefText
$CompileOut=Join-Path $RunDir 'java_compile_stdout.log';$CompileErr=Join-Path $RunDir 'java_compile_stderr.log';Write-Text $CompileOut '';Write-Text $CompileErr '';$MetricJ=Join-Path $SourceStage 'LiNRR_M03A_4_Metrics.java';$BuilderJ=Join-Path $SourceStage 'LiNRR_M03A_4_ParameterTransfer.java';$LoadJ=Join-Path $SourceStage 'LiNRR_M03A_4_LoadCheck.java';$Steps=@(@('-prefsdir',$Prefs,$MetricJ),@('-prefsdir',$Prefs,'-classpathadd',$SourceStage,$BuilderJ),@('-prefsdir',$Prefs,'-classpathadd',$SourceStage,$LoadJ),@('-prefsdir',$Prefs,$BridgePath));for($i=0;$i-lt$Steps.Count;$i++){$O=Join-Path $RunDir "compile_$i.out";$E=Join-Path $RunDir "compile_$i.err";$Code=Invoke-Captured $Compiler $Steps[$i] $O $E;Write-Text $CompileOut ([IO.File]::ReadAllText($CompileOut)+[IO.File]::ReadAllText($O));Write-Text $CompileErr ([IO.File]::ReadAllText($CompileErr)+[IO.File]::ReadAllText($E));if($Code){throw "comsolcompile failed step $i"}}
$EcjOut=Join-Path $RunDir 'ecj_stdout.log';$EcjErr=Join-Path $RunDir 'ecj_stderr.log';$Sources=@($MetricJ,$BuilderJ,$LoadJ,$BridgePath);$Code=Invoke-Captured $Java (@('-jar',$Ecj,'-source','11','-target','11','-warn:none','-cp',("$Api;$ModelJar"),'-d',$ClassOut)+$Sources) $EcjOut $EcjErr;if($Code){throw 'ECJ compilation failed'}
$BuilderClass=Join-Path $ClassOut 'LiNRR_M03A_4_ParameterTransfer.class';$LoadClass=Join-Path $ClassOut 'LiNRR_M03A_4_LoadCheck.class';$BatchOut=Join-Path $RunDir 'comsol_batch_stdout.log';$BatchErr=Join-Path $RunDir 'comsol_batch_stderr.log';$BatchLog=Join-Path $RunDir 'comsol_batch.log';$SourceMph=Join-Path $ProjectRoot 'models\generated\LiNRR_M03A_3_prescribed_current_coupling.mph';$SourceHashBefore=(Get-FileHash -Algorithm SHA256 $SourceMph).Hash.ToLowerInvariant();$BatchExit=Invoke-Captured $Batch @('-prefsdir',$Prefs,'-autosave','off','-recoverydir',$RecoveryDir,'-tmpdir',$Tmp,'-classpathadd',$ClassOut,'-inputfile',$BuilderClass,'-batchlog',$BatchLog) $BatchOut $BatchErr;$SourceHashAfter=(Get-FileHash -Algorithm SHA256 $SourceMph).Hash.ToLowerInvariant();if($SourceHashBefore-ne$SourceHashAfter){throw 'M03A.3 source MPH changed'}
$Completion=[bool](Select-String -LiteralPath $BatchOut -SimpleMatch -Pattern 'M03A4_PROGRESS|FULL_SYNTHETIC_COUPLED_TRANSFER|COMPLETE' -Quiet);$FatalPattern='(?i)(out of memory|memory allocation|undefined|singular|failed to find|fatal error|lu factorization|error running java class)';$ChineseFatal='错误|失败|内存不足|奇异|未定义|无法|运行 Java 类时出错';$RuntimeCore=([IO.File]::ReadAllText($BatchErr)+"`n"+[IO.File]::ReadAllText($BatchLog));$JavaException=[bool]([regex]::IsMatch($RuntimeCore,'(?i)exception|java\.lang\.|运行 Java 类时出错'));$FatalMatches=@([regex]::Matches($RuntimeCore,$FatalPattern))+@([regex]::Matches($RuntimeCore,$ChineseFatal));$WarningMatches=@([regex]::Matches($RuntimeCore,'(?i)warning'))+@([regex]::Matches($RuntimeCore,'警告'))
$SolverStatus=if($BatchExit-ne0){'FAILED'}elseif($FatalMatches.Count){'FAILED'}elseif(-not$Completion){'MISSING_COMPLETION_MARKER'}elseif(-not(Test-Path $StagedMph -PathType Leaf)){'MISSING_EXPECTED_OUTPUT'}else{'SOLVED'}
if($BatchExit-ne0-or$JavaException-or$FatalMatches.Count-or-not$Completion-or$SolverStatus-ne'SOLVED'){throw "COMSOL runtime acceptance failed: exit=$BatchExit solver=$SolverStatus fatal=$($FatalMatches.Count) exception=$JavaException completion=$Completion"}
$BatchLines=@(Get-Content -Encoding UTF8 $BatchOut);$Cases=@(Convert-PipeRows @($BatchLines|Where-Object{$_-like'M03A4_CASE|*'}) M03A4_CASE);$Transfers=@(Convert-PipeRows @($BatchLines|Where-Object{$_-like'M03A4_TRANSFER|*'}) M03A4_TRANSFER);$Responses=@(Convert-PipeRows @($BatchLines|Where-Object{$_-like'M03A4_RESPONSE|*'}) M03A4_RESPONSE);$Closure=@(Convert-PipeRows @($BatchLines|Where-Object{$_-like'M03A4_CLOSURE|*'}) M03A4_CLOSURE)
if($Cases.Count-ne7-or@($Cases|Where-Object{$_.status-ne'PASS'}).Count){throw 'Seven full-coupled cases did not all pass'};if($Transfers.Count-ne35-or@($Transfers|Where-Object{$_.status-ne'PASS'}).Count){throw 'Five-parameter consumer audit failed'};if(@($Responses|Where-Object{$_.status-ne'PASS'}).Count){throw 'Parameter scaling response failed'};if($Closure.Count-ne1-or$Closure[0].status-ne'SYNTHETIC_PARAMETER_TRANSFER_PASS'){throw 'Actual TDS/Faraday/conservation closure failed'}
Export-CsvNoBom (Add-RunId $Cases $Stamp) (Join-Path $Stage 'M03A_4_case_results.csv');Export-CsvNoBom (Add-RunId $Transfers $Stamp) (Join-Path $Stage 'M03A_4_parameter_transfer.csv');Export-CsvNoBom (Add-RunId $Responses $Stamp) (Join-Path $Stage 'M03A_4_parameter_response.csv');Export-CsvNoBom (Add-RunId $Closure $Stamp) (Join-Path $Stage 'M03A_4_coupled_closure.csv')
$ReloadOut=Join-Path $RunDir 'comsol_reload_stdout.log';$ReloadErr=Join-Path $RunDir 'comsol_reload_stderr.log';$ReloadLog=Join-Path $RunDir 'comsol_reload.log';$ReloadExit=Invoke-Captured $Batch @('-prefsdir',$Prefs,'-autosave','off','-recoverydir',$RecoveryDir,'-tmpdir',$Tmp,'-classpathadd',$ClassOut,'-inputfile',$LoadClass,'-batchlog',$ReloadLog) $ReloadOut $ReloadErr;$ReloadLines=@(Get-Content -Encoding UTF8 $ReloadOut);$ReloadMarker=[bool]($ReloadLines|Where-Object{$_-like'M03A4_RELOAD|PASS|*'});$ReloadConsumers=@($ReloadLines|Where-Object{$_-like'M03A4_RELOAD_CONSUMER|*'});$ReloadParams=@(Convert-PipeRows @($ReloadLines|Where-Object{$_-like'M03A4_RELOAD_PARAM|*'}) M03A4_RELOAD_PARAM);if($ReloadExit-ne0-or-not$ReloadMarker-or$ReloadConsumers.Count-ne5-or$ReloadParams.Count-ne5-or@($ReloadParams|Where-Object{$_.status-ne'PASS'}).Count){throw 'Independent reload exact value/unit/provenance/consumer audit failed'};if(@($ReloadParams|Where-Object{$_.expected_target_parameter-ne$_.stored_target_parameter-or$_.expected_unit-ne$_.stored_unit-or$_.expected_origin-ne$_.stored_origin-or$_.expected_source_sha256-ne$_.stored_source_sha256-or$_.expected_resolved_sha256-ne$_.stored_resolved_sha256-or$_.expected_case_id-ne$_.stored_case_id-or$_.expected_quantity_name-ne$_.stored_quantity_name}).Count){throw 'Independent reload provenance mismatch'};Export-CsvNoBom (Add-RunId $ReloadParams $Stamp) (Join-Path $Stage 'M03A_4_reload_audit.csv')
$ReloadCore=([IO.File]::ReadAllText($ReloadErr)+"`n"+[IO.File]::ReadAllText($ReloadLog));$ReloadFatal=@([regex]::Matches($ReloadCore,$FatalPattern))+@([regex]::Matches($ReloadCore,$ChineseFatal));if($ReloadFatal.Count){throw 'Reload runtime fatal classification failed'}
$ProgressRequired=@('M03A4_PROGRESS|COMBINED_NONIDENTITY|GEOMETRY_REBUILT|PASS','M03A4_PROGRESS|COMBINED_NONIDENTITY|NAMED_SELECTION_AUDIT|PASS','M03A4_PROGRESS|COMBINED_NONIDENTITY|FRESH_FULL_COUPLED_STUDY|PASS','M03A4_PROGRESS|COMBINED_NONIDENTITY|SPF_ACTIVE|PASS','M03A4_PROGRESS|COMBINED_NONIDENTITY|TDS_ACTIVE|PASS','M03A4_PROGRESS|COMBINED_NONIDENTITY|CD_ACTIVE|PASS','M03A4_PROGRESS|COMBINED_NONIDENTITY|CURRENT_SOLUTION_CURRENT_RUN|PASS','M03A4_PROGRESS|COMBINED_NONIDENTITY|SPECIES_SOLUTION_CURRENT_RUN|PASS','M03A4_PROGRESS|DERIVATIVE_MPH_SAVE|COMPLETE');$ProgressPass=$true;foreach($P in $ProgressRequired){if(-not($BatchLines-contains$P)){$ProgressPass=$false}}
$SyntheticPass=$ProgressPass-and$Closure[0].status-eq'SYNTHETIC_PARAMETER_TRANSFER_PASS'-and@($Transfers|Where-Object{$_.case_id-eq'COMBINED_NONIDENTITY'-and$_.status-eq'PASS'}).Count-eq5-and@($Responses|Where-Object{$_.status-ne'PASS'}).Count-eq0-and$ReloadMarker-and$ReloadConsumers.Count-eq5-and$SourceHashBefore-eq$SourceHashAfter-and$BatchExit-eq0-and$ReloadExit-eq0-and$FatalMatches.Count-eq0-and$ReloadFatal.Count-eq0
$Gate=New-M03A4CompletenessGate $SyntheticPass;Export-CsvNoBom $Gate (Join-Path $Stage 'M03A_4_completeness_gate.csv');if(-not$SyntheticPass-or@($Gate|Where-Object{$_.item-eq'SYNTHETIC_PARAMETER_TRANSFER_PASS'-and$_.value-eq'TRUE'-and$_.status-eq'PASS'}).Count-ne1){throw 'Completeness gate rejected actual integration result'}
$Readiness=@([pscustomobject]@{item='RUN_STATE';value='SYNTHETIC_SMOKE_TEST';status='PASS';reason='numerical verification only'},[pscustomobject]@{item='CALIBRATION_MODE';value='PROVISIONAL';status='PASS';reason='experimental calibration incomplete'},[pscustomobject]@{item='PARAMETER_TRANSFER_MODE';value='SYNTHETIC_DRY_RUN';status='PASS';reason='synthetic fixture only'},[pscustomobject]@{item='EXPERIMENTAL_INPUT_COMPLETE';value='FALSE';status='PASS';reason='no real experimental file supplied'},[pscustomobject]@{item='M03B_READY';value='FALSE';status='PASS';reason='M03A.4 does not authorize M03B'});Export-CsvNoBom (Add-RunId $Readiness $Stamp) (Join-Path $Stage 'M03A_4_readiness.csv')
$RuntimeAudit=@([pscustomobject][ordered]@{run_id=$Stamp;process_exit_status=$BatchExit;completion_marker=$Completion;reload_exit_status=$ReloadExit;reload_marker=$ReloadMarker;solver_status=$SolverStatus;java_exception_marker=$JavaException;fatal_count=$FatalMatches.Count;reload_fatal_count=$ReloadFatal.Count;warning_count=($WarningMatches.Count);expected_outputs_present=(Test-Path $StagedMph);status='PASS';warning_classification=if($WarningMatches.Count){'RETAINED_NONFATAL_WARNING'}else{'NONE'}});Export-CsvNoBom $RuntimeAudit (Join-Path $Stage 'M03A_4_runtime_audit.csv')
$Attempts=@(
[pscustomobject][ordered]@{run_id='20260718_144603';completion_marker='ABSENT';process_exit_status='NOT_RECORDED';solver_status='NOT_STARTED_OR_NOT_RECORDED';fatal_classification='INCOMPLETE_ATTEMPT';accepted_for_formal_results='FALSE';reason='PowerShell preflight evidence retained; no accepted COMSOL completion evidence'},
[pscustomobject][ordered]@{run_id='20260718_144614';completion_marker='ABSENT';process_exit_status='NOT_RECORDED';solver_status='NOT_STARTED_OR_NOT_RECORDED';fatal_classification='INCOMPLETE_ATTEMPT';accepted_for_formal_results='FALSE';reason='PowerShell preflight evidence retained; no accepted COMSOL completion evidence'},
[pscustomobject][ordered]@{run_id='20260718_144705';completion_marker='ABSENT';process_exit_status='NONZERO_OR_ABORTED';solver_status='FAILED_ATTEMPT';fatal_classification='LU_OUT_OF_MEMORY';accepted_for_formal_results='FALSE';reason='Preserved COMSOL log reports LU factorization out of memory'},
[pscustomobject][ordered]@{run_id='20260718_145057';completion_marker='ABSENT';process_exit_status='NONZERO_OR_ABORTED';solver_status='FAILED_ATTEMPT';fatal_classification='LU_OUT_OF_MEMORY';accepted_for_formal_results='FALSE';reason='Preserved COMSOL log reports LU factorization out of memory'},
[pscustomobject][ordered]@{run_id='20260718_145541';completion_marker='PRESENT';process_exit_status='0_INFERRED_FROM_DRIVER_CONTINUATION';solver_status='CD_ONLY_SUPERSEDED';fatal_classification='NONE_IN_RETAINED_LOG';accepted_for_formal_results='FALSE';reason='Preserved successful cd-only attempt did not execute current-run full TDS closure'},
[pscustomobject][ordered]@{run_id='20260718_185218';completion_marker='ABSENT';process_exit_status='NONZERO';solver_status='NOT_STARTED';fatal_classification='WINDOWS_ENVIRONMENT_DUPLICATE_PATH';accepted_for_formal_results='FALSE';reason='Preserved infrastructure attempt stopped before COMSOL because PowerShell Start-Process rejected duplicate Path and PATH keys'},
[pscustomobject][ordered]@{run_id='20260718_185324';completion_marker='ABSENT';process_exit_status='NONZERO';solver_status='NOT_STARTED';fatal_classification='POWERSHELL5_TOKENIZATION';accepted_for_formal_results='FALSE';reason='Preserved pre-COMSOL attempt stopped while constructing canonical resolved inputs because a property comparison lacked required token spacing'},
[pscustomobject][ordered]@{run_id='20260718_185432';completion_marker='ABSENT';process_exit_status='TERMINATED_STALLED_COMPILER';solver_status='NOT_STARTED';fatal_classification='COMSOLCOMPILE_HIDDEN_SECURITY_PROMPT';accepted_for_formal_results='FALSE';reason='Preserved pre-solver attempt; builder comsolcompile stalled before isolated full-permission prefs were supplied'},
[pscustomobject][ordered]@{run_id='20260718_190243';completion_marker='ABSENT';process_exit_status='0';solver_status='JAVA_PRE_SOLVE_REJECTED';fatal_classification='CANONICAL_TARGET_VALIDATION';accepted_for_formal_results='FALSE';reason='Preserved Java batch rejected mismatched expected target name for resolved electrolyte resistance before geometry or solve'},
[pscustomobject][ordered]@{run_id='20260718_190415';completion_marker='ABSENT';process_exit_status='0';solver_status='FAILED_ATTEMPT';fatal_classification='RECOVERY_SAVEPOINT_PATH_UNAVAILABLE';accepted_for_formal_results='FALSE';reason='Preserved full-physics compile attempt failed because COMSOL recovery savepoint still targeted inaccessible user recovery directory'},
[pscustomobject][ordered]@{run_id='20260718_190709';completion_marker='ABSENT';process_exit_status='0_WITH_COMSOL_ERROR';solver_status='FAILED_ATTEMPT';fatal_classification='RECOVERY_PATH_PREF_DECODE_ERROR';accepted_for_formal_results='FALSE';reason='Preserved model-load attempt; absolute isolated recovery path was decoded incorrectly by COMSOL preferences'},
[pscustomobject][ordered]@{run_id='20260718_191024';completion_marker='ABSENT';process_exit_status='0_WITH_COMSOL_ERROR';solver_status='FAILED_ATTEMPT';fatal_classification='PREFSDIR_UNDERSCORE_DECODE_ERROR';accepted_for_formal_results='FALSE';reason='Preserved model-load attempt; blank recovery preference still inherited underscored workspace prefsdir and was decoded as spaces'},
[pscustomobject][ordered]@{run_id='20260718_191313';completion_marker='ABSENT';process_exit_status='0_WITH_COMSOL_ERROR';solver_status='FAILED_ATTEMPT';fatal_classification='SANDBOX_RECOVERY_WRITE_DENIED';accepted_for_formal_results='FALSE';reason='Preserved model-load attempt; correctly decoded isolated recovery directory was denied by nested COMSOL sandbox boundary'},
[pscustomobject][ordered]@{run_id='20260718_191607';completion_marker='ABSENT';process_exit_status='0_WITH_COMSOL_ERROR';solver_status='FAILED_ATTEMPT';fatal_classification='EXTERNAL_CLASS_RECOVERY_DIRECTORY_OPEN_ERROR';accepted_for_formal_results='FALSE';reason='Preserved model-load attempt; external-class bridge still opened default recovery directory until explicit batch recovery flags were added'},
[pscustomobject][ordered]@{run_id='20260718_191852';completion_marker='ABSENT';process_exit_status='0_WITH_COMSOL_ERROR';solver_status='FAILED_ATTEMPT';fatal_classification='RECOVERY_STORE_ROLE_CONFLICT';accepted_for_formal_results='FALSE';reason='Preserved model-load attempt; explicit recoverydir incorrectly reused the prefs comsol.recoveries management directory'},
[pscustomobject][ordered]@{run_id='20260718_192059';completion_marker='ABSENT';process_exit_status='0_WITH_COMSOL_ERROR';solver_status='FAILED_ATTEMPT';fatal_classification='ACTUAL_TDS_CLOSURE_THRESHOLD';accepted_for_formal_results='FALSE';reason='Preserved full seven-case coupled solve; parameter responses passed but coarse-mesh actual TDS boundary-flux and inlet/outlet closure did not satisfy formal thresholds'},
[pscustomobject][ordered]@{run_id='20260718_193033';completion_marker='ABSENT';process_exit_status='0_WITH_COMSOL_ERROR';solver_status='FAILED_ATTEMPT';fatal_classification='ACTUAL_TDS_CLOSURE_THRESHOLD';accepted_for_formal_results='FALSE';reason='Preserved full seven-case coupled solve with accurate boundary-flux reconstruction; closure improved but default stationary tolerance was insufficient for the trace-species flux scale'},
[pscustomobject][ordered]@{run_id='20260718_193345';completion_marker='PRESENT';process_exit_status='0';solver_status='FULL_SPF_TDS_CD_SOLVED';fatal_classification='POSTPROCESS_POWERSHELL_PARSE_ERROR';accepted_for_formal_results='FALSE';reason='Preserved full seven-case tight-tolerance solve passed all scientific thresholds and saved a staged derivative, but postprocess parsing stopped before independent reload and publication'},
[pscustomobject][ordered]@{run_id='20260718_193820';completion_marker='PRESENT';process_exit_status='0';solver_status='FULL_SPF_TDS_CD_SOLVED';fatal_classification='POSTPROCESS_SINGLE_ROW_ARRAY_ERROR';accepted_for_formal_results='FALSE';reason='Preserved full seven-case tight-tolerance solve passed all scientific thresholds; strict-mode postprocess did not wrap the single closure row as an array and stopped before reload'},
[pscustomobject][ordered]@{run_id='20260718_194207';completion_marker='PRESENT';process_exit_status='0';solver_status='FULL_SPF_TDS_CD_SOLVED_RELOAD_REJECTED';fatal_classification='RELOAD_ROUNDTRIP_PRECISION_MISMATCH';accepted_for_formal_results='FALSE';reason='Preserved full solve passed scientific thresholds; independent reload rejected 12-significant-digit parameter serialization because the conductivity inversion consumer was not an exact canonical-value round trip'},
[pscustomobject][ordered]@{run_id='20260718_194539';completion_marker='PRESENT';process_exit_status='0';solver_status='FULL_SPF_TDS_CD_SOLVED_AND_RELOADED';fatal_classification='SUPERSEDED_FORMAL_RUN';accepted_for_formal_results='FALSE';reason='Preserved successful run superseded by provenance-complete atomic release'},
[pscustomobject][ordered]@{run_id='20260719_112900';completion_marker='PRESENT';process_exit_status='0';solver_status='FULL_SPF_TDS_CD_SOLVED_AND_RELOADED';fatal_classification='POSTPROCESS_POWERSHELL_OPERATOR_TOKENIZATION';accepted_for_formal_results='FALSE';reason='Preserved full solve and complete provenance reload passed; PowerShell 5 parameter-mode operator tokenization stopped postprocess before release publication'},
[pscustomobject][ordered]@{run_id='20260719_113346';completion_marker='PRESENT';process_exit_status='0';solver_status='FULL_SPF_TDS_CD_SOLVED_AND_RELOADED';fatal_classification='POSTPROCESS_RELEASE_MANIFEST_KEYWORD_TOKENIZATION';accepted_for_formal_results='FALSE';reason='Preserved full solve and complete provenance reload passed; PowerShell 5 keyword tokenization stopped initial release-manifest construction before C037 or pointer activation'},
[pscustomobject][ordered]@{run_id=$Stamp;completion_marker='PRESENT';process_exit_status='0';solver_status='FULL_SPF_TDS_CD_SOLVED_AND_RELOADED';fatal_classification='NONE';accepted_for_formal_results='TRUE';reason='All current-run formal thresholds and independent reload passed'})
Export-CsvNoBom $Attempts (Join-Path $Stage 'M03A_4_attempt_history.csv')

New-AuditPng 'M03A.4 resolved synthetic EIS chain' @('Two accepted raw EIS replicates retained','Consensus mean is the only resolved EIS HFR total','Unique series ledger de-embedded before inversion','Experimental template remains missing') (Join-Path $Stage 'M03A_4_nyquist_audit.png')
New-AuditPng 'M03A.4 resistance de-embedding' @("Consensus HFR total = $($SyntheticLedger.R_HFR_total_ohm) ohm","Series sum = $($SyntheticLedger.R_non_electrolyte_ohm) ohm","Electrolyte resistance = $($SyntheticLedger.R_electrolyte_ohm) ohm",'Duplicate missing and invalid components block') (Join-Path $Stage 'M03A_4_resistance_deembedding.png')
New-AuditPng 'M03A.4 conductivity cross-check' @("HFR conductivity = $($Analytic.conductivity_S_m) S/m","Direct synthetic conductivity = $($DirectAudit.conductivity_S_m) S/m","Relative difference = $($Cross.relative_difference)",'No truth selected automatically') (Join-Path $Stage 'M03A_4_conductivity_crosscheck.png')
New-AuditPng 'M03A.4 full coupled five-parameter transfer' @('Seven synthetic identity perturbation and combined cases solved','Geometry and mesh rebuilt before each fresh solve','spf plus tds plus cd active in formal combined case','Actual TDS cathode flux and inlet outlet balances accepted','Reporting area changes current density only') (Join-Path $Stage 'M03A_4_parameter_transfer.png')

$DBase=[IO.File]::ReadAllBytes((Join-Path $BaselineTree 'docs\DECISIONS.md'));$DNow=[IO.File]::ReadAllBytes((Join-Path $ProjectRoot 'docs\DECISIONS.md'));if($DNow.Length-le$DBase.Length){throw 'D0015 not appended'};for($i=0;$i-lt$DBase.Length;$i++){if($DNow[$i]-ne$DBase[$i]){throw 'Pre-D0015 decision bytes changed'}};$Title='## D0015 '+[char]0x2014+' M03A.4 calibration intake framework and synthetic parameter-transfer dry-run';if(([regex]::Matches([Text.Encoding]::UTF8.GetString($DNow),[regex]::Escape($Title))).Count-ne1){throw 'D0015 exact title failed'}
$After=New-Object Collections.Generic.List[object];foreach($P in $Tracked){$Current=Join-Path $ProjectRoot $P;$Base=Join-Path $BaselineTree $P;$BH=(Get-FileHash -Algorithm SHA256 $Base).Hash.ToLowerInvariant();$CH=(Get-FileHash -Algorithm SHA256 $Current).Hash.ToLowerInvariant();$Allowed=$P-eq'docs/DECISIONS.md';if(-not$Allowed-and$BH-ne$CH){throw "Frozen tracked file changed: $P"};$After.Add([pscustomobject][ordered]@{path=$P;baseline_sha256=$BH;after_sha256=$CH;status=if($BH-eq$CH){'UNCHANGED'}else{'APPEND_ONLY_D0015'}})};Export-CsvNoBom @($After|ForEach-Object{$_}) (Join-Path $RunDir 'frozen_hashes_after.csv')
$TempRows=@(Get-ChildItem $Tmp -Recurse -Force -File|ForEach-Object{[pscustomobject]@{path=$_.FullName.Substring($Tmp.Length+1);bytes=$_.Length;classification='ISOLATED_COMSOL_TEMPORARY'}});if($TempRows.Count){Export-CsvNoBom $TempRows (Join-Path $RunDir 'temporary_file_audit.csv')}else{Export-CsvNoBom @([pscustomobject]@{path='';bytes=0;classification='NO_TEMPORARY_FILES_REMAIN'}) (Join-Path $RunDir 'temporary_file_audit.csv')};Copy-Item -Path (Join-Path $Prefs '*') -Destination $PrefsEvidence -Recurse -Force;Copy-Item -Path (Join-Path $Tmp '*') -Destination $TmpEvidence -Recurse -Force -ErrorAction SilentlyContinue
$MphHash=(Get-FileHash -Algorithm SHA256 $StagedMph).Hash.ToLowerInvariant();$Report=@"
# M03A.4 full synthetic coupled parameter-transfer dry-run

- Baseline: $BaselineCommit
- Run directory: $RunDir
- Canonical resolved-input SHA-256: $ResolvedHash
- Derived MPH SHA-256: $MphHash
- Frozen M03A.3 MPH SHA-256 before/after: $SourceHashBefore / $SourceHashAfter
- Parser module 40 preflight regressions and C037 real integration regression: PASS.
- Parent-provenance digest mutation missing-parent conductivity-uncertainty fixed-seed Monte Carlo and resolved-source consistency gates: PASS.
- Seven nonidentity transfer cases Java compile geometry rebuild named-selection audit mesh rebuild fresh spf+tds+cd solves actual current integration actual TDS cathode integration inlet/outlet balances nitrogen closure consumer response derivative save and independent reload: PASS.
- Runtime process exit and completion/reload markers: PASS; fatal count 0; warnings classified and retained.

The resolved synthetic EIS chain is raw EIS to replicate estimates to accepted consensus to de-embedding to conductivity. The formal combined nonidentity derivative uses a current-run full coupled solution. Algebraic imposed stoichiometry is reported only as ALGEBRAIC_STOICHIOMETRIC_MAPPING; formal Faraday closure uses actual TDS cathode flux and inlet/outlet balances.

The earlier 20260718_144705 and 20260718_145057 LU memory failures are preserved failed attempts and are not part of the final successful-run acceptance. Experimental calibration remains incomplete. There are no electrode kinetics and no M03B authorization.

RUN_STATE = SYNTHETIC_SMOKE_TEST
CALIBRATION_MODE = PROVISIONAL
PARAMETER_TRANSFER_MODE = SYNTHETIC_DRY_RUN
EXPERIMENTAL_INPUT_COMPLETE = FALSE
M03B_READY = FALSE
"@;Write-Text (Join-Path $Stage 'M03A_4_report.md') $Report
$BuildText="# M03A.4 build log`r`n`r`n## comsolcompile stdout`r`n$([IO.File]::ReadAllText($CompileOut))`r`n## comsolcompile stderr`r`n$([IO.File]::ReadAllText($CompileErr))`r`n## COMSOL batch stdout`r`n$([IO.File]::ReadAllText($BatchOut))`r`n## COMSOL batch stderr`r`n$([IO.File]::ReadAllText($BatchErr))`r`n## COMSOL batch log`r`n$([IO.File]::ReadAllText($BatchLog))`r`n## reload stdout`r`n$([IO.File]::ReadAllText($ReloadOut))`r`n## reload stderr`r`n$([IO.File]::ReadAllText($ReloadErr))`r`n## reload log`r`n$([IO.File]::ReadAllText($ReloadLog))";Write-Text (Join-Path $Stage 'M03A_4_build.log') $BuildText

foreach($N in $FormalCsv){$P=Join-Path $Stage $N;Assert-NoBom $P;$Rows=@(Import-Csv -LiteralPath $P -Encoding UTF8);if($Rows.Count-eq0){throw "CSV has no rows: $N"}}
foreach($N in $FormalPng){Test-Png (Join-Path $Stage $N)}
Assert-NoBom (Join-Path $Stage 'M03A_4_report.md');Assert-NoBom (Join-Path $Stage 'M03A_4_build.log')
&git diff --check;if($LASTEXITCODE){throw 'git diff --check failed before publication'}

# Phase A: assemble the complete immutable candidate bundle, then validate its final manifest twice.
foreach($N in $FormalCsv){Copy-Item -LiteralPath (Join-Path $Stage $N) -Destination (Join-Path $ReleaseTables $N)}
foreach($N in $FormalPng){Copy-Item -LiteralPath (Join-Path $Stage $N) -Destination (Join-Path $ReleaseFigures $N)}
Copy-Item -LiteralPath $StagedMph -Destination (Join-Path $ReleaseModels 'LiNRR_M03A_4_parameter_transfer_dry_run.mph')
Copy-Item -LiteralPath (Join-Path $Stage 'M03A_4_report.md') -Destination (Join-Path $ReleaseReports 'M03A_4_report.md')
Copy-Item -LiteralPath (Join-Path $Stage 'M03A_4_build.log') -Destination (Join-Path $ReleaseReports 'M03A_4_build.log')
$ReleaseManifestPath=Join-Path $ReleaseManifestDir 'M03A_4_RELEASE_MANIFEST.csv';[void](New-ReleaseManifest $ReleaseBundle $Stamp $ReleaseManifestPath);Assert-ReleaseManifest $ReleaseBundle $ReleaseManifestPath $Stamp
$IntegrationOut=Join-Path $RunDir 'integration_regression_first_stdout.log';$IntegrationErr=Join-Path $RunDir 'integration_regression_first_stderr.log';$Code=Invoke-Captured $Pwsh @('-NoProfile','-ExecutionPolicy','Bypass','-File',(Join-Path $ProjectRoot 'tests\powershell\Test_M03A_4_Calibration.ps1'),'-ProjectRoot',$ProjectRoot,'-IntegrationBundle',$ReleaseBundle,'-RunId',$Stamp) $IntegrationOut $IntegrationErr;if($Code){throw 'C037 initial integration regression failed'};$IntegrationLines=@(Get-Content -Encoding UTF8 $IntegrationOut);$C037Line=@($IntegrationLines|Where-Object{$_-like'M03A4_REGRESSION|C037|*'});if($C037Line.Count-ne1){throw 'C037 result missing'};$V=$C037Line[0]-split'\|',7;if($V[5]-ne'PASS'){throw 'C037 integration result failed'};$CurrentRegression=@(Import-Csv -LiteralPath (Join-Path $Stage 'M03A_4_synthetic_regression.csv') -Encoding UTF8);$CurrentRegression+=([pscustomobject][ordered]@{case_id=$V[1];case_name=$V[2];expected=$V[3];actual=$V[4];status=$V[5];failure_reason=$V[6]});Export-CsvNoBom $CurrentRegression (Join-Path $Stage 'M03A_4_synthetic_regression.csv');Copy-Item -LiteralPath (Join-Path $Stage 'M03A_4_synthetic_regression.csv') -Destination (Join-Path $ReleaseTables 'M03A_4_synthetic_regression.csv') -Force
[void](New-ReleaseManifest $ReleaseBundle $Stamp $ReleaseManifestPath);Assert-ReleaseManifest $ReleaseBundle $ReleaseManifestPath $Stamp
$IntegrationFinalOut=Join-Path $RunDir 'integration_regression_final_stdout.log';$IntegrationFinalErr=Join-Path $RunDir 'integration_regression_final_stderr.log';$Code=Invoke-Captured $Pwsh @('-NoProfile','-ExecutionPolicy','Bypass','-File',(Join-Path $ProjectRoot 'tests\powershell\Test_M03A_4_Calibration.ps1'),'-ProjectRoot',$ProjectRoot,'-IntegrationBundle',$ReleaseBundle,'-RunId',$Stamp) $IntegrationFinalOut $IntegrationFinalErr;if($Code-or-not(Select-String -LiteralPath $IntegrationFinalOut -SimpleMatch -Pattern 'M03A4_REGRESSION|C037|synthetic COMSOL integration artifact|SYNTHETIC_COMSOL_INTEGRATION_ARTIFACT_PASS|SYNTHETIC_COMSOL_INTEGRATION_ARTIFACT_PASS|PASS|' -Quiet)){throw 'C037 final immutable integration regression failed'};Assert-ReleaseManifest $ReleaseBundle $ReleaseManifestPath $Stamp
$ReleaseManifestHash=(Get-FileHash -Algorithm SHA256 -LiteralPath $ReleaseManifestPath).Hash.ToLowerInvariant();$MphHash=(Get-FileHash -Algorithm SHA256 -LiteralPath (Join-Path $ReleaseModels 'LiNRR_M03A_4_parameter_transfer_dry_run.mph')).Hash.ToLowerInvariant()

# Bootstrap the pre-existing accepted run as an explicit old release only when no pointer exists.
$ActivePointerPath=Join-Path $ProjectRoot 'results\M03A_4_ACTIVE_RELEASE.json'
if(-not(Test-Path -LiteralPath $ActivePointerPath -PathType Leaf)){$LegacyBundle=Join-Path $RunDir 'legacy_release_bundle';$LegacyTables=Join-Path $LegacyBundle 'tables';$LegacyFigures=Join-Path $LegacyBundle 'figures';$LegacyModels=Join-Path $LegacyBundle 'models';$LegacyReports=Join-Path $LegacyBundle 'reports';$LegacyManifestDir=Join-Path $LegacyBundle 'manifest';foreach($D in @($LegacyTables,$LegacyFigures,$LegacyModels,$LegacyReports,$LegacyManifestDir)){New-Item -ItemType Directory -Path $D|Out-Null};Get-ChildItem -LiteralPath (Join-Path $ProjectRoot 'results\tables') -Filter 'M03A_4_*.csv' -File|ForEach-Object{Copy-Item -LiteralPath $_.FullName -Destination (Join-Path $LegacyTables $_.Name)};Get-ChildItem -LiteralPath (Join-Path $ProjectRoot 'results\figures') -Filter 'M03A_4_*.png' -File|ForEach-Object{Copy-Item -LiteralPath $_.FullName -Destination (Join-Path $LegacyFigures $_.Name)};Copy-Item -LiteralPath $OutputMph -Destination (Join-Path $LegacyModels 'LiNRR_M03A_4_parameter_transfer_dry_run.mph');Copy-Item -LiteralPath (Join-Path $ProjectRoot 'runs\latest\M03A_4_report.md') -Destination (Join-Path $LegacyReports 'M03A_4_report.md');Copy-Item -LiteralPath (Join-Path $ProjectRoot 'runs\latest\M03A_4_build.log') -Destination (Join-Path $LegacyReports 'M03A_4_build.log');$LegacyManifestPath=Join-Path $LegacyManifestDir 'M03A_4_RELEASE_MANIFEST.csv';[void](New-ReleaseManifest $LegacyBundle '20260718_194539' $LegacyManifestPath);Assert-ReleaseManifest $LegacyBundle $LegacyManifestPath '20260718_194539';$LegacyResolved=Join-Path $LegacyTables 'M03A_4_resolved_inputs.csv';$LegacyMph=Join-Path $LegacyModels 'LiNRR_M03A_4_parameter_transfer_dry_run.mph';$LegacyPointer=[pscustomobject][ordered]@{run_id='20260718_194539';release_manifest_path=$LegacyManifestPath.Substring($ProjectRoot.Length+1).Replace('\','/');release_manifest_sha256=(Get-FileHash -Algorithm SHA256 -LiteralPath $LegacyManifestPath).Hash.ToLowerInvariant();resolved_inputs_sha256=(Get-FileHash -Algorithm SHA256 -LiteralPath $LegacyResolved).Hash.ToLowerInvariant();derived_mph_sha256=(Get-FileHash -Algorithm SHA256 -LiteralPath $LegacyMph).Hash.ToLowerInvariant();activation_timestamp=(Get-Date).ToString('o');status='ACTIVE'};Write-AtomicPointer $LegacyPointer $ActivePointerPath (Join-Path $RunDir 'bootstrap_pointer_backup.json')}

# Real failure injection: begin compatibility replacement, fail after three files, restore, and prove the old pointer stayed active.
$CompatibilityPairs=New-Object Collections.Generic.List[object];foreach($N in $FormalCsv){$CompatibilityPairs.Add([pscustomobject]@{Source=Join-Path $ReleaseTables $N;Destination=Join-Path $ProjectRoot "results\tables\$N";Relative="results\tables\$N"})};foreach($N in $FormalPng){$CompatibilityPairs.Add([pscustomobject]@{Source=Join-Path $ReleaseFigures $N;Destination=Join-Path $ProjectRoot "results\figures\$N";Relative="results\figures\$N"})};$CompatibilityPairs.Add([pscustomobject]@{Source=Join-Path $ReleaseModels 'LiNRR_M03A_4_parameter_transfer_dry_run.mph';Destination=$OutputMph;Relative='models\generated\LiNRR_M03A_4_parameter_transfer_dry_run.mph'});$CompatibilityPairs.Add([pscustomobject]@{Source=Join-Path $ReleaseReports 'M03A_4_report.md';Destination=Join-Path $ProjectRoot 'runs\latest\M03A_4_report.md';Relative='runs\latest\M03A_4_report.md'});$CompatibilityPairs.Add([pscustomobject]@{Source=Join-Path $ReleaseReports 'M03A_4_build.log';Destination=Join-Path $ProjectRoot 'runs\latest\M03A_4_build.log';Relative='runs\latest\M03A_4_build.log'});$CompatibilityPairs.Add([pscustomobject]@{Source=$ReleaseManifestPath;Destination=Join-Path $ProjectRoot 'results\tables\M03A_4_RELEASE_MANIFEST.csv';Relative='results\tables\M03A_4_RELEASE_MANIFEST.csv'})
$CompatibilityPairArray=@($CompatibilityPairs|ForEach-Object{$_});$PointerHashBeforeInjection=(Get-FileHash -Algorithm SHA256 -LiteralPath $ActivePointerPath).Hash.ToLowerInvariant();$CompatibilityBefore=@{};foreach($Pair in $CompatibilityPairArray){if(Test-Path -LiteralPath $Pair.Destination -PathType Leaf){$CompatibilityBefore[$Pair.Destination]=(Get-FileHash -Algorithm SHA256 -LiteralPath $Pair.Destination).Hash.ToLowerInvariant()}};$Injected=$false;try{Invoke-CompatibilityTransaction $CompatibilityPairArray (Join-Path $RunDir 'failure_injection_backup') (Join-Path $RunDir 'failure_injection_rollback') 3|Out-Null}catch{if($_.Exception.Message-like'INJECTED_COMPATIBILITY_COPY_FAILURE_AFTER_3'){$Injected=$true}else{throw}};if(-not$Injected){throw 'Compatibility failure injection did not fire'};if((Get-FileHash -Algorithm SHA256 -LiteralPath $ActivePointerPath).Hash.ToLowerInvariant()-ne$PointerHashBeforeInjection){throw 'Active pointer changed during compatibility failure injection'};foreach($Pair in $CompatibilityPairArray){if($CompatibilityBefore.ContainsKey($Pair.Destination)-and(Get-FileHash -Algorithm SHA256 -LiteralPath $Pair.Destination).Hash.ToLowerInvariant()-ne$CompatibilityBefore[$Pair.Destination]){throw "Compatibility rollback hash mismatch: $($Pair.Destination)"}};Export-CsvNoBom @([pscustomobject][ordered]@{run_id=$Stamp;failure_injected='TRUE';failure_after_file=3;old_pointer_unchanged='TRUE';compatibility_rollback='PASS';new_release_partially_declared='FALSE';status='PASS'}) (Join-Path $RunDir 'compatibility_failure_injection_audit.csv')

# Phase B: one atomic authoritative pointer switch, followed by rollback-capable compatibility copies.
$ActivePointer=[pscustomobject][ordered]@{run_id=$Stamp;release_manifest_path=$ReleaseManifestPath.Substring($ProjectRoot.Length+1).Replace('\','/');release_manifest_sha256=$ReleaseManifestHash;resolved_inputs_sha256=$ResolvedHash;derived_mph_sha256=$MphHash;activation_timestamp=(Get-Date).ToString('o');status='ACTIVE'};$PointerBackup=Join-Path $RunDir 'active_release_pointer_previous.json';Write-AtomicPointer $ActivePointer $ActivePointerPath $PointerBackup;$LoadedPointer=Get-Content -Raw -LiteralPath $ActivePointerPath|ConvertFrom-Json;if($LoadedPointer.run_id-ne$Stamp-or$LoadedPointer.release_manifest_sha256-ne$ReleaseManifestHash-or$LoadedPointer.resolved_inputs_sha256-ne$ResolvedHash-or$LoadedPointer.derived_mph_sha256-ne$MphHash-or$LoadedPointer.status-ne'ACTIVE'){throw 'Atomic active release pointer verification failed'}
try{Invoke-CompatibilityTransaction $CompatibilityPairArray (Join-Path $RunDir 'compatibility_backup') (Join-Path $RunDir 'compatibility_rollback')|Out-Null}catch{if(Test-Path -LiteralPath $PointerBackup -PathType Leaf){$RestoreTemp=Join-Path (Split-Path -Parent $ActivePointerPath) ('.M03A_4_ACTIVE_RELEASE.rollback.'+[guid]::NewGuid().ToString('N')+'.tmp');Copy-Item -LiteralPath $PointerBackup -Destination $RestoreTemp;[IO.File]::Replace($RestoreTemp,$ActivePointerPath,(Join-Path $RunDir 'failed_new_pointer.json'),$true)};throw}
foreach($Pair in $CompatibilityPairArray){if((Get-FileHash -Algorithm SHA256 -LiteralPath $Pair.Source).Hash.ToLowerInvariant()-ne(Get-FileHash -Algorithm SHA256 -LiteralPath $Pair.Destination).Hash.ToLowerInvariant()){throw "Compatibility publication mismatch: $($Pair.Relative)"}}
Assert-ReleaseManifest $ReleaseBundle $ReleaseManifestPath $Stamp;if((Get-FileHash -Algorithm SHA256 -LiteralPath $ReleaseManifestPath).Hash.ToLowerInvariant()-ne$ReleaseManifestHash){throw 'Release manifest changed after activation'};$AcceptedCount=@(Import-Csv -LiteralPath (Join-Path $ReleaseTables 'M03A_4_attempt_history.csv') -Encoding UTF8|Where-Object{$_.accepted_for_formal_results-eq'TRUE'}).Count;if($AcceptedCount-ne1){throw 'Accepted formal run count is not exactly one'}
Write-Output 'SUCCESS|M03A.4 provenance-complete full synthetic parameter-transfer dry-run complete|RUN_STATE=SYNTHETIC_SMOKE_TEST|CALIBRATION_MODE=PROVISIONAL|PARAMETER_TRANSFER_MODE=SYNTHETIC_DRY_RUN|EXPERIMENTAL_INPUT_COMPLETE=FALSE|M03B_READY=FALSE'
Write-Output "NEW_RUN_DIRECTORY|$RunDir"
Write-Output "ACTIVE_RELEASE_POINTER|$ActivePointerPath"
Write-Output "RELEASE_MANIFEST_SHA256|$ReleaseManifestHash"
Write-Output "RESOLVED_INPUT_SHA256|$ResolvedHash"
Write-Output "DERIVATIVE_MPH_SHA256|$MphHash"
Write-Output "M03A3_SOURCE_MPH_SHA256_BEFORE_AFTER|$SourceHashBefore|$SourceHashAfter"
Write-Output "ACCEPTED_RUN_COUNT|$AcceptedCount"
&git diff --check
&git --no-pager diff --stat
&git status --short --untracked-files=all
