[CmdletBinding()]
param()
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$ProjectRoot=(Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path
. (Join-Path $PSScriptRoot 'lib\Invoke-ComsolCaptured.ps1')
$Bin='F:\COMSOL64\Multiphysics\bin\win64';$Compiler=Join-Path $Bin 'comsolcompile.exe';$Batch=Join-Path $Bin 'comsolbatch.exe';$Input=Join-Path $ProjectRoot 'runs\M10A3\20260815_181029_transient_closure\checkpoint_07_rtd_medium_accepted.mph';$Final=Join-Path $ProjectRoot 'models\generated\LiNRR_M10A3_real_species_transport.mph';$Java=Join-Path $ProjectRoot 'src\java\LiNRR_M10A3_FinalAudit.java';$Evidence=Join-Path $ProjectRoot 'evidence\M10A3';if(-not(Test-Path -LiteralPath $Input -PathType Leaf)){throw 'ACCEPTED_RTD_CHECKPOINT_MISSING'}
$RtdTable=Join-Path $ProjectRoot 'results\tables\M10A3_RTD.csv';if(-not(Test-Path -LiteralPath $RtdTable -PathType Leaf)){throw 'M10A3_RTD_TABLE_MISSING'}
$Baseline=Join-Path $ProjectRoot 'models\generated\LiNRR_M10A2R_manual_reconciled.mph';$Collector=Join-Path $ProjectRoot 'cad\raw\M10A0_2\block_currentCollector_flowField_v03.2.1_20210525_STEP-AP203.STEP';$Chamber=Join-Path $ProjectRoot 'cad\raw\M10A0_2\electrolyteChamber_rectangularMask_v02.2.2_20210521_STEP-AP203.STEP';$Expected=@{$Baseline='B105EBEAF85582E63389427DFAD7320187FA4A472043E207B5363E258E94CEA7';$Collector='0091777D10ECA620E08780381438F3522B3BE31FEE307F9DDCF074A1FACDDFE9';$Chamber='AE350E006228A10EEC4476F79CAFCE6D63F18F10F58F0A8B3559EED0C37FF12C'};foreach($x in $Expected.GetEnumerator()){if((Get-FileHash $x.Key -Algorithm SHA256).Hash -cne $x.Value){throw "IMMUTABLE_HASH_MISMATCH $($x.Key)"}}
$Stamp=Get-Date -Format 'yyyyMMdd_HHmmss';$Run=Join-Path $ProjectRoot "runs\M10A3\${Stamp}_final_audit";[IO.Directory]::CreateDirectory($Run)|Out-Null;[IO.Directory]::CreateDirectory($Evidence)|Out-Null;$Compact=Join-Path $Run 'LiNRR_M10A3_real_species_transport_compact.mph';$Prefs=Join-Path $Run 'isolated_comsol_preferences';[IO.Directory]::CreateDirectory($Prefs)|Out-Null;$DefaultPrefs=Join-Path $env:USERPROFILE '.comsol\v64';foreach($name in @('comsol.prefs','comsolserver.prefs')){$source=Join-Path $DefaultPrefs $name;if(-not(Test-Path -LiteralPath $source -PathType Leaf)){throw "DEFAULT_COMSOL_PREFS_MISSING $source"};$pt=[IO.File]::ReadAllText($source).Replace('save.saving.optimize=speed','save.saving.optimize=size').Replace('security.external.filepermission=limited','security.external.filepermission=full');if($pt -notmatch 'save\.saving\.optimize=size'){throw "COMSOL_SIZE_PREF_NOT_SET $source"};if($pt -notmatch 'security\.external\.filepermission=full'){throw "COMSOL_FILE_PERMISSION_NOT_SET $source"};[IO.File]::WriteAllText((Join-Path $Prefs $name),$pt,(New-Object Text.UTF8Encoding($false)))}
function J([string]$x){$x.Replace('\','\\').Replace('"','\"')};$Runtime=Join-Path $Run 'LiNRR_M10A3_FinalRuntimeInputs.java';$Text=@"
public final class LiNRR_M10A3_FinalRuntimeInputs {
 public static final String INPUT_MPH="$(J $Input)";
 public static final String OUTPUT_MPH="$(J $Compact)";
 public static final String EVIDENCE_DIR="$(J $Evidence)";
 public static final String RTD_TABLE="$(J $RtdTable)";
}
"@;[IO.File]::WriteAllText($Runtime,$Text,(New-Object Text.UTF8Encoding($false)));foreach($item in @($Runtime,$Java)){$co=&$Compiler $item 2>&1;$ce=$LASTEXITCODE;$co|Set-Content (Join-Path $Run ((Split-Path $item -Leaf)+'.compile.txt'));if($ce-ne0){throw "COMPILE_FAILED $item"}}
$Out=Join-Path $Run 'M10A3_final_stdout.txt';$Err=Join-Path $Run 'M10A3_final_stderr.txt';$Log=Join-Path $Run 'M10A3_final.log';$cap=Invoke-ComsolCaptured -Executable $Batch -ArgumentList @('-prefsdir',$Prefs,'-classpathadd',$Run,'-inputfile',([IO.Path]::ChangeExtension($Java,'.class')),'-batchlog',$Log) -StdoutPath $Out -StderrPath $Err -MergedConsolePath (Join-Path $Run 'M10A3_final_merged.txt');if($cap.ExitCode-ne0){throw "FINAL_AUDIT_BATCH_EXIT=$($cap.ExitCode)"};foreach($marker in @('M10A3_FINAL_EVIDENCE_EXPORT=PASS','M10A3_INDEPENDENT_RELOAD=PASS')){if(-not(Select-String -LiteralPath $Out -Pattern $marker -SimpleMatch -Quiet)){throw "FINAL_MARKER_MISSING $marker"}};if(-not(Test-Path -LiteralPath $Compact -PathType Leaf)){throw 'COMPACT_FINAL_MPH_MISSING'};Move-Item -LiteralPath $Compact -Destination $Final -Force
Copy-Item (Join-Path $ProjectRoot 'results\tables\M10A3_*.csv') $Evidence -Force;foreach($x in $Expected.GetEnumerator()){if((Get-FileHash $x.Key -Algorithm SHA256).Hash -cne $x.Value){throw "IMMUTABLE_INPUT_CHANGED $($x.Key)"}};Write-Host "M10A3_FINAL_AUDIT=PASS`nRUN_DIR=$Run"
