[CmdletBinding()]
param([string]$RepoRoot)
$ErrorActionPreference='Stop'
if(-not $RepoRoot){$RepoRoot=(Resolve-Path (Join-Path $PSScriptRoot '../..')).Path}; Set-Location $RepoRoot
$sourceBase='a9314f89ee4a79492b88948dff912dc885feb7d6';$oldFreeze='8e7359b353c6e59ceb42781e819ba95aa2b4b270';$fail=New-Object System.Collections.Generic.List[string]
function Gate([bool]$ok,[string]$name,[string]$detail=''){if($ok){"$name=PASS"}else{$script:fail.Add("$name`: $detail");"$name=FAIL"}}
function HashFile([string]$p){if(-not(Test-Path -LiteralPath $p)){return ''};(Get-FileHash -Algorithm SHA256 -LiteralPath $p).Hash}
Gate ((git branch --show-current).Trim()-eq'paper/v1-freeze-corrective-v1.1') 'BRANCH_GATE'
git cat-file -e "$sourceBase^{commit}" 2>$null;Gate ($LASTEXITCODE-eq0) 'SOURCE_BASE_EXISTS'
Gate ((git rev-parse 'm10a4-realcell-electrochemistry-v1^{}').Trim()-eq$sourceBase) 'SOURCE_TAG_IDENTITY'
git merge-base --is-ancestor $sourceBase HEAD;Gate ($LASTEXITCODE-eq0) 'SOURCE_BASE_ANCESTOR_OF_FREEZE'
git show-ref --verify --quiet refs/remotes/origin/main;if($LASTEXITCODE-eq0){git merge-base --is-ancestor $sourceBase origin/main;Gate ($LASTEXITCODE-eq0) 'CURRENT_ORIGIN_MAIN_CONTAINS_SOURCE_BASE'}else{Gate $false 'CURRENT_ORIGIN_MAIN_CONTAINS_SOURCE_BASE' 'origin/main absent'}
$oldNow=(git rev-parse 'paper-v1-model-freeze^{}').Trim();Gate ($oldNow-eq$oldFreeze) 'OLD_FREEZE_TAG_UNCHANGED' $oldNow
$mph='models/generated/LiNRR_M10A4_ionic_current_li_plating.mph';$a3='models/generated/LiNRR_M10A3_real_species_transport.mph';$collector='cad/raw/M10A0_2/block_currentCollector_flowField_v03.2.1_20210525_STEP-AP203.STEP';$chamber='cad/raw/M10A0_2/electrolyteChamber_rectangularMask_v02.2.2_20210521_STEP-AP203.STEP'
Gate ((HashFile $mph)-eq'FADEEA4D8ADF9E472B4B855B05E39C22EF418214C0F62FB0C1977ACA36DA667B') 'M10A4_FINAL_MPH_HASH' (HashFile $mph); Gate ((Get-Item $mph).Length-eq807839751) 'M10A4_FINAL_MPH_SIZE'; Gate ((HashFile $a3)-eq'03612FDB08D993595ABDA41D5873CBBCAA97580DB432ADCD2FBCD2CA06260C00') 'M10A3_HASH'; Gate ((HashFile $collector)-eq'0091777D10ECA620E08780381438F3522B3BE31FEE307F9DDCF074A1FACDDFE9') 'COLLECTOR_STEP_HASH'; Gate ((HashFile $chamber)-eq'AE350E006228A10EEC4476F79CAFCE6D63F18F10F58F0A8B3559EED0C37FF12C') 'CHAMBER_STEP_HASH'
Gate ([bool](Get-Content evidence/M10A4/M10A4_final_report.txt|Where-Object{$_-eq'M10A4_OVERALL=PASS'})) 'M10A4_ACCEPTANCE'
$manifest=Import-Csv paper/v1/MODEL_FREEZE_MANIFEST.csv; $manifestBad=@(); foreach($r in $manifest){if(-not(Test-Path -LiteralPath $r.path)){$manifestBad+="missing:$($r.path)";continue};if((HashFile $r.path)-ne$r.SHA256){$manifestBad+="hash:$($r.path)"};if([string](Get-Item $r.path).Length-ne[string]$r.size_bytes){$manifestBad+="size:$($r.path)"}}
Gate ($manifestBad.Count-eq0) 'MODEL_FREEZE_MANIFEST' ($manifestBad-join';');Gate (@($manifest|Where-Object path -eq'paper/v1/MODEL_FREEZE_MANIFEST.csv').Count-eq0) 'MANIFEST_NO_SELF_ROW'
$commitBad=@(); foreach($r in $manifest){git cat-file -e "$($r.artifact_commit)^{commit}" 2>$null;if($LASTEXITCODE-ne0){$commitBad+="missing-commit:$($r.path)";continue};$actual=(git log -1 --format=%H -- $r.path).Trim();if($actual-ne$r.artifact_commit){$commitBad+="artifact-commit:$($r.path):$actual"};if($r.source_base_commit-ne$sourceBase){$commitBad+="source-base:$($r.path)"}}
Gate ($commitBad.Count-eq0) 'MANIFEST_ARTIFACT_COMMIT_VALID' ($commitBad-join';')
$paperFiles=@(Get-ChildItem paper/v1 -Recurse -File|ForEach-Object{$_.FullName.Substring($RepoRoot.Length+1).Replace('\','/')}|Where-Object{$_-ne'paper/v1/MODEL_FREEZE_MANIFEST.csv'-and$_-notmatch'/\.qa_rebuild_tmp/'});$unmanifested=@($paperFiles|Where-Object{$p=$_;@($manifest|Where-Object path -eq$p).Count-ne1});Gate ($unmanifested.Count-eq0) 'ALL_PAPER_ARTIFACTS_MANIFESTED' ($unmanifested-join',')
$prov=Import-Csv paper/v1/PARAMETER_PROVENANCE.csv;Gate (@($prov|Where-Object{[string]::IsNullOrWhiteSpace($_.source_class)-or[string]::IsNullOrWhiteSpace($_.source_reference)}).Count-eq0) 'PARAMETER_PROVENANCE'
$claims=Import-Csv paper/v1/CLAIM_EVIDENCE_MATRIX.csv;Gate (@($claims|Where-Object{[string]::IsNullOrWhiteSpace($_.authority_level)-or[string]::IsNullOrWhiteSpace($_.current_support)}).Count-eq0) 'CLAIM_EVIDENCE_MATRIX';Gate (@($claims|Where-Object{$_.claim_type-eq'MECHANISTIC_CLAIM'-and$_.current_support-ne'UNSUPPORTED_IN_PAPER_V1_MODEL'}).Count-eq0) 'UNSUPPORTED_MECHANISTIC_CLAIMS'
Gate (@(Import-Csv paper/v1/REGRESSION_EVIDENCE.csv|Where-Object{$_.status-notmatch'^PASS'}).Count-eq0) 'REGRESSION_EVIDENCE';Gate ((Import-Csv paper/v1/MODEL_LIMITATIONS.csv).Count-ge15) 'MODEL_LIMITATIONS'
$src=Import-Csv paper/v1/SOURCE_ARTIFACT_INDEX.csv;$srcBad=@($src|Where-Object{-not(Test-Path -LiteralPath $_.repository_path)-or(HashFile $_.repository_path)-ne$_.SHA256});Gate ($srcBad.Count-eq0) 'SOURCE_ARTIFACT_INDEX' (($srcBad.artifact_id)-join',')
$fm=Import-Csv paper/v1/figures/figure_manifest.csv;$panelKeys=@($fm|ForEach-Object{"$($_.figure_id)$($_.panel_id)"});Gate ($fm.Count-eq16-and($panelKeys|Select-Object-Unique).Count-eq16-and@($fm|Where-Object{$_.reproducible-ne'TRUE'}).Count-eq0) 'FIGURE_MANIFEST'
$deps=Import-Csv paper/v1/figures/FIGURE_DEPENDENCIES.csv;$depBad=@($deps|Where-Object{-not(Test-Path -LiteralPath $_.dependency_path)-or(HashFile $_.dependency_path)-ne$_.dependency_sha256-or$panelKeys-notcontains("$($_.figure_id)$($_.panel_id)")});$missingDeps=@($panelKeys|Where-Object{$k=$_;@($deps|Where-Object{"$($_.figure_id)$($_.panel_id)"-eq$k}).Count-lt1});Gate ($depBad.Count-eq0-and$missingDeps.Count-eq0) 'FIGURE_DEPENDENCIES' (($depBad.dependency_id+$missingDeps)-join',')
$bp=Import-Csv paper/v1/figures/FIGURE_BUILD_PROVENANCE.csv;$bpBad=@($bp|Where-Object{-not(Test-Path -LiteralPath $_.output_file)-or(HashFile $_.output_file)-ne$_.output_sha256-or-not(Test-Path -LiteralPath $_.builder_script)-or(HashFile $_.builder_script)-ne$_.builder_script_sha256-or-not(Test-Path -LiteralPath $_.source_data_file)-or(HashFile $_.source_data_file)-ne$_.source_data_sha256-or$_.scientific_data_modified-ne'FALSE'});Gate ($bp.Count-eq7-and$bpBad.Count-eq0) 'FIGURE_BUILD_PROVENANCE'
$qa=Import-Csv paper/v1/figures/FIGURE_QA.csv;$qaBad=@($qa|Where-Object{$_.status-ne'PASS'-or$_.deterministic_rebuild_ok-ne'TRUE'-or$_.dependency_hashes_ok-ne'TRUE'-or$_.manual_numeric_edit-ne'FALSE'-or$_.reproducible-ne'TRUE'});Gate ($qa.Count-eq16-and$qaBad.Count-eq0) 'FIGURE_QA';Gate (@($qa|Where-Object deterministic_rebuild_ok -ne'TRUE').Count-eq0) 'FIGURE_DETERMINISTIC_REBUILD'
$literalPattern='3844|0\.0621400622644018|0\.309354151871061|11\.016992179201|colim_MIXED_UNCLASSIFIED';$literalHits=Select-String scripts/windows/Build_PaperV1_Figures.ps1 -Pattern$literalPattern;Gate (-not$literalHits) 'FIGURE_SCIENTIFIC_LITERAL_AUDIT' (($literalHits.LineNumber)-join',')
$ident=Import-Csv paper/v1/CORRECTIVE_NUMERICAL_IDENTITY.csv;Gate ($ident.Count-ge24-and@($ident|Where-Object{$_.identical-ne'TRUE'-or$_.status-ne'PASS'}).Count-eq0) 'CORRECTIVE_NUMERICAL_IDENTITY'
Gate (-not(Test-Path paper/v1/manuscript_v1.md)) 'NO_MANUSCRIPT';$protected=@(git diff --name-only paper-v1-model-freeze..HEAD -- models/generated cad/raw src/java runs results/tables);Gate ($protected.Count-eq0) 'NO_ACCEPTED_MODEL_MUTATION' ($protected-join',');Gate (@(Get-ChildItem paper/v1 -Recurse -File -Filter*.mph).Count-eq0) 'NO_DUPLICATE_MPH'
$phrases='experimentally validated real-cell prediction|predicted FE|FE map|NH3 rate map|NH3 production map|real retained Li thickness|predicted real Li thickness|SEI mechanism confirmed|Li3N mechanism confirmed|HER selectivity prediction|HOR kinetics prediction|full-cell voltage prediction';$wordBad=@();foreach($p in @('paper/v1/MODEL_SCOPE.md','paper/v1/MODEL_FREEZE_REPORT.md')){$n=0;foreach($line in Get-Content $p){$n++;if($line-match$phrases-and$line-notmatch'(?i)does not|not |no |forbidden|outside|cannot|do not'){$wordBad+="${p}:${n}:$line"}}};Gate ($wordBad.Count-eq0) 'PROHIBITED_WORDING' ($wordBad-join';')
$secret='-----BEGIN (RSA |OPENSSH |EC )?PRIVATE KEY-----|ghp_[A-Za-z0-9]{30,}|github_pat_[A-Za-z0-9_]{40,}|AKIA[0-9A-Z]{16}';$secretBad=@();foreach($f in (Get-ChildItem paper/v1,scripts/windows -Recurse -File|Where-Object{$_.FullName-match'PaperV1' -and$_.Name-ne'PaperV1_ModelFreezeAudit.ps1'})){if(Select-String -LiteralPath $f.FullName -Pattern $secret){$secretBad+=$f.FullName}};Gate ($secretBad.Count-eq0) 'CREDENTIAL_AUDIT'
$dc=git diff --check paper-v1-model-freeze..HEAD 2>&1;Gate ($LASTEXITCODE-eq0) 'GIT_DIFF_CHECK' ($dc-join';');Gate ([bool](Get-Content evidence/M10A4/M10A4_final_report.txt|Where-Object{$_-eq'NO_PROHIBITED_PHYSICS=TRUE'})) 'NO_PROHIBITED_PHYSICS'
Gate ($fail.Count-eq0) 'PAPER_V1_MODEL_FREEZE_V1_1' ($fail-join' | ');if($fail.Count){'PAPER_V1_MODEL_FREEZE_V1_1=BLOCKED';$fail|ForEach-Object{"BLOCKER=$_"};exit 1}
"SOURCE_BASE_COMMIT=$sourceBase";'OLD_FREEZE_TAG=paper-v1-model-freeze';"OLD_FREEZE_TAG_TARGET=$oldFreeze";'OLD_FREEZE_TAG_UNCHANGED=TRUE';'CORRECTIVE_BRANCH=paper/v1-freeze-corrective-v1.1';'M10A4_FINAL_MPH_SHA256=FADEEA4D8ADF9E472B4B855B05E39C22EF418214C0F62FB0C1977ACA36DA667B';'M10A3_SHA256=03612FDB08D993595ABDA41D5873CBBCAA97580DB432ADCD2FBCD2CA06260C00';'NEW_COMSOL_SOLVES=0';'NEW_PHYSICS_CREATED=FALSE';'SCIENTIFIC_RESULTS_CHANGED=FALSE';'FIGURE_SCIENTIFIC_LITERAL_AUDIT=PASS';'FIGURE_PANEL_PROVENANCE=PASS';'FIGURE_DEPENDENCY_HASH_AUDIT=PASS';'FIGURE_DETERMINISTIC_REBUILD=PASS';'FIGURE_QA=PASS';'MANIFEST_ARTIFACT_COMMIT_VALID=PASS';'CORRECTIVE_NUMERICAL_IDENTITY=PASS';'SOURCE_BASE_ANCESTRY=PASS';'PARAMETER_PROVENANCE=PASS';'CLAIM_EVIDENCE_MATRIX=PASS';'NO_PROHIBITED_PHYSICS=TRUE';'MANUSCRIPT_CREATED=FALSE';'PAPER_V1_MODEL_FREEZE_VERSION=1.1';'PAPER_V1_MODEL_FREEZE=PASS';'PAPER_V1_MODEL_FREEZE_V1_1=PASS'
